/**
 * Industry Brain Catalog — structured source of truth.
 *
 * This catalog is the dense, consultant-grade variable reference that backs
 * the Industry Brain. It is intentionally separated from the editable
 * `industry_brain_entries` rows so that:
 *
 *  - admins can edit, archive, and version individual rows without losing
 *    the canonical variable coverage,
 *  - the diagnostic, repair-map, implementation, and RGS Control System
 *    surfaces have a stable list of variables to map against,
 *  - completeness can be tested deterministically (see
 *    `industryBrainVariableCompleteness.test.ts`).
 *
 * Cannabis / MMJ / MMC / Rec entries are dispensary / retail / regulated
 * cannabis operations only — never healthcare, patient-care, HIPAA,
 * insurance claims, medical billing, or clinical workflows. The word
 * "medical" only refers to medical marijuana in this file.
 *
 * Third-party brand names use the exact official capitalization (see
 * `src/config/brands.ts`).
 */

import type { IndustryKey } from "@/lib/industryBrain";

export type CatalogCategoryKey =
  | "revenue_streams"
  | "lead_demand_sources"
  | "conversion_variables"
  | "operational_variables"
  | "financial_visibility"
  | "owner_dependence_risks"
  | "staffing_labor"
  | "customer_experience_handoff"
  | "software_evidence_sources"
  | "capacity_constraints"
  | "margin_profitability"
  | "industry_specific_failure_points"
  | "repair_map_implications"
  | "tool_report_mappings"
  | "rgs_control_system_signals";

export const CATALOG_CATEGORY_LABEL: Record<CatalogCategoryKey, string> = {
  revenue_streams: "Revenue streams",
  lead_demand_sources: "Lead / demand sources",
  conversion_variables: "Conversion variables",
  operational_variables: "Operational variables",
  financial_visibility: "Financial visibility",
  owner_dependence_risks: "Owner-dependence risks",
  staffing_labor: "Staffing / labor",
  customer_experience_handoff: "Customer experience / handoff",
  software_evidence_sources: "Software / evidence sources",
  capacity_constraints: "Capacity constraints",
  margin_profitability: "Margin / profitability",
  industry_specific_failure_points: "Industry-specific failure points",
  repair_map_implications: "Repair-map implications",
  tool_report_mappings: "RGS tool / report mappings",
  rgs_control_system_signals: "RGS Control System monitoring signals",
};

export const CATALOG_CATEGORIES: CatalogCategoryKey[] = [
  "revenue_streams",
  "lead_demand_sources",
  "conversion_variables",
  "operational_variables",
  "financial_visibility",
  "owner_dependence_risks",
  "staffing_labor",
  "customer_experience_handoff",
  "software_evidence_sources",
  "capacity_constraints",
  "margin_profitability",
  "industry_specific_failure_points",
  "repair_map_implications",
  "tool_report_mappings",
  "rgs_control_system_signals",
];

export type IndustryCatalog = Record<CatalogCategoryKey, string[]>;

// --- Shared, non-industry-specific reference lists ----------------------
// These are used by every industry catalog so the repair-map / tool /
// monitoring vocabulary stays consistent. They are NOT generic filler —
// each industry adds its own industry-specific variables on top.

const SHARED_REPAIR_MAP_IMPLICATIONS: string[] = [
  "Standardize the workflow end-to-end",
  "Document the process in a written SOP",
  "Assign a single accountable owner per step",
  "Install tracking for the variable in the source system",
  "Set a daily, weekly, or monthly review cadence",
  "Reduce owner dependency by delegating with decision rights",
  "Clarify customer/internal handoff points",
  "Tighten financial visibility on this category",
  "Build a training module so the SOP is teachable",
  "Connect the evidence source so data does not depend on memory",
  "Set a monitoring signal in the RGS Control System",
  "Create a scorecard metric tied to this variable",
  "Create an Implementation Roadmap task with a due date",
  "Add a Priority Action with severity and owner",
  "Add to Monthly System Review for trend tracking",
];

const SHARED_TOOL_REPORT_MAPPINGS: string[] = [
  "Owner Diagnostic Interview",
  "0–1000 Business Stability Scorecard",
  "Admin Diagnostic Review Dashboard",
  "Diagnostic Report Builder",
  "Priority Repair Map / Roadmap Tool",
  "Implementation Roadmap Tool",
  "SOP / Training Bible Creator",
  "Decision Rights / Accountability Tool",
  "Workflow / Process Mapping Tool",
  "Tool Assignment + Training Tracker",
  "RGS Control System",
  "Revenue Control System",
  "Revenue & Risk Monitor",
  "Priority Action Tracker",
  "Owner Decision Dashboard",
  "Scorecard History / Stability Trend Tracker",
  "Monthly System Review Tool",
  "Tool Library / Resource Center",
  "Advisory Notes / Clarification Log",
  "Financial Visibility / Connector UI",
  "Client Health / Renewal Risk",
];

const SHARED_CONTROL_SIGNALS: string[] = [
  "Lead source quality and attribution coverage",
  "Lead response time",
  "Quote / estimate close rate",
  "Revenue by category or service line",
  "Gross margin trend",
  "Job / order margin trend",
  "Labor cost as percentage of revenue",
  "Inventory variance",
  "Cash handling variance",
  "Capacity utilization vs available hours",
  "Customer complaints volume",
  "Rework / callback / remake rate",
  "Refund and discount leakage",
  "Repeat customer rate",
  "Owner-dependent task count",
  "Overdue Priority Action count",
  "Unresolved risk flags",
  "Diagnostic / report trend movement",
  "Scorecard stability trend",
  "Implementation task completion percentage",
  "Client health and renewal risk score",
];

// --- TRADES / FIELD SERVICE --------------------------------------------

const TRADES: IndustryCatalog = {
  revenue_streams: [
    "Service jobs (residential)",
    "Service jobs (commercial)",
    "Recurring maintenance contracts",
    "Emergency / after-hours work",
    "Diagnostic and trip-fee revenue",
    "Parts and materials markup",
    "Warranty and callback work",
    "Add-on upsells at the job site",
    "Project / installation revenue",
    "Subcontracted work",
    "Seasonal demand (heating, cooling, storm, holiday)",
    "Service plan / membership revenue",
    "Financing fee revenue",
    "Reactivated past-customer revenue",
  ],
  lead_demand_sources: [
    "Organic search traffic to the website",
    "Direct traffic (typed-in or saved)",
    "Google Business Profile views and calls",
    "Google Search Console — local and branded queries",
    "Map-pack visibility for service-area terms",
    "Paid search (Google Ads, Bing)",
    "Service-area paid social ads (Meta Ads)",
    "Referrals from past customers",
    "Repeat customers",
    "Vendor and partner referrals (plumbers ↔ HVAC ↔ electricians)",
    "Review platforms (Google, Yelp, BBB, Angi)",
    "Phone calls (tracked vs untracked)",
    "Quote / estimate request forms",
    "Email list re-engagement",
    "SMS list re-engagement",
    "Truck wraps, signage, and door-hangers",
    "Community and local sponsorships",
    "Home-services marketplaces (Angi, Thumbtack, HomeAdvisor)",
  ],
  conversion_variables: [
    "Lead response time (minutes from inquiry)",
    "Phone answer rate during business hours",
    "After-hours capture rate",
    "Estimate / quote sent within 24 hours",
    "Estimate-to-close rate",
    "Quote follow-up cadence",
    "Win/loss reason captured",
    "Pricing objection patterns",
    "Owner-only approvals slowing close",
    "Scope clarity in the estimate",
    "Financing offered consistently",
    "Upsell at job-site consistency",
    "Booked job vs completed job conversion",
    "Same-day close rate for emergency work",
  ],
  operational_variables: [
    "Dispatch and scheduling routing",
    "Crew / technician utilization",
    "Drive time vs billable time",
    "Job packet completeness (scope, materials, customer history)",
    "Parts and material availability",
    "Truck inventory accuracy",
    "Change-order capture (verbal vs written)",
    "Photo and document trail per job",
    "Callback and rework log",
    "Quality-control walkthrough",
    "Job completion vs invoice timing",
    "Status updates sent to customer",
    "Emergency work disrupting scheduled work",
    "Permitting and inspection workflow",
    "Supplier and vendor lead times",
    "Equipment downtime tracking",
  ],
  financial_visibility: [
    "Revenue by service line",
    "Job-level profitability",
    "Gross margin by service category",
    "Net margin by month",
    "Labor cost as percentage of revenue",
    "Materials cost vs estimate",
    "Unbilled work / WIP visibility",
    "AR aging buckets (0–30 / 31–60 / 61–90 / 90+)",
    "Deposit and progress-payment tracking",
    "Discount and warranty-credit leakage",
    "Service-area profitability blind spots",
    "Cash flow timing vs payroll cycle",
    "Owner draw visibility",
    "Budget vs actual by month",
    "QuickBooks / Xero reconciliation cadence",
    "Bank statement reconciliation cadence",
  ],
  owner_dependence_risks: [
    "Owner is the only estimator",
    "Owner approves every quote and price exception",
    "Owner schedules and dispatches every job",
    "Owner handles every customer escalation",
    "Owner is the only person who knows the pricing rules",
    "Owner manages all vendor ordering",
    "Owner is the only closer on large jobs",
    "Owner is the only trainer for technicians",
    "Owner performs manual reporting in spreadsheets",
    "Owner does final quality control on every job",
    "Owner has sole access to job-management software admin",
    "Owner is the bottleneck in hiring",
    "Owner is the bottleneck in cash decisions",
    "Institutional knowledge lives in owner's head/email",
  ],
  staffing_labor: [
    "Role clarity per technician / lead / dispatcher",
    "Onboarding time to first solo job",
    "Cross-training across trades",
    "Certification and licensing tracking",
    "Truck assignment and accountability",
    "Overtime by crew",
    "Labor utilization vs available hours",
    "Turnover and exit-interview themes",
    "Manager / lead-tech readiness",
    "Performance expectations per role",
    "Tool / SOP adoption per technician",
    "Customer-facing communication standards",
    "Safety / PPE compliance by crew",
    "Subcontractor performance tracking",
  ],
  customer_experience_handoff: [
    "Inquiry response message and tone",
    "Intake / booking flow clarity",
    "Estimate clarity and line-item readability",
    "Pre-arrival confirmation (ETA, technician name, photo)",
    "On-site introduction and walkthrough",
    "Post-job cleanup standard",
    "Status updates during long jobs",
    "Invoice clarity and payment options",
    "Review request cadence",
    "Warranty and callback handling",
    "Refund handling",
    "Repeat-customer outreach (maintenance reminders)",
    "Complaint escalation path",
    "Customer education on what was fixed",
  ],
  software_evidence_sources: [
    "Field service / job management (Jobber, Housecall Pro, ServiceTitan)",
    "Accounting (QuickBooks, Xero)",
    "Payments (Stripe, Square, PayPal)",
    "CRM and pipeline (HubSpot, Salesforce, Pipedrive)",
    "Scheduling and dispatch software",
    "Call tracking and recording",
    "Email / SMS platform",
    "Website analytics (Google Analytics)",
    "Search visibility (Google Search Console)",
    "Google Business Profile insights",
    "Review platforms (Google, Yelp, Angi)",
    "Payroll / labor system (Paycom, ADP, Gusto)",
    "Inventory and parts system",
    "Document and photo storage",
    "Spreadsheets used as systems of record",
  ],
  capacity_constraints: [
    "Available crew-hours per week",
    "Available trucks and equipment",
    "Dispatch / routing limits",
    "Service-area drive radius",
    "Permit and inspection scheduling delays",
    "Vendor lead times for parts",
    "Lead volume vs fulfillment capacity",
    "Owner availability as a hidden cap",
    "Cash constraints on materials purchasing",
    "Seasonal demand spikes",
    "Training capacity for new hires",
    "Manager / lead-tech capacity",
    "Office / dispatch capacity",
    "Emergency vs scheduled capacity split",
  ],
  margin_profitability: [
    "Gross margin by service line",
    "Net margin by month",
    "Job margin variance vs estimate",
    "Materials markup discipline",
    "Labor cost per billable hour",
    "Callback / rework cost",
    "Discount and warranty-credit leakage",
    "Service-area profitability variance",
    "Trip-fee economics",
    "Emergency-work premium pricing",
    "Vendor pricing changes not reflected in price book",
    "Price-increase readiness and last update date",
    "High-volume low-margin service traps",
    "Low-volume high-margin opportunity gaps",
  ],
  industry_specific_failure_points: [
    "Quote follow-up slipping past 72 hours",
    "Dispatch conflicts and double-booking",
    "Callback / rework rate above acceptable threshold",
    "Parts unavailable on first visit",
    "Unbilled work after job completion",
    "Job costing gaps (labor and materials not closed out)",
    "Technician utilization invisible per crew",
    "Emergency work disrupting scheduled work",
    "Owner-only estimating creating a queue",
    "Service-area profitability blind spots",
    "Truck inventory shrink",
    "Permitting delays not flagged",
  ],
  repair_map_implications: SHARED_REPAIR_MAP_IMPLICATIONS,
  tool_report_mappings: SHARED_TOOL_REPORT_MAPPINGS,
  rgs_control_system_signals: SHARED_CONTROL_SIGNALS,
};

// --- RESTAURANT / FOOD SERVICE -----------------------------------------

const RESTAURANT: IndustryCatalog = {
  revenue_streams: [
    "Dine-in revenue",
    "Takeout / pickup revenue",
    "Delivery (in-house drivers)",
    "Delivery (third-party platforms — DoorDash, Uber Eats, Grubhub)",
    "Catering and large orders",
    "Private events / buyouts",
    "Beverage program (alcohol)",
    "Beverage program (non-alcohol)",
    "Retail / merchandise",
    "Loyalty / membership revenue",
    "Gift card sales and redemption",
    "Seasonal / LTO menu revenue",
    "Online ordering revenue",
    "Catering subscriptions or recurring orders",
  ],
  lead_demand_sources: [
    "Walk-in foot traffic",
    "Reservations and waitlist",
    "Organic search traffic",
    "Direct traffic to the website",
    "Google Business Profile views and calls",
    "Map-pack visibility",
    "Online ordering platform discovery",
    "Third-party delivery app discovery",
    "Loyalty / repeat customers",
    "Email list",
    "SMS list",
    "Social media (Instagram, TikTok, Facebook)",
    "Review platforms (Google, Yelp, TripAdvisor)",
    "Local press and influencer mentions",
    "Community events and sponsorships",
    "Signage and curb appeal",
    "Promotions and discount campaigns",
    "Catering and B2B referrals",
  ],
  conversion_variables: [
    "Phone answer rate during peak hours",
    "Reservation booking rate",
    "Online order completion rate",
    "Cart abandonment on the ordering site",
    "Average ticket size",
    "Upsell consistency at the register / server",
    "Add-on attach rate (drinks, dessert, sides)",
    "Loyalty signup rate",
    "Wait-time abandonment",
    "Catering quote follow-up rate",
    "Event booking close rate",
    "Promo / discount redemption rate",
    "Review-to-revisit conversion (signal)",
  ],
  operational_variables: [
    "Ticket time and rail-to-table duration",
    "Prep workflow and par levels",
    "Line / station bottlenecks at peak",
    "Order accuracy and remake rate",
    "POS to kitchen ticket integrity",
    "Inventory receiving accuracy",
    "Vendor ordering cadence",
    "Daily cash and tip reconciliation",
    "Opening and closing checklists",
    "Health and food-safety checklists",
    "Equipment maintenance schedule",
    "Delivery handoff to drivers / couriers",
    "Reservation seating flow",
    "Section assignments and table turn",
    "Catering production schedule",
  ],
  financial_visibility: [
    "Prime cost (food + labor) tracked weekly",
    "Food cost percentage by category",
    "Labor cost percentage by daypart",
    "Sales by daypart",
    "Sales by menu category",
    "Item-level menu margin",
    "Comp and void tracking",
    "Discount and promo leakage",
    "Third-party delivery fees and effective margin",
    "Cash variance by shift",
    "Tip pool reconciliation",
    "Inventory variance vs theoretical usage",
    "Waste / spoilage log",
    "AR for catering accounts",
    "QuickBooks / Xero reconciliation cadence",
  ],
  owner_dependence_risks: [
    "Owner is the only person ordering inventory",
    "Owner does the schedule every week",
    "Owner handles every cash count",
    "Owner is the only trainer for new staff",
    "Owner manages every vendor relationship",
    "Owner approves every comp and refund",
    "Owner is the only menu-engineer",
    "Owner is the only person reading the P&L",
    "Owner is the only contact for catering",
    "Owner is the only person resolving customer complaints",
    "Owner has sole admin access to POS",
    "Owner manages payroll personally",
    "Recipes and prep specs live in owner's head",
  ],
  staffing_labor: [
    "Role clarity per station and shift",
    "Onboarding time to a productive shift",
    "Cross-training across stations",
    "Manager-on-duty readiness",
    "Server upsell consistency",
    "Bartender pour cost discipline",
    "Labor scheduling vs forecasted demand",
    "Overtime by role",
    "Turnover by role",
    "Tip distribution clarity",
    "Food-handler certification tracking",
    "Sexual-harassment / safety training tracking",
    "Performance expectations per role",
    "POS adoption per server",
  ],
  customer_experience_handoff: [
    "Greeting and seating standard",
    "Server check-back rhythm",
    "Order accuracy at handoff to kitchen",
    "Food runner handoff to table",
    "Pickup / takeout handoff at counter",
    "Delivery driver handoff and packaging standard",
    "Wait-time communication",
    "Complaint and recovery script",
    "Review request cadence",
    "Loyalty signup ask",
    "Catering delivery confirmation and setup",
    "Reservation confirmation and reminders",
    "Allergen and dietary communication",
  ],
  software_evidence_sources: [
    "POS (Toast, Square, Clover, Aloha, etc.)",
    "Online ordering platform",
    "Third-party delivery dashboards",
    "Reservation / waitlist platform",
    "Inventory management software",
    "Accounting (QuickBooks, Xero)",
    "Payments (Stripe, Square, PayPal)",
    "Payroll / labor system (Paycom, ADP, Gusto)",
    "Email / SMS marketing platform",
    "Loyalty platform",
    "Review platforms (Google, Yelp)",
    "Google Business Profile",
    "Google Analytics for the ordering site",
    "Vendor portals and invoices",
    "Spreadsheets used as systems of record",
  ],
  capacity_constraints: [
    "Seats and table capacity",
    "Kitchen / line throughput at peak",
    "Prep capacity for next-day par",
    "Driver / courier capacity",
    "Catering production capacity",
    "Walk-in cooler / freezer capacity",
    "Vendor delivery windows",
    "Cash on hand for produce / protein orders",
    "Manager-on-duty coverage",
    "Daypart staffing capacity",
    "Reservation slot capacity",
    "Parking and curbside capacity",
    "Seasonal demand spikes",
  ],
  margin_profitability: [
    "Gross margin by menu category",
    "Item-level menu margin and menu-engineering quadrant",
    "Prime cost ratio",
    "Discount and comp leakage",
    "Promo effectiveness vs incremental margin",
    "Third-party delivery effective margin after fees",
    "Wholesale ingredient cost trend",
    "Beverage program margin",
    "Catering margin vs dine-in margin",
    "Waste / spoilage cost",
    "Refund and recook cost",
    "Payment processing fees",
    "Price-increase readiness and last menu update",
    "High-volume low-margin item traps",
  ],
  industry_specific_failure_points: [
    "Prime cost not monitored weekly",
    "Food cost variance vs theoretical usage",
    "Prep inconsistency between shifts",
    "Ticket time bottlenecks at peak",
    "Labor scheduling mismatch with demand",
    "Menu margin blind spots",
    "Third-party delivery fees eroding margin",
    "Remakes and refunds eating margin",
    "Vendor ordering gaps causing 86s",
    "Peak-hour service breakdown",
    "Cash variance by shift not investigated",
    "Catering deposits and AR not tracked",
  ],
  repair_map_implications: SHARED_REPAIR_MAP_IMPLICATIONS,
  tool_report_mappings: SHARED_TOOL_REPORT_MAPPINGS,
  rgs_control_system_signals: SHARED_CONTROL_SIGNALS,
};

// --- RETAIL ------------------------------------------------------------

const RETAIL: IndustryCatalog = {
  revenue_streams: [
    "In-store retail sales",
    "Ecommerce / website sales",
    "Marketplace sales (Amazon, Etsy, eBay)",
    "Wholesale / B2B revenue",
    "Subscription / club revenue",
    "Custom / special-order revenue",
    "Service add-ons (alterations, repair, install)",
    "Gift card sales and redemption",
    "Seasonal / LTO collection revenue",
    "Loyalty / membership revenue",
    "Returns and exchange revenue impact",
    "Promotional / clearance revenue",
    "Event / pop-up revenue",
  ],
  lead_demand_sources: [
    "Foot traffic from street and mall",
    "Organic search traffic",
    "Direct traffic",
    "Ecommerce paid search and shopping ads",
    "Paid social (Meta Ads, TikTok)",
    "Email list",
    "SMS list",
    "Loyalty / repeat customers",
    "Google Business Profile",
    "Map-pack visibility",
    "Marketplace search visibility",
    "Influencer and affiliate referrals",
    "Review platforms (Google, Yelp, product reviews)",
    "In-store signage and merchandising",
    "Local events and pop-ups",
    "Press and PR",
    "Promotions and discount campaigns",
  ],
  conversion_variables: [
    "In-store conversion rate (visitors → buyers)",
    "Add-to-cart rate online",
    "Checkout abandonment rate",
    "Average basket size",
    "Average order value online",
    "Items per transaction",
    "Upsell / cross-sell consistency at register",
    "Loyalty signup rate at checkout",
    "Email capture rate",
    "Wait time at checkout",
    "Promo redemption rate",
    "Return / exchange-to-rebuy conversion",
    "Wholesale quote close rate",
  ],
  operational_variables: [
    "Receiving and putaway accuracy",
    "Inventory cycle counts",
    "POS / ecommerce inventory sync",
    "Restocking cadence on best-sellers",
    "Visual merchandising refresh schedule",
    "Staff coverage by daypart",
    "Returns processing time",
    "Pick / pack / ship throughput",
    "Marketplace order routing",
    "Loss-prevention checks",
    "Vendor receiving discrepancies",
    "Markdown and clearance workflow",
    "Layaway / hold workflow",
  ],
  financial_visibility: [
    "Sales by SKU and category",
    "Gross margin by category",
    "Inventory turnover by category",
    "Sell-through rate per collection",
    "Discount and promo leakage",
    "Markdown impact on margin",
    "Return rate and return-related cost",
    "Shrink as a percentage of sales",
    "Cash variance by shift",
    "AR for wholesale accounts",
    "Vendor cost changes vs price tag",
    "Cash flow timing for inventory orders",
    "QuickBooks / Xero reconciliation cadence",
    "Channel-level profitability (in-store vs online vs marketplace)",
  ],
  owner_dependence_risks: [
    "Owner does all buying / merchandising",
    "Owner sets every price personally",
    "Owner approves every markdown and discount",
    "Owner is the only person reading the inventory report",
    "Owner handles every wholesale customer",
    "Owner is the only person closing the register",
    "Owner does payroll personally",
    "Owner manages every vendor relationship",
    "Owner runs all paid ads",
    "Owner is the only person trained on ecommerce backend",
    "Owner makes every refund decision",
    "Owner is the bottleneck on receiving",
  ],
  staffing_labor: [
    "Role clarity per shift (cashier, floor, stockroom)",
    "Sales associate upsell consistency",
    "Onboarding time to a productive shift",
    "Cross-training across departments",
    "Manager-on-duty readiness",
    "Labor scheduling vs forecasted traffic",
    "Overtime by role",
    "Turnover by role",
    "Loss-prevention training",
    "POS adoption per associate",
    "Performance expectations per role",
    "Customer-service standards per role",
  ],
  customer_experience_handoff: [
    "Greeting and approach standard",
    "Fitting room / try-on experience",
    "Checkout experience and wait time",
    "Loyalty / email capture ask",
    "Bagging and receipt standard",
    "Returns and exchange experience",
    "Online order pickup (BOPIS) handoff",
    "Shipping confirmation and tracking",
    "Post-purchase follow-up",
    "Review request cadence",
    "Complaint and recovery script",
    "Wholesale onboarding and reorder cadence",
  ],
  software_evidence_sources: [
    "POS (Square, Lightspeed, Shopify POS, Clover)",
    "Ecommerce platform (Shopify, WooCommerce, BigCommerce)",
    "Inventory management software",
    "Accounting (QuickBooks, Xero)",
    "Payments (Stripe, Square, PayPal)",
    "Email / SMS marketing platform",
    "Loyalty platform",
    "Review platforms",
    "Marketplace dashboards (Amazon Seller Central, Etsy, eBay)",
    "Google Analytics",
    "Google Search Console",
    "Google Business Profile",
    "Paid ads dashboards (Google Ads, Meta Ads)",
    "Vendor portals and invoices",
    "Payroll / labor system (Paycom, ADP, Gusto)",
  ],
  capacity_constraints: [
    "Square footage and shelf space",
    "Stockroom and back-of-house capacity",
    "Open-to-buy budget",
    "Cash on hand for inventory orders",
    "Vendor lead times",
    "Pick / pack / ship throughput",
    "Staff capacity by daypart",
    "Customer-service phone / chat capacity",
    "Marketplace listing limits",
    "Seasonal demand spikes (holiday, back-to-school)",
    "Truck / delivery window capacity",
    "Manager-on-duty coverage",
  ],
  margin_profitability: [
    "Gross margin by category",
    "Sell-through rate by collection",
    "Markdown leakage",
    "Discount and promo leakage",
    "Return rate and reverse-logistics cost",
    "Shrink cost",
    "Vendor cost changes vs current pricing",
    "Marketplace fees and effective margin",
    "Ecommerce shipping and fulfillment cost",
    "Payment processing fees",
    "Channel-level margin (in-store vs online vs marketplace)",
    "Best-seller margin vs long-tail margin",
    "Price-increase readiness and last update date",
  ],
  industry_specific_failure_points: [
    "Stockouts on best-sellers",
    "Dead stock and aged inventory",
    "Inventory turnover gaps by category",
    "Shrink not investigated",
    "Merchandising refresh slipping",
    "Basket size below target",
    "Return patterns not analyzed",
    "Promo leakage from layered discounts",
    "POS / ecommerce inventory mismatch",
    "Marketplace fee creep",
    "Channel-level margin blind spots",
    "Open-to-buy not enforced",
  ],
  repair_map_implications: SHARED_REPAIR_MAP_IMPLICATIONS,
  tool_report_mappings: SHARED_TOOL_REPORT_MAPPINGS,
  rgs_control_system_signals: SHARED_CONTROL_SIGNALS,
};

// --- CANNABIS / MMJ / MMC / Rec ----------------------------------------
// Dispensary / regulated cannabis retail / inventory / margin operations.
// NOT healthcare, NOT patient-care, NOT HIPAA, NOT insurance claims,
// NOT clinical workflows, NOT medical billing.

const CANNABIS: IndustryCatalog = {
  revenue_streams: [
    "In-store dispensary sales (recreational)",
    "In-store dispensary sales (medical marijuana / MMJ)",
    "Pickup and curbside revenue (where allowed)",
    "Delivery revenue (where allowed by state)",
    "Pre-order / online menu revenue",
    "Loyalty and repeat-customer revenue",
    "Promotional and discount-event revenue",
    "Vendor day / brand activation revenue",
    "Category sales (flower)",
    "Category sales (vape and concentrates)",
    "Category sales (edibles)",
    "Category sales (pre-rolls)",
    "Category sales (accessories)",
    "Bundle / mix-and-match revenue",
  ],
  lead_demand_sources: [
    "Walk-in dispensary traffic",
    "Local organic search visibility (within regulated marketing limits)",
    "Direct traffic to the dispensary website",
    "Google Business Profile (where the listing is permitted)",
    "Cannabis-specific menu platforms (Weedmaps, Leafly, Dutchie)",
    "Loyalty / repeat customers",
    "Email list (where regulator-compliant)",
    "SMS list (where regulator-compliant)",
    "Review platforms (Google, Weedmaps, Leafly)",
    "Vendor and brand co-marketing (within state rules)",
    "Community and local sponsorships (where allowed)",
    "In-store signage and curb appeal",
    "Promotions and discount campaigns (within state rules)",
    "Budtender word-of-mouth and recommendations",
  ],
  conversion_variables: [
    "Walk-in to ID-checked customer rate",
    "ID-checked to transaction rate",
    "Average ticket size",
    "Items per transaction",
    "Budtender upsell consistency",
    "Bundle / mix-and-match attach rate",
    "Loyalty signup rate at checkout",
    "Pre-order pickup completion rate",
    "Delivery order completion rate (where allowed)",
    "Promo / discount redemption rate",
    "Wait-time abandonment at peak",
    "Repeat-visit cadence",
  ],
  operational_variables: [
    "POS and menu accuracy vs in-stock inventory",
    "Inventory traceability into the state system (Metrc / BioTrack / Leaf, where applicable)",
    "Receiving and intake from licensed vendors",
    "Cycle counts and inventory variance reconciliation",
    "ID and age verification workflow",
    "Purchase-limit enforcement workflow",
    "Cash handling and drop procedure",
    "Cash deposit and armored-pickup cadence",
    "Compliance-sensitive task checklists (visibility support only)",
    "Vendor and license documentation organization",
    "Camera and security log retention",
    "Opening and closing checklists",
    "Waste / destruction logging",
    "Recall and hold procedure",
    "Delivery manifest workflow (where applicable)",
  ],
  financial_visibility: [
    "Gross margin by product category",
    "Gross margin by brand and SKU",
    "Discount and promo leakage by category",
    "Cash variance by shift",
    "Cash deposit reconciliation cadence",
    "Inventory variance value (overage / shortage)",
    "Dead stock and aged inventory value",
    "Vendor cost changes vs menu price",
    "Excise / sales tax accrual visibility",
    "Effective margin after taxes and fees",
    "Loyalty discount cost",
    "Daily sales-to-margin reporting cadence",
    "QuickBooks / Xero reconciliation cadence (where banking allows)",
    "Channel-level profitability (in-store vs delivery vs pickup)",
  ],
  owner_dependence_risks: [
    "Owner is the only person reconciling cash",
    "Owner approves every refund and discount exception",
    "Owner is the only menu / pricing manager",
    "Owner is the only person trained on the state traceability system",
    "Owner is the only person handling vendor and license paperwork",
    "Owner is the only person closing the register",
    "Owner is the only person investigating inventory variance",
    "Owner is the only contact for compliance audits and inspections",
    "Owner makes every staffing decision personally",
    "Owner runs all marketing personally",
    "Owner has sole admin access to POS and menu platform",
    "Owner is the only trainer for budtenders",
  ],
  staffing_labor: [
    "Budtender role clarity and section ownership",
    "Budtender product-knowledge training cadence",
    "Budtender upsell and bundle script consistency",
    "Manager-on-duty readiness for compliance-sensitive moments",
    "Onboarding time to first solo shift",
    "Cross-training across register, floor, and intake",
    "Cash handling certification per role",
    "ID / age verification training and refreshers",
    "Labor scheduling vs forecasted demand",
    "Overtime by role",
    "Turnover by role and exit-interview themes",
    "Performance expectations per role",
    "POS adoption per budtender",
    "Compliance-sensitive checklist completion per shift",
  ],
  customer_experience_handoff: [
    "Front-door ID and intake experience",
    "Waiting-room / queue communication",
    "Budtender greeting and consultation standard",
    "Menu and category education",
    "Allergen / potency / dosage communication (cannabis-product, not clinical)",
    "Checkout experience and wait time",
    "Pickup / delivery handoff (where allowed)",
    "Loyalty signup ask",
    "Receipt and purchase-limit communication",
    "Complaint and recovery handling",
    "Review request cadence",
    "Repeat-customer outreach (within state rules)",
  ],
  software_evidence_sources: [
    "Cannabis POS (Dutchie, Treez, Flowhub, Cova, etc.)",
    "Online menu / ordering platform (Dutchie, Weedmaps, Leafly)",
    "State traceability system (Metrc, BioTrack, Leaf — where applicable)",
    "Inventory management module of the POS",
    "Accounting (QuickBooks, Xero — where banking allows)",
    "Cash management / smart-safe vendor",
    "Payments (cash, debit, ACH, where allowed)",
    "Loyalty platform (within state rules)",
    "Email / SMS marketing platform (regulator-compliant)",
    "Review platforms (Google, Weedmaps, Leafly)",
    "Camera / security platform",
    "Vendor and license document storage",
    "Payroll / labor system (Paycom, ADP, Gusto)",
    "Spreadsheets used as systems of record",
  ],
  capacity_constraints: [
    "Square footage and customer-on-floor cap (state-specific)",
    "Register and budtender capacity at peak",
    "Vault and inventory storage capacity",
    "Cash handling and deposit capacity",
    "Vendor lead times and license-to-license transfers",
    "Delivery driver / vehicle capacity (where applicable)",
    "Compliance-sensitive checklist time per shift",
    "Owner availability as a hidden cap",
    "Manager-on-duty coverage",
    "Seasonal demand spikes (holidays, 4/20)",
    "Online order throughput",
    "Camera storage and retention capacity",
  ],
  margin_profitability: [
    "Gross margin by category (flower, vape, edibles, pre-rolls, accessories)",
    "Gross margin by brand",
    "Discount and promo leakage by category",
    "Loyalty discount cost",
    "Vendor cost changes vs current menu price",
    "Effective margin after excise and sales tax",
    "Dead stock and aged-inventory write-down cost",
    "Inventory variance / shrink cost",
    "Refund and exchange cost",
    "Payment processing and cash-management fees",
    "Channel-level margin (in-store vs delivery vs pickup)",
    "High-volume low-margin SKU traps",
    "Price-increase readiness and last menu update",
  ],
  industry_specific_failure_points: [
    "POS and inventory not reconciling to the state traceability system",
    "Menu pricing inconsistent across in-store, online, and third-party platforms",
    "Cash handling variance not investigated",
    "ID / age verification gaps at the door",
    "Purchase-limit enforcement gaps at the register",
    "Budtender upsell inconsistency suppressing ticket size",
    "Compliance-sensitive checklist gaps (visibility support only)",
    "Evidence and document readiness gaps for inspections",
    "Inventory aging and expiration risk where applicable",
    "Vendor and license documentation gaps",
    "Discount / promo stacking eroding margin",
    "Channel-level margin blind spots",
    "State-specific rules may apply — professional review may be required",
    "Not legal advice. Not a compliance guarantee.",
  ],
  repair_map_implications: SHARED_REPAIR_MAP_IMPLICATIONS,
  tool_report_mappings: SHARED_TOOL_REPORT_MAPPINGS,
  rgs_control_system_signals: SHARED_CONTROL_SIGNALS,
};

// --- GENERAL / MIXED SMALL BUSINESS ------------------------------------

const GENERAL: IndustryCatalog = {
  revenue_streams: [
    "Service-based revenue",
    "Product-based revenue",
    "Recurring / subscription revenue",
    "One-time project revenue",
    "Retainer / ongoing-engagement revenue",
    "Add-on and upsell revenue",
    "Repeat-customer revenue",
    "Referral-driven revenue",
    "Seasonal / event-driven revenue",
    "Wholesale / B2B revenue",
    "Online / ecommerce revenue",
    "Promotional / discount-driven revenue",
  ],
  lead_demand_sources: [
    "Organic search traffic",
    "Direct traffic",
    "Referrals",
    "Repeat customers",
    "Email list",
    "SMS list",
    "Paid search",
    "Paid social",
    "Google Business Profile",
    "Google Search Console insights",
    "Review platforms",
    "Social media",
    "Local partnerships",
    "Community events",
    "Phone calls",
    "Quote / inquiry forms",
    "Loyalty program",
    "Vendor / partner referrals",
  ],
  conversion_variables: [
    "Lead response time",
    "Phone answer rate",
    "Quote / proposal sent within 24 hours",
    "Estimate-to-close rate",
    "Proposal clarity and pricing readability",
    "Pricing objection patterns",
    "Owner-only approvals slowing close",
    "Sales script / talk-track consistency",
    "Upsell and cross-sell consistency",
    "Follow-up cadence on stalled leads",
    "Cart / checkout abandonment (where applicable)",
    "Booked-to-completed conversion",
  ],
  operational_variables: [
    "Workflow bottlenecks",
    "Task ownership and accountability",
    "SOP coverage",
    "Customer handoff points",
    "Quality-control checks",
    "Rework / revision rate",
    "Inventory or material handling (where applicable)",
    "Status tracking and visibility",
    "Exception handling and escalation",
    "Duplicate manual work between systems",
    "Tool / equipment readiness",
    "Capacity vs demand visibility",
    "Vendor and supplier coordination",
  ],
  financial_visibility: [
    "Revenue by product / service line",
    "Recurring vs one-time revenue split",
    "Gross margin",
    "Net margin",
    "Job / project profitability",
    "Labor cost as percentage of revenue",
    "AR aging buckets",
    "Cash flow timing vs payroll cycle",
    "Discount / promo leakage",
    "Owner draw visibility",
    "Fixed vs variable cost split",
    "Break-even visibility",
    "Budget vs actual",
    "Forecast vs actual",
    "QuickBooks / Xero reconciliation cadence",
  ],
  owner_dependence_risks: [
    "Owner approves every decision",
    "Owner does final estimates",
    "Owner handles all scheduling",
    "Owner handles every customer escalation",
    "Owner holds undocumented process knowledge",
    "Owner manages vendor ordering",
    "Owner controls every price",
    "Owner is the only closer",
    "Owner is the only trainer",
    "Owner performs manual reporting",
    "Owner does quality control on every job",
    "Owner is the only person reading the P&L",
    "Owner has sole admin access to core software",
    "Owner is the bottleneck in hiring and cash decisions",
  ],
  staffing_labor: [
    "Role clarity per position",
    "Onboarding time to productivity",
    "Cross-training across roles",
    "Manager / lead readiness",
    "Performance expectations per role",
    "Accountability and review cadence",
    "Tool / SOP adoption per team member",
    "Customer-facing communication standards",
    "Labor scheduling vs forecasted demand",
    "Overtime visibility",
    "Turnover by role",
    "Training records and certifications (where applicable)",
  ],
  customer_experience_handoff: [
    "Inquiry response time and tone",
    "Intake / booking flow clarity",
    "Quote / proposal clarity",
    "Onboarding and customer instructions",
    "Status updates during fulfillment",
    "Delivery / completion handoff",
    "Post-sale follow-up",
    "Review request cadence",
    "Complaint and refund handling",
    "Loyalty / retention touchpoints",
    "Appointment reminders",
    "Customer education on what to expect",
  ],
  software_evidence_sources: [
    "Accounting (QuickBooks, Xero, FreshBooks)",
    "CRM and pipeline (HubSpot, Salesforce, Pipedrive)",
    "Payments (Stripe, Square, PayPal)",
    "Email / SMS marketing platform",
    "Website analytics (Google Analytics)",
    "Search visibility (Google Search Console)",
    "Google Business Profile",
    "Paid ads dashboards (Google Ads, Meta Ads)",
    "Scheduling / booking software",
    "Project / task management software",
    "Review platforms",
    "Payroll / labor system (Paycom, ADP, Gusto)",
    "Document and file storage",
    "Spreadsheets used as systems of record",
  ],
  capacity_constraints: [
    "Available labor hours per week",
    "Owner availability as a hidden cap",
    "Cash constraints on growth",
    "Vendor and supplier lead times",
    "Software / tooling licenses",
    "Office / facility capacity",
    "Lead volume vs fulfillment capacity",
    "Manager / lead capacity",
    "Training capacity for new hires",
    "Seasonal demand spikes",
    "Customer-service phone / chat capacity",
    "Project pipeline capacity",
  ],
  margin_profitability: [
    "Gross margin by product / service line",
    "Net margin by month",
    "Job / project margin variance vs estimate",
    "Discount and promo leakage",
    "Refund and chargeback leakage",
    "Labor cost per delivered unit / hour",
    "Vendor cost changes vs current pricing",
    "Payment processing fees",
    "Marketing cost per acquired customer",
    "Lifetime value vs acquisition cost",
    "High-volume low-margin offering traps",
    "Low-volume high-margin opportunity gaps",
    "Price-increase readiness and last update date",
  ],
  industry_specific_failure_points: [
    "Unclear lead source tracking",
    "No revenue split by service or product line",
    "Weak follow-up on quotes and proposals",
    "Owner bottlenecks across the workflow",
    "Missing or unwritten SOPs",
    "Financial dashboard gaps",
    "Handoff inconsistency between roles",
    "Unclear accountability per task",
    "No review cadence (weekly / monthly)",
    "Forecast vs actual not compared",
    "Manual duplicate work between tools",
    "Repeat-customer touchpoints missing",
  ],
  repair_map_implications: SHARED_REPAIR_MAP_IMPLICATIONS,
  tool_report_mappings: SHARED_TOOL_REPORT_MAPPINGS,
  rgs_control_system_signals: SHARED_CONTROL_SIGNALS,
};

export const INDUSTRY_BRAIN_CATALOG: Record<IndustryKey, IndustryCatalog> = {
  trades_services: TRADES,
  restaurant_food_service: RESTAURANT,
  retail: RETAIL,
  cannabis_mmj_mmc: CANNABIS,
  general_small_business: GENERAL,
};

export function getIndustryCatalog(key: IndustryKey): IndustryCatalog {
  return INDUSTRY_BRAIN_CATALOG[key];
}

export function totalVariablesForIndustry(key: IndustryKey): number {
  const cat = INDUSTRY_BRAIN_CATALOG[key];
  return CATALOG_CATEGORIES.reduce((n, c) => n + cat[c].length, 0);
}