/** P93E-E2G — Cannabis / MMJ Dispensary Operations starter bank.
 *
 * SAFETY: This bank captures operational visibility and documentation
 * readiness only. It is NOT legal, tax, accounting, or compliance
 * certification, and does NOT guarantee regulatory compliance.
 */
import { CANNABIS_DISCLAIMER, type DiagnosticQuestion, type IndustryQuestionBank } from "../types";
const I = "cannabis_mmj_dispensary" as const;
const Q = (key: string, gear: DiagnosticQuestion["gear"], section: string, plain: string,
  extra: Partial<DiagnosticQuestion> = {}): DiagnosticQuestion => ({
  key: `cannabis.${key}`, industry: I, gear, section,
  plain_language_question: plain, answer_type: "narrative", capture: { notes: true }, ...extra,
});
const QUESTIONS: DiagnosticQuestion[] = [
  Q("bp_license_type", "business_profile", "License type",
    "What license type(s) do you operate under, and in what state?",
    { admin_only_notes: "Operational visibility only — do not advise on license terms." }),
  Q("bp_locations", "business_profile", "Locations",
    "How many locations, and what's the role of each (retail, cultivation, processing, delivery)?",
    { answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_team", "business_profile", "Team",
    "How is staffing structured — budtenders, lead, GM, security, compliance lead?"),
  Q("dg_foot_traffic", "demand", "Foot traffic",
    "Roughly how many customers per day, and how does it swing weekday vs weekend?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true, seasonal: true } }),
  Q("dg_loyalty", "demand", "Loyalty / repeat",
    "What share of customers are repeat, and is there a loyalty program?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_local_marketing", "demand", "Local marketing",
    "What's allowed in your market for marketing, and what are you actually doing?"),
  Q("rc_avg_basket", "sales", "Average basket",
    "What's the average basket size?",
    { business_term: "Average ticket", answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("rc_attach", "sales", "Attach / upsell",
    "How is attach / upsell trained at the counter?"),
  Q("op_pos", "operations", "POS / seed-to-sale",
    "What POS and seed-to-sale system are you on, and how often does manual reconciliation happen?",
    { source_of_truth_guidance: "POS / METRC / state seed-to-sale system",
      admin_only_notes: "Documentation visibility only — never represent as compliance certification." }),
  Q("op_inventory_variance", "operations", "Inventory variance",
    "What does inventory variance look like between physical count and system?",
    { repair_map_signal: "Inventory Variance Risk", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_sops_doc", "operations", "Documented SOPs",
    "What SOPs are written down today vs. in someone's head?"),
  Q("op_security", "operations", "Security / cash handling",
    "Walk me through cash handling and security at end of day."),
  Q("op_audit_readiness", "operations", "Audit / inspection readiness",
    "If a state inspector walked in tomorrow, how long would it take to pull the records they'd ask for?",
    { admin_only_notes: "Document readiness signal only — not a compliance guarantee." }),
  Q("fv_books", "financial", "Books status",
    "Who keeps the books, and how is 280E being handled in your reporting?",
    { admin_only_notes: "Operational visibility only — refer the client to a qualified cannabis CPA for 280E treatment." }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's average monthly revenue right now?",
    { answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true } }),
  Q("fv_cash_handling", "financial", "Cash handling cost",
    "Roughly what does cash handling and banking cost you each month?",
    { answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_taxes", "financial", "Tax filings",
    "Are state and excise tax filings current and on time?",
    { admin_only_notes: "Operational visibility only — confirm with qualified counsel / CPA." }),
  Q("oi_owner_role", "owner_independence", "Owner role",
    "What parts of operations still need you personally each week?",
    { repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_gm", "owner_independence", "GM coverage",
    "Is there a GM who can run the store and handle compliance documentation without you?"),
  Q("ev_pos_export", "evidence", "POS / seed-to-sale export",
    "Could you export the last 90 days of POS and seed-to-sale reports?",
    { evidence_prompt: "POS + state seed-to-sale (METRC) — last 90 days" }),
  Q("ev_sops", "evidence", "SOP samples",
    "Could you share two or three of your most-used SOPs?"),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent P&L?", { evidence_prompt: "Trailing 12-month P&L" }),
];
export const CANNABIS_MMJ_DISPENSARY_BANK: IndustryQuestionBank = {
  industry: I, label: "Cannabis / MMJ Dispensary Operations",
  disclaimer: CANNABIS_DISCLAIMER, questions: QUESTIONS,
};
