/**
 * P93E-E2G-P6 — Cannabis / MMJ Dispensary Operations full-depth diagnostic interview bank.
 *
 * Plain-English scripted interview, deep diagnostic structure for cannabis
 * retail / dispensary operators (single- and multi-location, MMJ and
 * adult-use where applicable) running POS + seed-to-sale workflows
 * (METRC / BioTrack / state systems referenced as manual export sources
 * unless a real live connector is wired).
 *
 * SAFETY BOUNDARY: This bank captures operational visibility and
 * documentation-readiness only. It is NOT legal advice, tax advice,
 * accounting advice, fiduciary advice, healthcare advice, patient-care
 * advice, product/medical advice, or compliance certification, and does
 * NOT promise regulatory compliance. References to 280E, METRC,
 * BioTrack, and seed-to-sale systems are operational/documentation-process
 * visibility only and must always be coordinated with a qualified
 * cannabis CPA and qualified counsel.
 */
import { CANNABIS_DISCLAIMER, type DiagnosticQuestion, type IndustryQuestionBank } from "../types";

const I = "cannabis_mmj_dispensary" as const;

const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `cannabis.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

const CDD = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  parent: string,
  triggerWhen: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "conditional_deep_dive",
    parent_key: `cannabis.${parent}`,
    trigger_when: triggerWhen,
    ...extra,
  });

const EV = (
  key: string,
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, "evidence", section, plain, {
    prompt_kind: "evidence_source_of_truth",
    ...extra,
  });

const ADM = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "admin_interpretation_support",
    ...extra,
  });

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile ─────────────────────────────────────────────
  Q("bp_license_type", "business_profile", "License type",
    "What license type(s) do you operate under, and in what state?",
    { business_term: "License type and state",
      admin_only_notes: "Operational visibility only. Never advise on license terms or state-specific legal conclusions." }),
  Q("bp_operation_model", "business_profile", "Operation model",
    "Are you medical-only, adult-use, or both, and do you do delivery, curbside, or in-store only?",
    { business_term: "Operation model" }),
  Q("bp_locations", "business_profile", "Locations",
    "How many locations do you run, and what's the role of each (retail, cultivation, processing, delivery)?",
    { business_term: "Location footprint",
      answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_team", "business_profile", "Team",
    "How is staffing structured — budtenders, lead, GM, security, inventory lead, admin?",
    { business_term: "Staffing structure" }),
  Q("bp_hours", "business_profile", "Hours",
    "What are your operating hours, and which days or shifts are busiest?",
    { business_term: "Hours of operation" }),
  Q("bp_brands_carried", "business_profile", "Brands carried",
    "Roughly how many brands and SKUs do you carry today, and which categories anchor the menu?",
    { business_term: "Brand and SKU footprint" }),
  Q("bp_target_customer", "business_profile", "Target customer",
    "In plain words, who is your typical customer and what brings them in?",
    { business_term: "Target customer" }),
  Q("bp_competitors", "business_profile", "Competitive landscape",
    "Who are your two or three closest competitors, and what makes customers choose you over them?",
    { business_term: "Competitive landscape" }),
  Q("bp_growth_goal", "business_profile", "Growth ambition",
    "Over the next 12 months, are you focused on holding steady, growing this store, or opening another location?",
    { business_term: "12-month growth ambition" }),
  // ── Demand Generation ────────────────────────────────────────────
  Q("dg_customer_source", "demand", "Customer source",
    "How do most customers find or return to the store right now?",
    { business_term: "Customer source and repeat-visit visibility",
      report_finding_seed: "Primary customer source mix is informal and not measured.",
      repair_map_trigger_seed: "customer_source_visibility_install" }),
  Q("dg_repeat_rate", "demand", "Repeat customers",
    "Roughly what share of weekly customers are repeat vs. first-time?",
    { business_term: "Repeat customer share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_loyalty_program", "demand", "Loyalty / rewards",
    "Do you run a loyalty or rewards program where allowed, and how is it tracked?",
    { business_term: "Loyalty / rewards program" }),
  Q("dg_online_menu", "demand", "Online menu",
    "What online menu do customers see (Dutchie, Weedmaps, Leafly, your own site), and who keeps it updated?",
    { business_term: "Online menu surfaces" }),
  Q("dg_menu_accuracy", "demand", "Menu accuracy",
    "How often does the online menu match what's actually on the shelf?",
    { business_term: "Menu accuracy",
      report_finding_seed: "Online menu accuracy vs. shelf inventory is owner-estimated.",
      repair_map_trigger_seed: "menu_inventory_sync_install" }),
  Q("dg_reviews", "demand", "Reviews and reputation",
    "Where do most reviews land (Google, Weedmaps, Leafly), and who reads and responds to them?",
    { business_term: "Review and reputation visibility" }),
  Q("dg_seasonality", "demand", "Local market seasonality",
    "What seasonal patterns shape demand at this store across the year?",
    { business_term: "Local market seasonality",
      capture: { notes: true, seasonal: true } }),
  Q("dg_traffic_pattern", "demand", "Day and time traffic",
    "Which days and time blocks are clearly your peaks, and which are clearly your lulls?",
    { business_term: "Traffic patterns by day and time" }),
  Q("dg_product_visibility", "demand", "New product visibility",
    "When a new product or restock arrives, how do regular customers learn about it?",
    { business_term: "New product visibility" }),
  Q("dg_brand_recall", "demand", "Brand recall",
    "If a customer described you in one sentence to a friend, what would they say?",
    { business_term: "Brand and store recall" }),
  Q("dg_referrals", "demand", "Referrals and word of mouth",
    "How much of your traffic comes from friend-to-friend referrals, and is that tracked?",
    { business_term: "Referral and word-of-mouth pattern" }),
  Q("dg_channel_concentration", "demand", "Channel concentration",
    "If your top customer source dropped tomorrow, how exposed is the store?",
    { business_term: "Customer-source concentration" }),
  Q("dg_communication_channel", "demand", "Customer communication",
    "Where allowed, how do you communicate with customers (text, email, in-store), and how often?",
    { business_term: "Customer communication process" }),

  CDD("dg_cdd_menu_mismatch", "demand", "Menu mismatch",
    "dg_menu_accuracy",
    "When the owner says menu and inventory are 'usually close' or mismatch is informal.",
    "When the menu doesn't match the shelf, who notices first and how is it corrected?",
    { admin_interpretation: "Treat 'usually close' as menu/POS/inventory sync gap until cadence and ownership are documented.",
      report_finding_seed: "Menu / POS / inventory sync correction process is informal.",
      repair_map_trigger_seed: "menu_inventory_sync_install" }),
  CDD("dg_cdd_review_response", "demand", "Review response process",
    "dg_reviews",
    "When review responses are inconsistent, owner-only, or no documented cadence.",
    "Walk me through what happens when a one- or two-star review lands.",
    { admin_interpretation: "Lack of a written response cadence = reputation-handling gap and owner-bottleneck signal." }),
  CDD("dg_cdd_repeat_untracked", "demand", "Repeat rate untracked",
    "dg_repeat_rate",
    "When repeat-rate is owner-estimated, not pulled from POS or loyalty data.",
    "Where would we look to confirm the repeat-customer share you described?",
    { source_of_truth_guidance: "POS customer report or loyalty platform export.",
      report_finding_seed: "Repeat-customer share is owner estimate without POS or loyalty confirmation." }),
  CDD("dg_cdd_channel_concentration", "demand", "Channel concentration drilldown",
    "dg_channel_concentration",
    "When one source (Dutchie, Weedmaps, Leafly, or walk-in) appears to drive majority of traffic.",
    "Roughly what share of weekly visits comes from that top source?",
    { admin_interpretation: "Top-source share above ~60% = customer-source concentration risk.",
      report_finding_seed: "Most visits depend on a single customer source.",
      repair_map_trigger_seed: "customer_source_diversification_install" }),
  CDD("dg_cdd_traffic_swings", "demand", "Traffic swings unmanaged",
    "dg_traffic_pattern",
    "When peaks and lulls are known but staffing or product availability isn't adjusted to them.",
    "When you spot a peak coming, what changes in staffing, prep, or inventory?"),
  CDD("dg_cdd_communication_frequency", "demand", "Communication frequency",
    "dg_communication_channel",
    "When customer communication is ad-hoc, owner-driven, or has no schedule.",
    "How often does a typical customer hear from you in a month, and who hits send?"),
  CDD("dg_cdd_new_product_launch", "demand", "New product launch process",
    "dg_product_visibility",
    "When new product visibility is informal, word-of-mouth only, or staff-dependent.",
    "When a new SKU lands, what are the steps from receiving to customers knowing it's available?"),
  // ── Revenue Conversion ───────────────────────────────────────────
  Q("rc_walkin_conversion", "sales", "Walk-in conversion",
    "Out of customers who walk in or place an order online, roughly what share end up purchasing?",
    { business_term: "Walk-in / online conversion rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_online_to_visit", "sales", "Online to visit",
    "If you offer online ordering or reservations, how often does an online order turn into a pickup or in-store visit?",
    { business_term: "Online-order to visit conversion" }),
  Q("rc_avg_basket", "sales", "Average basket",
    "What's the average basket size today?",
    { business_term: "Average basket / ticket",
      answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("rc_items_per_ticket", "sales", "Items per ticket",
    "On a typical ticket, how many items do customers usually buy?",
    { business_term: "Items per ticket",
      answer_type: "numeric", capture: { notes: true, estimated_value: true } }),
  Q("rc_category_mix", "sales", "Category mix",
    "Roughly how does revenue split across flower, pre-rolls, vapes, edibles, concentrates, and accessories?",
    { business_term: "Product category mix" }),
  Q("rc_budtender_consistency", "sales", "Budtender consistency",
    "How consistent is the customer experience from one budtender to the next?",
    { business_term: "Budtender consistency" }),
  Q("rc_education_process", "sales", "Product education process",
    "How are budtenders trained to talk about products as retail staff, not as medical or healthcare advisors?",
    { business_term: "Product education process",
      admin_only_notes: "Frame strictly as retail product education and operations. Never as medical, patient-care, or healthcare advice." }),
  Q("rc_addon_process", "sales", "Add-on / cross-sell",
    "Where allowed, how do budtenders suggest add-ons or complementary items?",
    { business_term: "Add-on / cross-sell process" }),
  Q("rc_purchase_limit", "sales", "Purchase limit handling",
    "Walk me through how budtenders confirm purchase limits at the counter as part of the operating process.",
    { business_term: "Purchase-limit operating process",
      admin_only_notes: "Operational process visibility only — not a regulatory determination." }),
  Q("rc_id_checkin", "sales", "ID and check-in",
    "What's the flow from front-door ID check to budtender handoff?",
    { business_term: "ID / check-in handoff" }),
  Q("rc_queue_wait", "sales", "Queue and wait time",
    "Roughly how long do customers wait at peak, and what triggers a queue intervention?",
    { business_term: "Queue / wait-time process" }),
  Q("rc_loyalty_conversion", "sales", "Loyalty conversion",
    "Where allowed, how does loyalty / rewards translate into repeat visits and bigger baskets?",
    { business_term: "Loyalty conversion" }),
  Q("rc_discount_process", "sales", "Discount and promo process",
    "Where allowed, who can run discounts or promos, and how is approval recorded?",
    { business_term: "Discount / promo process" }),
  Q("rc_complaint_recovery", "sales", "Complaint recovery",
    "When a customer is unhappy at the counter, what's the recovery flow and who owns the resolution?",
    { business_term: "Complaint recovery handoff" }),

  CDD("rc_cdd_walkin_untracked", "sales", "Walk-in conversion untracked",
    "rc_walkin_conversion",
    "When walk-in conversion is owner-estimated and not pulled from POS traffic counters.",
    "Where would we confirm the walk-in conversion number you just gave me?",
    { source_of_truth_guidance: "POS traffic counter report or door counter export.",
      report_finding_seed: "Walk-in conversion is owner estimate without door-count or POS confirmation." }),
  CDD("rc_cdd_basket_flat", "sales", "Basket flat",
    "rc_avg_basket",
    "When average basket has been flat or unknown for 6+ months.",
    "When did average basket last move noticeably, and what changed?",
    { repair_map_trigger_seed: "basket_growth_review" }),
  CDD("rc_cdd_category_unknown", "sales", "Category mix unknown",
    "rc_category_mix",
    "When category split is owner-estimated rather than pulled from POS reports.",
    "Could we pull the last 30 days of POS sales by category to confirm the split?",
    { source_of_truth_guidance: "POS sales-by-category report — last 30 days." }),
  CDD("rc_cdd_budtender_variance", "sales", "Budtender variance",
    "rc_budtender_consistency",
    "When the owner names one or two budtenders as much stronger sellers than others.",
    "What does the strongest budtender do differently that's not yet written down?",
    { report_finding_seed: "Budtender performance variance is not documented or transferred." }),
  CDD("rc_cdd_education_inconsistent", "sales", "Education inconsistent",
    "rc_education_process",
    "When budtender training is informal, verbal, or differs by shift.",
    "Walk me through what a brand-new budtender learns in their first week.",
    { admin_only_notes: "Training depth signal only — never frame as medical or healthcare instruction." }),
  CDD("rc_cdd_discount_overuse", "sales", "Discount overuse",
    "rc_discount_process",
    "When discounts feel frequent, blanket, or used to cover slow days.",
    "On a typical week, what share of tickets have a discount applied?",
    { repair_map_trigger_seed: "discount_margin_review" }),
  CDD("rc_cdd_complaint_dropoff", "sales", "Complaint drop-off",
    "rc_complaint_recovery",
    "When complaints are handled verbally and not logged.",
    "Where do complaints land after the counter, and who reads them later?",
    { report_finding_seed: "Customer complaints are not logged or routed for review." }),
  CDD("rc_cdd_queue_threshold", "sales", "Queue exceeds threshold",
    "rc_queue_wait",
    "When peak waits regularly exceed 10–15 minutes with no queue protocol.",
    "When the line gets long, who calls it, and what happens next?"),
  // ── Operational Efficiency ───────────────────────────────────────
  Q("op_pos", "operations", "POS system",
    "What POS system do you run, and how is it set up day to day?",
    { business_term: "Point-of-sale system",
      source_of_truth_guidance: "POS configuration screenshot or admin export." }),
  Q("op_seed_to_sale", "operations", "Seed-to-sale system",
    "What seed-to-sale system are you on (METRC, BioTrack, state system), and who is the daily operator?",
    { business_term: "Seed-to-sale system",
      admin_only_notes: "Documentation-process visibility only — never represent as compliance certification or regulatory approval." }),
  Q("op_receiving", "operations", "Inventory receiving",
    "Walk me through what happens from the moment a vendor delivery shows up to the products being on the floor.",
    { business_term: "Inventory receiving workflow" }),
  Q("op_manifest_intake", "operations", "Manifest intake",
    "How are manifests checked against what physically arrives, and who signs off?",
    { business_term: "Manifest intake process" }),
  Q("op_reconciliation_cadence", "operations", "Reconciliation cadence",
    "How often is system inventory reconciled against the physical count?",
    { business_term: "Inventory reconciliation cadence",
      report_finding_seed: "Inventory reconciliation cadence is informal or owner-estimated.",
      repair_map_trigger_seed: "inventory_reconciliation_install" }),
  Q("op_count_cadence", "operations", "Count cadence",
    "How often do staff perform full or partial inventory counts?",
    { business_term: "Inventory count cadence" }),
  Q("op_discrepancy_handling", "operations", "Discrepancy handling",
    "When a count doesn't match the system, what's the documented next step?",
    { business_term: "Discrepancy handling process",
      report_finding_seed: "Inventory discrepancies are handled verbally and not tracked to closure.",
      repair_map_trigger_seed: "discrepancy_closure_install" }),
  Q("op_stop_sell", "operations", "Stop-sell process",
    "If a product needs to be pulled from sale, what's the documented stop-sell or hold process?",
    { business_term: "Stop-sell / hold process" }),
  Q("op_waste_logging", "operations", "Waste logging",
    "Walk me through how waste is logged from identification to system entry.",
    { business_term: "Waste logging process" }),
  Q("op_quarantine", "operations", "Quarantine / hold",
    "When product needs to be quarantined or held back, where does it physically go and how is that recorded?",
    { business_term: "Quarantine / hold process" }),
  Q("op_tag_label_integrity", "operations", "Tag and label integrity",
    "When a tag or label is wrong, who fixes it, and where is the correction recorded?",
    { business_term: "Tag / label integrity process" }),
  Q("op_menu_pos_inventory_sync", "operations", "Menu / POS / inventory sync",
    "How does the online menu, POS inventory, and physical shelf stay aligned during the day?",
    { business_term: "Menu / POS / inventory sync process" }),
  Q("op_purchase_limit_control", "operations", "Purchase-limit process control",
    "How does the POS or process protect against accidental over-limit sales?",
    { business_term: "Purchase-limit process control",
      admin_only_notes: "Operational process visibility only — not a regulatory conclusion." }),
  Q("op_cash_drawer_flow", "operations", "Cash drawer flow",
    "Walk me through cash flow at the register from open to close.",
    { business_term: "Cash drawer operating flow" }),
  Q("op_drawer_closeout", "operations", "Drawer closeout",
    "What's the drawer closeout process, and where are variances recorded?",
    { business_term: "Drawer closeout process" }),
  Q("op_safe_drop", "operations", "Safe / drop process",
    "Walk me through the safe and drop process during the day and at close.",
    { business_term: "Safe / drop process" }),
  Q("op_deposit_cadence", "operations", "Deposit cadence",
    "How often does cash leave the store for deposit, and who handles it?",
    { business_term: "Deposit cadence" }),
  Q("op_camera_review", "operations", "Camera and security review",
    "How often are camera coverage, retention, and alarm logs reviewed as an operating process?",
    { business_term: "Camera / security operating review",
      admin_only_notes: "Operational process visibility only — not a security or regulatory determination." }),
  Q("op_visitor_protocol", "operations", "Visitor protocol",
    "What's the visitor protocol, and where are visitor logs kept?",
    { business_term: "Visitor protocol" }),
  Q("op_badge_training_records", "operations", "Badge / training records",
    "Where do staff badges, renewals, and training records live, and how easy are they to find?",
    { business_term: "Badge / training records" }),
  Q("op_opening", "operations", "Opening procedure",
    "Walk me through the opening procedure from first key in the door.",
    { business_term: "Opening procedure" }),
  Q("op_closing", "operations", "Closing procedure",
    "Walk me through the closing procedure from last customer to alarm set.",
    { business_term: "Closing procedure" }),
  Q("op_shift_handoff", "operations", "Shift handoff",
    "How do shifts hand off — what's said, what's written down?",
    { business_term: "Shift handoff process" }),
  Q("op_vendor_receiving", "operations", "Vendor receiving workflow",
    "Beyond the manifest, what does a clean vendor receiving event look like end to end?",
    { business_term: "Vendor receiving workflow" }),

  CDD("op_cdd_recon_reactive", "operations", "Reactive reconciliation",
    "op_reconciliation_cadence",
    "When reconciliation only happens after something looks off.",
    "When was the last time a reconciliation was run because of cadence, not because of a problem?",
    { admin_interpretation: "Reactive-only reconciliation = documentation-velocity risk and inventory-reconciliation risk.",
      report_finding_seed: "Reconciliation is reactive rather than scheduled.",
      repair_map_trigger_seed: "inventory_reconciliation_install" }),
  CDD("op_cdd_manifest_mismatch", "operations", "Manifest mismatch",
    "op_manifest_intake",
    "When manifest mismatches are handled by phone or memory rather than written notes.",
    "When the manifest doesn't match what arrived, where does that discrepancy get written down?",
    { report_finding_seed: "Manifest mismatches are not consistently documented." }),
  CDD("op_cdd_discrepancy_informal", "operations", "Informal discrepancy",
    "op_discrepancy_handling",
    "When discrepancies are escalated verbally and not tracked to closure.",
    "Where would I see the trail from spotted discrepancy to fix and sign-off?",
    { source_of_truth_guidance: "Discrepancy log or reconciliation note file." }),
  CDD("op_cdd_stopsell_undocumented", "operations", "Stop-sell undocumented",
    "op_stop_sell",
    "When stop-sell or hold is verbal-only or inconsistent across shifts.",
    "If a stop-sell happened tonight, what would the next shift see in writing tomorrow morning?",
    { repair_map_trigger_seed: "stop_sell_process_install" }),
  CDD("op_cdd_waste_verbal", "operations", "Waste logged late or verbally",
    "op_waste_logging",
    "When waste is logged hours later, batched, or only known to one person.",
    "From the moment waste is identified, how long until it's recorded in writing?",
    { repair_map_trigger_seed: "waste_logging_process_install" }),
  CDD("op_cdd_tag_corrections", "operations", "Tag / label corrections untracked",
    "op_tag_label_integrity",
    "When tag/label corrections aren't logged or counted.",
    "Roughly how many tag or label corrections happen in a typical week, and where are they recorded?"),
  CDD("op_cdd_menu_sync_breaks", "operations", "Menu sync breaks",
    "op_menu_pos_inventory_sync",
    "When menu and shelf drift more than once a week, or sync is one person's job.",
    "Who notices first when menu, POS, and shelf drift apart, and what's the fix?",
    { repair_map_trigger_seed: "menu_inventory_sync_install" }),
  CDD("op_cdd_cash_variance_trend", "operations", "Cash variance trend",
    "op_drawer_closeout",
    "When closeout variances happen but aren't trended or reviewed by name.",
    "How are repeat cash variances spotted across drawers and shifts?",
    { source_of_truth_guidance: "Drawer closeout / variance log." }),
  CDD("op_cdd_drawer_skim_risk", "operations", "Drawer skim risk",
    "op_safe_drop",
    "When drops are infrequent, large, or not witnessed.",
    "Walk me through who is in the room, and who signs, when a drop is made.",
    { admin_interpretation: "Solo, unwitnessed drops = cash-control documentation gap." }),
  CDD("op_cdd_visitor_logs_informal", "operations", "Visitor logs informal",
    "op_visitor_protocol",
    "When visitor logs are paper, ad-hoc, or not retained.",
    "Where would we find last month's visitor log, and how complete is it?",
    { repair_map_trigger_seed: "visitor_log_process_install" }),
  CDD("op_cdd_badge_expiry", "operations", "Badge expiry untracked",
    "op_badge_training_records",
    "When badge renewals aren't tracked to a calendar.",
    "Who watches badge renewal dates, and how far ahead do they get flagged?",
    { repair_map_trigger_seed: "badge_training_tracker_install" }),
  CDD("op_cdd_security_review_skipped", "operations", "Security review skipped",
    "op_camera_review",
    "When camera coverage and alarm logs aren't reviewed on a fixed cadence.",
    "When was the last time someone confirmed camera coverage and retention as part of an operating routine?"),
  CDD("op_cdd_incident_undocumented", "operations", "Incident undocumented",
    "op_closing",
    "When near-miss or incident events aren't written up.",
    "How do near-misses or in-store incidents get documented after they happen?",
    { source_of_truth_guidance: "Incident log or shift report file." }),
  // ── Financial Visibility ─────────────────────────────────────────
  Q("fv_books_owner", "financial", "Bookkeeping owner",
    "Who keeps the books — in-house, a bookkeeper, or a cannabis-specific CPA?",
    { business_term: "Bookkeeping owner",
      admin_only_notes: "Operational visibility only. Refer the client to a qualified cannabis CPA for 280E and tax treatment." }),
  Q("fv_margin_by_category", "financial", "Margin by category",
    "Do you currently see gross margin broken out by product category, and how often?",
    { business_term: "Gross margin by category",
      report_finding_seed: "Gross margin by category is not reviewed on a fixed cadence.",
      repair_map_trigger_seed: "category_margin_review_install" }),
  Q("fv_product_profitability", "financial", "Product profitability",
    "Which categories or top SKUs do you believe are most and least profitable today?",
    { business_term: "Product / category profitability" }),
  Q("fv_inventory_cash_tied", "financial", "Inventory cash tied up",
    "Roughly how much cash is sitting in inventory right now?",
    { business_term: "Inventory cash position",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_inventory_aging", "financial", "Inventory aging",
    "How is aging or slow-moving inventory spotted, and how often is that reviewed?",
    { business_term: "Inventory aging review" }),
  Q("fv_shrink_cost", "financial", "Shrink and discrepancy cost",
    "Roughly what does inventory shrink and discrepancies cost you in a typical month?",
    { business_term: "Shrink / discrepancy cost",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_waste_cost", "financial", "Waste cost",
    "Roughly what does logged waste cost you in a typical month?",
    { business_term: "Monthly waste cost",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_cash_visibility", "financial", "Cash management visibility",
    "How clearly can you see how much cash is on hand across drawers, safe, and pending deposit?",
    { business_term: "Cash management visibility" }),
  Q("fv_deposit_process", "financial", "Deposit process",
    "Walk me through how cash gets from the safe to whatever banking or processor channel you use.",
    { business_term: "Cash deposit process",
      admin_only_notes: "Operational visibility only — not banking, processor, or financial-services advice." }),
  Q("fv_vendor_bills", "financial", "Vendor bills",
    "How are vendor bills tracked from receipt to payment, and who approves payment?",
    { business_term: "Vendor bills process" }),
  Q("fv_cogs_visibility", "financial", "COGS visibility",
    "How clearly is COGS broken out so a CPA can use it for tax and 280E coordination?",
    { business_term: "COGS visibility for CPA coordination",
      admin_only_notes: "CPA/tax-professional coordinated visibility only — not 280E or tax direction." }),
  Q("fv_280e_visibility", "financial", "280E-aware bookkeeping",
    "Is your bookkeeping currently set up so a cannabis CPA can work 280E cleanly, or is that still being built?",
    { business_term: "280E-aware bookkeeping (CPA coordinated visibility)",
      admin_only_notes: "Reference 280E ONLY as CPA/tax-professional coordinated visibility. Never advise on 280E treatment, position, or strategy." }),
  Q("fv_tax_set_aside", "financial", "Tax set-aside cash planning",
    "Do you set aside cash for tax obligations on a schedule, in coordination with your CPA?",
    { business_term: "Tax set-aside cash planning (CPA coordinated)",
      admin_only_notes: "Operational cash planning visibility only. Never advise on tax amount, treatment, or filings." }),
  Q("fv_pos_acct_recon", "financial", "POS / accounting reconciliation",
    "How often is POS revenue reconciled against accounting, and who owns the reconciliation?",
    { business_term: "POS / accounting reconciliation" }),
  Q("fv_processor_constraints", "financial", "Processor / banking constraints",
    "What are the practical processor and banking constraints you operate under day to day?",
    { business_term: "Processor / banking operating constraints",
      admin_only_notes: "Operational visibility only — not banking or financial-services advice." }),
  Q("fv_payroll", "financial", "Payroll and labor",
    "Roughly what does payroll and labor cost you per week, and how is it trending?",
    { business_term: "Payroll / labor cost",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_fixed_costs", "financial", "Rent / security / insurance",
    "What are your big fixed costs each month — rent, security, insurance — and how are they trending?",
    { business_term: "Fixed-cost visibility" }),
  Q("fv_discount_margin", "financial", "Discount margin impact",
    "Where allowed, do you measure how discounts and promos affect category margin?",
    { business_term: "Discount / promo margin impact" }),
  Q("fv_sales_by_category", "financial", "Sales by category",
    "How often do you review sales by category, and who reads it?",
    { business_term: "Sales by category review" }),
  Q("fv_daily_sales_review", "financial", "Daily / weekly sales review",
    "Is there a daily or weekly sales review that the manager or owner runs from a real number?",
    { business_term: "Daily / weekly sales review cadence" }),
  Q("fv_breakeven", "financial", "Break-even awareness",
    "Roughly how much revenue per day or week does this store need to break even right now?",
    { business_term: "Break-even awareness" }),
  Q("fv_cash_runway", "financial", "Cash runway",
    "If revenue dropped by a third for 60 days, how clearly could you see what you'd need to cut and when?",
    { business_term: "Cash runway visibility" }),

  CDD("fv_cdd_margin_not_by_cat", "financial", "Margin not by category",
    "fv_margin_by_category",
    "When margin is only seen at store-level, not by category.",
    "Could we pull a margin-by-category view from the POS or accounting today?",
    { source_of_truth_guidance: "POS or accounting category margin report.",
      repair_map_trigger_seed: "category_margin_review_install" }),
  CDD("fv_cdd_cogs_unclear", "financial", "COGS unclear",
    "fv_cogs_visibility",
    "When COGS is described as 'roughly' or only the CPA understands it.",
    "If we asked the CPA for a COGS breakout today, how confident would they be in it?",
    { admin_interpretation: "Unclear COGS = downstream 280E/tax-professional coordination risk; refer to qualified cannabis CPA." }),
  CDD("fv_cdd_280e_unclear", "financial", "280E coordination unclear",
    "fv_280e_visibility",
    "When 280E is described as 'the CPA handles it' with no shared visibility.",
    "What does the owner currently see about 280E-related categorization, even at a high level?",
    { admin_only_notes: "Refer to qualified cannabis CPA. RGS provides operational visibility only.",
      repair_map_trigger_seed: "cogs_280e_visibility_install" }),
  CDD("fv_cdd_processor_disruption", "financial", "Processor disruption history",
    "fv_processor_constraints",
    "When processor or banking interruptions have happened in the last 12 months.",
    "When was the most recent processor or banking interruption, and how was it handled operationally?"),
  CDD("fv_cdd_deposit_irregular", "financial", "Deposits irregular",
    "fv_deposit_process",
    "When deposit cadence is inconsistent or owner-only.",
    "What determines whether a deposit happens on a given day?",
    { repair_map_trigger_seed: "cash_handling_visibility_install" }),
  CDD("fv_cdd_payroll_trend", "financial", "Payroll trend",
    "fv_payroll",
    "When payroll-as-share-of-revenue trend is not reviewed.",
    "How do you know whether payroll is rising or falling as a share of revenue?"),
  CDD("fv_cdd_discount_leak", "financial", "Discount margin leak",
    "fv_discount_margin",
    "When discount frequency is high but margin impact isn't measured.",
    "Roughly how much margin do discounts cost in a typical week?",
    { repair_map_trigger_seed: "discount_margin_review" }),
  CDD("fv_cdd_breakeven_unknown", "financial", "Break-even unknown",
    "fv_breakeven",
    "When daily or weekly break-even isn't a number the owner can say out loud.",
    "If we sat down today, could we calculate the daily break-even from your fixed and variable costs?",
    { repair_map_trigger_seed: "breakeven_visibility_install" }),
  CDD("fv_cdd_runway_short", "financial", "Cash runway short",
    "fv_cash_runway",
    "When the owner can't articulate a 60–90 day downside plan.",
    "If you had to cut costs to survive a 60-day downturn, what's the first lever?"),
  // ── Owner Independence ───────────────────────────────────────────
  Q("oi_owner_role", "owner_independence", "Owner role",
    "Which parts of operations and admin still need you personally each week?",
    { business_term: "Owner / admin task dependency",
      report_finding_seed: "Several core operating tasks still depend on the owner personally.",
      repair_map_trigger_seed: "owner_admin_redundancy_install" }),
  Q("oi_seed_to_sale_owner", "owner_independence", "Seed-to-sale owner",
    "Who is the primary daily operator of the seed-to-sale system, and who is the trained backup?",
    { business_term: "Seed-to-sale operator coverage" }),
  Q("oi_metrc_knowledge", "owner_independence", "METRC / BioTrack knowledge",
    "If your seed-to-sale operator was out for a week, who would carry the workflow without help?",
    { business_term: "Seed-to-sale knowledge redundancy",
      report_finding_seed: "Seed-to-sale workflow knowledge sits with one person." }),
  Q("oi_manager_authority", "owner_independence", "Manager authority",
    "What decisions can your GM or store manager make without checking with you?",
    { business_term: "Manager decision authority" }),
  Q("oi_inventory_lead_authority", "owner_independence", "Inventory lead authority",
    "Who can sign off on receiving, counts, and reconciliation when the inventory lead is away?",
    { business_term: "Inventory lead redundancy" }),
  Q("oi_cash_redundancy", "owner_independence", "Cash-handling redundancy",
    "How many trained people can run a clean drawer closeout, safe drop, and deposit?",
    { business_term: "Cash-handling redundancy" }),
  Q("oi_receiving_redundancy", "owner_independence", "Receiving redundancy",
    "How many trained people can receive a vendor delivery start to finish?",
    { business_term: "Vendor receiving redundancy" }),
  Q("oi_training_redundancy", "owner_independence", "Training and documentation",
    "Where do trained processes live in writing, vs. only in someone's head?",
    { business_term: "Training / documentation redundancy" }),
  Q("oi_escalation", "owner_independence", "Escalation process",
    "When something goes wrong on the floor, what's the documented escalation path?",
    { business_term: "Escalation process" }),
  Q("oi_documented_coverage", "owner_independence", "Documented process coverage",
    "Roughly what share of your operating processes are written down today?",
    { business_term: "Documented process coverage",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("oi_visitor_owner", "owner_independence", "Visitor protocol owner",
    "Who owns the visitor protocol and the visitor log day to day?",
    { business_term: "Visitor protocol owner" }),
  Q("oi_vacation_test", "owner_independence", "Vacation test",
    "If you took two unplanned weeks off starting tomorrow, what would break first?",
    { business_term: "Vacation test",
      report_finding_seed: "Two-week owner absence would break at least one core operating process.",
      repair_map_trigger_seed: "vacation_test_install" }),

  CDD("oi_cdd_one_person_seed_to_sale", "owner_independence", "One-person seed-to-sale risk",
    "oi_metrc_knowledge",
    "When only one person can operate the seed-to-sale system end to end.",
    "If that person quit Friday, what's the realistic catch-up plan for the next 30 days?",
    { admin_interpretation: "One-person seed-to-sale = key-person and documentation-readiness risk.",
      repair_map_trigger_seed: "seed_to_sale_redundancy_install" }),
  CDD("oi_cdd_manager_limited", "owner_independence", "Manager authority limited",
    "oi_manager_authority",
    "When the GM or manager can't make routine operating decisions without owner approval.",
    "Where is the line between what the manager can decide and what comes back to you?"),
  CDD("oi_cdd_no_cash_redundancy", "owner_independence", "No cash redundancy",
    "oi_cash_redundancy",
    "When only one or two people can close drawers and run deposits.",
    "What's the cross-training plan to add at least one more closer in the next 60 days?",
    { repair_map_trigger_seed: "cash_handling_redundancy_install" }),
  CDD("oi_cdd_no_receiving_backup", "owner_independence", "No receiving backup",
    "oi_receiving_redundancy",
    "When only one person owns vendor receiving.",
    "If that person calls in tomorrow, who walks the next vendor delivery from truck to shelf?"),
  CDD("oi_cdd_escalation_undefined", "owner_independence", "Escalation undefined",
    "oi_escalation",
    "When escalation is described as 'they call me' with no written ladder.",
    "Where would I find the escalation ladder in writing today?",
    { repair_map_trigger_seed: "escalation_documentation_install" }),
  CDD("oi_cdd_vacation_impossible", "owner_independence", "Vacation impossible",
    "oi_vacation_test",
    "When the owner says a two-week absence is not currently feasible.",
    "What are the top three jobs you'd need to delegate to make a two-week absence possible?",
    { report_finding_seed: "Owner cannot currently take a two-week absence without operational breakage." }),
  // ── Evidence / Source of Truth ───────────────────────────────────
  EV("ev_pos_export", "POS reports",
    "Could you export the last 90 days of POS sales and traffic reports?",
    { evidence_prompt: "POS sales + traffic reports — last 90 days." }),
  EV("ev_seed_to_sale_export", "Seed-to-sale system export",
    "Could you export the last 90 days of seed-to-sale activity from your state system?",
    { evidence_prompt: "Seed-to-sale activity export — last 90 days. Treated as manual export, not live sync." }),
  EV("ev_metrc_biotrack_export", "METRC / BioTrack export",
    "If applicable, could you export METRC or BioTrack reports for the last 90 days?",
    { evidence_prompt: "METRC or BioTrack export — last 90 days. Treated as manual export, not live sync.",
      admin_only_notes: "Operational documentation visibility only. Never represent METRC/BioTrack export as compliance certification." }),
  EV("ev_recon_records", "Reconciliation records",
    "Could you share the last three inventory reconciliation records?",
    { evidence_prompt: "Three most recent inventory reconciliations." }),
  EV("ev_count_sheets", "Count sheets",
    "Could you share two recent inventory count sheets?",
    { evidence_prompt: "Two recent inventory count sheets." }),
  EV("ev_manifest_records", "Manifest / receiving records",
    "Could you share two recent manifests with receiving notes?",
    { evidence_prompt: "Two recent manifests with receiving notes." }),
  EV("ev_discrepancy_log", "Discrepancy log",
    "Could you share the discrepancy log from the last 90 days?",
    { evidence_prompt: "Discrepancy log — last 90 days." }),
  EV("ev_stop_sell_records", "Stop-sell / hold records",
    "Could you share any stop-sell, hold, or quarantine records from the last 90 days?",
    { evidence_prompt: "Stop-sell / hold / quarantine records — last 90 days." }),
  EV("ev_waste_logs", "Waste logs",
    "Could you share waste logs for the last 60 days?",
    { evidence_prompt: "Waste logs — last 60 days." }),
  EV("ev_tag_label_log", "Tag / label correction log",
    "Could you share any tag or label correction records from the last 60 days?",
    { evidence_prompt: "Tag / label correction log — last 60 days." }),
  EV("ev_menu_sync_records", "Menu / POS sync records",
    "Could you share any menu and POS sync notes or screenshots showing how mismatches got fixed?",
    { evidence_prompt: "Menu / POS / inventory sync notes or screenshots." }),
  EV("ev_vendor_invoices", "Vendor invoices",
    "Could you share vendor invoices for the last 90 days?",
    { evidence_prompt: "Vendor invoices — last 90 days." }),
  EV("ev_category_sales_report", "Category sales report",
    "Could you export a sales-by-category report for the last 30 days?",
    { evidence_prompt: "POS sales-by-category report — last 30 days." }),
  EV("ev_category_margin_report", "Category margin report",
    "Could you export a margin-by-category report for the last 30 days?",
    { evidence_prompt: "Margin-by-category report — last 30 days." }),
  EV("ev_inventory_aging", "Inventory aging report",
    "Could you export an inventory aging report?",
    { evidence_prompt: "Inventory aging report from POS or seed-to-sale system." }),
  EV("ev_drawer_closeout", "Drawer closeout records",
    "Could you share drawer closeout records and variance notes for the last 30 days?",
    { evidence_prompt: "Drawer closeout records + variance notes — last 30 days." }),
  EV("ev_safe_drop_log", "Safe / drop log",
    "Could you share the safe and drop log for the last 30 days?",
    { evidence_prompt: "Safe / drop log — last 30 days." }),
  EV("ev_deposit_records", "Deposit records",
    "Could you share deposit records for the last 30 days?",
    { evidence_prompt: "Deposit records — last 30 days." }),
  EV("ev_visitor_log", "Visitor log",
    "Could you share the visitor log for the last 30 days?",
    { evidence_prompt: "Visitor log — last 30 days." }),
  EV("ev_badge_training", "Badge / training records",
    "Could you share staff badge and training records?",
    { evidence_prompt: "Staff badge + training records." }),
  EV("ev_camera_check_log", "Camera / security check log",
    "Could you share any camera coverage, retention, or alarm review notes from the last 90 days?",
    { evidence_prompt: "Camera / security check log — last 90 days." }),
  EV("ev_pl", "Accounting / P&L",
    "Could you share a recent P&L and a COGS breakout you've already shared with your CPA?",
    { evidence_prompt: "Trailing 12-month P&L + CPA-coordinated COGS breakout.",
      admin_only_notes: "CPA/tax-professional coordinated visibility only. Never advise on tax or accounting treatment." }),
  // ── Admin Interpretation Support (owner-quote handling) ──────────
  ADM("ai_quote_inventory_handled", "operations", "Owner quote: inventory handled",
    "Owner says: 'Our inventory is handled. One person knows that system really well.'",
    { admin_interpretation: "Treat as seed-to-sale admin dependency, process redundancy risk, and documentation-readiness risk. Evidence needed: reconciliation cadence, role coverage, documented procedure. Never imply compliance certification." }),
  ADM("ai_quote_reconcile_when_off", "operations", "Owner quote: reconcile when off",
    "Owner says: 'We reconcile when something looks off.'",
    { admin_interpretation: "Reactive reconciliation = documentation-velocity risk and inventory-reconciliation risk. Evidence needed: last reconciliation date, count records, variance logs." }),
  ADM("ai_quote_manager_handles_metrc", "owner_independence", "Owner quote: manager handles METRC / BioTrack",
    "Owner says: 'The manager handles METRC or BioTrack.'",
    { admin_interpretation: "Delegated does not mean controlled. Ask who covers when the manager is out. Evidence needed: procedure, backup role, audit trail, reconciliation logs." }),
  ADM("ai_quote_documents_somewhere", "operations", "Owner quote: documents somewhere",
    "Owner says: 'We have the documents somewhere.'",
    { admin_interpretation: "Treat as missing evidence / documentation-location risk. Classify as structured_interview_claim or missing_evidence until produced." }),
  ADM("ai_quote_cash_fine", "financial", "Owner quote: cash process is fine",
    "Owner says: 'Our cash process is fine.'",
    { admin_interpretation: "Do not treat as verified. Ask for drawer closeout records, safe / drop log, deposit records, and variance notes." }),
  ADM("ai_quote_menu_close", "operations", "Owner quote: menu and inventory usually close",
    "Owner says: 'Our menu and inventory are usually close.'",
    { admin_interpretation: "Treat as menu / POS / inventory sync gap. Ask when mismatch happens and how it gets corrected. Request POS / menu / inventory sync records." }),
  ADM("ai_quote_things_good", "business_profile", "Owner quote: things are good",
    "Owner says: 'Things are good right now.'",
    { admin_interpretation: "Anchor with evidence: POS trend, reconciliation cadence, drawer variance, owner-absence test. Owner narrative without evidence stays an owner_estimate." }),
];

export const CANNABIS_MMJ_DISPENSARY_BANK: IndustryQuestionBank = {
  industry: I,
  label: "Cannabis / MMJ Dispensary Operations",
  disclaimer: CANNABIS_DISCLAIMER,
  questions: QUESTIONS,
};
