/** P93E-E2G — E-commerce / Online Retail starter bank. */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";
const I = "ecommerce_online_retail" as const;
const Q = (key: string, gear: DiagnosticQuestion["gear"], section: string, plain: string,
  extra: Partial<DiagnosticQuestion> = {}): DiagnosticQuestion => ({
  key: `ecom.${key}`, industry: I, gear, section,
  plain_language_question: plain, answer_type: "narrative", capture: { notes: true }, ...extra,
});
const QUESTIONS: DiagnosticQuestion[] = [
  Q("bp_platform", "business_profile", "Platform",
    "What platform are you on — Shopify, WooCommerce, BigCommerce, custom — and what's the catalog size?"),
  Q("bp_channels", "business_profile", "Channels",
    "Which channels are you selling on (own site, Amazon, Etsy, wholesale)?"),
  Q("bp_team", "business_profile", "Team",
    "Who's actually running the store — marketing, fulfillment, customer service?"),
  Q("dg_traffic_sources", "demand", "Traffic sources",
    "Where does traffic come from — organic, paid (Meta / Google), email, affiliates?",
    { source_of_truth_guidance: "Google Analytics / GA4 + ad platform reports" }),
  Q("dg_paid_spend", "demand", "Paid ad spend",
    "About how much are you spending on paid ads each month?",
    { answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true, range: true } }),
  Q("dg_email", "demand", "Email / SMS",
    "How big is the email and SMS list, and how often are flows sending?",
    { answer_type: "numeric", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("rc_conversion", "sales", "Site conversion",
    "What's your site conversion rate?",
    { business_term: "Site conversion rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_aov", "sales", "Average order value",
    "What's your average order value?",
    { business_term: "AOV", answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("rc_cart_abandon", "sales", "Cart abandonment",
    "What's your cart-abandonment rate, and is there a recovery flow?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_fulfillment", "operations", "Fulfillment",
    "Walk me through fulfillment — in-house, 3PL, dropship — and how long from order to ship?"),
  Q("op_returns", "operations", "Returns",
    "What's your return rate, and how is it handled?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_inventory", "operations", "Inventory accuracy",
    "How often does inventory get out of sync between channels?",
    { repair_map_signal: "Inventory Variance Risk" }),
  Q("op_cs_volume", "operations", "Customer service",
    "How many CS tickets a week, and who's answering them?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_qb", "financial", "Books status",
    "Are your books current, and is Shopify / Stripe / PayPal feeding into them cleanly?",
    { source_of_truth_guidance: "QuickBooks + Stripe / PayPal / Square reconciliation" }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's average monthly gross revenue right now?",
    { answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true } }),
  Q("fv_contribution_margin", "financial", "Contribution margin",
    "Do you know your contribution margin per order after product cost, shipping, fees, and ad spend?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_cac_ltv", "financial", "CAC / LTV",
    "Do you have a sense of acquisition cost vs. customer lifetime value?",
    { business_term: "CAC / LTV" }),
  Q("oi_owner_role", "owner_independence", "Owner role",
    "What parts of the business still depend on you personally — buying, marketing, CS, fulfillment?",
    { repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_team_decisions", "owner_independence", "Team decision rights",
    "Who can decide on a promo, a price change, or a new SKU besides you?"),
  Q("ev_ga", "evidence", "Analytics export",
    "Could you share access to Google Analytics or a 90-day traffic report?",
    { evidence_prompt: "GA4 / Google Search Console — last 90 days" }),
  Q("ev_ad_platform", "evidence", "Ad platform reports",
    "Could you share Meta Ads / Google Ads reports for the last 90 days?",
    { evidence_prompt: "Ad platform performance — last 90 days" }),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent P&L?", { evidence_prompt: "Trailing 12-month P&L" }),
];
export const ECOMMERCE_ONLINE_RETAIL_BANK: IndustryQuestionBank = {
  industry: I, label: "E-commerce / Online Retail", questions: QUESTIONS,
};
