/**
 * P93E-E2G-P5 — E-commerce / Online Retail full-depth diagnostic interview bank.
 *
 * Plain-English scripted interview, deep diagnostic structure for online
 * retailers: Shopify / WooCommerce / BigCommerce stores, Amazon / Etsy / eBay
 * / Walmart marketplace sellers, DTC brands, online boutiques, mixed
 * owned-site + marketplace sellers, fulfillment-heavy online sellers,
 * paid-ad-driven stores, and email/SMS-driven stores.
 *
 * Every prompt is classified as `core`, `conditional_deep_dive`,
 * `evidence_source_of_truth`, or `admin_interpretation_support` and may carry
 * report-finding seeds and Repair-Map trigger seeds.
 *
 * Pricing, ad spend, returns, inventory, and platform questions are framed
 * as operational visibility and documentation readiness only — never as
 * legal, tax, accounting, employment-law, fiduciary, or platform-policy
 * advice, and never as guaranteed outcomes.
 */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";

const I = "ecommerce_online_retail" as const;

const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `ecom.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

const CDD = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  parent: string,
  triggerWhen: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "conditional_deep_dive",
    parent_key: `ecom.${parent}`,
    trigger_when: triggerWhen,
    ...extra,
  });

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile ───────────────────────────────────────────────────
  Q("bp_platform", "business_profile", "Platform",
    "What platform is your store on — Shopify, WooCommerce, BigCommerce, custom, or something else?",
    { business_term: "Storefront platform" }),
  Q("bp_channels", "business_profile", "Channels",
    "Where do you actually sell — your own site, Amazon, Etsy, eBay, Walmart, wholesale, or a mix?",
    { business_term: "Sales channels" }),
  Q("bp_catalog_size", "business_profile", "Catalog size",
    "Roughly how many active SKUs are you selling right now?",
    { business_term: "Active SKU count",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("bp_product_type", "business_profile", "Product type",
    "What kind of products do you sell, and who is the typical buyer in one sentence?",
    { business_term: "Product type & buyer" }),
  Q("bp_team", "business_profile", "Team shape",
    "Who's actually running this — marketing, fulfillment, customer service, ads — and how many people total?",
    { business_term: "Team shape" }),
  Q("bp_business_model", "business_profile", "Business model",
    "Are you mostly DTC, mostly marketplace, mostly wholesale, or a real mix?",
    { business_term: "Business model mix" }),
  Q("bp_age", "business_profile", "Time in market",
    "How long has the store been live, and when did sales actually start being meaningful?",
    { business_term: "Time in market" }),
  Q("bp_fulfillment_model", "business_profile", "Fulfillment model",
    "How are orders fulfilled today — in-house, 3PL, dropship, FBA, or a combination?",
    { business_term: "Fulfillment model" }),
  Q("bp_seasonality", "business_profile", "Seasonality",
    "Are there months that are clearly bigger or smaller than the rest?",
    { business_term: "Demand seasonality",
      answer_type: "seasonal_range", capture: { notes: true, seasonal: true } }),

  // ── Demand Generation ──────────────────────────────────────────────────
  Q("dg_traffic_sources", "demand", "Traffic sources",
    "Where does most of your traffic come from — paid ads, organic search, social, email, marketplaces, or referrals?",
    { business_term: "Traffic source mix",
      report_finding_seed: "Channel concentration",
      repair_map_trigger_seed: "channel_diversification" }),
  Q("dg_top_channel", "demand", "Top channel share",
    "What share of revenue or traffic comes from your single biggest channel?",
    { business_term: "Top channel share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_paid_spend", "demand", "Paid ad spend",
    "About how much are you spending on paid ads each month, across all platforms combined?",
    { business_term: "Monthly ad spend",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true } }),
  Q("dg_paid_platforms", "demand", "Paid platforms",
    "Which paid platforms do you use — Meta Ads, Google Ads, TikTok Ads, Amazon Ads, Pinterest, others?",
    { business_term: "Paid platform mix" }),
  Q("dg_organic", "demand", "Organic search",
    "Does organic search bring in real traffic, or is it mostly branded?",
    { business_term: "Organic search role",
      source_of_truth_guidance: "Google Analytics / GA4 + Google Search Console" }),
  Q("dg_social", "demand", "Social media",
    "Which social channels actually move sales — not just followers?",
    { business_term: "Revenue-moving social channels" }),
  Q("dg_creators", "demand", "Influencers / creators",
    "Are creators or influencers driving sales today, and how do you track which ones work?",
    { business_term: "Creator-driven traffic" }),
  Q("dg_email_sms", "demand", "Email & SMS",
    "How big is the email and SMS list, and how often are flows or campaigns sending?",
    { business_term: "Owned audience size",
      answer_type: "numeric", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("dg_marketplace_traffic", "demand", "Marketplace traffic",
    "If you sell on marketplaces, how much of total revenue comes from Amazon, Etsy, eBay, or Walmart combined?",
    { business_term: "Marketplace revenue share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_affiliate", "demand", "Affiliate / referral",
    "Do you have affiliate or referral traffic, and is it tracked?",
    { business_term: "Affiliate / referral channel" }),
  Q("dg_brand_search", "demand", "Brand demand",
    "Are people searching for your brand by name, or only finding you through ads and marketplaces?",
    { business_term: "Brand search demand" }),
  Q("dg_campaign_tracking", "demand", "Campaign tracking",
    "When you run a campaign, can you tell which one drove which sales?",
    { business_term: "Campaign attribution" }),
  Q("dg_repeat_strategy", "demand", "Repeat buyer strategy",
    "What is the actual plan for getting a first-time buyer to buy again?",
    { business_term: "Repeat purchase plan" }),
  Q("dg_owner_runs_ads", "demand", "Owner runs ads",
    "Who actually runs the paid ad accounts day to day — you, an in-house person, or an agency?",
    { business_term: "Ad account ownership" }),
  // Demand CDDs
  CDD("dg_cdd_channel_concentration", "demand", "Channel concentration risk",
    "dg_top_channel",
    "Top channel is 60% or more of revenue or traffic.",
    "If your top channel went dark for 60 days, what would you actually do to replace that revenue?",
    { report_finding_seed: "Channel Concentration Risk",
      repair_map_trigger_seed: "channel_concentration_relief",
      admin_interpretation: "Single-channel dominance ≥60% = channel concentration risk regardless of how strong it feels." }),
  CDD("dg_cdd_marketplace_dependence", "demand", "Marketplace dependence",
    "dg_marketplace_traffic",
    "Marketplace share is 50% or more of revenue.",
    "If Amazon, Etsy, eBay, or Walmart suspended your account for 30 days, what would happen to the business?",
    { report_finding_seed: "Marketplace Dependence Risk",
      repair_map_trigger_seed: "marketplace_dependence_relief",
      admin_interpretation: "Marketplace dependence is also a customer-ownership risk — you don't own the buyer relationship." }),
  CDD("dg_cdd_paid_acquisition", "demand", "Paid acquisition profitability",
    "dg_paid_spend",
    "Paid ad spend is meaningful but ROAS is the only success measure.",
    "Beyond ROAS, do you know your contribution margin after ad spend, shipping, returns, and payment fees?",
    { report_finding_seed: "Paid Acquisition Profitability Gap",
      repair_map_trigger_seed: "paid_acquisition_profitability_install",
      admin_interpretation: "ROAS-only thinking hides whether paid sales are actually profitable after everything." }),
  CDD("dg_cdd_email_sms_gap", "demand", "Email / SMS flow gap",
    "dg_email_sms",
    "Owner can't list which automated flows are live (welcome, abandoned cart, post-purchase, winback).",
    "Which of these flows are actually live and sending today: welcome, abandoned cart, post-purchase, winback?",
    { report_finding_seed: "Email/SMS Flow Gap",
      repair_map_trigger_seed: "email_sms_flow_install" }),
  CDD("dg_cdd_campaign_attribution", "demand", "Campaign attribution gap",
    "dg_campaign_tracking",
    "Owner can't say which campaign drove which sales in the last 30 days.",
    "When was the last time you turned off a campaign because the data clearly said it wasn't working?",
    { report_finding_seed: "Campaign attribution gap",
      repair_map_trigger_seed: "campaign_attribution_install" }),
  CDD("dg_cdd_owner_ad_dependency", "demand", "Owner ad dependency",
    "dg_owner_runs_ads",
    "Owner is the only person with real visibility into ad accounts.",
    "If you stepped away from the ad accounts for 30 days, who would notice a bad campaign and pause it?",
    { report_finding_seed: "Owner ad-account dependency",
      repair_map_trigger_seed: "ad_account_redundancy_install" }),
  CDD("dg_cdd_brand_demand", "demand", "Brand demand gap",
    "dg_brand_search",
    "Brand searches are flat or unknown despite paid spend.",
    "If paid ads stopped tomorrow, how many people would still come looking for you by name?",
    { report_finding_seed: "Brand demand gap",
      repair_map_trigger_seed: "brand_demand_install" }),
  CDD("dg_cdd_creator_tracking", "demand", "Creator attribution gap",
    "dg_creators",
    "Creators are used but contribution per creator isn't tracked.",
    "How would you know today which creator partnership actually paid back?",
    { report_finding_seed: "Creator attribution gap",
      repair_map_trigger_seed: "creator_attribution_install" }),
  CDD("dg_cdd_seasonality_plan", "demand", "Seasonality planning",
    "bp_seasonality",
    "Slow months are a known pattern but no plan exists to fill them.",
    "What's the plan for the next slow stretch — promotion, content, email push, or wait it out?",
    { report_finding_seed: "Seasonality planning gap",
      repair_map_trigger_seed: "seasonal_demand_plan" }),

  // ── Revenue Conversion (Sales) ─────────────────────────────────────────
  Q("rc_site_conversion", "sales", "Site conversion rate",
    "What's your store's conversion rate — visitors who actually buy?",
    { business_term: "Site conversion rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_aov", "sales", "Average order value",
    "What's your average order value right now?",
    { business_term: "AOV",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true } }),
  Q("rc_cart_abandon", "sales", "Cart abandonment",
    "What's your cart-abandonment rate, and is there a recovery flow that catches it?",
    { business_term: "Cart abandonment rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_checkout_completion", "sales", "Checkout completion",
    "Of people who reach checkout, what share actually finish?",
    { business_term: "Checkout completion rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_product_pages", "sales", "Product page performance",
    "Are some product pages clearly converting better than others, and do you know why?",
    { business_term: "Product page performance" }),
  Q("rc_landing_pages", "sales", "Landing page performance",
    "When you run paid traffic, where does it land — product page, collection, or a real landing page?",
    { business_term: "Landing page strategy" }),
  Q("rc_offers", "sales", "Offers & promotions",
    "What promotions or offers do you run, and how often?",
    { business_term: "Offer cadence" }),
  Q("rc_bundles_upsell", "sales", "Bundles & upsells",
    "Do you run bundles, upsells, or cross-sells today, and where in the flow?",
    { business_term: "Bundle / upsell strategy" }),
  Q("rc_subscription", "sales", "Subscription / replenishment",
    "If your product fits, do you offer subscription or replenishment — and how is it doing?",
    { business_term: "Subscription / replenishment role" }),
  Q("rc_repeat_rate", "sales", "Repeat purchase rate",
    "Of customers who bought once, what share buy again within 90 days?",
    { business_term: "Repeat purchase rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_reviews", "sales", "Customer reviews",
    "Are you capturing customer reviews, and how visible are they on the site?",
    { business_term: "Reviews capture" }),
  Q("rc_payment_options", "sales", "Payment & checkout options",
    "What payment options does checkout offer — Stripe, Square, PayPal, Shop Pay, Apple Pay, buy-now-pay-later?",
    { business_term: "Payment & checkout options" }),
  Q("rc_marketplace_conversion", "sales", "Marketplace conversion",
    "If you sell on marketplaces, what's the conversion picture there vs. your own site?",
    { business_term: "Marketplace conversion" }),
  Q("rc_offer_clarity", "sales", "Offer clarity",
    "If a brand-new visitor lands on your homepage, do they immediately understand what you sell and why to buy it?",
    { business_term: "Offer clarity" }),
  // Sales CDDs
  CDD("rc_cdd_cart_abandon_high", "sales", "Cart abandonment friction",
    "rc_cart_abandon",
    "Cart abandonment is over 70% or unknown.",
    "What happens between someone adding to cart and reaching the thank-you page — what's slowing them down?",
    { report_finding_seed: "Cart Abandonment / Checkout Friction",
      repair_map_trigger_seed: "checkout_friction_install" }),
  CDD("rc_cdd_checkout_drop", "sales", "Checkout drop-off",
    "rc_checkout_completion",
    "Checkout completion is below 60% or unknown.",
    "Have you walked through your own checkout on mobile in the last 30 days?",
    { report_finding_seed: "Checkout completion gap",
      repair_map_trigger_seed: "checkout_completion_review" }),
  CDD("rc_cdd_repeat_low", "sales", "Repeat-purchase weakness",
    "rc_repeat_rate",
    "Repeat-purchase rate is below 20% or unknown.",
    "What is the actual plan to get a customer to buy a second time within 90 days?",
    { report_finding_seed: "Repeat purchase weakness",
      repair_map_trigger_seed: "repeat_purchase_plan_install" }),
  CDD("rc_cdd_offer_clarity", "sales", "Offer clarity gap",
    "rc_offer_clarity",
    "Owner can't summarize the value proposition in one sentence.",
    "What does your homepage say in the first 3 seconds — and what should it say?",
    { report_finding_seed: "Offer clarity gap",
      repair_map_trigger_seed: "homepage_clarity_install" }),
  CDD("rc_cdd_review_capture", "sales", "Review capture gap",
    "rc_reviews",
    "Reviews aren't being captured systematically or display poorly on product pages.",
    "Where in the post-purchase flow does the review request happen — and is it triggered automatically?",
    { report_finding_seed: "Review capture gap",
      repair_map_trigger_seed: "review_capture_install" }),
  CDD("rc_cdd_landing_pages", "sales", "Landing page mismatch",
    "rc_landing_pages",
    "Paid traffic lands on generic product or collection pages, not purpose-built landers.",
    "If we built one dedicated landing page for your top ad set, what would it need to say?",
    { report_finding_seed: "Landing page mismatch",
      repair_map_trigger_seed: "landing_page_install" }),
  CDD("rc_cdd_marketplace_underperform", "sales", "Marketplace performance gap",
    "rc_marketplace_conversion",
    "Marketplace listings underperform vs. owned site, or owner doesn't know.",
    "When was the last time you reviewed your marketplace listing photos, copy, and reviews?",
    { report_finding_seed: "Marketplace listing weakness",
      repair_map_trigger_seed: "marketplace_listing_review" }),
  CDD("rc_cdd_payment_friction", "sales", "Payment friction",
    "rc_payment_options",
    "Checkout offers limited payment options or one specific option is creating friction.",
    "Which payment option do customers ask for that they don't currently see at checkout?",
    { report_finding_seed: "Payment friction",
      repair_map_trigger_seed: "payment_options_review" }),

  // ── Operational Efficiency ─────────────────────────────────────────────
  Q("op_fulfillment_workflow", "operations", "Fulfillment workflow",
    "Walk me through what happens between an order coming in and it shipping out the door.",
    { business_term: "Fulfillment workflow" }),
  Q("op_ship_speed", "operations", "Shipping speed",
    "How long from order placed to order shipped on a typical day?",
    { business_term: "Order-to-ship speed" }),
  Q("op_order_accuracy", "operations", "Order accuracy",
    "What share of orders ship correctly the first time — right item, right address, right quantity?",
    { business_term: "Order accuracy",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_shipping_cost", "operations", "Shipping cost control",
    "How is shipping cost handled today — flat, calculated, free over a threshold, included in price?",
    { business_term: "Shipping cost model" }),
  Q("op_returns_process", "operations", "Returns process",
    "Walk me through how a return actually gets handled today.",
    { business_term: "Returns process" }),
  Q("op_return_rate", "operations", "Return rate",
    "What's your return rate, and do you know the top reasons people return?",
    { business_term: "Return rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_inventory_accuracy", "operations", "Inventory accuracy",
    "How often does inventory go out of sync between your site, marketplaces, and what's actually on the shelf?",
    { business_term: "Inventory accuracy",
      report_finding_seed: "Inventory sync risk",
      repair_map_trigger_seed: "inventory_sync_install" }),
  Q("op_stockouts", "operations", "Stockouts",
    "How often do you run out of a best-selling SKU, and do you know when it's about to happen?",
    { business_term: "Stockout pattern" }),
  Q("op_overselling", "operations", "Overselling risk",
    "Has the store ever oversold a product because inventory was wrong across channels?",
    { business_term: "Overselling incidents" }),
  Q("op_supplier_reliability", "operations", "Supplier reliability",
    "How reliable are your suppliers on lead time, cost, and quality — and is that tracked?",
    { business_term: "Supplier reliability" }),
  Q("op_purchasing", "operations", "Purchase ordering",
    "How do you decide when to reorder — gut, par level, sales velocity, or a system?",
    { business_term: "Reorder discipline" }),
  Q("op_receiving", "operations", "Receiving",
    "When inventory arrives, what's the process for counting it in and getting it live for sale?",
    { business_term: "Receiving process" }),
  Q("op_3pl", "operations", "3PL / warehouse",
    "If you use a 3PL or outside warehouse, what visibility do you have into errors, late shipments, and damage?",
    { business_term: "3PL visibility" }),
  Q("op_cs_volume", "operations", "Customer support volume",
    "Roughly how many support tickets a week, and who's answering them?",
    { business_term: "Support ticket volume",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_cs_response", "operations", "Customer support response time",
    "What's the typical first-response time on a support ticket?",
    { business_term: "Support response time" }),
  Q("op_integrations", "operations", "Integrations & apps",
    "Which apps and integrations are connected to the store — and are any held together with manual workarounds?",
    { business_term: "Integrations & manual workarounds" }),
  // Ops CDDs
  CDD("op_cdd_fulfillment_errors", "operations", "Fulfillment error drag",
    "op_order_accuracy",
    "Order accuracy is below 97% or unknown, or owner can't quote it.",
    "What were the last 3 fulfillment mistakes, and what caused each one?",
    { report_finding_seed: "Fulfillment Error Drag",
      repair_map_trigger_seed: "fulfillment_error_review",
      admin_interpretation: "If owner can't recall recent error categories, errors aren't being tracked." }),
  CDD("op_cdd_returns_leakage", "operations", "Return cost leakage",
    "op_return_rate",
    "Return rate is meaningful but return reasons, costs, and margin impact aren't analyzed.",
    "Of last month's returns, do you know how much they cost in shipping, restocking, and refunded fees?",
    { report_finding_seed: "Return Cost Leakage",
      repair_map_trigger_seed: "return_cost_visibility_install" }),
  CDD("op_cdd_inventory_accuracy", "operations", "Inventory accuracy gap",
    "op_inventory_accuracy",
    "Inventory drifts out of sync between site, marketplaces, and shelf.",
    "When was the last full physical count, and how far off were the numbers?",
    { report_finding_seed: "Inventory accuracy gap",
      repair_map_trigger_seed: "inventory_count_cadence_install" }),
  CDD("op_cdd_stockout_risk", "operations", "Stockout risk",
    "op_stockouts",
    "Best sellers go out of stock with no advance signal.",
    "What system today tells you a top SKU is 14 days from running out?",
    { report_finding_seed: "Stockout visibility gap",
      repair_map_trigger_seed: "stockout_alert_install" }),
  CDD("op_cdd_overselling", "operations", "Overselling incidents",
    "op_overselling",
    "Overselling has happened in the last 90 days.",
    "When it happened, what did you do — refund, back-order, source it elsewhere — and how was the customer told?",
    { report_finding_seed: "Overselling incidents",
      repair_map_trigger_seed: "channel_inventory_sync_install" }),
  CDD("op_cdd_supplier_risk", "operations", "Supplier reliability risk",
    "op_supplier_reliability",
    "Supplier delays, cost changes, or quality issues are not tracked.",
    "Of your top 3 suppliers, which one are you most worried about right now and why?",
    { report_finding_seed: "Supplier / Vendor Reliability Risk",
      repair_map_trigger_seed: "supplier_reliability_review" }),
  CDD("op_cdd_3pl_blind", "operations", "3PL visibility gap",
    "op_3pl",
    "3PL is in use but error reports, late shipments, and damage rates aren't reviewed.",
    "When was the last time you reviewed your 3PL's error report or SLA performance?",
    { report_finding_seed: "3PL visibility gap",
      repair_map_trigger_seed: "three_pl_review_cadence_install",
      admin_interpretation: "Outsourced does not mean controlled — owner often assumes 3PL is fine because complaints are low." }),
  CDD("op_cdd_cs_visibility", "operations", "Customer support visibility",
    "op_cs_volume",
    "Owner can't quote support volume, response time, or recurring issue categories.",
    "What are the top 3 issues your support team handles every week?",
    { report_finding_seed: "Customer Support Visibility Gap",
      repair_map_trigger_seed: "support_categorization_install" }),
  CDD("op_cdd_cs_response", "operations", "Support response drag",
    "op_cs_response",
    "First-response time is over 24 hours or unknown.",
    "What's the standard you want for first response, and what's blocking it from happening today?",
    { report_finding_seed: "Support response drag",
      repair_map_trigger_seed: "support_response_sla_install" }),
  CDD("op_cdd_manual_glue", "operations", "Manual workaround drag",
    "op_integrations",
    "Critical workflows depend on manual exports, copy-paste, or a single person remembering to do them.",
    "Which manual step would break the store hardest if the person doing it disappeared?",
    { report_finding_seed: "Manual workaround risk",
      repair_map_trigger_seed: "manual_workflow_review" }),

  // ── Financial Visibility ───────────────────────────────────────────────
  Q("fv_books", "financial", "Books status",
    "Are your books current, and is Shopify, Stripe, Square, or PayPal feeding into them cleanly?",
    { business_term: "Books currency",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks reconciled against Stripe / Square / PayPal" }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's average monthly gross revenue across all channels right now?",
    { business_term: "Monthly gross revenue",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true } }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know your gross margin after product cost — by the whole store, not just a guess?",
    { business_term: "Gross margin",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_contribution_margin", "financial", "Contribution margin per order",
    "Do you know your contribution margin per order after product cost, shipping, payment fees, and ad spend?",
    { business_term: "Contribution margin per order",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_mer", "financial", "MER vs ROAS",
    "Do you watch MER (total revenue ÷ total ad spend), or only platform ROAS?",
    { business_term: "MER vs platform ROAS" }),
  Q("fv_cac", "financial", "Customer acquisition cost",
    "Do you know what it actually costs to get a new customer right now?",
    { business_term: "CAC" }),
  Q("fv_ltv", "financial", "Customer lifetime value",
    "Do you have a sense of what a typical customer spends over their lifetime, or just first-order value?",
    { business_term: "Customer lifetime value" }),
  Q("fv_sku_profitability", "financial", "SKU profitability",
    "Do you know which products are actually most profitable — not just best-selling?",
    { business_term: "SKU-level profitability" }),
  Q("fv_landed_cost", "financial", "Landed cost",
    "When you cost a product, do you include freight in, duties, and packaging — or just the unit price?",
    { business_term: "Landed cost" }),
  Q("fv_processing_fees", "financial", "Payment & marketplace fees",
    "Do you track payment processing fees and marketplace fees as a real line item?",
    { business_term: "Processing & marketplace fees" }),
  Q("fv_discount_impact", "financial", "Discount impact",
    "When you run a promo, do you measure the margin impact, or only the revenue lift?",
    { business_term: "Discount margin impact" }),
  Q("fv_inventory_cash", "financial", "Inventory cash tied up",
    "Roughly how much cash is sitting in inventory right now?",
    { business_term: "Inventory cash tied up",
      answer_type: "currency",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_inventory_aging", "financial", "Inventory aging",
    "Do you know which products have been sitting too long and aren't really moving?",
    { business_term: "Aged / slow-moving inventory" }),
  Q("fv_break_even", "financial", "Break-even awareness",
    "Do you know roughly what monthly revenue level the store needs just to break even?",
    { business_term: "Break-even visibility" }),
  // Financial CDDs
  CDD("fv_cdd_books_lag", "financial", "Books lag",
    "fv_books",
    "Books are more than 30 days behind, or owner isn't sure.",
    "When was the last month closed in QuickBooks, Xero, or FreshBooks, and who closed it?",
    { report_finding_seed: "Books currency gap",
      repair_map_trigger_seed: "books_close_cadence_install" }),
  CDD("fv_cdd_contribution_blind", "financial", "Contribution margin blind spot",
    "fv_contribution_margin",
    "Owner can't quote contribution margin per order within ±5 points.",
    "If we picked one paid order from yesterday, could we trace product cost, shipping, payment fee, and ad cost on it?",
    { report_finding_seed: "Contribution Margin Blind Spot",
      repair_map_trigger_seed: "contribution_margin_install",
      admin_interpretation: "If contribution margin per order is unknown, every ROAS claim is incomplete." }),
  CDD("fv_cdd_sku_profit", "financial", "SKU profitability gap",
    "fv_sku_profitability",
    "Owner names best sellers by volume but can't rank them by margin.",
    "If we ranked products by profit, not revenue, do you think the top 3 would change?",
    { report_finding_seed: "Product Profitability Gap",
      repair_map_trigger_seed: "sku_margin_visibility_install" }),
  CDD("fv_cdd_mer", "financial", "MER blind spot",
    "fv_mer",
    "Only platform ROAS is watched; MER isn't tracked.",
    "What's your total revenue divided by total ad spend last month — across every platform combined?",
    { report_finding_seed: "MER visibility gap",
      repair_map_trigger_seed: "mer_visibility_install" }),
  CDD("fv_cdd_inventory_cash_trap", "financial", "Inventory cash trap",
    "fv_inventory_cash",
    "Significant cash is in inventory but sell-through and aging aren't tracked.",
    "Of inventory on hand, how much do you think is older than 90 days with little movement?",
    { report_finding_seed: "Inventory Cash Trap",
      repair_map_trigger_seed: "inventory_cash_review_install" }),
  CDD("fv_cdd_landed_cost", "financial", "Landed cost gap",
    "fv_landed_cost",
    "Product cost is unit-only and excludes freight, duties, or packaging.",
    "What would your top product's true landed cost look like if we added freight, duties, and packaging?",
    { report_finding_seed: "Landed cost visibility gap",
      repair_map_trigger_seed: "landed_cost_install" }),
  CDD("fv_cdd_discount_margin", "financial", "Discount margin risk",
    "fv_discount_impact",
    "Discounts and promos run regularly but margin impact isn't reviewed.",
    "After your last promo, did you check whether contribution margin actually went up or down?",
    { report_finding_seed: "Discount / Promotion Margin Risk",
      repair_map_trigger_seed: "promo_margin_review_install" }),
  CDD("fv_cdd_shipping_cost", "financial", "Shipping cost visibility",
    "fv_processing_fees",
    "Shipping cost is treated as overhead instead of tied to SKU, order, or channel profitability.",
    "Do you know which products lose money once shipping is properly allocated?",
    { report_finding_seed: "Shipping Cost Visibility Gap",
      repair_map_trigger_seed: "shipping_cost_allocation_install" }),

  // ── Owner Independence ─────────────────────────────────────────────────
  Q("oi_owner_role", "owner_independence", "Owner role",
    "What parts of the business still depend on you personally — buying, marketing, ads, fulfillment, support?",
    { business_term: "Owner dependency map",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_platform_admin", "owner_independence", "Platform / admin access",
    "Who has admin access to Shopify, WooCommerce, BigCommerce, or your platform of record besides you?",
    { business_term: "Platform admin access",
      report_finding_seed: "Platform / Admin Dependency",
      repair_map_trigger_seed: "platform_admin_access_install" }),
  Q("oi_ads_dependency", "owner_independence", "Ads dependency",
    "Who else can pause a bad campaign or read the ad accounts besides you?",
    { business_term: "Ad account redundancy" }),
  Q("oi_email_dependency", "owner_independence", "Email / SMS dependency",
    "Who can build, schedule, and review an email or SMS campaign without you?",
    { business_term: "Email/SMS ownership" }),
  Q("oi_fulfillment_dependency", "owner_independence", "Fulfillment dependency",
    "If you didn't show up for a week, would orders still ship correctly?",
    { business_term: "Fulfillment dependency" }),
  Q("oi_cs_dependency", "owner_independence", "Support dependency",
    "Who answers customer questions besides you, and who can resolve a refund or replacement on their own?",
    { business_term: "Support resolution authority" }),
  Q("oi_supplier_dependency", "owner_independence", "Supplier dependency",
    "Are you the only person who talks to suppliers, or does someone else have a working relationship?",
    { business_term: "Supplier relationship redundancy" }),
  Q("oi_product_launches", "owner_independence", "Product launches",
    "When a new product launches, who runs it end-to-end — listings, photos, copy, ads, email?",
    { business_term: "Product launch ownership" }),
  Q("oi_decision_rights", "owner_independence", "Decision rights",
    "What decisions can the team make without checking with you — promos, price changes, refunds, new SKUs?",
    { business_term: "Decision rights" }),
  Q("oi_documented_workflows", "owner_independence", "Documented workflows",
    "Are the day-to-day store workflows written down, or do they live in your head?",
    { business_term: "Documented workflows" }),
  Q("oi_vacation_test", "owner_independence", "Vacation test",
    "If you took 14 straight days off with no contact, what would break first?",
    { business_term: "Vacation-test break point" }),
  // OI CDDs
  CDD("oi_cdd_platform_dependency", "owner_independence", "Platform/admin dependency",
    "oi_platform_admin",
    "Owner is the only person with admin access to the platform.",
    "If you lost access to your platform tomorrow, who could rebuild a working order?",
    { report_finding_seed: "Platform / Admin Dependency",
      repair_map_trigger_seed: "platform_access_redundancy_install",
      admin_interpretation: "Platform single-admin = both an operational risk and a key-person risk." }),
  CDD("oi_cdd_fulfillment_solo", "owner_independence", "Fulfillment dependency",
    "oi_fulfillment_dependency",
    "Owner is the only person who knows the full pick-pack-ship flow.",
    "Who is the second person who could run fulfillment for a week if needed?",
    { report_finding_seed: "Fulfillment dependency",
      repair_map_trigger_seed: "fulfillment_redundancy_install" }),
  CDD("oi_cdd_cs_solo", "owner_independence", "Support escalation dependency",
    "oi_cs_dependency",
    "All non-routine support escalates to the owner.",
    "What's the limit a support person can resolve on their own — refund amount, replacement, exchange?",
    { report_finding_seed: "Support escalation dependency",
      repair_map_trigger_seed: "support_authority_install" }),
  CDD("oi_cdd_decision_rights", "owner_independence", "Decision rights gap",
    "oi_decision_rights",
    "Team can't list 5 decisions they own without checking with the owner.",
    "What's one decision the team should own that they currently don't?",
    { report_finding_seed: "Decision rights gap",
      repair_map_trigger_seed: "decision_rights_install" }),
  CDD("oi_cdd_documentation", "owner_independence", "Documentation gap",
    "oi_documented_workflows",
    "Workflows mostly live in the owner's head.",
    "If you hired one new person tomorrow, what would they read in their first week?",
    { report_finding_seed: "Workflow documentation gap",
      repair_map_trigger_seed: "workflow_documentation_install" }),
  CDD("oi_cdd_launch_solo", "owner_independence", "Launch dependency",
    "oi_product_launches",
    "Owner runs new product launches end-to-end.",
    "What part of a launch could someone else own next time, even partially?",
    { report_finding_seed: "Launch dependency",
      repair_map_trigger_seed: "launch_handoff_install" }),

  // ── Evidence / Source-of-Truth ─────────────────────────────────────────
  Q("ev_platform_sales", "evidence", "Platform sales report",
    "Could you export a 90-day sales report from Shopify, WooCommerce, or BigCommerce?",
    { evidence_prompt: "90-day sales report from storefront platform",
      source_of_truth_guidance: "Shopify / WooCommerce / BigCommerce sales export" }),
  Q("ev_marketplace_sales", "evidence", "Marketplace sales report",
    "Could you pull a 90-day sales report from each marketplace you sell on?",
    { evidence_prompt: "Marketplace sales reports — Amazon / Etsy / eBay / Walmart",
      source_of_truth_guidance: "Marketplace seller dashboards" }),
  Q("ev_channel_sales", "evidence", "Channel sales summary",
    "Could we see total revenue split by channel for the last 90 days?",
    { evidence_prompt: "Channel sales summary — last 90 days" }),
  Q("ev_traffic", "evidence", "Traffic report",
    "Could you share a 90-day traffic report from Google Analytics or GA4?",
    { evidence_prompt: "GA4 / Google Analytics — 90-day traffic by source",
      source_of_truth_guidance: "Google Analytics / GA4 + Google Search Console" }),
  Q("ev_ad_meta", "evidence", "Meta Ads report",
    "Could you share a Meta Ads performance report for the last 90 days?",
    { evidence_prompt: "Meta Ads — 90-day performance" }),
  Q("ev_ad_google", "evidence", "Google Ads report",
    "Could you share a Google Ads performance report for the last 90 days?",
    { evidence_prompt: "Google Ads — 90-day performance" }),
  Q("ev_mer_summary", "evidence", "MER / ad spend summary",
    "Could you share a summary of total ad spend vs. total revenue for the last 90 days?",
    { evidence_prompt: "MER summary — total revenue ÷ total ad spend, last 90 days" }),
  Q("ev_email_flows", "evidence", "Email / SMS flow report",
    "Could you share flow reports from your email and SMS tool — open, click, and revenue per flow?",
    { evidence_prompt: "Email / SMS flow performance report" }),
  Q("ev_abandoned_cart", "evidence", "Abandoned cart report",
    "Could you pull the abandoned cart report and the abandoned cart flow stats?",
    { evidence_prompt: "Abandoned cart report + recovery flow stats" }),
  Q("ev_checkout_funnel", "evidence", "Checkout funnel report",
    "Could you share the checkout funnel report — from add to cart to thank-you page?",
    { evidence_prompt: "Checkout funnel — add to cart → checkout → completed" }),
  Q("ev_sku_sales", "evidence", "SKU sales report",
    "Could you export a product / SKU sales report for the last 90 days?",
    { evidence_prompt: "Product / SKU sales report — last 90 days" }),
  Q("ev_sku_margin", "evidence", "Product margin report",
    "Is there a product margin report — even informal — that ranks SKUs by margin, not revenue?",
    { evidence_prompt: "Product margin report (revenue − COGS − fees − shipping)" }),
  Q("ev_landed_cost", "evidence", "Landed cost record",
    "Could you share how landed cost is recorded — supplier invoices, freight, duties, packaging?",
    { evidence_prompt: "Landed cost records by SKU" }),
  Q("ev_inventory_valuation", "evidence", "Inventory valuation report",
    "Could you pull an inventory valuation report — units on hand and dollar value?",
    { evidence_prompt: "Inventory valuation report — units × cost on hand" }),
  Q("ev_inventory_aging", "evidence", "Inventory aging report",
    "Is there an inventory aging report — what's been sitting how long?",
    { evidence_prompt: "Inventory aging by SKU (0–30 / 31–60 / 61–90 / 90+ days)" }),
  Q("ev_supplier_invoices", "evidence", "Supplier invoices",
    "Could you share recent supplier invoices and any purchase orders you have on file?",
    { evidence_prompt: "Recent supplier invoices + purchase orders" }),
  Q("ev_3pl_reports", "evidence", "3PL / warehouse report",
    "If you use a 3PL, could you pull their fulfillment, shipping cost, and error reports?",
    { evidence_prompt: "3PL fulfillment, shipping cost, and error reports" }),
  Q("ev_shipping_cost", "evidence", "Shipping cost report",
    "Could you share a shipping cost report by carrier or by order for the last 90 days?",
    { evidence_prompt: "Shipping cost by carrier / by order — last 90 days" }),
  Q("ev_returns_report", "evidence", "Returns report",
    "Could you pull a returns report — count, reason codes, and refund value?",
    { evidence_prompt: "Returns report with reason codes and refund value" }),
  Q("ev_refund_chargeback", "evidence", "Refunds & chargebacks",
    "Could you share refund and chargeback records from Stripe, Square, or PayPal?",
    { evidence_prompt: "Refund and chargeback records from Stripe / Square / PayPal" }),
  Q("ev_cs_tickets", "evidence", "Support ticket report",
    "Could you share a support ticket report — volume, response time, and top categories?",
    { evidence_prompt: "Support ticket volume, response time, and category breakdown" }),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent profit and loss statement?",
    { evidence_prompt: "Trailing 12-month P&L from QuickBooks / Xero / FreshBooks",
      source_of_truth_guidance: "Accounting system P&L" }),

  // ── Admin Interpretation Support (admin-only listening cues) ───────────
  Q("ai_quote_ads_working", "demand", "Owner-quote: ads working",
    "Listen for: 'Ads are working because revenue is up.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "ROAS / contribution margin confusion signal",
      admin_interpretation: "Possible ROAS / MER / contribution-margin confusion. Trigger ad spend, MER, SKU margin, shipping, returns, and processing-fee evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_best_seller", "financial", "Owner-quote: best seller = best product",
    "Listen for: 'We sell a lot of that product, so it's definitely our best product.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Volume vs. margin confusion signal",
      admin_interpretation: "Sales volume does not prove product profitability. Trigger SKU margin, return rate, and fulfillment cost evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_returns_normal", "operations", "Owner-quote: returns are normal",
    "Listen for: 'Returns are just part of online sales.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Return cost normalization signal",
      admin_interpretation: "Possible return cost leakage. Trigger return-reason tracking, product page review, sizing, quality, and fulfillment evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_3pl_handles", "operations", "Owner-quote: 3PL handles it",
    "Listen for: 'The 3PL handles fulfillment, so I don't really worry about it.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "3PL outsourced-control signal",
      admin_interpretation: "Outsourced does not mean controlled. Trigger SLA, error reports, late shipment reports, and support ticket category evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_only_one_knows", "owner_independence", "Owner-quote: only one who knows",
    "Listen for: 'I'm the only one who really knows Shopify and the ad accounts.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Platform / admin dependency signal",
      admin_interpretation: "Platform/admin dependency + access-control + owner-independence risk. Trigger access list, role permissions, and SOP evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_amazon_carrying", "demand", "Owner-quote: Amazon carries us",
    "Listen for: 'Amazon basically carries the business right now.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Marketplace dependence signal",
      admin_interpretation: "Marketplace dependence + customer-ownership risk. Trigger marketplace share, owned-list size, and brand search evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_promo_revenue", "financial", "Owner-quote: promo worked",
    "Listen for: 'That promo worked great — revenue went way up.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Promo margin blind-spot signal",
      admin_interpretation: "Revenue lift does not prove margin lift. Trigger promo margin impact, contribution margin, and discount cost evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
];

export const ECOMMERCE_ONLINE_RETAIL_BANK: IndustryQuestionBank = {
  industry: I,
  label: "E-commerce / Online Retail",
  questions: QUESTIONS,
};