/** P93E-E2G — Professional Services starter bank. */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";
const I = "professional_services" as const;
const Q = (key: string, gear: DiagnosticQuestion["gear"], section: string, plain: string,
  extra: Partial<DiagnosticQuestion> = {}): DiagnosticQuestion => ({
  key: `prosvc.${key}`, industry: I, gear, section,
  plain_language_question: plain, answer_type: "narrative", capture: { notes: true }, ...extra,
});
const QUESTIONS: DiagnosticQuestion[] = [
  Q("bp_practice", "business_profile", "Practice area",
    "What service do you sell, who's the typical client, and what does an engagement look like?"),
  Q("bp_team", "business_profile", "Team",
    "How many billable people, and how many admin / support people?",
    { answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_engagement_type", "business_profile", "Engagement type",
    "Are engagements mostly retainers, projects, hourly, or fixed-fee?"),
  Q("dg_lead_sources", "demand", "Lead sources",
    "Where do new clients usually come from — referrals, partners, content, outbound?"),
  Q("dg_referral_share", "demand", "Referral share",
    "What share of new business is referral-driven?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_pipeline", "demand", "Pipeline visibility",
    "Where does your pipeline live today — CRM (HubSpot, Salesforce, Pipedrive), spreadsheet, or in someone's head?",
    { source_of_truth_guidance: "CRM (HubSpot / Salesforce / Pipedrive)" }),
  Q("rc_close_rate", "sales", "Close rate",
    "Of the qualified opportunities, what percent become signed engagements?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_avg_deal", "sales", "Average deal size",
    "What's the average size of a signed engagement?",
    { business_term: "Average deal size", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true } }),
  Q("rc_proposal_turnaround", "sales", "Proposal turnaround",
    "From first call to proposal sent, how long does it usually take?"),
  Q("op_utilization", "operations", "Utilization",
    "What percent of billable hours are actually billed each week?",
    { business_term: "Utilization rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_realization", "operations", "Realization",
    "Of the hours you bill, how much actually gets collected?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_project_management", "operations", "Project management",
    "How are engagements actually managed — what tool, and who owns delivery?"),
  Q("op_scope_creep", "operations", "Scope creep",
    "How often does scope creep eat margin, and how is it caught?"),
  Q("fv_qb", "financial", "Books status",
    "Are your books current, and who keeps them up?"),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's average monthly revenue?",
    { answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("fv_open_ar", "financial", "Open AR",
    "How much is owed to you right now from clients?",
    { business_term: "Open AR / unpaid invoices", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks AR Aging Report" }),
  Q("fv_realization_rate", "financial", "Realization vs collection",
    "Do you know your realization and collection rates?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("oi_owner_billable", "owner_independence", "Owner billable load",
    "What percent of your week is still on billable client work?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_delegation", "owner_independence", "Delegation depth",
    "Who owns delivery of an engagement when it isn't you?"),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent P&L?", { evidence_prompt: "Trailing 12-month P&L" }),
  Q("ev_ar_aging", "evidence", "AR aging",
    "Could you pull AR aging from QuickBooks?",
    { evidence_prompt: "AR Aging Summary (current)" }),
  Q("ev_crm_pipeline", "evidence", "CRM pipeline export",
    "Could you export your pipeline from your CRM?",
    { evidence_prompt: "CRM pipeline with stage history" }),
];
export const PROFESSIONAL_SERVICES_BANK: IndustryQuestionBank = {
  industry: I, label: "Professional Services", questions: QUESTIONS,
};
