/**
 * P93E-E2G-P4 — Professional Services full-depth diagnostic interview bank.
 *
 * Plain-English scripted interview, deep diagnostic structure for service firms:
 * consultants, agencies, accountants/bookkeepers, legal/professional offices,
 * design/creative firms, IT/MSP services, marketing services, fractional and
 * coaching/advisory firms, and project-or-retainer-based B2B service firms.
 *
 * Every prompt is classified as `core`, `conditional_deep_dive`,
 * `evidence_source_of_truth`, or `admin_interpretation_support` and may carry
 * report-finding seeds and Repair-Map trigger seeds.
 *
 * Pricing, billing, scope, retention, and hiring questions are framed as
 * operational visibility and documentation readiness only — never as legal,
 * tax, accounting, employment-law, fiduciary, or licensing advice.
 */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";

const I = "professional_services" as const;

const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `prosvc.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

const CDD = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  parent: string,
  triggerWhen: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "conditional_deep_dive",
    parent_key: `prosvc.${parent}`,
    trigger_when: triggerWhen,
    ...extra,
  });

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile ───────────────────────────────────────────────────
  Q("bp_practice", "business_profile", "Practice area",
    "What service do you sell, and who is the typical client in one sentence?",
    { business_term: "Service & ideal client" }),
  Q("bp_engagement_model", "business_profile", "Engagement model",
    "Are most engagements retainers, projects, hourly, or fixed-fee?",
    { business_term: "Engagement model mix" }),
  Q("bp_team_shape", "business_profile", "Team shape",
    "How many billable people do you have, and how many admin or support people?",
    { business_term: "Billable vs. support headcount",
      answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_service_lines", "business_profile", "Service lines",
    "What are your top two or three service lines by revenue right now?",
    { business_term: "Top service lines" }),
  Q("bp_client_count", "business_profile", "Active clients",
    "Roughly how many active clients are you serving this month?",
    { business_term: "Active client count",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("bp_engagement_length", "business_profile", "Engagement length",
    "How long does a typical engagement last, from kickoff to wrap-up?",
    { business_term: "Average engagement length" }),
  Q("bp_geography", "business_profile", "Geography",
    "Where are your clients — local, regional, national, or remote-anywhere?",
    { business_term: "Client geography" }),
  Q("bp_niche", "business_profile", "Niche",
    "If a friend asked who you are best for, what would you say?",
    { business_term: "Niche positioning" }),
  Q("bp_seasonality", "business_profile", "Seasonality",
    "Are there months that are clearly busier or slower than the rest?",
    { business_term: "Demand seasonality",
      answer_type: "seasonal_range", capture: { notes: true, seasonal: true } }),

  // ── Demand Generation ──────────────────────────────────────────────────
  Q("dg_lead_sources", "demand", "Lead sources",
    "Where do most new client opportunities come from right now?",
    { business_term: "Lead source concentration",
      report_finding_seed: "Lead source concentration",
      repair_map_trigger_seed: "lead_source_diversification" }),
  Q("dg_top_source_share", "demand", "Top-source share",
    "What share of new business comes from your single biggest source?",
    { business_term: "Top lead source share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_referrals", "demand", "Referrals",
    "How does a typical referral happen — who sends it, and what do they say?",
    { business_term: "Referral mechanism" }),
  Q("dg_inbound", "demand", "Inbound inquiries",
    "When someone reaches out cold, where did they usually find you?",
    { business_term: "Inbound discovery path" }),
  Q("dg_website", "demand", "Website & content",
    "Does your website actually generate inquiries, or is it mostly a brochure?",
    { business_term: "Website lead role" }),
  Q("dg_thought_leadership", "demand", "Thought leadership",
    "Do you publish anything regularly — articles, talks, podcasts, posts?",
    { business_term: "Thought leadership cadence" }),
  Q("dg_proof", "demand", "Proof",
    "What proof can a prospect see — case studies, testimonials, named clients?",
    { business_term: "Proof inventory" }),
  Q("dg_partnerships", "demand", "Partner channels",
    "Do you get business from partners or other firms, and how does that flow?",
    { business_term: "Partner referral channels" }),
  Q("dg_outbound", "demand", "Outbound",
    "Do you do any outbound — targeted outreach, networking, or follow-up campaigns?",
    { business_term: "Outbound activity" }),
  Q("dg_owner_network", "demand", "Owner network",
    "How much of new business still comes through your personal relationships?",
    { business_term: "Owner relationship dependency",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      report_finding_seed: "Owner relationship dependency in lead flow",
      repair_map_trigger_seed: "owner_sales_dependency_reduction" }),
  Q("dg_pipeline_visibility", "demand", "Pipeline visibility",
    "Where does your pipeline live today — a CRM (HubSpot, Salesforce, Pipedrive), a spreadsheet, or someone's head?",
    { business_term: "Pipeline system",
      source_of_truth_guidance: "CRM (HubSpot / Salesforce / Pipedrive) or pipeline spreadsheet" }),
  Q("dg_pipeline_tracked", "demand", "Pipeline tracking discipline",
    "When a new opportunity comes in, what gets recorded — source, stage, and next follow-up?",
    { business_term: "Lead tracking fields" }),
  Q("dg_lead_consistency", "demand", "Lead consistency",
    "Are leads steady week to week, or do they come in big bursts and dry spells?",
    { business_term: "Lead flow consistency" }),
  // Demand CDDs
  CDD("dg_cdd_pipeline_gap", "demand", "Pipeline discipline gap",
    "dg_pipeline_visibility",
    "Pipeline lives in someone's head, in a stale spreadsheet, or fields are inconsistent.",
    "Walk me through how you would know today which 5 opportunities are closest to signing.",
    { report_finding_seed: "Pipeline discipline gap",
      repair_map_trigger_seed: "pipeline_discipline_install",
      admin_interpretation: "If owner can't name top 5 + next step + close date, treat pipeline as not tracked.",
      admin_only_notes: "Pipeline Discipline Gap risk trigger." }),
  CDD("dg_cdd_referral_concentration", "demand", "Referral concentration",
    "dg_top_source_share",
    "Top source share is 60% or more of new business.",
    "If referrals from that source slowed for 90 days, what would replace them?",
    { report_finding_seed: "Referral concentration risk",
      repair_map_trigger_seed: "referral_diversification",
      admin_interpretation: "High referral share masks pipeline fragility — treat lead flow as owner-relationship dependent." }),
  CDD("dg_cdd_no_proof", "demand", "Proof inventory gap",
    "dg_proof",
    "Owner can't name 3 reachable case studies, testimonials, or named-client proofs.",
    "Could you list 3 specific clients whose results you could show a prospect this week?",
    { report_finding_seed: "Proof inventory gap",
      repair_map_trigger_seed: "case_study_capture_install" }),
  CDD("dg_cdd_owner_network_high", "demand", "Owner-network dependency",
    "dg_owner_network",
    "Owner-network share of new business is 60% or more.",
    "If you stopped attending events and personal intros for 6 months, what would happen to leads?",
    { report_finding_seed: "Owner Sales Bottleneck",
      repair_map_trigger_seed: "owner_sales_bottleneck_relief",
      admin_interpretation: "Owner network 60%+ = Owner Sales Bottleneck signal even when revenue looks healthy." }),
  CDD("dg_cdd_lead_source_tracking", "demand", "Lead source tracking",
    "dg_pipeline_tracked",
    "Lead source isn't recorded for every new opportunity.",
    "When you look back 90 days, can you tell what % of leads came from each source?",
    { report_finding_seed: "Lead source visibility gap",
      repair_map_trigger_seed: "lead_source_capture_install" }),
  CDD("dg_cdd_seasonality_planning", "demand", "Seasonality planning",
    "bp_seasonality",
    "Slow months are a known pattern but no plan exists to fill them.",
    "What is the plan for the next slow stretch — outbound, content, partner push, or wait it out?",
    { report_finding_seed: "Seasonality planning gap",
      repair_map_trigger_seed: "seasonal_pipeline_plan" }),
  CDD("dg_cdd_inbound_dropoff", "demand", "Inbound dropoff",
    "dg_inbound",
    "Inbound inquiries arrive but conversion to discovery call is low or unknown.",
    "What happens between someone filling out a form and getting on a call with you?",
    { report_finding_seed: "Inbound response gap",
      repair_map_trigger_seed: "inbound_response_sla_install" }),
  CDD("dg_cdd_content_consistency", "demand", "Content consistency",
    "dg_thought_leadership",
    "Publishing happens occasionally but no cadence or owner is named.",
    "Who owns the publishing calendar, and when did the last piece actually go out?",
    { report_finding_seed: "Thought leadership cadence gap",
      repair_map_trigger_seed: "publishing_cadence_install" }),

  // ── Revenue Conversion (Sales) ─────────────────────────────────────────
  Q("rc_discovery", "sales", "Discovery process",
    "Walk me through what happens between a first reply and a discovery call.",
    { business_term: "Discovery process" }),
  Q("rc_qualification", "sales", "Qualification",
    "How do you decide whether a prospect is a fit before writing a proposal?",
    { business_term: "Client qualification" }),
  Q("rc_decision_maker", "sales", "Decision-maker access",
    "Are you usually talking to the actual decision-maker, or to someone who has to ask?",
    { business_term: "Decision-maker access" }),
  Q("rc_proposal_speed", "sales", "Proposal turnaround",
    "From first call to proposal sent, how long does it usually take?",
    { business_term: "Proposal turnaround" }),
  Q("rc_proposal_template", "sales", "Proposal templates",
    "Do proposals start from a template, or are they written from scratch each time?",
    { business_term: "Proposal templates" }),
  Q("rc_close_rate", "sales", "Close rate",
    "Of qualified opportunities, roughly what percent become signed engagements?",
    { business_term: "Close rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_followup", "sales", "Proposal follow-up",
    "After a proposal goes out, what is the follow-up cadence — and who owns it?",
    { business_term: "Proposal follow-up cadence" }),
  Q("rc_stalled", "sales", "Stalled proposals",
    "When a proposal goes quiet, what usually happens — and why does it stall?",
    { business_term: "Stalled proposal handling" }),
  Q("rc_pricing_model", "sales", "Pricing model",
    "How do you set the price — fixed, hourly, value-based, or some mix?",
    { business_term: "Pricing model" }),
  Q("rc_discounting", "sales", "Discounting",
    "How often do you discount to close, and what triggers it?",
    { business_term: "Discounting behavior" }),
  Q("rc_avg_deal", "sales", "Average deal size",
    "What's the average size of a signed engagement?",
    { business_term: "Average deal size",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true } }),
  Q("rc_cycle_length", "sales", "Sales cycle length",
    "From first contact to signed agreement, how long does a typical deal take?",
    { business_term: "Sales cycle length" }),
  Q("rc_handoff", "sales", "Sales-to-delivery handoff",
    "Once a deal is signed, how does it get handed to the team that delivers it?",
    { business_term: "Sales-to-delivery handoff" }),
  Q("rc_owner_sales", "sales", "Owner involvement in sales",
    "Of every closed engagement, what share involved you personally on the call or in the close?",
    { business_term: "Owner sales involvement",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  // Sales CDDs
  CDD("rc_cdd_proposal_followup_gap", "sales", "Proposal follow-up gap",
    "rc_followup",
    "Follow-up isn't on a defined cadence or no one owns it.",
    "Of the last 10 proposals, how many got a 2nd, 3rd, and 4th follow-up — and who did them?",
    { report_finding_seed: "Proposal Follow-Up Gap",
      repair_map_trigger_seed: "proposal_followup_cadence_install",
      admin_interpretation: "If owner can't recall follow-up history, treat proposal aging as informal." }),
  CDD("rc_cdd_stalled_root", "sales", "Stalled proposal root cause",
    "rc_stalled",
    "Owner cannot point to the top 2 reasons proposals stall.",
    "When was the last time you asked a stalled prospect directly what was holding them up?",
    { report_finding_seed: "Stalled proposal root-cause gap",
      repair_map_trigger_seed: "stalled_proposal_recovery_install" }),
  CDD("rc_cdd_scope_clarity", "sales", "Scope clarity",
    "rc_proposal_template",
    "Proposals are written from scratch or scope is described loosely.",
    "Show me how a typical scope-of-work paragraph reads — what's in, what's out, what's a change order?",
    { report_finding_seed: "Scope clarity gap",
      repair_map_trigger_seed: "scope_template_install" }),
  CDD("rc_cdd_discount_pattern", "sales", "Discount pattern",
    "rc_discounting",
    "Discounts happen often or are not tracked.",
    "When you discount, do you record the reason and the amount, or is it forgotten after the close?",
    { report_finding_seed: "Discount discipline gap",
      repair_map_trigger_seed: "discount_capture_install" }),
  CDD("rc_cdd_owner_sales_bottleneck", "sales", "Owner sales bottleneck",
    "rc_owner_sales",
    "Owner share of closes is 70% or more.",
    "If you took 30 days off, how many of your current open proposals would close without you?",
    { report_finding_seed: "Owner Sales Bottleneck",
      repair_map_trigger_seed: "sales_team_close_capability_install",
      admin_interpretation: "Owner closing 70%+ = Owner Sales Bottleneck even if revenue looks healthy." }),
  CDD("rc_cdd_qualification_gap", "sales", "Qualification gap",
    "rc_qualification",
    "Owner can't list 3 disqualifying criteria they actually use.",
    "What kind of prospect do you now turn down that you used to take?",
    { report_finding_seed: "Qualification discipline gap",
      repair_map_trigger_seed: "qualification_criteria_install" }),
  CDD("rc_cdd_proposal_speed", "sales", "Proposal speed risk",
    "rc_proposal_speed",
    "Proposal turnaround averages 7+ days.",
    "What slows a proposal down most often — pricing, scope, dependencies, or owner time?",
    { report_finding_seed: "Proposal turnaround drag",
      repair_map_trigger_seed: "proposal_turnaround_install" }),
  CDD("rc_cdd_handoff_gap", "sales", "Sales-to-delivery handoff gap",
    "rc_handoff",
    "Handoff is informal — same person sells and delivers, or kickoff is improvised.",
    "When a deal is signed, what specifically gets passed to the delivery team and what stays in your head?",
    { report_finding_seed: "Sales-to-delivery handoff gap",
      repair_map_trigger_seed: "sales_handoff_install" }),

  // ── Operational Efficiency ─────────────────────────────────────────────
  Q("op_delivery_workflow", "operations", "Delivery workflow",
    "Walk me through what a typical engagement looks like from kickoff to wrap-up.",
    { business_term: "Delivery workflow" }),
  Q("op_kickoff", "operations", "Client kickoff",
    "What happens in the first 7 days after a client signs?",
    { business_term: "Client kickoff process" }),
  Q("op_onboarding_doc", "operations", "Onboarding documentation",
    "Is there a written onboarding checklist, or does each engagement start a little differently?",
    { business_term: "Onboarding standardization" }),
  Q("op_pm_system", "operations", "Project management system",
    "What tool actually runs the work — and is it used the same way by everyone?",
    { business_term: "PM system" }),
  Q("op_capacity", "operations", "Capacity planning",
    "How do you decide whether the team can take on another engagement?",
    { business_term: "Capacity planning" }),
  Q("op_utilization", "operations", "Utilization",
    "What share of the team's hours each week is actually billable?",
    { business_term: "Utilization rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_rework", "operations", "Rework",
    "How often does work need to be redone, and what usually causes it?",
    { business_term: "Rework rate" }),
  Q("op_scope_creep", "operations", "Scope creep",
    "How often does scope creep eat margin, and how is it caught when it happens?",
    { business_term: "Scope creep frequency",
      report_finding_seed: "Scope Creep Leakage",
      repair_map_trigger_seed: "change_order_discipline_install" }),
  Q("op_change_order", "operations", "Change orders",
    "When a client asks for something outside scope, what is the actual process?",
    { business_term: "Change order process" }),
  Q("op_deadlines", "operations", "Deadline tracking",
    "How do you know today which engagements are on time and which are slipping?",
    { business_term: "Deadline visibility" }),
  Q("op_communication", "operations", "Client communication cadence",
    "What is the regular client communication rhythm — emails, status calls, written updates?",
    { business_term: "Client communication cadence" }),
  Q("op_quality", "operations", "Quality control",
    "What gets reviewed before work goes to a client, and who reviews it?",
    { business_term: "Internal QA process" }),
  Q("op_meeting_load", "operations", "Meeting load",
    "How many hours per week does your team spend in internal meetings?",
    { business_term: "Internal meeting load",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_approvals", "operations", "Approvals",
    "Where do approvals get stuck most often — and whose desk are they sitting on?",
    { business_term: "Approval bottlenecks" }),
  Q("op_task_ownership", "operations", "Task ownership",
    "For each open engagement, can you name the one person responsible for delivery?",
    { business_term: "Task ownership clarity" }),
  Q("op_recurring", "operations", "Recurring service cadence",
    "For retainer work, what is the standard rhythm, and what gets delivered each cycle?",
    { business_term: "Retainer delivery cadence" }),
  // Ops CDDs
  CDD("op_cdd_onboarding", "operations", "Client onboarding weakness",
    "op_onboarding_doc",
    "Onboarding checklist is missing or each engagement starts a little differently.",
    "What's the first thing that gets forgotten when a new client signs?",
    { report_finding_seed: "Client Onboarding Weakness",
      repair_map_trigger_seed: "client_onboarding_install" }),
  CDD("op_cdd_pm_discipline", "operations", "PM system discipline",
    "op_pm_system",
    "PM tool exists but task status, owner, or due date isn't kept current.",
    "If I opened your PM tool right now, would I see real status — or would you say 'don't go by that'?",
    { report_finding_seed: "PM discipline gap",
      repair_map_trigger_seed: "pm_discipline_install" }),
  CDD("op_cdd_capacity", "operations", "Capacity planning gap",
    "op_capacity",
    "Owner answers capacity questions by gut, not by hours/headcount.",
    "How would you know today whether you can add one more 80-hour project this month?",
    { report_finding_seed: "Capacity Planning Gap",
      repair_map_trigger_seed: "capacity_planning_install",
      admin_interpretation: "Capacity 'feels full' without numbers = capacity gap, not actual full." }),
  CDD("op_cdd_utilization", "operations", "Utilization visibility gap",
    "op_utilization",
    "Owner can't quote utilization within ±10%.",
    "How do you currently track billable vs. non-billable hours by person?",
    { report_finding_seed: "Utilization Visibility Gap",
      repair_map_trigger_seed: "utilization_visibility_install" }),
  CDD("op_cdd_scope_creep", "operations", "Scope creep enforcement",
    "op_change_order",
    "Out-of-scope work is done without a tracked change order.",
    "Of the last 5 things a client asked for outside scope, how many turned into a change order?",
    { report_finding_seed: "Scope Creep Leakage",
      repair_map_trigger_seed: "change_order_enforcement_install",
      admin_interpretation: "If 'we just helped them' is the pattern, scope leakage is bleeding margin invisibly." }),
  CDD("op_cdd_quality_dependent", "operations", "Quality dependence on owner",
    "op_quality",
    "Quality varies by who performs the work or owner reviews everything.",
    "What happens to quality when you don't personally review the deliverable?",
    { report_finding_seed: "Delivery Standards Gap",
      repair_map_trigger_seed: "delivery_standards_install" }),
  CDD("op_cdd_deadline_slip", "operations", "Deadline slippage",
    "op_deadlines",
    "Owner can't quickly identify which engagements are slipping.",
    "What is the system for catching a slipping deadline before the client notices?",
    { report_finding_seed: "Deadline visibility gap",
      repair_map_trigger_seed: "deadline_dashboard_install" }),
  CDD("op_cdd_meeting_load", "operations", "Meeting load drag",
    "op_meeting_load",
    "Internal meeting load exceeds 8 hours per person per week.",
    "Which recurring meetings would the team quietly cancel if you let them?",
    { report_finding_seed: "Internal meeting drag",
      repair_map_trigger_seed: "meeting_load_review" }),
  CDD("op_cdd_recurring_drift", "operations", "Retainer cadence drift",
    "op_recurring",
    "Retainer deliverables aren't standardized or monthly value isn't documented.",
    "What does each retainer client get every month, and where is that written down?",
    { report_finding_seed: "Retainer cadence drift",
      repair_map_trigger_seed: "retainer_deliverable_standardization" }),

  // ── Financial Visibility ───────────────────────────────────────────────
  Q("fv_books", "financial", "Books status",
    "Are your books current, and who keeps them up?",
    { business_term: "Books currency",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks" }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's your average monthly revenue right now?",
    { business_term: "Monthly revenue",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("fv_revenue_by_service", "financial", "Revenue by service line",
    "Do you know revenue split by service line, or only the top-line number?",
    { business_term: "Revenue by service line" }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know your gross margin by project or service?",
    { business_term: "Gross margin by project",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_effective_rate", "financial", "Effective hourly rate",
    "Do you know what each engagement actually earns per hour after delivery time?",
    { business_term: "Effective hourly rate" }),
  Q("fv_billable_split", "financial", "Billable vs non-billable",
    "What share of your team's time is billable vs. internal?",
    { business_term: "Billable vs non-billable split",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_open_ar", "financial", "Open AR",
    "How much money is owed to you right now from clients?",
    { business_term: "Open AR / unpaid invoices",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks AR Aging Report" }),
  Q("fv_billing_cadence", "financial", "Billing cadence",
    "When does an invoice usually go out — at milestones, monthly, or when work feels 'done enough'?",
    { business_term: "Billing cadence" }),
  Q("fv_collection", "financial", "Collection",
    "When an invoice goes past due, what is the actual follow-up process?",
    { business_term: "AR collection process" }),
  Q("fv_writeoffs", "financial", "Write-offs",
    "How often do you end up writing off time or invoices, and what causes it?",
    { business_term: "Write-off pattern" }),
  Q("fv_retainer_mix", "financial", "Retainer / project mix",
    "What share of revenue is retainer vs. one-off project work?",
    { business_term: "Retainer vs. project mix",
      answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("fv_concentration", "financial", "Client concentration",
    "What share of revenue comes from your single largest client?",
    { business_term: "Top-client revenue share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_backlog", "financial", "Backlog visibility",
    "How much signed work do you have on the books for the next 90 days?",
    { business_term: "Signed backlog",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_forecast", "financial", "Forecast visibility",
    "When you look at the next 90 days, can you tell whether revenue will be up, flat, or down?",
    { business_term: "Forecast visibility" }),
  // Financial CDDs
  CDD("fv_cdd_books_lag", "financial", "Books lag",
    "fv_books",
    "Books are more than 30 days behind or owner isn't sure.",
    "When was the last month closed in QuickBooks, and who closed it?",
    { report_finding_seed: "Books currency gap",
      repair_map_trigger_seed: "books_close_cadence_install" }),
  CDD("fv_cdd_project_profit", "financial", "Project profitability",
    "fv_gross_margin",
    "Owner knows revenue per project but can't quote cost or hours per project.",
    "Pick your last big engagement — can you tell me revenue and total delivery hours on it?",
    { report_finding_seed: "Project Profitability Gap",
      repair_map_trigger_seed: "project_margin_visibility_install",
      admin_interpretation: "If hours per project aren't tracked, all margin claims are owner estimate." }),
  CDD("fv_cdd_effective_rate", "financial", "Effective hourly blind spot",
    "fv_effective_rate",
    "Owner can't quote effective hourly rate by service line.",
    "If we divided last month's billed revenue by total delivery hours, would you know the number?",
    { report_finding_seed: "Effective Hourly Rate Blind Spot",
      repair_map_trigger_seed: "effective_rate_visibility_install" }),
  CDD("fv_cdd_ar_aging", "financial", "AR aging risk",
    "fv_open_ar",
    "Owner can't quote AR within ±20% or AR > 30 days is unknown.",
    "How much of that AR is more than 30 days old, and who is the largest piece?",
    { report_finding_seed: "AR / Billing Cadence Risk",
      repair_map_trigger_seed: "ar_aging_review_install" }),
  CDD("fv_cdd_billing_cadence", "financial", "Billing cadence risk",
    "fv_billing_cadence",
    "Invoicing happens 'when work feels done' or owner controls timing case by case.",
    "What is the rule that says 'this invoice should go out today'?",
    { report_finding_seed: "AR / Billing Cadence Risk",
      repair_map_trigger_seed: "billing_cadence_install",
      admin_interpretation: "Subjective billing timing = cash flow risk and owner dependency on billing decisions." }),
  CDD("fv_cdd_collection_owner", "financial", "Owner-driven collections",
    "fv_collection",
    "Owner personally chases overdue invoices.",
    "If you stopped chasing collections personally, what would happen in 30 days?",
    { report_finding_seed: "Collections owner dependency",
      repair_map_trigger_seed: "collections_process_install" }),
  CDD("fv_cdd_concentration", "financial", "Client concentration risk",
    "fv_concentration",
    "Top client is 25% or more of revenue.",
    "If your top client paused for 90 days, what would the business look like?",
    { report_finding_seed: "Client Concentration Risk",
      repair_map_trigger_seed: "client_concentration_diversification",
      admin_interpretation: "Top-client share ≥25% = concentration risk regardless of relationship strength." }),
  CDD("fv_cdd_retainer_mix", "financial", "Retainer / project mix risk",
    "fv_retainer_mix",
    "Less than 30% of revenue is recurring retainer.",
    "What would it take to convert 2 of your project clients into a retainer this quarter?",
    { report_finding_seed: "Retainer / Project Mix Risk",
      repair_map_trigger_seed: "retainer_conversion_program" }),
  CDD("fv_cdd_backlog_blind", "financial", "Backlog blind spot",
    "fv_backlog",
    "Owner can't quote 90-day signed backlog.",
    "If hiring depended on knowing your backlog this morning, where would you go to find it?",
    { report_finding_seed: "Backlog visibility gap",
      repair_map_trigger_seed: "backlog_visibility_install" }),

  // ── Owner Independence ─────────────────────────────────────────────────
  Q("oi_billable_owner", "owner_independence", "Owner billable load",
    "What share of your week is still spent on billable client work?",
    { business_term: "Owner billable load",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_delivery_dependency", "owner_independence", "Owner delivery dependency",
    "On a typical engagement, what only you can deliver?",
    { business_term: "Owner delivery dependency",
      report_finding_seed: "Owner Delivery Bottleneck",
      repair_map_trigger_seed: "delivery_team_capability_install" }),
  Q("oi_escalation", "owner_independence", "Client escalation",
    "When a client gets unhappy, who do they call — you or someone else?",
    { business_term: "Client escalation path" }),
  Q("oi_proposal_dependency", "owner_independence", "Proposal dependency",
    "Can anyone other than you write and send a proposal end-to-end?",
    { business_term: "Proposal dependency" }),
  Q("oi_team_lead", "owner_independence", "Team lead authority",
    "Is there a team lead or manager with real decision authority below you?",
    { business_term: "Team lead authority" }),
  Q("oi_decision_rights", "owner_independence", "Decision rights",
    "What decisions can the team make without checking with you?",
    { business_term: "Decision rights" }),
  Q("oi_handoff_rules", "owner_independence", "Client handoff rules",
    "When a client moves from sales to delivery, what gets handed off and what stays with you?",
    { business_term: "Client handoff rules" }),
  Q("oi_documented_standards", "owner_independence", "Documented delivery standards",
    "Are delivery standards written down, or are they 'how we do it' that lives in your head?",
    { business_term: "Documented delivery standards" }),
  Q("oi_vacation_test", "owner_independence", "Vacation test",
    "If you took 14 straight days off with no contact, what would break first?",
    { business_term: "Vacation-test break point" }),
  Q("oi_client_knowledge", "owner_independence", "Client knowledge concentration",
    "How much of what each client wants and dislikes lives only in your head?",
    { business_term: "Client knowledge concentration" }),
  Q("oi_quality_owner", "owner_independence", "Quality review ownership",
    "Who owns the final quality check on client deliverables?",
    { business_term: "Quality review ownership" }),
  // OI CDDs
  CDD("oi_cdd_delivery_bottleneck", "owner_independence", "Owner delivery bottleneck",
    "oi_delivery_dependency",
    "More than 40% of delivery still requires the owner.",
    "If you were unavailable for 30 days, which active engagements would actually pause?",
    { report_finding_seed: "Owner Delivery Bottleneck",
      repair_map_trigger_seed: "delivery_redundancy_install",
      admin_interpretation: "Owner-on-everything = bottleneck even when team is technically capable." }),
  CDD("oi_cdd_escalation", "owner_independence", "Escalation dependency",
    "oi_escalation",
    "Unhappy clients always escalate to the owner.",
    "What is the defined first response when a client says 'we have a problem'?",
    { report_finding_seed: "Client Escalation Dependency",
      repair_map_trigger_seed: "escalation_path_install" }),
  CDD("oi_cdd_proposal_dependency", "owner_independence", "Proposal dependency",
    "oi_proposal_dependency",
    "Owner is the only person who writes proposals.",
    "What part of a proposal could be drafted by someone else this quarter, even partially?",
    { report_finding_seed: "Proposal owner dependency",
      repair_map_trigger_seed: "proposal_authoring_redundancy" }),
  CDD("oi_cdd_decision_rights", "owner_independence", "Decision rights gap",
    "oi_decision_rights",
    "Team can't list 5 decisions they own without checking with the owner.",
    "What is one decision the team should be making without you that they aren't?",
    { report_finding_seed: "Decision rights gap",
      repair_map_trigger_seed: "decision_rights_install" }),
  CDD("oi_cdd_documented_gap", "owner_independence", "Documentation gap",
    "oi_documented_standards",
    "Delivery standards mostly live in the owner's head.",
    "If you hired one new delivery person tomorrow, what would they read in their first week?",
    { report_finding_seed: "Delivery Standards Gap",
      repair_map_trigger_seed: "delivery_standards_documentation",
      admin_interpretation: "If onboarding is 'shadow me', standards aren't documented." }),
  CDD("oi_cdd_vacation_test", "owner_independence", "Vacation test failure",
    "oi_vacation_test",
    "Owner believes more than one critical thing would break in 14 days.",
    "Of those break points, which one would you fix first if it had to hold for a real vacation?",
    { report_finding_seed: "Vacation-test failure",
      repair_map_trigger_seed: "vacation_test_remediation" }),
  CDD("oi_cdd_client_knowledge", "owner_independence", "Client knowledge trapped",
    "oi_client_knowledge",
    "Owner says 'most of it' lives in their head.",
    "Where would a teammate go to learn what your top 3 clients hate before a call?",
    { report_finding_seed: "Client knowledge concentration",
      repair_map_trigger_seed: "client_account_brief_install" }),

  // ── Evidence / Source-of-Truth ─────────────────────────────────────────
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent profit and loss statement?",
    { evidence_prompt: "Trailing 12-month P&L from QuickBooks / Xero / FreshBooks",
      source_of_truth_guidance: "Accounting system P&L (QuickBooks / Xero / FreshBooks)" }),
  Q("ev_ar_aging", "evidence", "AR aging",
    "Could you pull AR aging from your accounting system?",
    { evidence_prompt: "AR Aging Summary as of today",
      source_of_truth_guidance: "QuickBooks / Xero AR Aging Report" }),
  Q("ev_crm_pipeline", "evidence", "CRM pipeline export",
    "Could you export your pipeline from your CRM?",
    { evidence_prompt: "CRM pipeline with stage, owner, and close-date fields",
      source_of_truth_guidance: "HubSpot / Salesforce / Pipedrive pipeline export" }),
  Q("ev_proposal_log", "evidence", "Proposal log",
    "Could you pull a list of every proposal sent in the last 90 days?",
    { evidence_prompt: "90-day proposal log with status, value, and last-touch date",
      source_of_truth_guidance: "Proposal tool, CRM, or proposal folder" }),
  Q("ev_close_rate_report", "evidence", "Close-rate report",
    "Could we see a close-rate calculation by source for the last 6 months?",
    { evidence_prompt: "Close rate by lead source, last 6 months" }),
  Q("ev_discovery_notes", "evidence", "Discovery call notes",
    "Where do discovery call notes live, and could you share an example?",
    { evidence_prompt: "Sample discovery call notes (last 30 days)" }),
  Q("ev_scope_sow", "evidence", "Signed scope / SOW",
    "Could you share a recent signed scope of work or engagement letter?",
    { evidence_prompt: "Recent signed SOW / engagement letter" }),
  Q("ev_change_orders", "evidence", "Change order records",
    "Could you pull your change order records from the last 90 days?",
    { evidence_prompt: "Change orders with date, scope delta, and price impact" }),
  Q("ev_pm_export", "evidence", "PM system export",
    "Could you export tasks and statuses from your project management tool?",
    { evidence_prompt: "PM export with task, owner, due date, and status" }),
  Q("ev_time_tracking", "evidence", "Time tracking report",
    "Could you pull a time-tracking report by person and project for the last 30 days?",
    { evidence_prompt: "Time tracking by person × project, last 30 days",
      source_of_truth_guidance: "Time tracker (Harvest / Toggl / built-in PM tool)" }),
  Q("ev_utilization_report", "evidence", "Utilization report",
    "Is there a utilization report we can review?",
    { evidence_prompt: "Utilization rate by person, last 30/60/90 days" }),
  Q("ev_project_margin", "evidence", "Project margin report",
    "Is there a per-project margin report, even informal?",
    { evidence_prompt: "Project margin = revenue − labor cost − pass-through" }),
  Q("ev_revenue_service_line", "evidence", "Revenue by service line",
    "Could you share revenue by service line for the last 12 months?",
    { evidence_prompt: "Revenue by service line, trailing 12 months" }),
  Q("ev_client_concentration", "evidence", "Client concentration report",
    "Could we see a top-client revenue concentration list?",
    { evidence_prompt: "Top 10 clients by revenue, trailing 12 months" }),
  Q("ev_invoice_aging", "evidence", "Invoice aging",
    "Could we see invoice aging by client?",
    { evidence_prompt: "Invoice aging by client (current / 30 / 60 / 90+)" }),
  Q("ev_billing_cadence", "evidence", "Billing cadence record",
    "Could you show the billing cadence for your top 5 clients — when each is billed and how?",
    { evidence_prompt: "Billing cadence per client (milestone / monthly / hourly)" }),
  Q("ev_retainer_list", "evidence", "Retainer list",
    "Could you share a list of active retainer clients with monthly value?",
    { evidence_prompt: "Active retainer list with start date and monthly value" }),
  Q("ev_onboarding_checklist", "evidence", "Client onboarding checklist",
    "Is there a written client onboarding checklist?",
    { evidence_prompt: "Client onboarding checklist document" }),
  Q("ev_kickoff_checklist", "evidence", "Kickoff checklist",
    "Is there a written kickoff checklist for new engagements?",
    { evidence_prompt: "Kickoff checklist document" }),
  Q("ev_delivery_sops", "evidence", "Delivery SOPs",
    "Could you share any written delivery SOPs or playbooks?",
    { evidence_prompt: "Delivery SOPs / playbooks for top service lines" }),
  Q("ev_qa_checklist", "evidence", "Quality review checklist",
    "Is there a quality review checklist used before deliverables go out?",
    { evidence_prompt: "Pre-delivery QA checklist" }),
  Q("ev_owner_calendar", "evidence", "Owner calendar",
    "Could we see two recent typical weeks of your calendar?",
    { evidence_prompt: "Owner calendar — 2 representative weeks",
      admin_only_notes: "Used to verify owner billable load and meeting drag claims." }),

  // ── Admin Interpretation Support (admin-only listening cues) ───────────
  Q("ai_quote_busy_unsure_worth", "financial", "Owner-quote: busy but unsure",
    "Listen for: 'We're busy, but I'm not sure which projects are actually worth it.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Project profitability blind spot signal",
      admin_interpretation: "Signals utilization + project profitability + scope creep risk. Trigger time tracking, project margin, AR, and proposal evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_referrals_no_pipeline", "demand", "Owner-quote: referrals only",
    "Listen for: 'Most clients come from referrals, so we don't really track pipeline.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Referral-only pipeline signal",
      admin_interpretation: "Signals referral concentration + pipeline visibility gap + owner relationship dependency. Trigger CRM and referral-log evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_help_them_anyway", "operations", "Owner-quote: small favors",
    "Listen for: 'We usually just help the client if they ask for something small.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Scope creep leakage signal",
      admin_interpretation: "Signals scope creep + weak change order discipline + margin/time leakage. Trigger SOW and change-order evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_owner_quality", "owner_independence", "Owner-quote: quality control",
    "Listen for: 'I still jump in on most projects because I want the quality right.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Owner delivery bottleneck signal",
      admin_interpretation: "Signals owner delivery bottleneck + delivery standards gap + team lead readiness gap. Trigger SOPs/standards evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_invoice_when_done", "financial", "Owner-quote: subjective billing",
    "Listen for: 'We invoice when the project gets to a good stopping point.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Subjective billing cadence signal",
      admin_interpretation: "Signals billing cadence risk + cash-flow timing risk + AR visibility gap. Trigger billing cadence + AR aging evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_team_capable_but", "owner_independence", "Owner-quote: partial delegation",
    "Listen for: 'The team can run things, but they always check with me on pricing and scope.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Partial delegation signal",
      admin_interpretation: "Partial delegation = decision-rights gap and proposal dependency even when delivery looks delegated.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
  Q("ai_quote_one_big_client", "financial", "Owner-quote: one big client",
    "Listen for: 'One client is most of our revenue, but the relationship is rock solid.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Concentration confidence signal",
      admin_interpretation: "Strong relationship does not reduce concentration risk. Trigger client concentration + backlog evidence asks.",
      admin_only_notes: "Admin-only listening cue — never read to client." }),
];

export const PROFESSIONAL_SERVICES_BANK: IndustryQuestionBank = {
  industry: I,
  label: "Professional Services",
  questions: QUESTIONS,
};
