/** P93E-E2G — Restaurants / Food Service starter bank. */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";
const I = "restaurants_food_service" as const;
const Q = (key: string, gear: DiagnosticQuestion["gear"], section: string, plain: string,
  extra: Partial<DiagnosticQuestion> = {}): DiagnosticQuestion => ({
  key: `restaurants.${key}`, industry: I, gear, section,
  plain_language_question: plain, answer_type: "narrative", capture: { notes: true }, ...extra,
});
const QUESTIONS: DiagnosticQuestion[] = [
  Q("bp_concept", "business_profile", "Concept & format",
    "What's the concept — fast casual, full service, ghost kitchen, catering — and how many seats / how big is the kitchen?"),
  Q("bp_dayparts", "business_profile", "Dayparts",
    "Which dayparts (breakfast, lunch, dinner, late night) actually drive the revenue?",
    { capture: { notes: true, seasonal: true } }),
  Q("bp_locations", "business_profile", "Locations",
    "How many locations and how is staffing structured across them?", { answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("dg_traffic", "demand", "Customer traffic",
    "Roughly how many guests do you serve per week, and how does that swing seasonally?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true, seasonal: true } }),
  Q("dg_delivery_mix", "demand", "Delivery / 3rd-party mix",
    "What share of revenue comes through DoorDash, Uber Eats, Grubhub, or your own delivery?", { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_reviews", "demand", "Reviews / Google",
    "How are reviews looking on Google and Yelp, and who responds to them?"),
  Q("rc_avg_check", "sales", "Average check",
    "What's your average check or per-guest spend right now?",
    { business_term: "Average ticket", answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("rc_upsell", "sales", "Upsell / attach",
    "What's your process for upselling apps, drinks, desserts? Does it actually happen?"),
  Q("op_pos", "operations", "POS system",
    "What POS are you using — Square, Toast, Clover, Aloha — and what does it actually report on?",
    { source_of_truth_guidance: "POS sales mix / labor / item-level reports" }),
  Q("op_labor_pct", "operations", "Labor as % of sales",
    "Do you know what your labor cost as a percent of sales is week to week?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_food_cost", "operations", "Food cost",
    "What's your food cost percentage, and how often is inventory counted?",
    { business_term: "Food cost / COGS", answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_waste", "operations", "Waste / spoilage",
    "Is waste tracked? How do you catch spoilage and over-portioning?",
    { repair_map_signal: "Inventory Variance Risk" }),
  Q("op_scheduling", "operations", "Scheduling / no-shows",
    "Walk me through how shifts get built and what happens when someone no-shows."),
  Q("op_health_compliance", "operations", "Health / inspection",
    "When was your last health inspection, and how do you stay ready between them?"),
  Q("fv_qb", "financial", "Books status",
    "Are your books current in QuickBooks/Xero, and who keeps them up?",
    { source_of_truth_guidance: "QuickBooks / Xero" }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's your average monthly revenue right now?", { answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true } }),
  Q("fv_prime_cost", "financial", "Prime cost",
    "Do you track prime cost (food + labor) weekly?",
    { business_term: "Prime cost (food + labor)", answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("oi_owner_role", "owner_independence", "Owner in operations",
    "How many shifts a week are you personally on the floor or in the kitchen?",
    { repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_gm", "owner_independence", "GM / KM coverage",
    "Do you have a GM and a kitchen manager who can actually run the shift without you?"),
  Q("ev_pos_export", "evidence", "POS export",
    "Could you export the last 90 days of POS sales-by-day and labor reports?",
    { evidence_prompt: "POS sales mix + labor by day, last 90 days" }),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent P&L?",
    { evidence_prompt: "Trailing 12-month P&L" }),
  Q("ev_health_records", "evidence", "Health inspection records",
    "Can you share your most recent health inspection report?"),
];
export const RESTAURANTS_FOOD_SERVICE_BANK: IndustryQuestionBank = {
  industry: I, label: "Restaurants / Food Service", questions: QUESTIONS,
};
