/**
 * P93E-E2G-P2 — Restaurants / Food Service full-depth diagnostic interview bank.
 *
 * Plain-English scripted interview, deep diagnostic structure. Each prompt is
 * classified as `core`, `conditional_deep_dive`, `evidence_source_of_truth`,
 * or `admin_interpretation_support` and may carry report-finding seeds and
 * Repair-Map trigger seeds.
 *
 * Health/safety/process questions are framed as operational readiness and
 * documentation visibility only — never as compliance certification.
 */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";

const I = "restaurants_food_service" as const;

const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `restaurants.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

const CDD = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  parent: string,
  triggerWhen: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "conditional_deep_dive",
    parent_key: `restaurants.${parent}`,
    trigger_when: triggerWhen,
    ...extra,
  });

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile ───────────────────────────────────────────────────
  Q("bp_concept", "business_profile", "Concept & format",
    "What's the concept — fast casual, full service, ghost kitchen, or catering — and how big is the kitchen?",
    { business_term: "Concept & format" }),
  Q("bp_seats", "business_profile", "Seating & format",
    "How many seats do you have, and what's the split between dine-in, takeout, and delivery?",
    { business_term: "Seating & service mix", capture: { notes: true, estimated_value: true } }),
  Q("bp_dayparts", "business_profile", "Dayparts",
    "Which dayparts — breakfast, lunch, dinner, late night — actually drive the revenue?",
    { business_term: "Daypart revenue mix", capture: { notes: true, seasonal: true } }),
  Q("bp_locations", "business_profile", "Locations",
    "How many locations do you run, and how is staffing split across them?",
    { business_term: "Locations & staffing structure",
      answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_service_style", "business_profile", "Service style",
    "Walk me through how a customer orders — counter, server, kiosk, app, or a mix?",
    { business_term: "Service style" }),
  Q("bp_menu_size", "business_profile", "Menu size",
    "Roughly how many items are on the menu right now?",
    { business_term: "Menu size",
      answer_type: "numeric", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("bp_kitchen_layout", "business_profile", "Kitchen layout",
    "Walk me through the line — how many stations, and where does the bottleneck usually show up?",
    { business_term: "Kitchen line layout" }),
  Q("bp_neighborhood", "business_profile", "Neighborhood",
    "What's the neighborhood like — foot traffic, parking, nearby competition?",
    { business_term: "Neighborhood traffic context" }),

  // ── Demand Generation ──────────────────────────────────────────────────
  Q("dg_traffic", "demand", "Customer traffic",
    "Roughly how many guests do you serve per week, and how does that swing across the year?",
    { business_term: "Weekly guest volume",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true, seasonal: true },
      source_of_truth_guidance: "POS guest count / cover count report" }),
  Q("dg_repeat_customers", "demand", "Repeat customers",
    "What share of your guests are regulars versus first-timers?",
    { business_term: "Repeat customer share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_delivery_mix", "demand", "Delivery / 3rd-party mix",
    "What share of revenue comes through DoorDash, Uber Eats, Grubhub, or your own delivery?",
    { business_term: "3rd-party delivery share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_reviews", "demand", "Reviews — Google & Yelp",
    "How are reviews looking on Google and Yelp right now, and where are most of them coming from?",
    { business_term: "Review reputation",
      source_of_truth_guidance: "Google Business Profile + Yelp dashboards" }),
  Q("dg_review_response", "demand", "Review response",
    "Who responds to reviews, and how quickly do replies usually go out?",
    { business_term: "Review response cadence" }),
  Q("dg_referrals", "demand", "Referrals & word of mouth",
    "How much of your business is people telling friends about you?",
    { business_term: "Referral / word-of-mouth share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_social", "demand", "Social media",
    "Which social platforms are you actually active on, and who posts?",
    { business_term: "Social media activity" }),
  Q("dg_email_sms", "demand", "Email / SMS list",
    "Do you have an email or text list, and roughly how big is it?",
    { business_term: "Owned audience list size",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_loyalty", "demand", "Loyalty / rewards",
    "Do you have a loyalty or rewards program, and how many people actually use it?",
    { business_term: "Loyalty program adoption" }),
  Q("dg_catering", "demand", "Catering & events",
    "Do you take catering or event business, and how often does an inquiry come in?",
    { business_term: "Catering / event inquiries",
      answer_type: "numeric", capture: { notes: true, estimated_value: true } }),
  Q("dg_promotions", "demand", "Promotions & specials",
    "How often do you run a promotion, special, or LTO, and who decides what to run?",
    { business_term: "Promotion cadence" }),
  Q("dg_source_tracking", "demand", "Customer source tracking",
    "Do you have any way of knowing where new customers are hearing about you?",
    { business_term: "Customer source tracking",
      repair_map_signal: "Demand Source Visibility Gap" }),
  Q("dg_seasonality", "demand", "Seasonality",
    "How big is the swing between your busiest month and your slowest month?",
    { business_term: "Seasonal demand swing",
      answer_type: "seasonal_range", capture: { notes: true, seasonal: true } }),

  // ── Revenue Conversion ─────────────────────────────────────────────────
  Q("rc_avg_check", "sales", "Average check",
    "What's your average check or per-guest spend right now?",
    { business_term: "Average check (per-guest spend)",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "POS sales-by-day / per-cover report" }),
  Q("rc_table_turns", "sales", "Table turns",
    "On a busy night, how many times do you turn each table?",
    { business_term: "Table turns per service",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_upsell", "sales", "Upsell & attach",
    "How do servers or order takers offer apps, drinks, and desserts — and does it actually happen?",
    { business_term: "Upsell / attach consistency" }),
  Q("rc_reservations", "sales", "Reservations & no-shows",
    "Do you take reservations, and what's your no-show rate look like?",
    { business_term: "Reservation flow & no-show rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_phone_orders", "sales", "Phone orders",
    "How many phone orders come in on a normal day, and who takes them?",
    { business_term: "Phone order volume",
      answer_type: "numeric", capture: { notes: true, estimated_value: true } }),
  Q("rc_online_ordering", "sales", "Online ordering",
    "What share of orders come in through your own website or app?",
    { business_term: "Direct online order share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_catering_close", "sales", "Catering close rate",
    "Of catering inquiries that come in, what share actually book?",
    { business_term: "Catering inquiry close rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_menu_engineering", "sales", "Menu engineering",
    "Do you know which items are your stars and which are dragging margin down?",
    { business_term: "Menu engineering visibility",
      source_of_truth_guidance: "POS menu sales mix + recipe cost" }),
  Q("rc_high_margin_movement", "sales", "High-margin item movement",
    "What share of orders include your highest-margin items?",
    { business_term: "High-margin item attach",
      answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("rc_loyalty_conversion", "sales", "Loyalty conversion",
    "Do loyalty members spend more or come back more often than non-members?",
    { business_term: "Loyalty repeat spend lift" }),
  Q("rc_order_accuracy", "sales", "Order accuracy",
    "Roughly how often does an order have to be remade or refunded for accuracy reasons?",
    { business_term: "Order accuracy / remake rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("rc_guest_recovery", "sales", "Guest experience recovery",
    "When a guest is unhappy, what's the actual process for making it right?",
    { business_term: "Service recovery process" }),
  Q("rc_comp_void_controls", "sales", "Comps, voids & discounts",
    "Who can give a comp, void, or discount, and how is it tracked?",
    { business_term: "Comp / void / discount controls",
      repair_map_signal: "Revenue Leakage — Comp/Void/Discount" }),

  // ── Operational Efficiency ─────────────────────────────────────────────
  Q("op_pos", "operations", "POS system",
    "What POS are you using — Square, Toast, Clover, Aloha, or something else — and what does it actually report on?",
    { business_term: "POS platform & reporting depth",
      source_of_truth_guidance: "POS sales mix / labor / item-level reports" }),
  Q("op_prep_systems", "operations", "Prep systems & pars",
    "Do you have written prep sheets and par levels for each station?",
    { business_term: "Prep sheets & par levels" }),
  Q("op_ticket_times", "operations", "Ticket times",
    "Do you track ticket times, and what's a normal target for the line?",
    { business_term: "Ticket time tracking",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_kitchen_bottlenecks", "operations", "Kitchen bottlenecks",
    "When the kitchen gets behind, where does it usually back up first?",
    { business_term: "Line bottleneck pattern" }),
  Q("op_expo_process", "operations", "Expo process",
    "Walk me through the expo — who calls tickets, who plates, who runs?",
    { business_term: "Expo process" }),
  Q("op_waste", "operations", "Waste & spoilage",
    "Is waste tracked anywhere, and how do you catch spoilage or over-portioning?",
    { business_term: "Waste & spoilage tracking",
      repair_map_signal: "Waste / Inventory Leakage" }),
  Q("op_inventory_counts", "operations", "Inventory counts",
    "How often do you count inventory, and who does the counts?",
    { business_term: "Inventory count cadence" }),
  Q("op_ordering_rhythm", "operations", "Vendor ordering rhythm",
    "Walk me through how vendor orders get placed each week — what's on a fixed day, what's reactive?",
    { business_term: "Vendor ordering rhythm" }),
  Q("op_receiving", "operations", "Receiving process",
    "When a delivery comes in, who receives it, and is it actually checked against the invoice?",
    { business_term: "Receiving process" }),
  Q("op_recipe_specs", "operations", "Recipe & spec sheets",
    "Are recipes and plate specs written down where the line can see them?",
    { business_term: "Recipe / spec documentation" }),
  Q("op_portion_control", "operations", "Portion control",
    "How is portion control actually enforced day to day?",
    { business_term: "Portion control discipline" }),
  Q("op_open_close_checklists", "operations", "Open / close checklists",
    "Are there written opening and closing checklists, and does someone sign off?",
    { business_term: "Open/close checklists" }),
  Q("op_side_work", "operations", "Side work",
    "Do servers and line staff have a written side-work list, and does it actually get done?",
    { business_term: "Side-work consistency" }),
  Q("op_cleaning_logs", "operations", "Cleaning logs",
    "Are cleaning logs kept anywhere, even informally?",
    { business_term: "Cleaning log practice" }),
  Q("op_health_readiness", "operations", "Health inspection readiness",
    "When was your last health inspection, and what do you do day-to-day to stay ready between them?",
    { business_term: "Health inspection operational readiness",
      admin_only_notes: "Operational readiness only — never frame as health-department compliance certification.",
      source_of_truth_guidance: "Most recent health inspection report (operational visibility only)" }),
  Q("op_staffing_coverage", "operations", "Staffing coverage",
    "On a normal week, do you have enough staff to cover every shift comfortably?",
    { business_term: "Staffing coverage" }),
  Q("op_training", "operations", "New-hire training",
    "Walk me through what a new hire's first two weeks actually look like.",
    { business_term: "New-hire training program" }),
  Q("op_shift_handoff", "operations", "Shift handoff",
    "How does the closing manager hand off to the opening manager — verbally, written log, app?",
    { business_term: "Shift handoff method" }),
  Q("op_manager_log", "operations", "Manager shift notes",
    "Is there a manager logbook or app where issues from each shift are written down?",
    { business_term: "Manager shift log" }),
  Q("op_delivery_workflow", "operations", "Delivery order workflow",
    "How do delivery orders get into the kitchen, and who's accountable for them?",
    { business_term: "Delivery order workflow" }),
  Q("op_pos_menu_setup", "operations", "POS menu setup",
    "How often do you check that menu items, prices, and modifiers in the POS still match the actual menu?",
    { business_term: "POS menu setup accuracy" }),
  Q("op_scheduling", "operations", "Scheduling & no-shows",
    "Walk me through how shifts get built, and what happens when someone no-shows.",
    { business_term: "Scheduling & no-show response" }),
  Q("op_labor_pct", "operations", "Labor as % of sales",
    "Do you know what your labor cost as a percent of sales is week to week?",
    { business_term: "Labor cost % of sales",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_food_cost", "operations", "Food cost %",
    "What's your food cost percentage, and how often is it actually calculated?",
    { business_term: "Food cost / COGS %",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),

  // ── Financial Visibility ───────────────────────────────────────────────
  Q("fv_qb", "financial", "Books status",
    "Are your books current in QuickBooks, Xero, or FreshBooks, and who keeps them up?",
    { business_term: "Bookkeeping system & currency",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks file" }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's your average monthly revenue right now?",
    { business_term: "Average monthly revenue",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true },
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks P&L" }),
  Q("fv_prime_cost", "financial", "Prime cost",
    "Do you track prime cost — food plus labor — every week?",
    { business_term: "Prime cost (food + labor)",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Prime Cost Visibility Gap" }),
  Q("fv_food_cost_target", "financial", "Food cost target",
    "Do you have a target food cost percentage, and how often do you actually hit it?",
    { business_term: "Food cost target adherence",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_beverage_cost", "financial", "Beverage cost",
    "If you sell alcohol or specialty beverages, do you track beverage cost separately?",
    { business_term: "Beverage cost %",
      answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("fv_labor_weekly", "financial", "Labor cost — weekly",
    "Do you look at labor as a percent of sales every week, or only at month-end?",
    { business_term: "Weekly labor review cadence" }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know what your gross margin is after food, beverage, and direct labor?",
    { business_term: "Gross margin",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_menu_profitability", "financial", "Menu profitability",
    "Do you know which menu items make you the most money, and which lose money?",
    { business_term: "Menu / category profitability visibility",
      repair_map_signal: "Menu Profitability Gap" }),
  Q("fv_daily_sales_review", "financial", "Daily sales review",
    "Do you look at sales every day, or only when something feels off?",
    { business_term: "Daily sales review cadence" }),
  Q("fv_cash_handling", "financial", "Cash handling",
    "Walk me through how cash is counted, deposited, and reconciled.",
    { business_term: "Cash handling controls" }),
  Q("fv_tip_payroll", "financial", "Tip & payroll handling",
    "How are tips collected and paid out, and who runs payroll?",
    { business_term: "Tip & payroll process" }),
  Q("fv_delivery_fees", "financial", "Delivery platform fees",
    "Do you know what you actually net after DoorDash, Uber Eats, and Grubhub fees?",
    { business_term: "Delivery platform net margin",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_waste_cost", "financial", "Waste cost",
    "Is the dollar value of waste tracked anywhere, even roughly?",
    { business_term: "Waste cost tracking",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_comp_void_tracking", "financial", "Comp / void / discount tracking",
    "Are comps, voids, and discounts shown on a report each week?",
    { business_term: "Comp / void / discount reporting",
      source_of_truth_guidance: "POS comp/void/discount report" }),
  Q("fv_vendor_bills", "financial", "Vendor bills",
    "How are vendor bills entered and paid — and is anyone behind on payments?",
    { business_term: "Vendor bill timeliness" }),
  Q("fv_inventory_value", "financial", "Inventory valuation",
    "Do you know the dollar value of inventory sitting in the building right now?",
    { business_term: "Inventory valuation",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_break_even", "financial", "Break-even awareness",
    "Do you know what you need to do in sales each day or week just to break even?",
    { business_term: "Break-even awareness" }),
  Q("fv_pos_recon", "financial", "POS ↔ accounting reconciliation",
    "Are POS sales reconciled to what shows up in accounting each week?",
    { business_term: "POS-to-accounting reconciliation" }),
  Q("fv_cash_deposits", "financial", "Cash deposits",
    "How often do you make cash deposits, and how do you confirm what hit the bank?",
    { business_term: "Cash deposit cadence" }),
  Q("fv_catering_ar", "financial", "Catering deposits & AR",
    "Do catering jobs require deposits, and how is open AR tracked?",
    { business_term: "Catering deposits / AR" }),
  Q("fv_weekly_review", "financial", "Weekly financial review",
    "Do you sit down once a week to look at the numbers, or is it more month-end?",
    { business_term: "Weekly financial review cadence" }),

  // ── Owner Independence ─────────────────────────────────────────────────
  Q("oi_owner_role", "owner_independence", "Owner shifts",
    "How many shifts a week are you personally on the floor or in the kitchen?",
    { business_term: "Owner shift coverage",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_open_close", "owner_independence", "Owner opens / closes",
    "Do you usually open or close the restaurant yourself?",
    { business_term: "Owner open/close dependency" }),
  Q("oi_owner_ordering", "owner_independence", "Vendor ordering",
    "Who actually places vendor orders each week — you or someone else?",
    { business_term: "Vendor-ordering owner dependency" }),
  Q("oi_owner_cash", "owner_independence", "Cash handling",
    "Are you the only one who handles end-of-day cash and deposits?",
    { business_term: "Cash-handling owner dependency" }),
  Q("oi_owner_hiring", "owner_independence", "Hiring & training",
    "Do you run hiring and training yourself, or does a manager own that?",
    { business_term: "Hiring/training ownership" }),
  Q("oi_gm_km", "owner_independence", "GM & KM coverage",
    "Do you have a GM and a kitchen manager who can actually run a shift without you?",
    { business_term: "Manager bench" }),
  Q("oi_manager_authority", "owner_independence", "Manager authority",
    "What can your managers decide on their own without checking with you?",
    { business_term: "Manager decision rights" }),
  Q("oi_shift_lead_readiness", "owner_independence", "Shift lead readiness",
    "Are there shift leads who can step up if a manager calls out?",
    { business_term: "Shift lead bench" }),
  Q("oi_escalation_rules", "owner_independence", "Escalation rules",
    "When something goes wrong on a shift, who calls who?",
    { business_term: "Escalation rules" }),
  Q("oi_documented_standards", "owner_independence", "Documented standards",
    "What parts of how the restaurant runs are written down, vs. in your head?",
    { business_term: "Documented operating standards" }),
  Q("oi_comp_void_authority", "owner_independence", "Comp / void authority",
    "Who can give a comp, void, or discount on the line — anyone, only managers, only you?",
    { business_term: "Comp / void decision rights" }),
  Q("oi_angry_customer", "owner_independence", "Angry customers",
    "When a guest is upset, who's allowed to handle it without calling you?",
    { business_term: "Customer recovery decision rights" }),
  Q("oi_cost_owner", "owner_independence", "Labor / food cost ownership",
    "Who watches labor and food cost during the week — you, a GM, or no one specifically?",
    { business_term: "Cost ownership" }),
  Q("oi_menu_pos_owner", "owner_independence", "Menu / POS ownership",
    "Who updates the menu and the POS when something changes?",
    { business_term: "Menu/POS update ownership" }),
  Q("oi_inventory_owner", "owner_independence", "Inventory ownership",
    "Who owns the inventory count — including making sure it actually happens?",
    { business_term: "Inventory ownership" }),
  Q("oi_owner_absent", "owner_independence", "Owner-absent test",
    "If you took two weeks off starting Monday, what would break first?",
    { business_term: "Owner-absent test",
      repair_map_signal: "Owner Bottleneck Risk" }),

  // ── Conditional Deep Dives ─────────────────────────────────────────────
  CDD("cdd_review_response_speed", "demand", "Review response",
    "dg_review_response", "Reviews aren't responded to within 48 hours.",
    "How long, on average, does a Google or Yelp review sit before someone replies?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Review response cadence gap." }),
  CDD("cdd_review_decline_cause", "demand", "Reviews",
    "dg_reviews", "Reviews are trending down or owner is unsure why.",
    "When a 1- or 2-star review comes in, what's usually the complaint — food, service, wait, or accuracy?",
    { admin_interpretation: "Maps the dominant guest-experience leak class." }),
  CDD("cdd_loyalty_program_use", "demand", "Loyalty",
    "dg_loyalty", "Loyalty program exists but adoption is unclear.",
    "Of guests who could enroll in your rewards program, what share actually do?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  CDD("cdd_email_sms_cadence", "demand", "Email / SMS cadence",
    "dg_email_sms", "List exists but no regular send cadence.",
    "When was the last time you actually sent the list a message, and how often do you usually send?",
    { repair_map_trigger_seed: "Owned-audience send cadence gap." }),
  CDD("cdd_promotions_attribution", "demand", "Promotions attribution",
    "dg_promotions", "Promotions run but lift isn't measured.",
    "When you run a promotion, can you tell whether it actually drove extra traffic?",
    { admin_interpretation: "Unattributed promos = silent margin leakage." }),
  CDD("cdd_neighborhood_traffic_impact", "demand", "Neighborhood traffic",
    "bp_neighborhood", "Owner mentions construction, parking, or competition changes.",
    "Has anything changed in the neighborhood recently — construction, a new competitor, parking — that's affecting traffic?",
    { admin_interpretation: "External demand pressure vs. internal demand drop are different repairs." }),
  CDD("cdd_seasonal_swing_plan", "demand", "Seasonal planning",
    "dg_seasonality", "Big seasonal swing with no written plan.",
    "What's your plan for filling the slow season — promotions, catering, hours, or just ride it out?",
    { repair_map_trigger_seed: "Slow-season demand plan gap." }),

  CDD("cdd_table_turn_blockers", "sales", "Table turns",
    "rc_table_turns", "Table turns feel low for the format.",
    "When tables turn slowly, what's usually the blocker — kitchen, server, payment, or guests lingering?",
    { admin_interpretation: "Identifies whether the constraint is service or kitchen." }),
  CDD("cdd_no_show_capture", "sales", "No-shows",
    "rc_reservations", "Reservations exist but no-shows aren't tracked.",
    "Do you require deposits or credit-card holds for reservations, and do you charge no-show fees?",
    { repair_map_trigger_seed: "Reservation no-show recovery gap." }),
  CDD("cdd_phone_order_capture", "sales", "Phone orders",
    "rc_phone_orders", "Phone orders are frequent but not centralized.",
    "Who answers phone orders during a rush, and how often do calls go unanswered?",
    { repair_map_trigger_seed: "Phone-order capture gap." }),
  CDD("cdd_online_ordering_friction", "sales", "Online ordering",
    "rc_online_ordering", "Direct online order share is low.",
    "Is there friction in your online ordering — menu, checkout, mobile experience, or just no one promoting it?",
    { admin_interpretation: "Direct vs. third-party share is a margin signal." }),
  CDD("cdd_upsell_consistency", "sales", "Upsell consistency",
    "rc_upsell", "Upsell happens inconsistently or by personality.",
    "Do certain servers or order takers consistently outperform on attach, and do you know why?",
    { admin_interpretation: "Personality-driven upsell = no system, not a sales engine." }),
  CDD("cdd_order_accuracy_root_cause", "sales", "Order accuracy root cause",
    "rc_order_accuracy", "Remake/refund rate is non-trivial.",
    "When orders go wrong, where does it usually break — order entry, kitchen, expo, or delivery?",
    { repair_map_trigger_seed: "Order accuracy root-cause gap." }),
  CDD("cdd_catering_profitability", "sales", "Catering profitability",
    "rc_catering_close", "Catering is taken without confirmed margin.",
    "When you book a catering job, do you know its food and labor cost before you quote it?",
    { repair_map_trigger_seed: "Catering profitability visibility gap." }),

  CDD("cdd_kitchen_bottleneck_specific", "operations", "Kitchen bottleneck",
    "op_kitchen_bottlenecks", "Kitchen backs up regularly under volume.",
    "Which station backs up first — grill, fry, sauté, expo — and what's the longest ticket time you've seen recently?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  CDD("cdd_recipe_spec_drift", "operations", "Recipe drift",
    "op_recipe_specs", "Recipes are 'mostly' followed.",
    "Do different cooks make the same dish slightly differently, and does anyone check?",
    { repair_map_trigger_seed: "Recipe / spec drift." }),
  CDD("cdd_portion_drift", "operations", "Portion drift",
    "op_portion_control", "Portion control isn't measured.",
    "Are portions weighed or scooped to spec, or done by eye?",
    { admin_interpretation: "By-eye portioning is a top food-cost leak." }),
  CDD("cdd_receiving_check", "operations", "Receiving discipline",
    "op_receiving", "Deliveries aren't checked against the invoice.",
    "Has anyone caught a short delivery or a wrong substitution in the last month?",
    { admin_interpretation: "If 'no' = vendor leakage that may not be visible in cost reports." }),
  CDD("cdd_vendor_substitution", "operations", "Vendor substitution",
    "op_ordering_rhythm", "Vendor swaps in different brands/cuts.",
    "How often does the vendor send a substitute item, and who decides whether to accept it?",
    { repair_map_trigger_seed: "Vendor substitution control gap." }),
  CDD("cdd_pos_menu_drift", "operations", "POS menu drift",
    "op_pos_menu_setup", "Menu has changed but POS not fully updated.",
    "When you last changed prices or items, did the POS get fully updated — including modifiers and online ordering?",
    { repair_map_trigger_seed: "POS menu drift." }),
  CDD("cdd_training_consistency", "operations", "Training consistency",
    "op_training", "Training is on-the-fly.",
    "Do you have a written training plan with checkpoints, or is it 'learn by working a shift'?",
    { repair_map_trigger_seed: "Training program gap." }),
  CDD("cdd_cleaning_log_use", "operations", "Cleaning logs in practice",
    "op_cleaning_logs", "Cleaning logs exist but aren't signed off.",
    "When cleaning logs are kept, are they actually filled in each shift, or mostly empty?",
    { admin_interpretation: "Empty logs = false confidence on health-readiness." }),
  CDD("cdd_shift_consistency", "operations", "Shift consistency",
    "op_open_close_checklists", "No written open/close checklist.",
    "If two different managers open the restaurant, would the prep state look the same at noon?",
    { repair_map_trigger_seed: "Shift consistency gap." }),
  CDD("cdd_manager_accountability", "operations", "Manager accountability",
    "op_manager_log", "No manager logbook in use.",
    "How do issues from last night's shift actually reach the morning team if it isn't written down?",
    { repair_map_trigger_seed: "Manager accountability gap." }),
  CDD("cdd_delivery_workflow_friction", "operations", "Delivery workflow friction",
    "op_delivery_workflow", "Multiple delivery tablets exist on the line.",
    "How many delivery tablets are on the line, and who's actually watching them during a rush?",
    { admin_interpretation: "Tablet sprawl drives missed delivery tickets." }),
  CDD("cdd_line_execution", "operations", "Line execution",
    "op_ticket_times", "Ticket times aren't tracked.",
    "If we asked tonight's expo what tonight's average ticket time was, could they tell us?",
    { repair_map_trigger_seed: "Line execution visibility gap." }),
  CDD("cdd_inventory_control", "operations", "Inventory control",
    "op_inventory_counts", "Counts are skipped or inconsistent.",
    "When was the last full inventory count, and does the count match what's in the POS?",
    { repair_map_trigger_seed: "Inventory control gap." }),
  CDD("cdd_waste_inventory_leakage", "operations", "Waste & inventory leakage",
    "op_waste", "Waste isn't tracked or only tracked when bad.",
    "When you do see waste, what's the most common cause — over-prep, spoilage, comps, or theft?",
    { admin_interpretation: "Causes drive different repairs (par levels vs. controls)." }),
  CDD("cdd_ordering_dependency", "operations", "Ordering dependency",
    "oi_owner_ordering", "Owner places most vendor orders.",
    "If you couldn't place orders this week, who could pick it up and not run the restaurant out of anything?",
    { repair_map_trigger_seed: "Vendor-ordering owner dependency." }),

  CDD("cdd_prime_cost_visibility", "financial", "Prime cost visibility",
    "fv_prime_cost", "Prime cost is not tracked weekly.",
    "If we asked for last week's prime cost percentage right now, could you give us a number you trust?",
    { admin_interpretation: "Self-rated visibility — drives whether margin work is needed before pricing changes.",
      repair_map_trigger_seed: "Prime cost visibility gap." }),
  CDD("cdd_food_cost_target_gap", "financial", "Food cost vs. target",
    "fv_food_cost_target", "Actual food cost is over target or unknown.",
    "When food cost runs over target, where do you typically find the leak — over-portioning, waste, theft, or pricing?",
    { admin_interpretation: "Owner intuition is itself a finding when no count data exists." }),
  CDD("cdd_labor_control", "financial", "Labor control",
    "fv_labor_weekly", "Labor reviewed monthly or not at all.",
    "When labor runs hot, do you adjust the schedule mid-week, or only see it at month-end?",
    { repair_map_trigger_seed: "Labor control cadence gap." }),
  CDD("cdd_menu_margin_deep_dive", "financial", "Menu margin deep dive",
    "fv_menu_profitability", "Menu profitability isn't visible.",
    "If we sorted your menu by profit per item, would you bet you know the top three and bottom three?",
    { admin_interpretation: "Confidence vs. data gap is the finding." }),
  CDD("cdd_delivery_net_margin", "financial", "Delivery platform net",
    "fv_delivery_fees", "Owner can't quantify delivery net.",
    "After all platform fees, what do you net on a $50 delivery order?",
    { answer_type: "currency", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Delivery platform margin risk." }),
  CDD("cdd_cash_deposit_lag", "financial", "Cash deposit lag",
    "fv_cash_deposits", "Cash sits on site multiple days.",
    "How many days does cash typically sit before it hits the bank?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      admin_interpretation: "Deposit lag is a control risk, not just a finance issue." }),
  CDD("cdd_break_even_per_day", "financial", "Break-even per day",
    "fv_break_even", "Break-even isn't known per day.",
    "Do your managers know what each shift needs to do in sales just to break even?",
    { repair_map_trigger_seed: "Shift-level break-even visibility gap." }),
  CDD("cdd_weekly_review_cadence", "financial", "Weekly review cadence",
    "fv_weekly_review", "No weekly financial review happens.",
    "If we put a weekly numbers review on the calendar, who would actually attend and own it?",
    { repair_map_trigger_seed: "Weekly review cadence gap." }),
  CDD("cdd_revenue_leakage_comp_void", "financial", "Comp / void leakage",
    "rc_comp_void_controls", "Comps/voids aren't reviewed weekly.",
    "Of last week's comps, voids, and discounts, can you say which manager or server they came from?",
    { source_of_truth_guidance: "POS comp/void/discount report by employee",
      repair_map_trigger_seed: "Comp / void / discount accountability gap." }),

  CDD("cdd_shift_dependency", "owner_independence", "Shift dependency",
    "oi_owner_role", "Owner covers shifts regularly.",
    "If you stopped covering shifts tomorrow, which shift would actually be at risk first?",
    { repair_map_trigger_seed: "Shift dependency risk." }),
  CDD("cdd_owner_open_close_blast", "owner_independence", "Open/close blast radius",
    "oi_open_close", "Owner opens or closes most days.",
    "If you stopped opening or closing for a month, what's the first thing that would slip?",
    { admin_interpretation: "Identifies the first systems-failure point under owner removal." }),
  CDD("cdd_owner_cash_redundancy", "owner_independence", "Cash redundancy",
    "oi_owner_cash", "Owner is the only person who handles cash.",
    "If you couldn't be there for a week, who could legally count, deposit, and reconcile cash?",
    { repair_map_trigger_seed: "Cash-handling redundancy gap." }),
  CDD("cdd_manager_decision_rights", "owner_independence", "Manager decision rights",
    "oi_manager_authority", "Managers escalate small decisions.",
    "What kinds of decisions are managers afraid to make without you, even when they probably should?",
    { admin_interpretation: "Listen for cultural avoidance vs. actual policy gap." }),
  CDD("cdd_owner_absent_blast", "owner_independence", "Owner-absent blast radius",
    "oi_owner_absent", "Owner says something would break if absent.",
    "Walk me through what would actually fall over in week one of you being gone, day by day.",
    { repair_map_trigger_seed: "Owner blast-radius mapping." }),

  // ── Evidence / Source-of-Truth Prompts ─────────────────────────────────
  Q("ev_pos_export", "evidence", "POS export",
    "Could you export the last 90 days of POS sales-by-day and labor reports?",
    { evidence_prompt: "POS sales mix + labor by day, last 90 days" }),
  Q("ev_menu_sales_mix", "evidence", "Menu sales mix",
    "Could you pull a menu item sales mix report for the last 90 days?",
    { evidence_prompt: "Menu item sales mix, last 90 days",
      source_of_truth_guidance: "POS menu sales mix report" }),
  Q("ev_labor_report", "evidence", "Labor report",
    "Could you export the labor report by day for the last 30 days?",
    { evidence_prompt: "Labor report by day, last 30 days" }),
  Q("ev_payroll_report", "evidence", "Payroll summary",
    "Could you share the most recent payroll summary?",
    { evidence_prompt: "Most recent payroll summary",
      source_of_truth_guidance: "Paycom / ADP / Gusto" }),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent profit-and-loss statement?",
    { evidence_prompt: "Trailing 12-month P&L from QuickBooks/Xero/FreshBooks",
      evidence_required: true }),
  Q("ev_balance_sheet", "evidence", "Balance sheet",
    "Could you share a current balance sheet?",
    { evidence_prompt: "Most recent balance sheet" }),
  Q("ev_vendor_invoices", "evidence", "Vendor invoices",
    "Could you share the last month of food and beverage vendor invoices?",
    { evidence_prompt: "Vendor invoices, last 30 days" }),
  Q("ev_inventory_count_sheets", "evidence", "Inventory count sheets",
    "Could you share your most recent inventory count sheet?",
    { evidence_prompt: "Most recent inventory count sheet" }),
  Q("ev_waste_log", "evidence", "Waste log",
    "Could you share whatever waste log you keep, even if informal?",
    { evidence_prompt: "Waste log, last 30 days" }),
  Q("ev_prep_sheets", "evidence", "Prep sheets",
    "Could you share a recent prep sheet for a service?",
    { evidence_prompt: "Recent prep sheet" }),
  Q("ev_recipe_specs", "evidence", "Recipe / spec sheets",
    "Could you share a recipe and plate spec for one of your top-selling items?",
    { evidence_prompt: "Recipe + plate spec for a top-3 item" }),
  Q("ev_open_close_checklists", "evidence", "Open / close checklists",
    "Could you share your opening and closing checklists?",
    { evidence_prompt: "Open & close checklists" }),
  Q("ev_manager_logbook", "evidence", "Manager logbook",
    "Could you share recent pages from the manager logbook, or a screenshot of the app?",
    { evidence_prompt: "Manager logbook, last 14 days" }),
  Q("ev_review_dashboard", "evidence", "Review dashboard",
    "Could you share a screenshot of your Google and Yelp review dashboards?",
    { evidence_prompt: "Google + Yelp review dashboard screenshots" }),
  Q("ev_reservation_data", "evidence", "Reservation / no-show data",
    "If you take reservations, could you export reservation and no-show data for the last 30 days?",
    { evidence_prompt: "Reservation + no-show export, last 30 days" }),
  Q("ev_delivery_reports", "evidence", "Delivery platform reports",
    "Could you share the last 30 days of reports from DoorDash, Uber Eats, or Grubhub?",
    { evidence_prompt: "Delivery platform reports, last 30 days" }),
  Q("ev_catering_invoices", "evidence", "Catering invoices",
    "Could you share recent catering or event invoices, including deposits?",
    { evidence_prompt: "Catering / event invoices, last 90 days" }),
  Q("ev_cash_deposits", "evidence", "Cash deposit records",
    "Could you share the last 30 days of cash deposit records?",
    { evidence_prompt: "Cash deposit records, last 30 days" }),
  Q("ev_comp_void_report", "evidence", "Comp / void / discount report",
    "Could you export the last 30 days of comps, voids, and discounts by employee?",
    { evidence_prompt: "Comp/void/discount report by employee, last 30 days",
      source_of_truth_guidance: "POS comp/void/discount report" }),
  Q("ev_health_records", "evidence", "Health inspection records",
    "Could you share your most recent health inspection report?",
    { evidence_prompt: "Most recent health inspection report",
      admin_only_notes: "Operational visibility only — not a compliance certification or food-safety attestation." }),
  Q("ev_org_chart", "evidence", "Org chart",
    "Could you share an org chart with names, roles, and decision authority?",
    { evidence_prompt: "Org chart with titles and decision rights" }),
  Q("ev_owner_calendar", "evidence", "Owner calendar",
    "Could you share two weeks of your calendar so we can see where your time really goes?",
    { evidence_prompt: "Two-week owner calendar export" }),
];

export const RESTAURANTS_FOOD_SERVICE_BANK: IndustryQuestionBank = {
  industry: I,
  label: "Restaurants / Food Service",
  questions: QUESTIONS,
};
