/**
 * P93E-E2G-P3 — Retail / Brick-and-Mortar full-depth diagnostic interview bank.
 *
 * Plain-English scripted interview, deep diagnostic structure. Each prompt is
 * classified as `core`, `conditional_deep_dive`, `evidence_source_of_truth`,
 * or `admin_interpretation_support` and may carry report-finding seeds and
 * Repair-Map trigger seeds.
 *
 * Inventory, shrink, and cash-handling questions are framed as operational
 * visibility and documentation readiness only — never as compliance, audit,
 * accounting, or tax certification.
 */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";

const I = "retail_brick_mortar" as const;

const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `retail.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

const CDD = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  parent: string,
  triggerWhen: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "conditional_deep_dive",
    parent_key: `retail.${parent}`,
    trigger_when: triggerWhen,
    ...extra,
  });

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile ───────────────────────────────────────────────────
  Q("bp_format", "business_profile", "Store format",
    "What does the store sell, and how would you describe the format in one sentence?",
    { business_term: "Store format & category" }),
  Q("bp_locations", "business_profile", "Locations",
    "How many locations do you run, and which one drives the most revenue?",
    { business_term: "Locations & revenue concentration",
      answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_footprint", "business_profile", "Footprint",
    "Roughly how big is the selling floor, and how much is stockroom or back-of-house?",
    { business_term: "Selling floor vs. stockroom split" }),
  Q("bp_sku_count", "business_profile", "SKU count",
    "Roughly how many active SKUs do you carry on the floor right now?",
    { business_term: "Active SKU count",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("bp_categories", "business_profile", "Top categories",
    "What are your top three product categories by sales right now?",
    { business_term: "Top sales categories" }),
  Q("bp_staffing", "business_profile", "Staffing",
    "How many people are on the floor on a typical day, and who is running the shift?",
    { business_term: "Floor staffing structure" }),
  Q("bp_hours", "business_profile", "Hours & shifts",
    "What are your hours, and how do shifts split across opens, mids, and closes?",
    { business_term: "Operating hours & shift pattern" }),
  Q("bp_neighborhood", "business_profile", "Neighborhood",
    "What is the neighborhood like — foot traffic, parking, anchor stores, nearby competition?",
    { business_term: "Neighborhood traffic context" }),
  Q("bp_seasonality", "business_profile", "Seasonality",
    "How big is the swing between your busiest month and your slowest month?",
    { business_term: "Seasonal demand swing",
      answer_type: "seasonal_range", capture: { notes: true, seasonal: true } }),

  // ── Demand Generation ──────────────────────────────────────────────────
  Q("dg_walk_in_traffic", "demand", "Walk-in traffic",
    "Roughly how many shoppers walk through the door in a normal week?",
    { business_term: "Weekly walk-in traffic",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true, seasonal: true },
      source_of_truth_guidance: "Door counter / POS transaction count" }),
  Q("dg_customer_source", "demand", "Customer source",
    "How do most new customers find the store right now?",
    { business_term: "Customer source visibility",
      repair_map_signal: "Demand Source Visibility Gap",
      admin_interpretation: "If the owner can't name the top 1–2 sources with proof, treat as a source-tracking gap." }),
  Q("dg_repeat_share", "demand", "Repeat customers",
    "What share of weekly sales comes from customers you have seen before?",
    { business_term: "Repeat customer share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_referrals", "demand", "Referrals & word of mouth",
    "How much of your business is people telling friends or family about you?",
    { business_term: "Referral / word-of-mouth share",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_reviews", "demand", "Reviews — Google & Yelp",
    "How are reviews looking on Google and Yelp right now, and where are most of them coming from?",
    { business_term: "Review reputation",
      source_of_truth_guidance: "Google Business Profile + Yelp dashboards" }),
  Q("dg_local_partnerships", "demand", "Local partnerships",
    "Do you have any local partnerships — schools, gyms, neighborhood businesses — that send you customers?",
    { business_term: "Local partnership network" }),
  Q("dg_events_popups", "demand", "Events & pop-ups",
    "Do you run events, pop-ups, or in-store activations, and how often?",
    { business_term: "Events & in-store activations" }),
  Q("dg_social", "demand", "Social media",
    "Which social platforms are you actually active on, and who posts?",
    { business_term: "Social media activity" }),
  Q("dg_email_sms", "demand", "Email / SMS list",
    "Do you have an email or text list, and roughly how big is it?",
    { business_term: "Owned audience list size",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_loyalty", "demand", "Loyalty program",
    "Do you have a loyalty or rewards program, and how many people actually use it?",
    { business_term: "Loyalty program adoption" }),
  Q("dg_promotions", "demand", "Promotions & sales events",
    "How often do you run a promotion, sale event, or product drop, and who decides what to run?",
    { business_term: "Promotion cadence" }),
  Q("dg_signage_window", "demand", "Signage & window display",
    "How often do you change the window display or front signage, and why?",
    { business_term: "Signage / window display cadence" }),
  Q("dg_local_seo", "demand", "Website / local SEO",
    "Is the store easy to find on Google Maps and search, and is the website current?",
    { business_term: "Local SEO presence",
      source_of_truth_guidance: "Google Business Profile + Google Search Console" }),

  // ── Revenue Conversion ─────────────────────────────────────────────────
  Q("rc_walk_in_conversion", "sales", "Walk-in conversion",
    "Of the people who walk in, what percent leave with something?",
    { business_term: "Walk-in conversion",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      source_of_truth_guidance: "Door counter vs. POS transaction count" }),
  Q("rc_avg_basket", "sales", "Average basket",
    "What is your average basket size or transaction value right now?",
    { business_term: "Average basket / transaction value",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "POS sales-by-day report" }),
  Q("rc_units_per_transaction", "sales", "Units per transaction",
    "On average, how many items are in a normal sale?",
    { business_term: "Units per transaction",
      answer_type: "numeric", capture: { notes: true, estimated_value: true } }),
  Q("rc_attach_upsell", "sales", "Attach & upsell",
    "How are staff trained to attach add-ons or suggest a second item, and does it actually happen?",
    { business_term: "Attach / upsell consistency" }),
  Q("rc_loyalty_repeat", "sales", "Loyalty repeat purchase",
    "Do loyalty members come back more often or spend more than non-members?",
    { business_term: "Loyalty repeat lift" }),
  Q("rc_merchandising_impact", "sales", "Merchandising impact",
    "When you change product placement or a display, can you tell whether sales actually moved?",
    { business_term: "Merchandising performance visibility" }),
  Q("rc_discounting", "sales", "Discounting",
    "How often do staff or managers give a discount on the floor, and why?",
    { business_term: "Floor discounting practice",
      repair_map_signal: "Discount Leakage Risk" }),
  Q("rc_promotion_performance", "sales", "Promotion performance",
    "When you run a promotion, how do you know whether it brought in extra sales versus just lower margin?",
    { business_term: "Promotion lift vs. margin impact" }),
  Q("rc_customer_objections", "sales", "Customer objections",
    "What are the most common reasons a shopper walks out without buying?",
    { business_term: "Common walk-out reasons" }),
  Q("rc_staff_selling_consistency", "sales", "Staff selling consistency",
    "Does conversion or basket size change a lot depending on which employee is working?",
    { business_term: "Staff selling consistency",
      repair_map_signal: "Staff Selling Consistency Gap" }),
  Q("rc_returns_exchanges", "sales", "Returns & exchanges",
    "Roughly how often does a sale come back as a return or exchange, and how is it processed?",
    { business_term: "Return / exchange rate",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_special_orders", "sales", "Special orders & holds",
    "Do you take special orders, holds, or reserves, and how is that tracked?",
    { business_term: "Special order / hold workflow" }),
  Q("rc_gift_cards", "sales", "Gift cards & store credit",
    "Do you sell gift cards or issue store credit, and how is the liability tracked?",
    { business_term: "Gift card / store credit liability" }),
  Q("rc_service_recovery", "sales", "Customer service recovery",
    "When a customer is unhappy, what is the actual process for making it right?",
    { business_term: "Service recovery process" }),

  // ── Operational Efficiency ─────────────────────────────────────────────
  Q("op_pos", "operations", "POS system",
    "What POS are you using — Square, Lightspeed, Shopify POS, Clover — and what does it actually report on?",
    { business_term: "POS platform & reporting depth",
      source_of_truth_guidance: "POS sales / inventory / category reports" }),
  Q("op_inventory_count_cadence", "operations", "Inventory count cadence",
    "How often is inventory actually counted, and who does the counts?",
    { business_term: "Inventory count cadence",
      repair_map_signal: "Inventory Variance Risk" }),
  Q("op_cycle_counts", "operations", "Cycle counts",
    "Do you run cycle counts on top-selling categories between full counts?",
    { business_term: "Cycle count practice" }),
  Q("op_inventory_accuracy", "operations", "Inventory accuracy",
    "When you count, how close is the count to what the POS says you should have?",
    { business_term: "Inventory accuracy",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_shrink", "operations", "Shrink",
    "Do you have a sense of shrink from theft, damage, or miscount, and is it tracked?",
    { business_term: "Shrink visibility",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Shrink / Stock Accuracy Gap" }),
  Q("op_damages", "operations", "Damages",
    "Where do damaged or defective items go, and is the cost recorded?",
    { business_term: "Damage handling & cost capture" }),
  Q("op_dead_stock", "operations", "Dead stock",
    "How do you decide an item is dead stock, and what do you do with it?",
    { business_term: "Dead stock review",
      repair_map_signal: "Dead Stock / Aging Inventory Risk" }),
  Q("op_stockouts", "operations", "Stockouts",
    "How often do best sellers actually run out, and how do you find out?",
    { business_term: "Stockout frequency",
      repair_map_signal: "Stockout / Reorder Process Gap" }),
  Q("op_reorder_process", "operations", "Reorder process",
    "Walk me through how reorders happen — who decides what to bring in and when?",
    { business_term: "Reorder decision process" }),
  Q("op_vendor_lead_times", "operations", "Vendor lead times",
    "For your top vendors, how long from order to product on the shelf?",
    { business_term: "Vendor lead times",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_receiving", "operations", "Receiving",
    "When a shipment arrives, who receives it, and is it actually checked against the invoice?",
    { business_term: "Receiving discipline" }),
  Q("op_stockroom", "operations", "Stockroom organization",
    "Walk me through the stockroom — can a new employee find a backup item without help?",
    { business_term: "Stockroom organization" }),
  Q("op_merchandising_workflow", "operations", "Merchandising workflow",
    "Who decides product placement and window displays, and how often does it change?",
    { business_term: "Merchandising workflow",
      repair_map_signal: "Merchandising Control Gap" }),
  Q("op_pricing_setup", "operations", "Price tag & SKU accuracy",
    "How do you make sure shelf tags, POS prices, and SKU data actually agree?",
    { business_term: "Price tag / SKU accuracy",
      repair_map_signal: "POS / SKU Setup Control Gap" }),
  Q("op_pos_setup", "operations", "POS setup discipline",
    "When a new product comes in, who sets it up in the POS — categories, taxes, modifiers, barcodes?",
    { business_term: "POS setup ownership" }),
  Q("op_returns_processing", "operations", "Returns processing",
    "Walk me through how a return is actually processed and put back into inventory.",
    { business_term: "Return processing workflow" }),
  Q("op_open_close_checklists", "operations", "Open / close checklists",
    "Are there written opening and closing checklists, and does someone sign off?",
    { business_term: "Open/close checklists" }),
  Q("op_register_procedure", "operations", "Register procedure",
    "Walk me through how a register is opened, used, and counted out at end of shift.",
    { business_term: "Register procedure" }),
  Q("op_cash_drawer", "operations", "Cash drawer process",
    "How are cash drawer variances handled when the count does not match?",
    { business_term: "Cash drawer variance handling",
      repair_map_signal: "Cash Handling Visibility Gap" }),
  Q("op_store_recovery", "operations", "Store recovery & cleaning",
    "Who is responsible for store recovery, restock, and cleaning each day?",
    { business_term: "Store recovery routine" }),
  Q("op_staff_coverage", "operations", "Staff coverage",
    "On a normal week, do you have enough staff to cover every shift comfortably?",
    { business_term: "Staff coverage" }),
  Q("op_task_lists", "operations", "Task lists",
    "Do staff have written task lists for each shift, or do they figure it out?",
    { business_term: "Shift task lists" }),
  Q("op_customer_handoff", "operations", "Customer handoff",
    "When a customer needs help that one staff member can't answer, what is the handoff process?",
    { business_term: "Customer handoff process" }),
  Q("op_display_standards", "operations", "Product display standards",
    "Are there written standards for how product is displayed, faced, and priced?",
    { business_term: "Display & pricing standards" }),

  // ── Financial Visibility ───────────────────────────────────────────────
  Q("fv_qb", "financial", "Books status",
    "Are your books current in QuickBooks, Xero, or FreshBooks, and who keeps them up?",
    { business_term: "Bookkeeping system & currency",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks file" }),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What is your average monthly revenue right now?",
    { business_term: "Average monthly revenue",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true },
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks P&L" }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know your overall gross margin after cost of goods?",
    { business_term: "Gross margin",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_category_margin", "financial", "Category margin",
    "Do you know gross margin broken out by product category?",
    { business_term: "Category-level margin visibility",
      repair_map_signal: "Category Margin Blind Spot" }),
  Q("fv_sku_profitability", "financial", "SKU profitability",
    "Can you see profit by SKU or product, or only at category or store level?",
    { business_term: "SKU-level profitability visibility" }),
  Q("fv_inventory_turnover", "financial", "Inventory turnover",
    "Do you know how many times your inventory turns in a year?",
    { business_term: "Inventory turnover",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Inventory Cash Trap" }),
  Q("fv_inventory_value", "financial", "Inventory dollars",
    "Do you know the dollar value of inventory sitting in the building right now?",
    { business_term: "Inventory cash tied up",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_dead_stock_cost", "financial", "Dead stock cost",
    "Do you have a sense of how much money is currently sitting in product that isn't selling?",
    { business_term: "Dead stock cost",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_shrink_cost", "financial", "Shrink cost",
    "Is the dollar value of shrink tracked anywhere, even roughly?",
    { business_term: "Shrink dollar impact",
      answer_type: "currency", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_discount_impact", "financial", "Discount impact",
    "Are discounts and promotions reviewed for margin impact, or only for sales lift?",
    { business_term: "Discount margin review" }),
  Q("fv_return_cost", "financial", "Return cost",
    "Is the cost of returns and exchanges (restocking, damages, refunds) tracked?",
    { business_term: "Return cost tracking" }),
  Q("fv_vendor_terms", "financial", "Vendor terms",
    "What are your typical vendor payment terms — net 30, prepay, COD, consignment?",
    { business_term: "Vendor payment terms" }),
  Q("fv_sales_by_category", "financial", "Sales by category",
    "Do you look at sales by category each week, or only at total sales?",
    { business_term: "Sales-by-category cadence" }),
  Q("fv_pos_recon", "financial", "POS ↔ accounting reconciliation",
    "Are POS sales reconciled to what shows up in accounting each week?",
    { business_term: "POS-to-accounting reconciliation" }),
  Q("fv_cash_deposits", "financial", "Cash deposits",
    "How often do you make cash deposits, and how do you confirm what hit the bank?",
    { business_term: "Cash deposit cadence" }),
  Q("fv_payroll_labor", "financial", "Payroll / labor",
    "How is payroll processed — Paycom, ADP, Gusto, or in-house — and what does labor cost as a percent of sales?",
    { business_term: "Payroll system & labor %",
      answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_rent_occupancy", "financial", "Rent / occupancy pressure",
    "What does rent and occupancy run as a percent of sales, and is it manageable in slow months?",
    { business_term: "Rent / occupancy as % of sales" }),
  Q("fv_merchant_fees", "financial", "Merchant processing fees",
    "What does card processing cost you — Stripe, Square, PayPal, or your processor — and is it reviewed?",
    { business_term: "Merchant processing fee review" }),
  Q("fv_seasonal_cash", "financial", "Seasonal cash planning",
    "Do you plan cash differently going into a slow season — inventory buying, hours, marketing?",
    { business_term: "Seasonal cash planning" }),
  Q("fv_break_even", "financial", "Break-even awareness",
    "Do you know what you need to do in sales each day or week just to break even?",
    { business_term: "Break-even awareness" }),
  Q("fv_open_to_buy", "financial", "Open-to-buy discipline",
    "Do you set a buying budget each month or season, or do you reorder as items move?",
    { business_term: "Open-to-buy discipline",
      repair_map_signal: "Vendor Terms / Buying Discipline Gap" }),
  Q("fv_aging_inventory", "financial", "Aging inventory",
    "Do you have a way to see how long product has been sitting on the floor?",
    { business_term: "Inventory aging visibility" }),

  // ── Owner Independence ─────────────────────────────────────────────────
  Q("oi_owner_floor", "owner_independence", "Owner on floor",
    "How many days a week are you personally on the floor or working a register?",
    { business_term: "Owner floor-time",
      answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "Store Coverage Risk" }),
  Q("oi_buying", "owner_independence", "Owner buying dependency",
    "Do you make most buying and reorder decisions yourself, or does someone else?",
    { business_term: "Buying decision ownership",
      repair_map_signal: "Owner Buying Bottleneck" }),
  Q("oi_discount_approval", "owner_independence", "Discount approval",
    "Who is allowed to approve a discount on the floor without checking with you?",
    { business_term: "Discount approval rights" }),
  Q("oi_escalations", "owner_independence", "Customer escalations",
    "When a customer is upset, who is allowed to handle it without calling you?",
    { business_term: "Escalation decision rights" }),
  Q("oi_cash_handling", "owner_independence", "Cash handling owner",
    "Are you the only person who counts the drawer or makes the deposit at the end of the day?",
    { business_term: "Cash-handling redundancy" }),
  Q("oi_merchandising_decisions", "owner_independence", "Merchandising decisions",
    "Who decides what goes in the window or front of store — you, a manager, or staff?",
    { business_term: "Merchandising decision ownership" }),
  Q("oi_vendor_relationships", "owner_independence", "Vendor relationships",
    "Are vendor relationships mostly through you, or do other people have direct contact?",
    { business_term: "Vendor relationship ownership" }),
  Q("oi_scheduling", "owner_independence", "Scheduling",
    "Who builds the schedule each week, and how is it shared?",
    { business_term: "Scheduling ownership" }),
  Q("oi_manager_authority", "owner_independence", "Manager authority",
    "Is there a store manager who can open, close, and run a normal day without you?",
    { business_term: "Store manager bench" }),
  Q("oi_returns_authority", "owner_independence", "Returns authority",
    "Who can approve a return or exchange that falls outside policy?",
    { business_term: "Return / exchange decision rights" }),
  Q("oi_reorder_authority", "owner_independence", "Reorder authority",
    "Who is allowed to place a reorder with a vendor without checking with you?",
    { business_term: "Reorder decision rights" }),
  Q("oi_documented_standards", "owner_independence", "Documented standards",
    "What parts of how the store runs are written down, vs. in your head?",
    { business_term: "Documented operating standards" }),
  Q("oi_owner_absent", "owner_independence", "Owner-absent test",
    "If you took two weeks off starting Monday, what would break first?",
    { business_term: "Owner-absent test",
      repair_map_signal: "Store Coverage Risk" }),

  // ── Conditional Deep Dives — Demand ────────────────────────────────────
  CDD("cdd_customer_source_proof", "demand", "Customer source proof",
    "dg_customer_source", "Owner names a top source but cannot show how it was measured.",
    "How do you know that is the top source — a survey at checkout, a tracked promo code, or a guess?",
    { admin_interpretation: "Verified source vs. owner intuition is a different repair." }),
  CDD("cdd_traffic_concentration", "demand", "Traffic concentration risk",
    "dg_walk_in_traffic", "One source or one neighborhood event drives most traffic.",
    "If your top traffic source disappeared next week, what share of revenue would be at risk?",
    { repair_map_trigger_seed: "Traffic concentration risk." }),
  CDD("cdd_review_response", "demand", "Review response cadence",
    "dg_reviews", "Reviews aren't responded to within a few days.",
    "How long, on average, does a Google or Yelp review sit before someone replies?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Review response cadence gap." }),
  CDD("cdd_loyalty_adoption", "demand", "Loyalty adoption",
    "dg_loyalty", "Loyalty program exists but adoption is unclear.",
    "Of customers who could enroll in your rewards program, what share actually do?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Loyalty adoption gap." }),
  CDD("cdd_email_sms_cadence", "demand", "Email / SMS cadence",
    "dg_email_sms", "List exists but no regular send cadence.",
    "When was the last time you actually sent the list a message, and how often do you usually send?",
    { repair_map_trigger_seed: "Owned-audience send cadence gap." }),
  CDD("cdd_promo_attribution", "demand", "Promotion attribution",
    "dg_promotions", "Promotions run but lift isn't measured.",
    "When you run a promo, can you tell whether it actually drove extra traffic versus just lower margin?",
    { admin_interpretation: "Unattributed promos = silent margin leakage." }),
  CDD("cdd_seasonal_plan", "demand", "Seasonal plan",
    "bp_seasonality", "Big seasonal swing with no written plan.",
    "What is your plan for the slow season — promotions, hours, staffing, inventory tightening?",
    { repair_map_trigger_seed: "Slow-season demand & cash plan gap." }),

  // ── Conditional Deep Dives — Sales ─────────────────────────────────────
  CDD("cdd_walk_out_reasons", "sales", "Walk-out reasons",
    "rc_customer_objections", "Walk-outs feel frequent or owner can't name reasons.",
    "Of the last ten shoppers who walked out empty-handed, can you name three reasons they didn't buy?",
    { admin_interpretation: "Inability to name reasons = no front-line capture." }),
  CDD("cdd_attach_consistency", "sales", "Attach consistency",
    "rc_attach_upsell", "Attach happens inconsistently or by personality.",
    "Do certain employees consistently outperform on basket size, and do you know why?",
    { admin_interpretation: "Personality-driven attach = no system, not a sales engine." }),
  CDD("cdd_discount_leakage", "sales", "Discount leakage",
    "rc_discounting", "Discounts are common but margin impact isn't reviewed.",
    "Roughly what share of last week's sales went out at any kind of discount?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Discount leakage risk." }),
  CDD("cdd_return_root_cause", "sales", "Return root cause",
    "rc_returns_exchanges", "Returns are processed but not analyzed by reason.",
    "When returns come back, do you log the reason — fit, defect, changed mind, gift — anywhere?",
    { repair_map_trigger_seed: "Returns / exchange leakage." }),
  CDD("cdd_gift_card_liability", "sales", "Gift card liability",
    "rc_gift_cards", "Gift cards are sold but liability isn't tracked.",
    "Do you know how much is currently outstanding on gift cards or store credit?",
    { answer_type: "currency", capture: { notes: true, estimated_value: true, range: true },
      admin_interpretation: "Untracked gift card balance is a hidden liability." }),
  CDD("cdd_special_orders", "sales", "Special order tracking",
    "rc_special_orders", "Special orders or holds happen but tracking is informal.",
    "When you take a special order or a hold, how does the customer get notified, and what stops it from being forgotten?",
    { repair_map_trigger_seed: "Special order / hold tracking gap." }),
  CDD("cdd_staff_consistency", "sales", "Staff consistency",
    "rc_staff_selling_consistency", "Conversion or basket changes a lot by employee.",
    "If your top-converting employee called out for a week, what would happen to sales?",
    { repair_map_trigger_seed: "Staff selling consistency gap." }),

  // ── Conditional Deep Dives — Operations ────────────────────────────────
  CDD("cdd_inventory_accuracy_root", "operations", "Inventory accuracy root cause",
    "op_inventory_accuracy", "Inventory accuracy is unknown or under 90%.",
    "When the count and the POS don't match, what is usually the cause — receiving, shrink, returns, or POS setup?",
    { repair_map_trigger_seed: "Inventory accuracy root-cause gap." }),
  CDD("cdd_cycle_count_cadence", "operations", "Cycle count cadence",
    "op_cycle_counts", "Cycle counts are skipped or inconsistent.",
    "Which categories actually get cycle-counted in a normal month, and who does it?",
    { repair_map_trigger_seed: "Cycle count cadence gap." }),
  CDD("cdd_shrink_tracking", "operations", "Shrink tracking",
    "op_shrink", "Shrink is suspected but not measured.",
    "Is shrink reviewed by category or by shift, or only as a single store-wide number?",
    { repair_map_trigger_seed: "Shrink visibility gap." }),
  CDD("cdd_dead_stock_cadence", "operations", "Dead stock cadence",
    "op_dead_stock", "No regular markdown or clearance cadence.",
    "How often do you actually walk the floor looking for stale or aging product?",
    { repair_map_trigger_seed: "Dead stock cadence gap." }),
  CDD("cdd_stockout_recovery", "operations", "Stockout recovery",
    "op_stockouts", "Best sellers run out and replenishment is reactive.",
    "When a best seller runs out, how long does it usually take to get it back on the shelf?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Stockout recovery gap." }),
  CDD("cdd_reorder_memory", "operations", "Reorder by memory",
    "op_reorder_process", "Reorders are placed from memory or 'looking thin'.",
    "Are reorder points written down for top items, or is it eyeballed each week?",
    { admin_interpretation: "Memory-based reorder is the most common stockout root cause." }),
  CDD("cdd_receiving_check", "operations", "Receiving discipline",
    "op_receiving", "Deliveries aren't checked against the invoice.",
    "Has anyone caught a short delivery or a wrong substitution in the last month?",
    { admin_interpretation: "If 'no' = vendor leakage that may not be visible in cost reports." }),
  CDD("cdd_pos_setup_drift", "operations", "POS setup drift",
    "op_pos_setup", "Owner or staff aren't sure who sets up new SKUs.",
    "When a SKU is set up wrong — wrong price, wrong category, wrong tax — how is it usually caught?",
    { repair_map_trigger_seed: "POS / SKU setup drift." }),
  CDD("cdd_pricing_audit", "operations", "Pricing audit",
    "op_pricing_setup", "Shelf tag, POS, and SKU prices may not match.",
    "If we picked five random shelf tags right now, how confident are you that all five match the POS?",
    { admin_interpretation: "Pricing drift is a quiet margin leak and a customer trust issue." }),
  CDD("cdd_merchandising_review", "operations", "Merchandising review",
    "op_merchandising_workflow", "Displays change informally with no review.",
    "When a display is changed, does anyone look at sales the next week to see if it worked?",
    { repair_map_trigger_seed: "Merchandising performance review gap." }),
  CDD("cdd_register_variance", "operations", "Register variance",
    "op_cash_drawer", "Cash drawer variances happen but aren't reviewed.",
    "How often does the drawer come up short or over, and is there a pattern by employee or shift?",
    { repair_map_trigger_seed: "Cash drawer variance pattern review." }),
  CDD("cdd_open_close_consistency", "operations", "Open / close consistency",
    "op_open_close_checklists", "No written checklist, or checklist isn't used.",
    "If two different employees open the store, would the floor look the same at 10 a.m.?",
    { repair_map_trigger_seed: "Shift consistency gap." }),

  // ── Conditional Deep Dives — Financial ─────────────────────────────────
  CDD("cdd_category_margin_visibility", "financial", "Category margin visibility",
    "fv_category_margin", "Owner knows total margin but not category margin.",
    "If we ranked your categories by margin right now, would you bet you know the top three and bottom three?",
    { admin_interpretation: "Confidence vs. data gap is itself the finding.",
      repair_map_trigger_seed: "Category margin blind spot." }),
  CDD("cdd_inventory_turnover_unknown", "financial", "Inventory turnover unknown",
    "fv_inventory_turnover", "Owner cannot quote inventory turnover.",
    "Roughly how long does an item sit before it sells, and which category sits longest?",
    { repair_map_trigger_seed: "Inventory turnover visibility gap." }),
  CDD("cdd_inventory_cash_trap", "financial", "Inventory cash trap",
    "fv_inventory_value", "Inventory dollars are large versus monthly revenue.",
    "If you had to convert a third of inventory to cash in 30 days, what would you have to do — and what would it cost?",
    { admin_interpretation: "Stress-test reveals real markdown room and cash exposure.",
      repair_map_trigger_seed: "Inventory cash trap." }),
  CDD("cdd_dead_stock_cash", "financial", "Dead stock cash",
    "fv_dead_stock_cost", "Aging product is visible but markdown plan is missing.",
    "What is the oldest item on your floor right now, and what would you sell it for tomorrow?",
    { repair_map_trigger_seed: "Dead stock markdown plan gap." }),
  CDD("cdd_discount_margin_review", "financial", "Discount margin review",
    "fv_discount_impact", "Discounts run but margin impact isn't reviewed.",
    "After your last big sale event, did you compare margin dollars to the same period without a sale?",
    { repair_map_trigger_seed: "Discount margin review gap." }),
  CDD("cdd_vendor_terms_discipline", "financial", "Vendor terms discipline",
    "fv_vendor_terms", "Vendor terms vary widely or aren't tracked.",
    "Are vendor minimums, lead times, and payment terms written down anywhere, or held in memory?",
    { repair_map_trigger_seed: "Vendor terms / buying discipline gap." }),
  CDD("cdd_cash_deposit_lag", "financial", "Cash deposit lag",
    "fv_cash_deposits", "Cash sits on site multiple days.",
    "How many days does cash typically sit before it hits the bank?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      admin_interpretation: "Deposit lag is a control risk, not just a finance issue." }),
  CDD("cdd_open_to_buy_discipline", "financial", "Open-to-buy discipline",
    "fv_open_to_buy", "Buying is reactive with no monthly budget.",
    "What stops a vendor visit from turning into a buy that you didn't budget for?",
    { repair_map_trigger_seed: "Open-to-buy discipline gap." }),
  CDD("cdd_break_even_per_day", "financial", "Break-even per day",
    "fv_break_even", "Break-even is not known per day.",
    "Do your managers know what each shift needs to do in sales just to break even?",
    { repair_map_trigger_seed: "Shift-level break-even visibility gap." }),

  // ── Conditional Deep Dives — Owner Independence ───────────────────────
  CDD("cdd_owner_buying_bottleneck", "owner_independence", "Buying bottleneck",
    "oi_buying", "Owner makes most buying decisions alone.",
    "If you couldn't buy for a month, who would pick it up, and what would they get wrong first?",
    { repair_map_trigger_seed: "Owner buying bottleneck." }),
  CDD("cdd_partial_delegation", "owner_independence", "Partial delegation",
    "oi_manager_authority", "Manager exists but staff still call owner for small items.",
    "What kinds of decisions do staff or managers still call you about that they probably shouldn't have to?",
    { admin_interpretation: "Partial delegation is the most common store-coverage failure mode." }),
  CDD("cdd_store_coverage_test", "owner_independence", "Store coverage test",
    "oi_owner_floor", "Owner is on the floor most days.",
    "If you stopped working the floor next month, which day or shift would actually be at risk first?",
    { repair_map_trigger_seed: "Store coverage risk." }),
  CDD("cdd_cash_handling_redundancy", "owner_independence", "Cash handling redundancy",
    "oi_cash_handling", "Owner is the only person who counts and deposits.",
    "If you couldn't be there for a week, who could legally count, deposit, and reconcile cash?",
    { repair_map_trigger_seed: "Cash-handling redundancy gap." }),
  CDD("cdd_vacation_test", "owner_independence", "Vacation test",
    "oi_owner_absent", "Owner says something would break if absent.",
    "Walk me through what would actually fall over in week one of you being gone, day by day.",
    { repair_map_trigger_seed: "Owner blast-radius mapping." }),
  CDD("cdd_documented_standards", "owner_independence", "Documented standards",
    "oi_documented_standards", "Most operating standards are not written down.",
    "If you had to hand a new manager one binder tomorrow, what would actually be in it?",
    { admin_interpretation: "What's in the binder vs. missing reveals priority docs." }),
  CDD("cdd_cross_training", "owner_independence", "Cross-training",
    "oi_manager_authority", "Most staff only know their own role.",
    "How many of your staff can run a register, receive a shipment, and close out a drawer?",
    { repair_map_trigger_seed: "Cross-training gap." }),

  // ── Evidence / Source-of-Truth Prompts ────────────────────────────────
  Q("ev_pos_sales", "evidence", "POS sales report",
    "Could you export the last 90 days of POS sales-by-day reports?",
    { evidence_prompt: "POS sales-by-day, last 90 days",
      source_of_truth_guidance: "POS sales report" }),
  Q("ev_pos_category", "evidence", "POS category report",
    "Could you pull a sales-by-category report for the last 90 days?",
    { evidence_prompt: "POS sales by category, last 90 days",
      source_of_truth_guidance: "POS category report" }),
  Q("ev_pos_sku", "evidence", "SKU / product sales",
    "Could you export the top and bottom 50 SKUs by sales for the last 90 days?",
    { evidence_prompt: "Top + bottom 50 SKUs, last 90 days" }),
  Q("ev_inventory_valuation", "evidence", "Inventory valuation",
    "Could you share the most recent inventory valuation report?",
    { evidence_prompt: "Most recent inventory valuation report",
      source_of_truth_guidance: "POS inventory valuation export" }),
  Q("ev_inventory_count_sheets", "evidence", "Inventory count sheets",
    "Could you share your most recent full inventory count sheet?",
    { evidence_prompt: "Most recent full inventory count" }),
  Q("ev_cycle_count_log", "evidence", "Cycle count log",
    "Could you share whatever cycle count log you keep, even if informal?",
    { evidence_prompt: "Cycle count log, last 90 days" }),
  Q("ev_shrink_log", "evidence", "Shrink / damage log",
    "Could you share whatever log you keep of shrink, theft, or damaged items?",
    { evidence_prompt: "Shrink / damage log, last 90 days" }),
  Q("ev_receiving_records", "evidence", "Receiving records",
    "Could you share the last 30 days of receiving records or signed packing slips?",
    { evidence_prompt: "Receiving records, last 30 days" }),
  Q("ev_vendor_invoices", "evidence", "Vendor invoices",
    "Could you share the last month of vendor invoices?",
    { evidence_prompt: "Vendor invoices, last 30 days" }),
  Q("ev_vendor_terms_doc", "evidence", "Vendor terms list",
    "Do you have a written list of your top vendors with terms, lead times, and minimums?",
    { evidence_prompt: "Vendor terms / lead times / minimums list" }),
  Q("ev_reorder_report", "evidence", "Reorder report",
    "Could you share whatever reorder list or report you use to decide what to buy?",
    { evidence_prompt: "Reorder list / suggested-order report" }),
  Q("ev_stockout_record", "evidence", "Stockout record",
    "Do you keep any record of stockouts on best sellers — even a notebook?",
    { evidence_prompt: "Stockout record / out-of-stock log" }),
  Q("ev_returns_report", "evidence", "Return / exchange report",
    "Could you export the last 90 days of returns and exchanges from the POS?",
    { evidence_prompt: "Returns / exchanges, last 90 days",
      source_of_truth_guidance: "POS returns report" }),
  Q("ev_discount_report", "evidence", "Discount / promotion report",
    "Could you export the last 90 days of discounts and promotions applied at the POS?",
    { evidence_prompt: "Discount / promotion report, last 90 days" }),
  Q("ev_loyalty_report", "evidence", "Loyalty / customer report",
    "Could you share a recent report from your loyalty platform showing enrollment and repeat purchase?",
    { evidence_prompt: "Loyalty enrollment + repeat purchase report" }),
  Q("ev_email_sms_report", "evidence", "Email / SMS report",
    "Could you share the last 90 days of email and SMS send reports?",
    { evidence_prompt: "Email / SMS send + open/click report" }),
  Q("ev_review_dashboard", "evidence", "Review dashboard",
    "Could you share a screenshot of your Google and Yelp review dashboards?",
    { evidence_prompt: "Google + Yelp review dashboard screenshots" }),
  Q("ev_cash_deposits", "evidence", "Cash deposit records",
    "Could you share the last 30 days of cash deposit records?",
    { evidence_prompt: "Cash deposit records, last 30 days" }),
  Q("ev_payroll_report", "evidence", "Payroll / scheduling report",
    "Could you share the most recent payroll summary and a scheduling export?",
    { evidence_prompt: "Most recent payroll summary + schedule",
      source_of_truth_guidance: "Paycom / ADP / Gusto" }),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent profit-and-loss statement?",
    { evidence_prompt: "Trailing 12-month P&L from QuickBooks/Xero/FreshBooks",
      evidence_required: true }),
  Q("ev_balance_sheet", "evidence", "Balance sheet",
    "Could you share a current balance sheet?",
    { evidence_prompt: "Most recent balance sheet" }),
  Q("ev_aged_inventory", "evidence", "Aged inventory report",
    "Could you share an aged inventory or dead stock report from the POS?",
    { evidence_prompt: "Aged inventory / dead stock report" }),
  Q("ev_merchandising_calendar", "evidence", "Merchandising calendar",
    "Could you share a merchandising calendar or product-drop plan if you keep one?",
    { evidence_prompt: "Merchandising calendar / product-drop plan" }),
  Q("ev_org_chart", "evidence", "Org chart",
    "Could you share an org chart with names, roles, and decision authority?",
    { evidence_prompt: "Org chart with titles and decision rights" }),

  // ── Admin Interpretation Support (owner-quote readiness) ───────────────
  Q("ai_quote_buying_intuition", "owner_independence", "Owner-quote: buying intuition",
    "Listen for: 'I know what sells because I'm here every day.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Owner buying intuition signal",
      admin_interpretation: "Buying intuition without POS category and SKU profitability data = owner buying dependency + possible category margin blind spot. Evidence needed: POS category sales, SKU margin, inventory turnover.",
      admin_only_notes: "Admin-only interpretation prompt — never shown to client." }),
  Q("ai_quote_inventory_reactive", "operations", "Owner-quote: reactive inventory",
    "Listen for: 'We do inventory counts when things look off.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Reactive inventory signal",
      admin_interpretation: "Reactive counting = stock accuracy gap. Evidence needed: count cadence, variance reports, shrink logs.",
      admin_only_notes: "Admin-only interpretation prompt — never shown to client." }),
  Q("ai_quote_volume_means_good", "financial", "Owner-quote: volume = good product",
    "Listen for: 'We sell a lot of that item, so it's definitely a good product.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Volume vs. margin confusion",
      admin_interpretation: "Sales volume does not prove margin. Trigger category/SKU margin deep dive before validating the claim.",
      admin_only_notes: "Admin-only interpretation prompt — never shown to client." }),
  Q("ai_quote_partial_delegation", "owner_independence", "Owner-quote: partial delegation",
    "Listen for: 'The team can run the store, but they call me for discounts or weird customer issues.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Partial delegation signal",
      admin_interpretation: "Partial delegation = decision-rights gap and store coverage risk even when manager exists.",
      admin_only_notes: "Admin-only interpretation prompt — never shown to client." }),
  Q("ai_quote_reorder_memory", "operations", "Owner-quote: reorder by memory",
    "Listen for: 'We usually reorder when we notice we're low.'",
    { prompt_kind: "admin_interpretation_support",
      business_term: "Memory-based reorder signal",
      admin_interpretation: "Informal reorder = stockout risk + owner/staff memory dependency. Trigger reorder process and stockout deep dives.",
      admin_only_notes: "Admin-only interpretation prompt — never shown to client." }),
];

export const RETAIL_BRICK_MORTAR_BANK: IndustryQuestionBank = {
  industry: I,
  label: "Retail / Brick-and-Mortar",
  questions: QUESTIONS,
};