/** P93E-E2G — Retail / Brick-and-Mortar starter bank. */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";
const I = "retail_brick_mortar" as const;
const Q = (key: string, gear: DiagnosticQuestion["gear"], section: string, plain: string,
  extra: Partial<DiagnosticQuestion> = {}): DiagnosticQuestion => ({
  key: `retail.${key}`, industry: I, gear, section,
  plain_language_question: plain, answer_type: "narrative", capture: { notes: true }, ...extra,
});
const QUESTIONS: DiagnosticQuestion[] = [
  Q("bp_format", "business_profile", "Store format",
    "What does the store sell, how many SKUs roughly, and what's the footprint?"),
  Q("bp_locations", "business_profile", "Locations",
    "How many locations, and which one drives the most revenue?",
    { answer_type: "numeric", capture: { notes: true, exact_value: true } }),
  Q("bp_staffing", "business_profile", "Staffing",
    "How many people are on the floor on a typical day, and who's running the shift?"),
  Q("dg_foot_traffic", "demand", "Foot traffic",
    "Roughly how many customers come through the door in a normal week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true, seasonal: true } }),
  Q("dg_local_marketing", "demand", "Local marketing",
    "What are you doing for local marketing right now, and what seems to actually work?"),
  Q("dg_loyalty", "demand", "Loyalty / repeat",
    "Do you have a loyalty or repeat-customer program? What share of sales is repeat?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true } }),
  Q("rc_avg_basket", "sales", "Average basket",
    "What's the average basket size or transaction value?",
    { business_term: "Average ticket", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("rc_conversion", "sales", "Conversion rate",
    "Of the people who walk in, what percent leave with something?",
    { business_term: "Walk-in conversion", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_attach", "sales", "Attach / upsell",
    "How are staff trained to upsell or attach add-on items?"),
  Q("op_pos", "operations", "POS system",
    "What POS are you using — Square, Lightspeed, Shopify POS, Clover — and what does it report on?",
    { source_of_truth_guidance: "POS sales / inventory reports" }),
  Q("op_inventory_count", "operations", "Inventory count cadence",
    "How often is inventory actually counted, and how big is the variance?",
    { repair_map_signal: "Inventory Variance Risk" }),
  Q("op_shrinkage", "operations", "Shrinkage",
    "Do you have a sense of shrinkage from theft, damage, or miscount?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_supplier", "operations", "Supplier / reorder",
    "How do reorders happen — who decides what to bring in and when?"),
  Q("fv_qb", "financial", "Books status",
    "Are your books current in QuickBooks/Xero, and who keeps them up?"),
  Q("fv_revenue", "financial", "Monthly revenue",
    "What's average monthly revenue right now?",
    { answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true } }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know your gross margin by category?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_open_ar", "financial", "Open AR (B2B portion)",
    "If you do any wholesale or B2B, how much is owed to you right now?",
    { answer_type: "currency", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("oi_owner_floor", "owner_independence", "Owner on floor",
    "How many days a week are you personally on the floor or working a register?",
    { repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_manager", "owner_independence", "Store manager",
    "Is there a store manager who can open, close, and run the day without you?"),
  Q("ev_pos_export", "evidence", "POS export",
    "Could you export the last 90 days of POS sales and inventory reports?",
    { evidence_prompt: "POS sales + inventory variance, last 90 days" }),
  Q("ev_pl", "evidence", "P&L",
    "Could you share a recent P&L?", { evidence_prompt: "Trailing 12-month P&L" }),
];
export const RETAIL_BRICK_MORTAR_BANK: IndustryQuestionBank = {
  industry: I, label: "Retail / Brick-and-Mortar", questions: QUESTIONS,
};
