/**
 * P93E-E2G — Trades / Home Services full-depth diagnostic interview bank.
 *
 * Target depth: enough structured truth for a serious 1.5–2 hour live admin-led
 * diagnostic interview. Each prompt is classified as `core`,
 * `conditional_deep_dive`, `evidence_source_of_truth`, or
 * `admin_interpretation_support` (see types.ts), and may carry
 * report-finding seeds and Repair-Map trigger seeds.
 */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";

const I = "trades_home_services" as const;
const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `trades.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

/**
 * Helper for conditional deep-dive prompts. The admin opens these only when
 * the parent answer reveals risk described by `triggerWhen`.
 */
const CDD = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  parent: string,
  triggerWhen: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion =>
  Q(key, gear, section, plain, {
    prompt_kind: "conditional_deep_dive",
    parent_key: `trades.${parent}`,
    trigger_when: triggerWhen,
    ...extra,
  });

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile (10) ──────────────────────────────────────────────
  Q("bp_services_offered", "business_profile", "Service mix",
    "What services do you offer today, and which one drives the most revenue?",
    { business_term: "Service mix / revenue concentration", capture: { notes: true } }),
  Q("bp_service_area", "business_profile", "Service area",
    "What geographic area do you serve, and how far will your crews travel for a job?",
    { business_term: "Service radius / drive-time cost" }),
  Q("bp_crew_structure", "business_profile", "Crew structure",
    "Walk me through your crew structure today — how many crews and what does a typical crew look like?",
    { business_term: "Crew composition", source_of_truth_guidance: "Org chart / payroll roster" }),
  Q("bp_service_techs", "business_profile", "Service techs",
    "How many service technicians do you have, and how many are full-time vs. part-time?",
    { business_term: "Service tech headcount", answer_type: "numeric",
      capture: { notes: true, exact_value: true } }),
  Q("bp_install_crews", "business_profile", "Install crews",
    "How many install crews do you run, and how big is each one?",
    { business_term: "Install crew capacity", answer_type: "numeric",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("bp_maintenance_techs", "business_profile", "Maintenance techs",
    "Do you have anyone dedicated to maintenance / tune-ups, or do service techs do it between calls?",
    { business_term: "Maintenance capacity" }),
  Q("bp_dispatch_admin", "business_profile", "Dispatch / admin",
    "Who handles dispatch, scheduling, and customer calls during the day?",
    { business_term: "Dispatch / admin support" }),
  Q("bp_service_manager", "business_profile", "Service manager",
    "Is there a service manager today, or does the owner still own that role?",
    { business_term: "Service manager role",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("bp_sales_role", "business_profile", "Sales / comfort advisor",
    "Do you have a dedicated sales or comfort-advisor role, or does the owner / a tech sell?",
    { business_term: "Sales role coverage" }),
  Q("bp_seasonality", "business_profile", "Seasonal demand",
    "How much does demand swing across the year — what does a peak month vs. a slow month look like?",
    { business_term: "Seasonal demand swing", answer_type: "seasonal_range",
      capture: { notes: true, seasonal: true } }),

  // ── Demand Generation (12) ─────────────────────────────────────────────
  Q("dg_calls_per_week", "demand", "Service calls",
    "Roughly how many service calls do you complete in a normal week?",
    { business_term: "Weekly service call volume", answer_type: "numeric",
      capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true },
      source_of_truth_guidance: "Scheduling / dispatch tool weekly report" }),
  Q("dg_maint_per_week", "demand", "Maintenance visits",
    "How many maintenance visits or tune-ups do you do in a normal week?",
    { answer_type: "numeric", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("dg_repairs_per_week", "demand", "Repairs",
    "About how many repair jobs are you running per week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true } }),
  Q("dg_installs_per_week", "demand", "Installs",
    "How many installs (full system replacements or new installs) happen in a typical week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, seasonal: true } }),
  Q("dg_referrals", "demand", "Referrals",
    "How many of your jobs come from referrals or word-of-mouth?",
    { business_term: "Referral share of demand", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_gbp", "demand", "Google Business Profile",
    "Do you actively manage your Google Business Profile, and who's responsible for it?",
    { business_term: "GBP ownership",
      source_of_truth_guidance: "Google Business Profile manager" }),
  Q("dg_reviews", "demand", "Reviews & request cadence",
    "Roughly how many Google reviews do you have, and do you have a consistent process for asking for them?",
    { business_term: "Review volume & request consistency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("dg_repeat_customers", "demand", "Repeat customers",
    "How much of your work is repeat customers calling you back?",
    { business_term: "Repeat customer share", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_web_leads", "demand", "Website / form leads",
    "Do leads come through your website forms, and roughly how many per week?",
    { business_term: "Web form lead volume", answer_type: "numeric",
      capture: { notes: true, estimated_value: true } }),
  Q("dg_missed_calls", "demand", "After-hours missed calls",
    "What happens to calls that come in after hours or when dispatch is busy?",
    { business_term: "After-hours / missed-call leakage",
      repair_map_signal: "Follow-Up Leakage" }),
  Q("dg_paid_ads", "demand", "Paid ads / boosts",
    "Are you running any paid ads, boosted posts, or LSAs right now? About how much per month?",
    { business_term: "Paid ad spend", answer_type: "currency",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_slow_season_plan", "demand", "Slow-season planning",
    "What's your plan for filling the schedule during the slow season?",
    { business_term: "Slow-season demand strategy" }),

  // ── Revenue Conversion (12) ────────────────────────────────────────────
  Q("rc_estimate_turnaround", "sales", "Estimate turnaround",
    "From the time someone asks for an estimate, how long until they get it?",
    { business_term: "Estimate turnaround time",
      source_of_truth_guidance: "CRM / estimate timestamps",
      repair_map_signal: "Follow-Up Leakage" }),
  Q("rc_quote_followup", "sales", "Quote follow-up",
    "Walk me through how you follow up on quotes that haven't been accepted yet.",
    { business_term: "Quote follow-up cadence" }),
  Q("rc_close_service", "sales", "Close rate — service",
    "Of the service calls you run, what percent end in approved repair work?",
    { business_term: "Service-to-repair close rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_close_repair", "sales", "Close rate — repair",
    "Of the repair estimates you give, what percent get approved?",
    { business_term: "Repair close rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_close_install", "sales", "Close rate — install",
    "Of the install or replacement quotes you give, what percent close?",
    { business_term: "Install/replacement close rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_avg_ticket", "sales", "Average ticket",
    "What's a typical ticket size for a completed job — service, repair, and install?",
    { business_term: "Average ticket",
      helper_text: "The average dollar amount of a completed job or sale.",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks invoice average / POS report" }),
  Q("rc_financing", "sales", "Financing presentation",
    "Do techs or comfort advisors offer financing on every install? How is it presented?",
    { business_term: "Financing attach rate" }),
  Q("rc_maintenance_agreements", "sales", "Maintenance agreement conversion",
    "What percent of customers leave with a maintenance agreement after a job?",
    { business_term: "Maintenance agreement attach rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_owner_dependency_large", "sales", "Owner involvement on large jobs",
    "Who closes your largest install or replacement jobs today?",
    { business_term: "Owner dependency on large estimates",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("rc_won_lost_tracking", "sales", "Won / lost tracking",
    "Do you track why estimates are won or lost? Where does that data live?",
    { business_term: "Won/lost reason tracking",
      source_of_truth_guidance: "CRM pipeline / won-lost report" }),
  Q("rc_replacement_process", "sales", "Replacement estimate process",
    "Walk me through what happens when a tech finds a system that should be replaced.",
    { business_term: "Replacement handoff process" }),
  Q("rc_sales_notes_quality", "sales", "Sales notes quality",
    "When a customer says 'no' or 'not yet,' do techs capture why in writing?",
    { business_term: "Sales note quality" }),

  // ── Operational Efficiency (18) ────────────────────────────────────────
  Q("op_dispatch_process", "operations", "Dispatch process",
    "Walk me through how a job gets from a phone call to the right tech showing up.",
    { business_term: "Dispatch workflow" }),
  Q("op_scheduling_tool", "operations", "Scheduling tool",
    "What tool are you using for scheduling and dispatch — Jobber, Housecall Pro, ServiceTitan, paper, or something else?",
    { business_term: "Field service / dispatch system",
      source_of_truth_guidance: "Field service platform (Jobber, Housecall Pro, ServiceTitan, etc.)" }),
  Q("op_tech_text_workarounds", "operations", "Tech texting / phone workarounds",
    "How often do techs text or call dispatch to figure out where to go next?",
    { business_term: "Shadow dispatch behavior",
      repair_map_signal: "Shadow Dispatcher Risk" }),
  Q("op_job_notes", "operations", "Job note quality",
    "When a tech finishes a job, what gets written down, and where?",
    { business_term: "Job note completeness",
      repair_map_signal: "First-Time Fix Drag" }),
  Q("op_callbacks", "operations", "Callbacks / rework",
    "About how many callbacks or rework visits happen per month?",
    { business_term: "Callback / rework rate", answer_type: "numeric",
      capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "First-Time Fix Drag" }),
  Q("op_first_time_fix", "operations", "First-time fix rate",
    "What percent of service calls are completely fixed on the first visit?",
    { business_term: "First-time fix rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_parts_ordering", "operations", "Parts ordering",
    "Walk me through how parts get ordered when a tech needs something they don't have.",
    { business_term: "Parts ordering workflow" }),
  Q("op_truck_inventory", "operations", "Truck inventory",
    "Do you have a standard truck stock list, and who's accountable for keeping trucks stocked?",
    { business_term: "Truck inventory accountability",
      repair_map_signal: "Truck Inventory Accountability Gap" }),
  Q("op_warranty", "operations", "Warranty handling",
    "How do you handle warranty claims and warranty parts today?",
    { business_term: "Warranty workflow" }),
  Q("op_job_closeout", "operations", "Job closeout",
    "What does 'job closed' actually look like — what has to happen for the job to be considered done?",
    { business_term: "Job closeout definition" }),
  Q("op_crew_capacity", "operations", "Crew capacity",
    "On a normal week, how many jobs can your crews realistically complete?",
    { business_term: "Crew / job capacity",
      helper_text: "How many crews or techs you can send out at once, and how many jobs they can realistically complete in a normal week.",
      answer_type: "numeric",
      capture: { notes: true, estimated_value: true, range: true, seasonal: true } }),
  Q("op_bottlenecks", "operations", "Bottlenecks",
    "Where does the workflow break first when you get busy?",
    { business_term: "Operational bottleneck" }),
  Q("op_quality_control", "operations", "Quality control",
    "Who checks that the work was done right? Is there any QC process?",
    { business_term: "QC process" }),
  Q("op_service_manager_escalation", "operations", "Service manager escalation",
    "When something escalates in the field, who does the tech call?",
    { business_term: "Escalation path",
      repair_map_signal: "Dispatch Decision Rights Gap" }),
  Q("op_customer_communication", "operations", "Customer communication",
    "How do customers know when the tech is on the way, and who manages that?",
    { business_term: "On-the-way communication" }),
  Q("op_subcontractors", "operations", "Subcontractors",
    "Do you sub any work out? When and to whom?",
    { business_term: "Subcontractor usage" }),
  Q("op_safety_incidents", "operations", "Safety / incidents",
    "How are safety incidents or property damage tracked when they happen?",
    { business_term: "Incident tracking" }),
  Q("op_after_hours_oncall", "operations", "After-hours on-call",
    "Who's on the after-hours on-call rotation, and how is it managed?",
    { business_term: "On-call rotation" }),

  // ── Financial Visibility (15) ──────────────────────────────────────────
  Q("fv_qb_status", "financial", "QuickBooks status",
    "Are your books in QuickBooks, Xero, or something else, and are they current?",
    { business_term: "Bookkeeping system & currency",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks file",
      evidence_prompt: "Most recent P&L (last 90 days)" }),
  Q("fv_books_frequency", "financial", "Bookkeeping frequency",
    "Who reconciles the books, and how often?",
    { business_term: "Book reconciliation cadence" }),
  Q("fv_revenue_monthly", "financial", "Monthly revenue",
    "Roughly what's your average monthly revenue right now?",
    { business_term: "Average monthly revenue", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true, seasonal: true },
      source_of_truth_guidance: "QuickBooks / P&L",
      evidence_prompt: "Trailing 12-month revenue from QuickBooks/Xero P&L" }),
  Q("fv_revenue_annual", "financial", "Annual revenue",
    "What did you do in revenue last year, and what are you tracking toward this year?",
    { business_term: "Annual revenue", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know what your gross margin looks like — what's left after labor, materials, and direct job costs?",
    { business_term: "Gross margin",
      helper_text: "Roughly how much is left after direct labor, materials, equipment, parts, subcontractors, and job costs — before overhead and owner profit.",
      answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks / P&L / job-costing report" }),
  Q("fv_margin_by_job", "financial", "Margin by job type",
    "Do you know which job types are most and least profitable?",
    { business_term: "Margin by service line" }),
  Q("fv_job_costing", "financial", "Job costing",
    "Do you do real job costing today, or is it more of a gut check?",
    { business_term: "Job costing maturity",
      source_of_truth_guidance: "Field-service or QuickBooks job costing report" }),
  Q("fv_labor_burden", "financial", "Labor burden",
    "Do you know what your real labor burden is compared to billable hours?",
    { business_term: "Labor burden",
      helper_text: "The real cost of labor compared to the work completed. If you do not track this, we can start with payroll hours compared to billable/job hours.",
      repair_map_signal: "Labor Burden Visibility Gap" }),
  Q("fv_payroll_billable", "financial", "Payroll-to-billable hours",
    "How many payroll hours do you pay vs. how many billable hours show up on jobs?",
    { business_term: "Payroll-to-billable ratio", answer_type: "range",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_open_ar", "financial", "Open AR / unpaid invoices",
    "How much money is currently owed to you for completed work that customers have not paid yet?",
    { business_term: "Open AR / unpaid invoices",
      helper_text: "Money customers owe you right now for completed work that has not been paid yet.",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks AR Aging Report",
      evidence_prompt: "AR Aging Summary (current)" }),
  Q("fv_cash_surprises", "financial", "Cash-flow surprises",
    "When was the last time cash flow caught you off guard?",
    { business_term: "Cash-flow predictability" }),
  Q("fv_tax_payroll_readiness", "financial", "Tax / payroll readiness",
    "Are payroll taxes and sales tax filings current?",
    { business_term: "Tax / payroll readiness" }),
  Q("fv_dashboard", "financial", "Dashboard availability",
    "What financial dashboard do you actually look at each week or month?",
    { business_term: "Financial dashboard cadence" }),
  Q("fv_owner_pay", "financial", "Owner compensation",
    "Are you paying yourself a real salary, or pulling distributions when there's cash?",
    { business_term: "Owner compensation pattern" }),
  Q("fv_cash_position", "financial", "Cash on hand",
    "About how much cash do you have on hand right now across all business accounts?",
    { business_term: "Cash on hand", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "Bank balances / QuickBooks bank feed" }),

  // ── Owner Independence (12) ────────────────────────────────────────────
  Q("oi_owner_hours", "owner_independence", "Owner hours",
    "About how many hours a week are you personally working in the business right now?",
    { business_term: "Owner weekly hours", answer_type: "numeric",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("oi_vacation_test", "owner_independence", "Vacation test",
    "If you took two weeks off starting tomorrow, what would break first?",
    { business_term: "Owner vacation test",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_approval_thresholds", "owner_independence", "Approval thresholds",
    "What dollar amount or decision still needs your personal approval?",
    { business_term: "Owner approval threshold",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("oi_dispatch_dependency", "owner_independence", "Dispatch dependency",
    "How often do dispatch or scheduling decisions come back to you?",
    { business_term: "Dispatch decision-rights gap",
      repair_map_signal: "Dispatch Decision Rights Gap" }),
  Q("oi_customer_escalations", "owner_independence", "Customer escalation dependency",
    "When a customer is upset, who handles it?",
    { business_term: "Customer escalation owner" }),
  Q("oi_service_manager_rights", "owner_independence", "Service manager decision rights",
    "Does your service manager (if you have one) have real decision-making authority on jobs and money?",
    { business_term: "Service manager decision rights" }),
  Q("oi_large_estimate_dependency", "owner_independence", "Large estimate dependency",
    "On larger jobs, who actually puts the estimate together and presents it?",
    { business_term: "Large estimate dependency" }),
  Q("oi_sops_documented", "owner_independence", "Documented SOPs",
    "What parts of how you run the business are written down today, vs. in someone's head?",
    { business_term: "Documented SOPs" }),
  Q("oi_48h_runner", "owner_independence", "Who can run the company for 48h",
    "If you disappeared for 48 hours, who would actually run the company?",
    { business_term: "48-hour owner-out test" }),
  Q("oi_finance_decisions", "owner_independence", "Financial decisions",
    "Who can sign checks or move money besides you?",
    { business_term: "Financial signing authority" }),
  Q("oi_hiring_decisions", "owner_independence", "Hiring decisions",
    "When you need to hire a tech, who runs that process today?",
    { business_term: "Hiring ownership" }),
  Q("oi_owner_calendar", "owner_independence", "Owner calendar",
    "If we looked at your calendar for the past two weeks, what would we see most of?",
    { business_term: "Owner time allocation",
      source_of_truth_guidance: "Owner calendar / 2-week time log" }),

  // ── Evidence & Documentation Readiness (10) ────────────────────────────
  Q("ev_pl", "evidence", "P&L readiness",
    "Could you share a recent profit-and-loss statement with us this week?",
    { business_term: "P&L availability",
      evidence_prompt: "Trailing 12-month P&L from QuickBooks/Xero/FreshBooks",
      evidence_required: true }),
  Q("ev_ar_aging", "evidence", "AR aging readiness",
    "Could you pull an AR aging report for us?",
    { business_term: "AR aging availability",
      evidence_prompt: "AR Aging Summary (current)",
      evidence_required: true }),
  Q("ev_payroll", "evidence", "Payroll summary",
    "Could you share a recent payroll summary so we can see hours vs. billable?",
    { business_term: "Payroll summary availability",
      evidence_prompt: "Most recent payroll summary",
      source_of_truth_guidance: "Paycom / ADP / Gusto" }),
  Q("ev_field_service_export", "evidence", "Field service export",
    "Could you export the last 90 days of jobs from your dispatch / field service tool?",
    { business_term: "Dispatch / field service export",
      evidence_prompt: "Last 90 days of jobs from Jobber / Housecall Pro / ServiceTitan" }),
  Q("ev_crm_export", "evidence", "CRM export",
    "Could you export your pipeline or won/lost report from your CRM?",
    { business_term: "CRM pipeline export",
      evidence_prompt: "Pipeline export with stage history" }),
  Q("ev_review_export", "evidence", "Review history",
    "Can you share a screenshot or export of your Google Business Profile reviews?",
    { business_term: "Review history" }),
  Q("ev_ad_platform", "evidence", "Ad platform reports",
    "If you're running ads, can you share the last 90 days of spend and lead reports?",
    { business_term: "Ad platform performance",
      evidence_prompt: "Google Ads / Meta Ads / LSA last 90 days",
      source_of_truth_guidance: "Ad platform / CRM / website analytics" }),
  Q("ev_sops", "evidence", "SOP examples",
    "Could you share one or two of your most-used SOPs, even if rough?",
    { business_term: "SOP samples" }),
  Q("ev_org_chart", "evidence", "Org chart",
    "Do you have an org chart or roster we can see?",
    { business_term: "Org chart / roster" }),
  Q("ev_owner_calendar_share", "evidence", "Owner calendar / time log",
    "Would you be willing to share two weeks of your calendar so we can see where your time really goes?",
    { business_term: "Owner calendar share",
      source_of_truth_guidance: "Owner calendar / 2-week time log" }),

  // ── Conditional Deep Dives — Demand ────────────────────────────────────
  CDD("cdd_calls_drop_cause", "demand", "Service calls",
    "dg_calls_per_week", "Owner reports declining or volatile call volume.",
    "When you compare this to last year, is call volume up, flat, or down — and what do you think is driving the change?",
    { admin_interpretation: "Distinguish demand-side weakness from capacity throttling (e.g. unanswered calls, slow estimates).",
      report_finding_seed: "Demand-trend visibility — owner-claimed direction, not yet evidence-verified." }),
  CDD("cdd_referral_program_formality", "demand", "Referrals",
    "dg_referrals", "Referral share is high (≥40%) but no documented program exists.",
    "Do you have any formal referral program or incentive, or is it all word-of-mouth?",
    { admin_interpretation: "High referral share with no system = fragile demand pillar.",
      report_finding_seed: "Referral concentration without formal program — single-channel demand risk." }),
  CDD("cdd_gbp_owner_loss_risk", "demand", "Google Business Profile",
    "dg_gbp", "Owner is the only person with Google Business Profile access.",
    "If you stepped away from the business, who else could log in to manage your Google Business Profile?",
    { repair_map_trigger_seed: "GBP access redundancy gap.",
      admin_interpretation: "Single-owner GBP access is a continuity and review-recovery risk." }),
  CDD("cdd_review_request_method", "demand", "Reviews & request cadence",
    "dg_reviews", "Review-request process is informal or owner-driven.",
    "Walk me through exactly how a review gets asked for after a job — who, when, and how.",
    { repair_map_trigger_seed: "Review-request consistency gap." }),
  CDD("cdd_missed_call_capture_path", "demand", "After-hours missed calls",
    "dg_missed_calls", "Missed or after-hours calls are not captured systematically.",
    "When a call is missed, what actually happens — voicemail, answering service, text-back, or nothing?",
    { repair_map_trigger_seed: "Missed-call capture path." }),
  CDD("cdd_after_hours_revenue_loss", "demand", "After-hours missed calls",
    "dg_missed_calls", "Owner suspects after-hours leakage but can't quantify it.",
    "Roughly how many after-hours calls do you think you lose in a typical week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      admin_interpretation: "This is owner estimate only — never report as verified leakage." }),
  CDD("cdd_ad_attribution", "demand", "Paid ads / boosts",
    "dg_paid_ads", "Owner is running paid ads but can't say what's working.",
    "When a lead comes in from ads, can you tell which campaign or platform it came from?",
    { repair_map_trigger_seed: "Ad attribution visibility gap.",
      source_of_truth_guidance: "Ad platform reports + CRM source field" }),
  CDD("cdd_lsa_dispute_workflow", "demand", "Paid ads / boosts",
    "dg_paid_ads", "Owner is running Google LSA.",
    "Do you dispute bad-quality LSA leads, and who handles that?",
    { admin_interpretation: "Most owners do not dispute LSA charges — silent ad spend leakage." }),
  CDD("cdd_web_lead_speed_to_first_touch", "demand", "Website / form leads",
    "dg_web_leads", "Web leads exist but no defined response SLA.",
    "From the time a website lead comes in, how long until someone actually contacts them?",
    { answer_type: "range", capture: { notes: true, range: true, estimated_value: true },
      repair_map_trigger_seed: "Web-lead response SLA gap." }),
  CDD("cdd_repeat_customer_winback", "demand", "Repeat customers",
    "dg_repeat_customers", "Repeat-customer share is unexpectedly low.",
    "Do you have any way to reach back out to past customers — email list, mailers, text campaigns?",
    { repair_map_trigger_seed: "Customer win-back system gap." }),

  // ── Conditional Deep Dives — Sales ─────────────────────────────────────
  CDD("cdd_estimate_bottleneck_owner", "sales", "Estimate turnaround",
    "rc_estimate_turnaround", "Estimates take longer than 24 hours.",
    "What part of the estimate process slows things down, and who has to touch it before it goes out?",
    { repair_map_trigger_seed: "Estimate handoff bottleneck.",
      admin_interpretation: "Owner-on-every-estimate is a top install close-rate killer." }),
  CDD("cdd_quote_followup_automation", "sales", "Quote follow-up",
    "rc_quote_followup", "Quote follow-up is ad hoc.",
    "Is there any automatic reminder or sequence after a quote goes out, or is follow-up manual?",
    { repair_map_trigger_seed: "Quote follow-up cadence gap." }),
  CDD("cdd_install_lost_reasons", "sales", "Close rate — install",
    "rc_close_install", "Install close rate < 35% or unknown.",
    "When an install quote is lost, what's the most common reason you hear?",
    { admin_interpretation: "Listen for price-objection vs. trust/process objections — they require different repairs." }),
  CDD("cdd_install_two_option_presentation", "sales", "Close rate — install",
    "rc_close_install", "Install quotes are presented as a single option.",
    "Do you give customers options on installs — good/better/best — or one number?",
    { repair_map_trigger_seed: "Install option-presentation gap." }),
  CDD("cdd_ticket_variance_by_tech", "sales", "Average ticket",
    "rc_avg_ticket", "Owner suspects ticket size varies a lot by tech.",
    "Do certain techs consistently have a higher or lower average ticket, and do you know why?",
    { admin_interpretation: "Tech-level variance is a coaching and pricing-discipline signal." }),
  CDD("cdd_financing_partner", "sales", "Financing presentation",
    "rc_financing", "Financing is offered.",
    "Which financing partner do you use, and how is it presented to the customer?",
    { source_of_truth_guidance: "Financing partner portal / approval reports" }),
  CDD("cdd_financing_presentation_script", "sales", "Financing presentation",
    "rc_financing", "Financing is offered but inconsistently.",
    "Do techs offer financing on every replacement quote, or only when the customer asks about price?",
    { repair_map_trigger_seed: "Financing presentation discipline gap." }),
  CDD("cdd_maintenance_agreement_renewal", "sales", "Maintenance agreement renewal",
    "rc_maintenance_agreements", "Maintenance agreements exist.",
    "Of the customers on a maintenance agreement, what percent renew each year?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      source_of_truth_guidance: "Maintenance agreement registry / CRM tag" }),
  CDD("cdd_largest_job_owner_close_share", "sales", "Owner involvement on large jobs",
    "rc_owner_dependency_large", "Owner closes most large jobs personally.",
    "Of last year's ten biggest jobs, how many did you personally close?",
    { repair_map_trigger_seed: "Large-deal owner dependency.",
      admin_interpretation: "If 8+/10 are owner-closed, the sales seat is not actually staffed." }),
  CDD("cdd_lost_reason_top3", "sales", "Won / lost tracking",
    "rc_won_lost_tracking", "Won/lost reasons are tracked but not reviewed.",
    "If you had to name the top three reasons you lose deals right now, what would they be?",
    { admin_interpretation: "Owner intuition vs. CRM data is itself a finding." }),

  // ── Conditional Deep Dives — Operations ────────────────────────────────
  CDD("cdd_dispatch_decision_authority", "operations", "Dispatch process",
    "op_dispatch_process", "Dispatch authority is unclear.",
    "When two jobs collide, who actually decides which crew goes where without checking with you?",
    { repair_map_trigger_seed: "Dispatch decision-rights gap." }),
  CDD("cdd_shadow_dispatch_volume", "operations", "Tech texting / phone workarounds",
    "op_tech_text_workarounds", "Techs text/call to figure out next job.",
    "On a busy day, roughly how many of those 'where do I go next' texts hit dispatch or you?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Shadow dispatcher load." }),
  CDD("cdd_callback_root_cause", "operations", "Callbacks / rework",
    "op_callbacks", "Callback rate is non-trivial or unknown.",
    "When you get a callback, what's the most common root cause — diagnosis, parts, install error, or expectation mismatch?",
    { admin_interpretation: "Causes are diagnostic — different repairs (training, QC, scope clarity)." }),
  CDD("cdd_callback_cost_eaten_by", "operations", "Callbacks / rework",
    "op_callbacks", "Callbacks happen but no one tracks who eats the cost.",
    "When a callback happens, who pays for it — the company, the tech, or the customer?",
    { repair_map_trigger_seed: "Callback cost accountability gap." }),
  CDD("cdd_first_time_fix_blockers", "operations", "First-time fix rate",
    "op_first_time_fix", "First-time fix rate is below 80% or unknown.",
    "What's the single most common reason a job doesn't get fixed on the first visit?",
    { admin_interpretation: "Listen for parts-on-truck vs. diagnosis vs. authorization issues." }),
  CDD("cdd_parts_truck_run_frequency", "operations", "Parts ordering",
    "op_parts_ordering", "Techs frequently leave the job to get parts.",
    "How many times in a typical week does a tech have to leave a job to go get parts?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Parts-run leakage." }),
  CDD("cdd_truck_audit_cadence", "operations", "Truck inventory",
    "op_truck_inventory", "Truck stock list exists but isn't audited.",
    "How often does someone actually walk a truck and confirm the stock list matches?",
    { repair_map_trigger_seed: "Truck audit cadence gap." }),
  CDD("cdd_warranty_recovery_rate", "operations", "Warranty handling",
    "op_warranty", "Warranty work is happening but recovery is unclear.",
    "Of the warranty parts you replace, do you actually file and recover most of them from the manufacturer?",
    { repair_map_trigger_seed: "Warranty recovery leakage." }),
  CDD("cdd_capacity_overflow_path", "operations", "Crew capacity",
    "op_crew_capacity", "Demand regularly exceeds crew capacity.",
    "When you can't take all the work, what happens — push the customer out, refer them out, or just lose it?",
    { admin_interpretation: "Lost overflow is silent demand leakage." }),
  CDD("cdd_sub_quality_control", "operations", "Subcontractors",
    "op_subcontractors", "Subcontractors are used regularly.",
    "How do you make sure sub work meets your quality standard, and who checks it?",
    { repair_map_trigger_seed: "Sub QC gap." }),
  CDD("cdd_oncall_compensation", "operations", "After-hours on-call",
    "op_after_hours_oncall", "On-call rotation exists.",
    "How are on-call techs compensated, and is the rotation written down anywhere?",
    { admin_interpretation: "Undocumented on-call comp = retention risk." }),

  // ── Conditional Deep Dives — Financial ─────────────────────────────────
  CDD("cdd_books_close_lag_days", "financial", "Bookkeeping frequency",
    "fv_books_frequency", "Books are not closed monthly.",
    "How many days after month-end are your books actually closed and reconciled?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks / Xero close timestamp" }),
  CDD("cdd_revenue_concentration_top_customer", "financial", "Monthly revenue",
    "fv_revenue_monthly", "Owner mentions a few large customers driving revenue.",
    "What percent of your revenue comes from your top customer or top three customers?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      report_finding_seed: "Revenue concentration risk — owner-stated, not verified." }),
  CDD("cdd_margin_by_service_line_visibility", "financial", "Margin by job type",
    "fv_margin_by_job", "Owner can't name margin by service line.",
    "If I asked you which service line is your most profitable, would you be guessing or would you have a number?",
    { admin_interpretation: "Self-rated visibility — guides whether margin work is needed before pricing changes." }),
  CDD("cdd_job_costing_per_job_or_summary", "financial", "Job costing",
    "fv_job_costing", "Some form of job costing happens.",
    "Do you cost each job individually, or just look at category totals at month-end?",
    { source_of_truth_guidance: "Field-service job-cost report vs. P&L category summary" }),
  CDD("cdd_overtime_pattern", "financial", "Labor burden",
    "fv_labor_burden", "Overtime is suspected to be high.",
    "Roughly what percent of your payroll is overtime in a typical week?",
    { answer_type: "percent", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Overtime pattern leakage." }),
  CDD("cdd_ar_over_60_days", "financial", "Open AR / unpaid invoices",
    "fv_open_ar", "Open AR exists.",
    "Of that open AR, how much is over 60 days past due?",
    { answer_type: "currency", capture: { notes: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks AR Aging — 60+ bucket",
      evidence_prompt: "AR Aging filtered to 60+ days" }),
  CDD("cdd_cash_surprise_root_causes", "financial", "Cash-flow surprises",
    "fv_cash_surprises", "Cash flow has surprised the owner recently.",
    "What was the surprise — payroll spike, slow collections, tax bill, big purchase, or something else?",
    { admin_interpretation: "Maps the dominant cash leak class without claiming dollars." }),
  CDD("cdd_owner_distribution_cadence", "financial", "Owner compensation",
    "fv_owner_pay", "Owner pulls distributions instead of salary.",
    "When you take money out of the business, is it on a schedule or only when there's cash?",
    { admin_interpretation: "Pulls-on-cash pattern is an owner-finance discipline signal — never frame as tax advice." }),

  // ── Conditional Deep Dives — Owner Independence ────────────────────────
  CDD("cdd_owner_hours_breakdown", "owner_independence", "Owner hours",
    "oi_owner_hours", "Owner is working >50 hrs/week.",
    "Of the hours you're working, roughly what share is in the field, in the office, on sales, and on owner-only work?",
    { admin_interpretation: "Time-allocation maps which seat is actually unstaffed." }),
  CDD("cdd_vacation_test_blast_radius", "owner_independence", "Vacation test",
    "oi_vacation_test", "Owner says something would break if they took 2 weeks off.",
    "If we walked through those two weeks day by day, what's the first thing that would actually fall over?",
    { repair_map_trigger_seed: "Owner blast-radius mapping." }),
  CDD("cdd_approval_threshold_bottleneck_count", "owner_independence", "Approval thresholds",
    "oi_approval_thresholds", "Approval threshold is low or vague.",
    "How many decisions like that hit your phone in a normal week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true } }),
  CDD("cdd_dispatch_owner_calls_per_day", "owner_independence", "Dispatch dependency",
    "oi_dispatch_dependency", "Dispatch frequently routes through the owner.",
    "On a normal day, how many times does dispatch or a tech ping you to make a call?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, range: true },
      repair_map_trigger_seed: "Dispatch decision routing through owner." }),
  CDD("cdd_sop_use_in_practice", "owner_independence", "Documented SOPs",
    "oi_sops_documented", "SOPs exist on paper.",
    "Do techs and admins actually follow those SOPs, or are they more reference material?",
    { admin_interpretation: "Documentation that isn't used is a false-confidence signal." }),
  CDD("cdd_check_signing_redundancy", "owner_independence", "Financial decisions",
    "oi_finance_decisions", "Owner is the only check signer.",
    "If you couldn't sign for a week, who could legally move money or pay vendors?",
    { repair_map_trigger_seed: "Financial signing redundancy gap." }),
  CDD("cdd_hiring_pipeline_visibility", "owner_independence", "Hiring decisions",
    "oi_hiring_decisions", "Hiring is reactive, not pipeline-driven.",
    "Do you have any active pipeline of techs you'd hire if a seat opened, or do you start from scratch each time?",
    { repair_map_trigger_seed: "Recruiting pipeline gap." }),

  // ── Extra Evidence / Source-of-Truth Prompts ───────────────────────────
  Q("ev_balance_sheet", "evidence", "Balance sheet",
    "Could you share a current balance sheet so we can see assets, liabilities, and equity?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Most recent balance sheet from QuickBooks/Xero/FreshBooks",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks balance sheet" }),
  Q("ev_bank_statements_90", "evidence", "Bank statements",
    "Could you share the last 90 days of business bank statements?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Bank statements (last 90 days)",
      admin_only_notes: "Used to spot-check revenue and recurring outflows. Never reframe as audit." }),
  Q("ev_top10_jobs_90", "evidence", "Top 10 jobs",
    "Could you pull the ten largest jobs from the last 90 days with revenue and tech assigned?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Top 10 jobs by revenue, last 90 days",
      source_of_truth_guidance: "Field service / dispatch system export" }),
  Q("ev_contract_template", "evidence", "Contract / proposal template",
    "Could you share the standard contract or proposal template you give customers?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Customer-facing contract / proposal template" }),
  Q("ev_warranty_log", "evidence", "Warranty log",
    "Could you share whatever warranty-claims log you have, even if informal?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Warranty claims log (last 12 months)" }),
  Q("ev_financing_export", "evidence", "Financing approvals",
    "If you offer financing, could you export approval / decline volume from your financing partner?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Financing partner approval / decline export" }),
  Q("ev_maintenance_agreement_count", "evidence", "Maintenance agreement registry",
    "Could you share a count of active maintenance agreements and a recent renewal report?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Active maintenance agreement count + renewal report" }),
  Q("ev_callback_log", "evidence", "Callback log",
    "Could you share whatever callback or rework log you have for the last 90 days?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Callback / rework log (last 90 days)" }),
  Q("ev_org_chart_titles", "evidence", "Org chart with titles",
    "Could you share an org chart showing names, titles, and decision authority?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Org chart with titles and decision rights" }),
  Q("ev_owner_calendar_export", "evidence", "Owner calendar export",
    "Could you share an export or screenshot of the past two weeks of your calendar?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Two-week owner calendar export" }),
  Q("ev_tax_filings_current", "evidence", "Tax filings",
    "Could you confirm payroll tax and sales tax filings are current — we are not auditing, just noting status?",
    { prompt_kind: "evidence_source_of_truth",
      admin_only_notes: "Document operational visibility only. Do not provide tax advice or claim filings are correct.",
      evidence_prompt: "Filing status confirmation (no documents required)" }),
  Q("ev_safety_log", "evidence", "Safety / incident log",
    "Could you share whatever safety incident log you have, even if informal?",
    { prompt_kind: "evidence_source_of_truth",
      evidence_prompt: "Safety / incident log (last 12 months)" }),
];

export const TRADES_HOME_SERVICES_BANK: IndustryQuestionBank = {
  industry: I,
  label: "Trades / Home Services",
  questions: QUESTIONS,
};
