/**
 * P93E-E2G — Trades / Home Services full-depth diagnostic interview bank.
 * Target depth: ~70-100 prompts across all RGS gears.
 */
import type { DiagnosticQuestion, IndustryQuestionBank } from "../types";

const I = "trades_home_services" as const;
const Q = (
  key: string,
  gear: DiagnosticQuestion["gear"],
  section: string,
  plain: string,
  extra: Partial<DiagnosticQuestion> = {},
): DiagnosticQuestion => ({
  key: `trades.${key}`,
  industry: I,
  gear,
  section,
  plain_language_question: plain,
  answer_type: "narrative",
  capture: { notes: true },
  ...extra,
});

const QUESTIONS: DiagnosticQuestion[] = [
  // ── Business Profile (10) ──────────────────────────────────────────────
  Q("bp_services_offered", "business_profile", "Service mix",
    "What services do you offer today, and which one drives the most revenue?",
    { business_term: "Service mix / revenue concentration", capture: { notes: true } }),
  Q("bp_service_area", "business_profile", "Service area",
    "What geographic area do you serve, and how far will your crews travel for a job?",
    { business_term: "Service radius / drive-time cost" }),
  Q("bp_crew_structure", "business_profile", "Crew structure",
    "Walk me through your crew structure today — how many crews and what does a typical crew look like?",
    { business_term: "Crew composition", source_of_truth_guidance: "Org chart / payroll roster" }),
  Q("bp_service_techs", "business_profile", "Service techs",
    "How many service technicians do you have, and how many are full-time vs. part-time?",
    { business_term: "Service tech headcount", answer_type: "numeric",
      capture: { notes: true, exact_value: true } }),
  Q("bp_install_crews", "business_profile", "Install crews",
    "How many install crews do you run, and how big is each one?",
    { business_term: "Install crew capacity", answer_type: "numeric",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("bp_maintenance_techs", "business_profile", "Maintenance techs",
    "Do you have anyone dedicated to maintenance / tune-ups, or do service techs do it between calls?",
    { business_term: "Maintenance capacity" }),
  Q("bp_dispatch_admin", "business_profile", "Dispatch / admin",
    "Who handles dispatch, scheduling, and customer calls during the day?",
    { business_term: "Dispatch / admin support" }),
  Q("bp_service_manager", "business_profile", "Service manager",
    "Is there a service manager today, or does the owner still own that role?",
    { business_term: "Service manager role",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("bp_sales_role", "business_profile", "Sales / comfort advisor",
    "Do you have a dedicated sales or comfort-advisor role, or does the owner / a tech sell?",
    { business_term: "Sales role coverage" }),
  Q("bp_seasonality", "business_profile", "Seasonal demand",
    "How much does demand swing across the year — what does a peak month vs. a slow month look like?",
    { business_term: "Seasonal demand swing", answer_type: "seasonal_range",
      capture: { notes: true, seasonal: true } }),

  // ── Demand Generation (12) ─────────────────────────────────────────────
  Q("dg_calls_per_week", "demand", "Service calls",
    "Roughly how many service calls do you complete in a normal week?",
    { business_term: "Weekly service call volume", answer_type: "numeric",
      capture: { notes: true, exact_value: true, estimated_value: true, seasonal: true },
      source_of_truth_guidance: "Scheduling / dispatch tool weekly report" }),
  Q("dg_maint_per_week", "demand", "Maintenance visits",
    "How many maintenance visits or tune-ups do you do in a normal week?",
    { answer_type: "numeric", capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("dg_repairs_per_week", "demand", "Repairs",
    "About how many repair jobs are you running per week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true } }),
  Q("dg_installs_per_week", "demand", "Installs",
    "How many installs (full system replacements or new installs) happen in a typical week?",
    { answer_type: "numeric", capture: { notes: true, estimated_value: true, seasonal: true } }),
  Q("dg_referrals", "demand", "Referrals",
    "How many of your jobs come from referrals or word-of-mouth?",
    { business_term: "Referral share of demand", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_gbp", "demand", "Google Business Profile",
    "Do you actively manage your Google Business Profile, and who's responsible for it?",
    { business_term: "GBP ownership",
      source_of_truth_guidance: "Google Business Profile manager" }),
  Q("dg_reviews", "demand", "Reviews & request cadence",
    "Roughly how many Google reviews do you have, and do you have a consistent process for asking for them?",
    { business_term: "Review volume & request consistency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("dg_repeat_customers", "demand", "Repeat customers",
    "How much of your work is repeat customers calling you back?",
    { business_term: "Repeat customer share", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_web_leads", "demand", "Website / form leads",
    "Do leads come through your website forms, and roughly how many per week?",
    { business_term: "Web form lead volume", answer_type: "numeric",
      capture: { notes: true, estimated_value: true } }),
  Q("dg_missed_calls", "demand", "After-hours missed calls",
    "What happens to calls that come in after hours or when dispatch is busy?",
    { business_term: "After-hours / missed-call leakage",
      repair_map_signal: "Follow-Up Leakage" }),
  Q("dg_paid_ads", "demand", "Paid ads / boosts",
    "Are you running any paid ads, boosted posts, or LSAs right now? About how much per month?",
    { business_term: "Paid ad spend", answer_type: "currency",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("dg_slow_season_plan", "demand", "Slow-season planning",
    "What's your plan for filling the schedule during the slow season?",
    { business_term: "Slow-season demand strategy" }),

  // ── Revenue Conversion (12) ────────────────────────────────────────────
  Q("rc_estimate_turnaround", "sales", "Estimate turnaround",
    "From the time someone asks for an estimate, how long until they get it?",
    { business_term: "Estimate turnaround time",
      source_of_truth_guidance: "CRM / estimate timestamps",
      repair_map_signal: "Follow-Up Leakage" }),
  Q("rc_quote_followup", "sales", "Quote follow-up",
    "Walk me through how you follow up on quotes that haven't been accepted yet.",
    { business_term: "Quote follow-up cadence" }),
  Q("rc_close_service", "sales", "Close rate — service",
    "Of the service calls you run, what percent end in approved repair work?",
    { business_term: "Service-to-repair close rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_close_repair", "sales", "Close rate — repair",
    "Of the repair estimates you give, what percent get approved?",
    { business_term: "Repair close rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_close_install", "sales", "Close rate — install",
    "Of the install or replacement quotes you give, what percent close?",
    { business_term: "Install/replacement close rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_avg_ticket", "sales", "Average ticket",
    "What's a typical ticket size for a completed job — service, repair, and install?",
    { business_term: "Average ticket",
      helper_text: "The average dollar amount of a completed job or sale.",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks invoice average / POS report" }),
  Q("rc_financing", "sales", "Financing presentation",
    "Do techs or comfort advisors offer financing on every install? How is it presented?",
    { business_term: "Financing attach rate" }),
  Q("rc_maintenance_agreements", "sales", "Maintenance agreement conversion",
    "What percent of customers leave with a maintenance agreement after a job?",
    { business_term: "Maintenance agreement attach rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("rc_owner_dependency_large", "sales", "Owner involvement on large jobs",
    "Who closes your largest install or replacement jobs today?",
    { business_term: "Owner dependency on large estimates",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("rc_won_lost_tracking", "sales", "Won / lost tracking",
    "Do you track why estimates are won or lost? Where does that data live?",
    { business_term: "Won/lost reason tracking",
      source_of_truth_guidance: "CRM pipeline / won-lost report" }),
  Q("rc_replacement_process", "sales", "Replacement estimate process",
    "Walk me through what happens when a tech finds a system that should be replaced.",
    { business_term: "Replacement handoff process" }),
  Q("rc_sales_notes_quality", "sales", "Sales notes quality",
    "When a customer says 'no' or 'not yet,' do techs capture why in writing?",
    { business_term: "Sales note quality" }),

  // ── Operational Efficiency (18) ────────────────────────────────────────
  Q("op_dispatch_process", "operations", "Dispatch process",
    "Walk me through how a job gets from a phone call to the right tech showing up.",
    { business_term: "Dispatch workflow" }),
  Q("op_scheduling_tool", "operations", "Scheduling tool",
    "What tool are you using for scheduling and dispatch — Jobber, Housecall Pro, ServiceTitan, paper, or something else?",
    { business_term: "Field service / dispatch system",
      source_of_truth_guidance: "Field service platform (Jobber, Housecall Pro, ServiceTitan, etc.)" }),
  Q("op_tech_text_workarounds", "operations", "Tech texting / phone workarounds",
    "How often do techs text or call dispatch to figure out where to go next?",
    { business_term: "Shadow dispatch behavior",
      repair_map_signal: "Shadow Dispatcher Risk" }),
  Q("op_job_notes", "operations", "Job note quality",
    "When a tech finishes a job, what gets written down, and where?",
    { business_term: "Job note completeness",
      repair_map_signal: "First-Time Fix Drag" }),
  Q("op_callbacks", "operations", "Callbacks / rework",
    "About how many callbacks or rework visits happen per month?",
    { business_term: "Callback / rework rate", answer_type: "numeric",
      capture: { notes: true, estimated_value: true, range: true },
      repair_map_signal: "First-Time Fix Drag" }),
  Q("op_first_time_fix", "operations", "First-time fix rate",
    "What percent of service calls are completely fixed on the first visit?",
    { business_term: "First-time fix rate", answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("op_parts_ordering", "operations", "Parts ordering",
    "Walk me through how parts get ordered when a tech needs something they don't have.",
    { business_term: "Parts ordering workflow" }),
  Q("op_truck_inventory", "operations", "Truck inventory",
    "Do you have a standard truck stock list, and who's accountable for keeping trucks stocked?",
    { business_term: "Truck inventory accountability",
      repair_map_signal: "Truck Inventory Accountability Gap" }),
  Q("op_warranty", "operations", "Warranty handling",
    "How do you handle warranty claims and warranty parts today?",
    { business_term: "Warranty workflow" }),
  Q("op_job_closeout", "operations", "Job closeout",
    "What does 'job closed' actually look like — what has to happen for the job to be considered done?",
    { business_term: "Job closeout definition" }),
  Q("op_crew_capacity", "operations", "Crew capacity",
    "On a normal week, how many jobs can your crews realistically complete?",
    { business_term: "Crew / job capacity",
      helper_text: "How many crews or techs you can send out at once, and how many jobs they can realistically complete in a normal week.",
      answer_type: "numeric",
      capture: { notes: true, estimated_value: true, range: true, seasonal: true } }),
  Q("op_bottlenecks", "operations", "Bottlenecks",
    "Where does the workflow break first when you get busy?",
    { business_term: "Operational bottleneck" }),
  Q("op_quality_control", "operations", "Quality control",
    "Who checks that the work was done right? Is there any QC process?",
    { business_term: "QC process" }),
  Q("op_service_manager_escalation", "operations", "Service manager escalation",
    "When something escalates in the field, who does the tech call?",
    { business_term: "Escalation path",
      repair_map_signal: "Dispatch Decision Rights Gap" }),
  Q("op_customer_communication", "operations", "Customer communication",
    "How do customers know when the tech is on the way, and who manages that?",
    { business_term: "On-the-way communication" }),
  Q("op_subcontractors", "operations", "Subcontractors",
    "Do you sub any work out? When and to whom?",
    { business_term: "Subcontractor usage" }),
  Q("op_safety_incidents", "operations", "Safety / incidents",
    "How are safety incidents or property damage tracked when they happen?",
    { business_term: "Incident tracking" }),
  Q("op_after_hours_oncall", "operations", "After-hours on-call",
    "Who's on the after-hours on-call rotation, and how is it managed?",
    { business_term: "On-call rotation" }),

  // ── Financial Visibility (15) ──────────────────────────────────────────
  Q("fv_qb_status", "financial", "QuickBooks status",
    "Are your books in QuickBooks, Xero, or something else, and are they current?",
    { business_term: "Bookkeeping system & currency",
      source_of_truth_guidance: "QuickBooks / Xero / FreshBooks file",
      evidence_prompt: "Most recent P&L (last 90 days)" }),
  Q("fv_books_frequency", "financial", "Bookkeeping frequency",
    "Who reconciles the books, and how often?",
    { business_term: "Book reconciliation cadence" }),
  Q("fv_revenue_monthly", "financial", "Monthly revenue",
    "Roughly what's your average monthly revenue right now?",
    { business_term: "Average monthly revenue", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true, seasonal: true },
      source_of_truth_guidance: "QuickBooks / P&L",
      evidence_prompt: "Trailing 12-month revenue from QuickBooks/Xero P&L" }),
  Q("fv_revenue_annual", "financial", "Annual revenue",
    "What did you do in revenue last year, and what are you tracking toward this year?",
    { business_term: "Annual revenue", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("fv_gross_margin", "financial", "Gross margin",
    "Do you know what your gross margin looks like — what's left after labor, materials, and direct job costs?",
    { business_term: "Gross margin",
      helper_text: "Roughly how much is left after direct labor, materials, equipment, parts, subcontractors, and job costs — before overhead and owner profit.",
      answer_type: "percent",
      capture: { notes: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks / P&L / job-costing report" }),
  Q("fv_margin_by_job", "financial", "Margin by job type",
    "Do you know which job types are most and least profitable?",
    { business_term: "Margin by service line" }),
  Q("fv_job_costing", "financial", "Job costing",
    "Do you do real job costing today, or is it more of a gut check?",
    { business_term: "Job costing maturity",
      source_of_truth_guidance: "Field-service or QuickBooks job costing report" }),
  Q("fv_labor_burden", "financial", "Labor burden",
    "Do you know what your real labor burden is compared to billable hours?",
    { business_term: "Labor burden",
      helper_text: "The real cost of labor compared to the work completed. If you do not track this, we can start with payroll hours compared to billable/job hours.",
      repair_map_signal: "Labor Burden Visibility Gap" }),
  Q("fv_payroll_billable", "financial", "Payroll-to-billable hours",
    "How many payroll hours do you pay vs. how many billable hours show up on jobs?",
    { business_term: "Payroll-to-billable ratio", answer_type: "range",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("fv_open_ar", "financial", "Open AR / unpaid invoices",
    "How much money is currently owed to you for completed work that customers have not paid yet?",
    { business_term: "Open AR / unpaid invoices",
      helper_text: "Money customers owe you right now for completed work that has not been paid yet.",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "QuickBooks AR Aging Report",
      evidence_prompt: "AR Aging Summary (current)" }),
  Q("fv_cash_surprises", "financial", "Cash-flow surprises",
    "When was the last time cash flow caught you off guard?",
    { business_term: "Cash-flow predictability" }),
  Q("fv_tax_payroll_readiness", "financial", "Tax / payroll readiness",
    "Are payroll taxes and sales tax filings current?",
    { business_term: "Tax / payroll readiness" }),
  Q("fv_dashboard", "financial", "Dashboard availability",
    "What financial dashboard do you actually look at each week or month?",
    { business_term: "Financial dashboard cadence" }),
  Q("fv_owner_pay", "financial", "Owner compensation",
    "Are you paying yourself a real salary, or pulling distributions when there's cash?",
    { business_term: "Owner compensation pattern" }),
  Q("fv_cash_position", "financial", "Cash on hand",
    "About how much cash do you have on hand right now across all business accounts?",
    { business_term: "Cash on hand", answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true, range: true },
      source_of_truth_guidance: "Bank balances / QuickBooks bank feed" }),

  // ── Owner Independence (12) ────────────────────────────────────────────
  Q("oi_owner_hours", "owner_independence", "Owner hours",
    "About how many hours a week are you personally working in the business right now?",
    { business_term: "Owner weekly hours", answer_type: "numeric",
      capture: { notes: true, estimated_value: true, range: true } }),
  Q("oi_vacation_test", "owner_independence", "Vacation test",
    "If you took two weeks off starting tomorrow, what would break first?",
    { business_term: "Owner vacation test",
      repair_map_signal: "Owner Bottleneck Risk" }),
  Q("oi_approval_thresholds", "owner_independence", "Approval thresholds",
    "What dollar amount or decision still needs your personal approval?",
    { business_term: "Owner approval threshold",
      answer_type: "currency",
      capture: { notes: true, exact_value: true, estimated_value: true } }),
  Q("oi_dispatch_dependency", "owner_independence", "Dispatch dependency",
    "How often do dispatch or scheduling decisions come back to you?",
    { business_term: "Dispatch decision-rights gap",
      repair_map_signal: "Dispatch Decision Rights Gap" }),
  Q("oi_customer_escalations", "owner_independence", "Customer escalation dependency",
    "When a customer is upset, who handles it?",
    { business_term: "Customer escalation owner" }),
  Q("oi_service_manager_rights", "owner_independence", "Service manager decision rights",
    "Does your service manager (if you have one) have real decision-making authority on jobs and money?",
    { business_term: "Service manager decision rights" }),
  Q("oi_large_estimate_dependency", "owner_independence", "Large estimate dependency",
    "On larger jobs, who actually puts the estimate together and presents it?",
    { business_term: "Large estimate dependency" }),
  Q("oi_sops_documented", "owner_independence", "Documented SOPs",
    "What parts of how you run the business are written down today, vs. in someone's head?",
    { business_term: "Documented SOPs" }),
  Q("oi_48h_runner", "owner_independence", "Who can run the company for 48h",
    "If you disappeared for 48 hours, who would actually run the company?",
    { business_term: "48-hour owner-out test" }),
  Q("oi_finance_decisions", "owner_independence", "Financial decisions",
    "Who can sign checks or move money besides you?",
    { business_term: "Financial signing authority" }),
  Q("oi_hiring_decisions", "owner_independence", "Hiring decisions",
    "When you need to hire a tech, who runs that process today?",
    { business_term: "Hiring ownership" }),
  Q("oi_owner_calendar", "owner_independence", "Owner calendar",
    "If we looked at your calendar for the past two weeks, what would we see most of?",
    { business_term: "Owner time allocation",
      source_of_truth_guidance: "Owner calendar / 2-week time log" }),

  // ── Evidence & Documentation Readiness (10) ────────────────────────────
  Q("ev_pl", "evidence", "P&L readiness",
    "Could you share a recent profit-and-loss statement with us this week?",
    { business_term: "P&L availability",
      evidence_prompt: "Trailing 12-month P&L from QuickBooks/Xero/FreshBooks",
      evidence_required: true }),
  Q("ev_ar_aging", "evidence", "AR aging readiness",
    "Could you pull an AR aging report for us?",
    { business_term: "AR aging availability",
      evidence_prompt: "AR Aging Summary (current)",
      evidence_required: true }),
  Q("ev_payroll", "evidence", "Payroll summary",
    "Could you share a recent payroll summary so we can see hours vs. billable?",
    { business_term: "Payroll summary availability",
      evidence_prompt: "Most recent payroll summary",
      source_of_truth_guidance: "Paycom / ADP / Gusto" }),
  Q("ev_field_service_export", "evidence", "Field service export",
    "Could you export the last 90 days of jobs from your dispatch / field service tool?",
    { business_term: "Dispatch / field service export",
      evidence_prompt: "Last 90 days of jobs from Jobber / Housecall Pro / ServiceTitan" }),
  Q("ev_crm_export", "evidence", "CRM export",
    "Could you export your pipeline or won/lost report from your CRM?",
    { business_term: "CRM pipeline export",
      evidence_prompt: "Pipeline export with stage history" }),
  Q("ev_review_export", "evidence", "Review history",
    "Can you share a screenshot or export of your Google Business Profile reviews?",
    { business_term: "Review history" }),
  Q("ev_ad_platform", "evidence", "Ad platform reports",
    "If you're running ads, can you share the last 90 days of spend and lead reports?",
    { business_term: "Ad platform performance",
      evidence_prompt: "Google Ads / Meta Ads / LSA last 90 days",
      source_of_truth_guidance: "Ad platform / CRM / website analytics" }),
  Q("ev_sops", "evidence", "SOP examples",
    "Could you share one or two of your most-used SOPs, even if rough?",
    { business_term: "SOP samples" }),
  Q("ev_org_chart", "evidence", "Org chart",
    "Do you have an org chart or roster we can see?",
    { business_term: "Org chart / roster" }),
  Q("ev_owner_calendar_share", "evidence", "Owner calendar / time log",
    "Would you be willing to share two weeks of your calendar so we can see where your time really goes?",
    { business_term: "Owner calendar share",
      source_of_truth_guidance: "Owner calendar / 2-week time log" }),
];

export const TRADES_HOME_SERVICES_BANK: IndustryQuestionBank = {
  industry: I,
  label: "Trades / Home Services",
  questions: QUESTIONS,
};
