/**
 * P79 — Client-Facing Tool Access Audit registry.
 *
 * Honest classification of which RGS tools should be client-facing for
 * guided independence and which must remain admin-only because they
 * create or approve official RGS findings, change deterministic scores,
 * or touch payment/access/system controls.
 *
 * This registry is admin-facing reference material. It does NOT grant
 * access — runtime access still flows through `ClientToolGuard`,
 * `ProtectedRoute requireRole="admin"`, RLS, and existing
 * stage/payment gates.
 */

export type CurrentAccess =
  | "admin_only"
  | "client_visible"
  | "client_assignable"
  | "client_internal"
  | "admin_review_required"
  | "planned"
  | "not_built";

export type RecommendedAccess =
  | "admin_only"
  | "client_assignable"
  | "client_internal"
  | "client_visible_read_only"
  | "client_visible_after_approval";

export interface ClientToolAccessAuditEntry {
  tool_key: string;
  tool_name: string;
  current_access: CurrentAccess;
  recommended_access: RecommendedAccess;
  reason: string;
  guided_independence_value: "high" | "medium" | "low" | "none";
  required_gates: string[];
  approval_controls_required: boolean;
  admin_notes_risk: boolean;
  deterministic_override_risk: boolean;
  regulated_claim_risk: boolean;
  ai_allowed_client_side: boolean;
  ai_brain_key?: string;
  walkthrough_video_key?: string;
  client_route?: string;
  admin_route?: string;
}

export const CLIENT_TOOL_ACCESS_AUDIT: ClientToolAccessAuditEntry[] = [
  {
    tool_key: "owner_diagnostic_interview",
    tool_name: "Owner Diagnostic Interview",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Owner-completed intake. RGS reviews answers; the interview itself does not publish findings.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "ClientToolGuard", "stage gate"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "owner_diagnostic_interview",
    client_route: "/portal/tools/owner-diagnostic-interview",
  },
  {
    tool_key: "diagnostic_tool_sequence",
    tool_name: "Diagnostic Tool Sequence",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Assigned diagnostic sub-tools. Outputs become findings only after RGS review.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "ClientToolGuard", "stage gate"],
    approval_controls_required: true,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
  },
  {
    tool_key: "rgs_stability_scorecard",
    tool_name: "RGS Business Stability Scorecard\u2122",
    current_access: "client_visible",
    recommended_access: "client_visible_read_only",
    reason: "Deterministic 0\u20131000 scoring. Clients see results; only RGS may run/override scoring.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: true,
    admin_notes_risk: false,
    deterministic_override_risk: true,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    client_route: "/portal/tools/scorecard-history",
  },
  {
    tool_key: "structural_health_report",
    tool_name: "RGS Structural Health Report\u2122",
    current_access: "admin_review_required",
    recommended_access: "client_visible_after_approval",
    reason: "Official RGS report. Drafted/reviewed by admin; clients see only the published version.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "approval", "client_safe_select"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: true,
    ai_allowed_client_side: false,
    client_route: "/portal/reports",
    admin_route: "/admin/report-drafts",
  },
  {
    tool_key: "rgs_repair_map",
    tool_name: "RGS Repair Map\u2122",
    current_access: "admin_review_required",
    recommended_access: "client_visible_after_approval",
    reason: "Repair priorities are official guidance. Clients see only approved Repair Map items.",
    guided_independence_value: "high",
    required_gates: ["approval", "client_safe_select"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "rgs_repair_map",
  },
  {
    tool_key: "evidence_vault",
    tool_name: "RGS Evidence Vault\u2122",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Clients upload/view their own evidence. Admin review of all clients stays admin-only.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "RLS tenant isolation", "signed URLs only"],
    approval_controls_required: false,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "evidence_vault",
  },
  {
    tool_key: "sop_training_bible",
    tool_name: "SOP / Training Bible Creator",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Owner drafts internal SOPs. AI-assisted drafting is server-side, suggestive, and never publishes RGS findings.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "ClientToolGuard", "RLS"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: true,
    ai_brain_key: "sop_training_bible_client",
    walkthrough_video_key: "sop_training_bible",
    client_route: "/portal/tools/sop-training-bible",
  },
  {
    tool_key: "cost_of_friction_calculator",
    tool_name: "Cost of Friction Calculator\u2122",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Deterministic friction estimates from owner inputs. Safe for guided independence.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "cost_of_friction_calculator",
    client_route: "/portal/tools/cost-of-friction",
  },
  {
    tool_key: "stability_to_value_lens",
    tool_name: "Stability-to-Value Lens\u2122",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Deterministic structure score with operational-readiness boundary. No valuation claims.",
    guided_independence_value: "high",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: true,
    ai_allowed_client_side: false,
    walkthrough_video_key: "stability_to_value_lens",
    client_route: "/portal/tools/stability-to-value-lens",
  },
  {
    tool_key: "revenue_risk_monitor",
    tool_name: "Revenue & Risk Monitor\u2122",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Client-safe revenue/risk view. Admin admin-side review remains separate.",
    guided_independence_value: "medium",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "revenue_risk_monitor",
    client_route: "/portal/tools/revenue-risk-monitor",
    admin_route: "/admin/customers/:customerId/revenue-risk-monitor",
  },
  {
    tool_key: "worn_tooth_signals",
    tool_name: "Worn Tooth Signals\u2122",
    current_access: "admin_review_required",
    recommended_access: "client_visible_after_approval",
    reason: "Signals are official observations. Clients see only admin-approved entries.",
    guided_independence_value: "medium",
    required_gates: ["approval", "client_safe_select"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "worn_tooth_signals",
  },
  {
    tool_key: "reality_check_flags",
    tool_name: "Reality Check Flags\u2122",
    current_access: "admin_review_required",
    recommended_access: "client_visible_after_approval",
    reason: "Clarification requests reach the client only after admin review; responses return to admin.",
    guided_independence_value: "medium",
    required_gates: ["approval", "client_safe_select"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    walkthrough_video_key: "reality_check_flags",
  },
  {
    tool_key: "buyer_persona_icp_journey",
    tool_name: "Buyer Persona / ICP / Buyer Journey",
    current_access: "planned",
    recommended_access: "client_assignable",
    reason: "Owner-thinking tool. Safe for client use once route exists; AI assist must remain server-side and suggestive.",
    guided_independence_value: "medium",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
  },
  {
    tool_key: "workflow_process_mapping",
    tool_name: "Workflow / Process Mapping Tool",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Owner-built workflow maps. Safe for guided independence.",
    guided_independence_value: "medium",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    client_route: "/portal/tools/workflow-process-mapping",
  },
  {
    tool_key: "decision_rights_accountability",
    tool_name: "Decision Rights / Accountability Tool",
    current_access: "client_assignable",
    recommended_access: "client_assignable",
    reason: "Owner-defined accountability map. Safe for guided independence.",
    guided_independence_value: "medium",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    client_route: "/portal/tools/decision-rights-accountability",
  },
  {
    tool_key: "owner_decision_dashboard",
    tool_name: "Owner Decision Dashboard",
    current_access: "client_assignable",
    recommended_access: "client_visible_read_only",
    reason: "Owner-facing decision summary. Reads from approved client-visible signals only.",
    guided_independence_value: "medium",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    client_route: "/portal/tools/owner-decision-dashboard",
  },
  {
    tool_key: "tool_assignment_training_tracker",
    tool_name: "Tool Assignment + Training Tracker",
    current_access: "client_visible",
    recommended_access: "client_visible_read_only",
    reason: "Client-safe view of assigned tools and training status. Admin manages assignments.",
    guided_independence_value: "medium",
    required_gates: ["ProtectedRoute", "ClientToolGuard"],
    approval_controls_required: false,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    client_route: "/portal/tools/tool-assignment-training-tracker",
  },
  {
    tool_key: "advisory_notes_clarification_log",
    tool_name: "Advisory Notes / Clarification Log",
    current_access: "admin_review_required",
    recommended_access: "client_visible_after_approval",
    reason: "Clients see only admin-approved clarification messages. Internal admin notes never leak.",
    guided_independence_value: "medium",
    required_gates: ["approval", "client_safe_select"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    client_route: "/portal/tools/advisory-notes",
    admin_route: "/admin/customers/:customerId/advisory-notes",
  },
  {
    tool_key: "tool_specific_reports",
    tool_name: "Tool-Specific Reports",
    current_access: "admin_review_required",
    recommended_access: "client_visible_after_approval",
    reason: "Reports are drafted/reviewed by admin; clients only see approved, client_visible reports via signed URLs.",
    guided_independence_value: "high",
    required_gates: ["approval", "client_visible flag", "signed URL"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: true,
    ai_allowed_client_side: false,
    walkthrough_video_key: "tool_specific_reports",
    client_route: "/portal/reports",
    admin_route: "/admin/report-drafts",
  },
  {
    tool_key: "standalone_tool_runner",
    tool_name: "Standalone Tool Runner / Gig Deliverable Generator",
    current_access: "admin_only",
    recommended_access: "admin_only",
    reason: "Admin/operator gig delivery surface. Must never reach clients.",
    guided_independence_value: "none",
    required_gates: ["ProtectedRoute requireRole=admin"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: true,
    ai_allowed_client_side: false,
    walkthrough_video_key: "standalone_tool_runner",
    admin_route: "/admin/standalone-tool-runner",
  },
  {
    tool_key: "admin_diagnostic_review_dashboard",
    tool_name: "Admin Diagnostic Review Dashboard",
    current_access: "admin_only",
    recommended_access: "admin_only",
    reason: "All-client diagnostic queue and admin notes. Admin-only.",
    guided_independence_value: "none",
    required_gates: ["ProtectedRoute requireRole=admin"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: true,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    admin_route: "/admin/diagnostic-workspace",
  },
  {
    tool_key: "payment_access_invite",
    tool_name: "Payment / Access / Invite Tools",
    current_access: "admin_only",
    recommended_access: "admin_only",
    reason: "Account creation, payment links, portal access controls. Admin-only.",
    guided_independence_value: "none",
    required_gates: ["ProtectedRoute requireRole=admin", "edge function admin auth"],
    approval_controls_required: true,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    admin_route: "/admin/payments",
  },
  {
    tool_key: "connector_source_of_truth_matrix",
    tool_name: "Connector / Source-of-Truth Matrix",
    current_access: "admin_only",
    recommended_access: "admin_only",
    reason: "Admin marketing-safety controls and honest connector status. Clients see only their own connector status, not the matrix.",
    guided_independence_value: "none",
    required_gates: ["ProtectedRoute requireRole=admin"],
    approval_controls_required: true,
    admin_notes_risk: false,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
  },
  {
    tool_key: "client_health_renewal_risk",
    tool_name: "Client Health / Renewal Risk",
    current_access: "admin_only",
    recommended_access: "admin_only",
    reason: "Internal account health and renewal scoring. Admin-only.",
    guided_independence_value: "none",
    required_gates: ["ProtectedRoute requireRole=admin"],
    approval_controls_required: false,
    admin_notes_risk: true,
    deterministic_override_risk: false,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
    admin_route: "/admin/client-health",
  },
  {
    tool_key: "ai_system_readiness_brain_registry",
    tool_name: "AI System Readiness / AI Brain Registry",
    current_access: "admin_only",
    recommended_access: "admin_only",
    reason: "Internal AI configuration and brain packs. Never client-facing.",
    guided_independence_value: "none",
    required_gates: ["ProtectedRoute requireRole=admin"],
    approval_controls_required: true,
    admin_notes_risk: true,
    deterministic_override_risk: true,
    regulated_claim_risk: false,
    ai_allowed_client_side: false,
  },
];

/**
 * Tool keys that must NEVER appear as client-facing/active in the portal
 * tool list. Enforced by tests.
 */
export const ADMIN_ONLY_TOOL_KEYS: ReadonlySet<string> = new Set(
  CLIENT_TOOL_ACCESS_AUDIT
    .filter((e) => e.recommended_access === "admin_only")
    .map((e) => e.tool_key),
);

export function getAuditEntry(toolKey: string): ClientToolAccessAuditEntry | null {
  return CLIENT_TOOL_ACCESS_AUDIT.find((e) => e.tool_key === toolKey) ?? null;
}