/**
 * P89 — General Industry Deterministic Depth expansion.
 *
 * Additive catalog layer for P86C Industry Operational Depth™. These metrics
 * deepen deterministic admin review coverage. They do not auto-create repair
 * map items, source-of-truth conflicts, client findings, or live connector
 * records.
 */
import type {
  DepthEvidenceSourceType,
  DepthGearKey,
  DepthIndustryKey,
  DepthMetricDefinition,
} from "@/config/industryOperationalDepth";
import type { QuickStartTemplateKey } from "@/config/stabilityQuickStartTemplates";

export type RepairMapTriggerKey =
  | "capture_missing_signal"
  | "standardize_operating_rhythm"
  | "tighten_follow_up"
  | "tighten_cash_visibility"
  | "pricing_margin_review"
  | "capacity_review"
  | "training_handoff"
  | "inventory_control"
  | "vendor_review"
  | "customer_experience_review"
  | "channel_concentration_review"
  | "source_of_truth_review";

export interface DepthMetricAdminAnnotation {
  metric_key: string;
  admin_only_note: string;
  repair_trigger: RepairMapTriggerKey;
  source_of_truth_conflict_capable: boolean;
  repair_map_trigger_behavior: "additive_admin_annotation_only";
}

interface ExpansionSeed {
  slug: string;
  label: string;
  gears: ReadonlyArray<DepthGearKey>;
  trigger_rule: string;
  threshold_value: number | null;
  threshold_unit: DepthMetricDefinition["threshold_unit"];
  client_safe_explanation: string;
  evidence_examples: ReadonlyArray<DepthEvidenceSourceType>;
  forward_risk: string;
  repair_map_recommendation: string;
  recommended_quick_start_templates: ReadonlyArray<QuickStartTemplateKey>;
  admin_only_note: string;
  repair_trigger: RepairMapTriggerKey;
  source_of_truth_conflict_capable?: boolean;
}

const GENERAL_EXPANSION: ExpansionSeed[] = [
  seed("lead_source_unclear", "Lead Source Unclear", ["demand_generation"], "Trigger when more than 20% of new inquiries have no source recorded in the review period.", 20, "percent", "When lead source is unclear, the owner cannot tell which demand channels deserve attention.", ["manual_spreadsheet", "hubspot_manual_export", "owner_interview"], "Demand decisions drift toward whoever is loudest instead of what is working.", "Install a lead tracking sheet and review source completeness weekly.", ["lead_tracking_sheet"], "Check whether the owner has one place where inquiry source is entered before recommending software.", "capture_missing_signal", true),
  seed("follow_up_overdue", "Follow-Up Overdue", ["revenue_conversion"], "Trigger when five or more open opportunities have no next follow-up date.", 5, "count", "Open opportunities without follow-up dates tend to stall quietly.", ["manual_spreadsheet", "hubspot_manual_export", "salesforce_manual_export"], "Revenue conversion weakens because interested buyers are not moved to a next step.", "Install a follow-up log with owner and next-date fields.", ["follow_up_log", "proposal_pipeline_tracker"], "Confirm whether missing follow-up is a process issue or a system-of-record issue.", "tighten_follow_up", true),
  seed("owner_calendar_overloaded", "Owner Calendar Overloaded", ["owner_independence", "operational_efficiency"], "Trigger when the owner spends more than 15 hours per week on repeatable non-owner tasks.", 15, "count", "When repeatable work consumes the owner calendar, decisions and growth work get squeezed.", ["owner_interview", "weekly_review_log", "manual_spreadsheet"], "The owner remains the pressure point and the business cannot delegate cleanly.", "Run an owner time audit and identify the first delegation candidate.", ["owner_time_audit_worksheet", "role_clarity_sheet"], "Use the audit to separate true owner-only judgment from tasks that need training or decision rights.", "capacity_review"),
  seed("cash_review_gap", "Cash Review Gap", ["financial_visibility"], "Trigger when cash is not reviewed on a weekly rhythm.", null, "boolean", "Without a weekly cash view, spending decisions can outrun what the business can see.", ["quickbooks_manual_export", "manual_spreadsheet", "weekly_review_log"], "Cash surprises show up late and force reactive decisions.", "Install a weekly scoreboard and daily cash count where cash handling exists.", ["weekly_scoreboard", "daily_cash_count"], "Treat accounting exports as manual evidence only unless a connected source is already approved.", "tighten_cash_visibility", true),
  seed("repeat_issue_not_logged", "Repeat Issue Not Logged", ["operational_efficiency"], "Trigger when recurring customer or staff issues are discussed but not logged.", null, "boolean", "Repeat issues that are not logged feel random even when the pattern is clear.", ["owner_interview", "weekly_review_log", "manual_spreadsheet"], "The business keeps solving the same issue one person at a time.", "Install a support or issue tracker and review patterns weekly.", ["customer_support_response_tracker"], "Keep the review operational. Do not turn this into warranty, legal, or HR advice.", "customer_experience_review"),
  seed("proposal_status_unknown", "Proposal Status Unknown", ["revenue_conversion"], "Trigger when the owner cannot list active proposals by stage.", null, "boolean", "Unknown proposal status means conversion depends on memory instead of a visible pipeline.", ["manual_spreadsheet", "pipedrive_manual_export", "owner_interview"], "Open revenue gets lost because stalled proposals are not separated from active ones.", "Install a proposal pipeline tracker and weekly close/next-step review.", ["proposal_pipeline_tracker", "follow_up_log"], "Compare CRM export and owner interview for source-of-truth conflict before approving.", "tighten_follow_up", true),
  seed("single_channel_dependency", "Single Channel Dependency", ["demand_generation", "financial_visibility"], "Trigger when one channel contributes more than 60% of leads or revenue.", 60, "percent", "A single-channel dependency makes the business more fragile if that source slows.", ["manual_spreadsheet", "google_analytics_manual_export", "meta_ads_manual_export"], "Demand stability weakens because one channel carries pressure it may not keep carrying.", "Run a channel concentration review and identify one diversification step.", ["channel_concentration_review"], "This is operating concentration visibility, not marketing attribution certainty.", "channel_concentration_review", true),
  seed("handoff_owner_dependent", "Handoff Owner Dependent", ["operational_efficiency", "owner_independence"], "Trigger when client or job handoffs require owner approval to proceed.", null, "boolean", "Owner-dependent handoffs slow work and keep the business tied to one person.", ["owner_interview", "sop_document", "weekly_review_log"], "Work waits for the owner and the team cannot move predictably.", "Document the handoff and assign decision rights for the common cases.", ["role_clarity_sheet", "client_onboarding_checklist"], "Tie this to decision-rights work only after the actual handoff pattern is clear.", "training_handoff"),
  seed("support_response_unknown", "Support Response Unknown", ["operational_efficiency", "revenue_conversion"], "Trigger when customer response time cannot be estimated from any record.", null, "boolean", "If response time is unknown, customer frustration can build before the owner sees it.", ["weekly_review_log", "owner_interview", "manual_spreadsheet"], "Small service misses become review damage and rework.", "Install a response tracker and review open requests weekly.", ["customer_support_response_tracker"], "Use customer-experience language as operational review, not a separate gear.", "customer_experience_review"),
  seed("monthly_margin_not_reviewed", "Monthly Margin Not Reviewed", ["financial_visibility"], "Trigger when gross margin or contribution margin is not reviewed monthly.", null, "boolean", "Revenue can look healthy while margin quietly weakens.", ["quickbooks_manual_export", "manual_spreadsheet", "weekly_review_log"], "Pricing and spending decisions get made without margin context.", "Add margin review to the weekly scoreboard and monthly review rhythm.", ["weekly_scoreboard"], "Use owner language. Do not imply accounting treatment or formal assurance.", "pricing_margin_review", true),
  seed("new_customer_onboarding_inconsistent", "New Customer Onboarding Inconsistent", ["revenue_conversion", "operational_efficiency"], "Trigger when new customer kickoff steps vary by staff member.", null, "boolean", "Inconsistent onboarding creates avoidable confusion right after a customer says yes.", ["owner_interview", "sop_document", "weekly_review_log"], "Early friction increases support load and weakens repeat business.", "Install an onboarding checklist for the first repeatable version.", ["client_onboarding_checklist"], "For non-service businesses, treat onboarding as customer handoff or first-order handoff.", "standardize_operating_rhythm"),
  seed("open_close_routine_missing", "Open / Close Routine Missing", ["operational_efficiency"], "Trigger when repeat daily start/end routines are not written down.", null, "boolean", "Unwritten daily routines vary by person and make misses harder to spot.", ["sop_document", "weekly_review_log", "owner_interview"], "Quality and cash-control checks drift when the routine depends on memory.", "Install an opening / closing checklist for the recurring routine.", ["opening_closing_checklist"], "Do not describe the checklist as a regulatory or safety artifact.", "standardize_operating_rhythm"),
  seed("roles_unclear_for_recurring_work", "Roles Unclear for Recurring Work", ["owner_independence", "operational_efficiency"], "Trigger when recurring work has no named owner.", null, "boolean", "Work without a named owner usually becomes owner follow-up by default.", ["owner_interview", "sop_document", "weekly_review_log"], "Tasks drift, duplicate, or wait until the owner notices.", "Install a role clarity sheet and name owners for the recurring work.", ["role_clarity_sheet"], "Separate role clarity from HR job-description or employment advice.", "training_handoff"),
  seed("inventory_or_supplies_guessed", "Inventory or Supplies Guessed", ["operational_efficiency", "financial_visibility"], "Trigger when supplies or inventory are reordered from memory instead of a count or reorder point.", null, "boolean", "Guessing on inventory or supplies ties up cash or creates avoidable delays.", ["inventory_count_sheet", "manual_spreadsheet", "owner_interview"], "Stockouts, rush purchases, and excess supplies become recurring friction.", "Start with a small inventory count sheet for the highest-movement items.", ["inventory_count_sheet", "stockout_backorder_log"], "Use only operational inventory language. Avoid valuation, tax, or regulated-inventory claims.", "inventory_control"),
  seed("decision_log_missing", "Decision Log Missing", ["owner_independence", "financial_visibility"], "Trigger when recurring owner decisions are made but not logged for later review.", null, "boolean", "Without a decision log, the owner cannot see whether repeated calls are improving the system.", ["owner_interview", "weekly_review_log", "manual_spreadsheet"], "The same decision gets remade without learning from prior context.", "Add decision notes to the weekly review rhythm and owner dashboard.", ["weekly_scoreboard", "owner_time_audit_worksheet"], "This is a review aid, not a substitute for owner authority.", "standardize_operating_rhythm"),
  seed("source_records_disagree", "Source Records Disagree", ["financial_visibility", "operational_efficiency"], "Trigger when two manual records show materially different totals for the same period.", 5, "percent", "When source records disagree, the owner needs to know which number is being used for review.", ["manual_spreadsheet", "quickbooks_manual_export", "stripe_manual_export"], "Decisions may be made from whichever number is easier to find.", "Flag for source-of-truth review before client-visible interpretation.", ["weekly_scoreboard"], "Route to Source-of-Truth Conflict Flags™ for admin review. Do not auto-publish.", "source_of_truth_review", true),
  seed("weekly_priorities_too_many", "Weekly Priorities Too Many", ["owner_independence", "operational_efficiency"], "Trigger when more than five active priorities are marked as current for the same week.", 5, "count", "Too many active priorities makes the business busy without making the system clearer.", ["weekly_review_log", "manual_spreadsheet", "owner_interview"], "The team spreads effort thin and the owner cannot tell what matters most.", "Reduce to the few priorities that protect stability first.", ["weekly_scoreboard"], "Use as a prioritization conversation, not a productivity judgment.", "capacity_review"),
];

const RESTAURANT_EXPANSION: ExpansionSeed[] = [
  seed("prep_variance_untracked", "Prep Variance Untracked", ["operational_efficiency", "financial_visibility"], "Trigger when prep waste or over-prep is discussed but not logged.", null, "boolean", "Untracked prep variance hides waste until food cost rises.", ["menu_engineering_sheet", "daily_sales_log", "manual_spreadsheet"], "Waste pressure builds quietly and affects margin by daypart.", "Add prep variance to the daily sales and labor log.", ["daily_sales_and_labor_log", "inventory_count_sheet"], "Operational margin review only. Do not describe as food-safety or regulatory review.", "pricing_margin_review"),
  seed("daypart_labor_unknown", "Daypart Labor Unknown", ["operational_efficiency", "financial_visibility"], "Trigger when labor cost cannot be reviewed by daypart.", null, "boolean", "Restaurant labor pressure often hides in specific dayparts.", ["pos_manual_export", "quickbooks_manual_export", "daily_sales_log"], "Scheduling stays broad instead of matching the real pressure points.", "Install a daily sales and labor log by daypart.", ["daily_sales_and_labor_log"], "Manual POS or payroll exports are evidence inputs, not live sync.", "capacity_review", true),
  seed("menu_item_margin_missing", "Menu Item Margin Missing", ["financial_visibility"], "Trigger when top-selling menu items do not have known item-level margin.", null, "boolean", "Top sellers can still weaken profit if item-level margin is unknown.", ["menu_engineering_sheet", "pos_manual_export", "manual_spreadsheet"], "High-volume low-margin items carry too much pressure.", "Run menu margin tracking for the top 20 items.", ["menu_margin_tracker"], "Keep recommendation operational. No accounting opinion.", "pricing_margin_review", true),
  seed("void_comp_pattern_unreviewed", "Void / Comp Pattern Unreviewed", ["financial_visibility", "operational_efficiency"], "Trigger when voids or comps exceed 3% of sales or are not reviewed weekly.", 3, "percent", "Voids and comps can point to training, process, or expectation gaps.", ["pos_manual_export", "daily_sales_log"], "Small exceptions add up and blur true sales performance.", "Add weekly void/comp review to the manager close routine.", ["opening_closing_checklist", "daily_sales_and_labor_log"], "Do not imply fraud or legal findings without separate qualified review.", "standardize_operating_rhythm", true),
  seed("stockout_specials_untracked", "Stockouts Not Logged", ["operational_efficiency", "revenue_conversion"], "Trigger when unavailable items are mentioned but not logged.", null, "boolean", "Guests cannot buy what the team cannot keep available.", ["inventory_count_sheet", "daily_sales_log", "pos_manual_export"], "Stockouts reduce realized sales and create avoidable service friction.", "Install a stockout/backorder log for key menu items.", ["stockout_backorder_log", "inventory_count_sheet"], "If cannabis terms appear, route to cannabis logic instead of restaurant logic.", "inventory_control"),
  seed("vendor_price_change_unmapped", "Vendor Price Change Unmapped", ["financial_visibility"], "Trigger when supplier price changes are not mapped to menu pricing or portion changes.", null, "boolean", "Vendor price changes move faster than menu updates unless someone reviews them.", ["manual_spreadsheet", "menu_engineering_sheet", "pos_manual_export"], "Margin slips while the menu still looks unchanged.", "Review vendor changes against the menu margin tracker.", ["menu_margin_tracker"], "Manual supplier invoices are evidence only; no guarantee of complete vendor capture.", "vendor_review", true),
  seed("opening_closing_variance", "Opening / Closing Variance", ["operational_efficiency"], "Trigger when open or close steps vary by shift lead.", null, "boolean", "Variable open/close routines create inconsistent cash, quality, and readiness checks.", ["sop_document", "owner_interview", "weekly_review_log"], "Small misses become recurring service or cash-control friction.", "Install an opening / closing checklist and review exceptions weekly.", ["opening_closing_checklist"], "Do not describe as compliance certification or food-safety review.", "standardize_operating_rhythm"),
  seed("table_turn_signal_missing", "Table Turn Signal Missing", ["revenue_conversion", "operational_efficiency"], "Trigger when table turn or service-cycle timing is not reviewed during busy periods.", null, "boolean", "Busy service can still underperform if the bottleneck is not visible.", ["pos_manual_export", "daily_sales_log", "owner_interview"], "Revenue capacity gets capped by a process step no one is measuring.", "Log table turn or service-cycle notes during peak periods.", ["daily_sales_and_labor_log"], "Use as operating visibility, not a staffing law or wage review.", "capacity_review"),
  seed("repeat_guest_signal_missing", "Repeat Guest Signal Missing", ["demand_generation", "revenue_conversion"], "Trigger when repeat guest or loyalty movement is not reviewed monthly.", null, "boolean", "Repeat guest movement shows whether demand is turning into a base.", ["pos_manual_export", "manual_spreadsheet", "weekly_review_log"], "The restaurant keeps buying attention instead of learning what brings guests back.", "Add repeat-guest notes to the weekly scoreboard.", ["weekly_scoreboard"], "If loyalty platform exports conflict with POS exports, flag for source review.", "source_of_truth_review", true),
  seed("cash_drop_variance_unexplained", "Cash Drop Variance Unexplained", ["financial_visibility"], "Trigger when cash variance occurs without a documented reason code.", null, "boolean", "Unexplained cash variance makes closeout visibility weaker.", ["daily_sales_log", "manual_spreadsheet", "pos_manual_export"], "Cash handling questions stay unresolved and repeat.", "Install daily cash count and exception notes.", ["daily_cash_count", "opening_closing_checklist"], "Operational cash visibility only. Not an accounting or legal determination.", "tighten_cash_visibility", true),
  seed("catering_pipeline_untracked", "Catering Pipeline Untracked", ["demand_generation", "revenue_conversion"], "Trigger when catering or large-order inquiries are handled without pipeline tracking.", null, "boolean", "Large opportunities need clearer follow-up than normal walk-in demand.", ["manual_spreadsheet", "owner_interview", "hubspot_manual_export"], "High-value inquiries go quiet because the next step is not visible.", "Install a proposal pipeline tracker for catering or large orders.", ["proposal_pipeline_tracker", "follow_up_log"], "Use only if the restaurant actually pursues catering/large-order revenue.", "tighten_follow_up"),
  seed("training_handoff_inconsistent", "Training Handoff Inconsistent", ["operational_efficiency", "owner_independence"], "Trigger when new staff learn shift routines only by shadowing.", null, "boolean", "Shadowing without a simple training standard makes execution depend on who trained them.", ["sop_document", "owner_interview", "weekly_review_log"], "Service quality varies and managers keep answering the same questions.", "Document first-week routines and handoff checks.", ["opening_closing_checklist"], "Do not frame as HR, wage, or employment classification guidance.", "training_handoff"),
  seed("weekly_manager_review_missing", "Weekly Manager Review Missing", ["owner_independence", "operational_efficiency"], "Trigger when managers do not review sales, labor, food cost, and exceptions weekly.", null, "boolean", "Without a weekly manager review, restaurant pressure reaches the owner late.", ["weekly_review_log", "daily_sales_log", "owner_interview"], "The owner becomes the only person connecting the signals.", "Install a weekly scoreboard and manager review block.", ["weekly_scoreboard", "daily_sales_and_labor_log"], "Use as operating cadence guidance, not performance management advice.", "standardize_operating_rhythm"),
  seed("waste_reason_missing", "Waste Reason Missing", ["financial_visibility", "operational_efficiency"], "Trigger when waste is recorded without reason codes.", null, "boolean", "Waste totals without reasons do not show whether the issue is prep, ordering, spoilage, or training.", ["inventory_count_sheet", "daily_sales_log", "manual_spreadsheet"], "The team sees waste but cannot decide what to change.", "Add reason codes to inventory count or daily close records.", ["inventory_count_sheet", "opening_closing_checklist"], "Avoid food-safety claims. This is operating visibility only.", "inventory_control"),
  seed("promotions_not_margin_checked", "Promotions Not Margin Checked", ["demand_generation", "financial_visibility"], "Trigger when promotions are run without margin review.", null, "boolean", "Promotions can increase traffic while weakening profit if margin is not checked.", ["menu_engineering_sheet", "pos_manual_export", "manual_spreadsheet"], "Marketing activity may create busy shifts without financial clarity.", "Review promotional items in the menu margin tracker.", ["menu_margin_tracker", "channel_concentration_review"], "Do not present as ROI guarantee.", "pricing_margin_review"),
  seed("supplier_dependency_high", "Supplier Dependency High", ["operational_efficiency", "financial_visibility"], "Trigger when a single supplier supports more than 50% of key inputs without a fallback noted.", 50, "percent", "Heavy supplier dependency creates avoidable operating fragility.", ["manual_spreadsheet", "inventory_count_sheet", "owner_interview"], "A delay or price change can pressure the menu before the owner can react.", "Add supplier concentration review to monthly operating review.", ["inventory_count_sheet", "channel_concentration_review"], "Operational dependency visibility only, not contract or legal review.", "vendor_review"),
  seed("guest_issue_not_closed", "Guest Issue Not Closed", ["revenue_conversion", "operational_efficiency"], "Trigger when guest issues have no owner or closeout date.", null, "boolean", "Guest issues need a clear owner so they do not become repeat friction.", ["manual_spreadsheet", "owner_interview", "weekly_review_log"], "Repeat complaints build because the process fix is unclear.", "Install a support response tracker for recurring guest issues.", ["customer_support_response_tracker"], "Do not imply consumer-protection advice.", "customer_experience_review"),
];

const RETAIL_EXPANSION: ExpansionSeed[] = [
  seed("top_sku_reorder_missing", "Top SKU Reorder Missing", ["operational_efficiency", "financial_visibility"], "Trigger when top SKUs have no reorder point or reorder owner.", null, "boolean", "Top sellers need visible reorder discipline so sales are not lost to preventable stockouts.", ["inventory_count_sheet", "pos_manual_export", "manual_spreadsheet"], "Demand turns into stockouts instead of revenue.", "Install inventory count and stockout/backorder logs for top SKUs.", ["inventory_count_sheet", "stockout_backorder_log"], "Operational inventory only. No valuation or tax treatment.", "inventory_control", true),
  seed("stockout_pattern_unreviewed", "Stockout Pattern Unreviewed", ["revenue_conversion", "operational_efficiency"], "Trigger when stockouts occur more than three times in a month without review.", 3, "count", "Recurring stockouts show demand the store is not capturing.", ["inventory_count_sheet", "pos_manual_export", "owner_interview"], "Customers learn the store may not have what they came for.", "Review stockout frequency by SKU and supplier.", ["stockout_backorder_log"], "If POS and manual logs conflict, flag for source-of-truth review.", "source_of_truth_review", true),
  seed("category_margin_gap", "Category Margin Gap", ["financial_visibility"], "Trigger when margin is not visible by category for the top categories.", null, "boolean", "Category margin helps the owner see which revenue is actually useful.", ["category_margin_report", "pos_manual_export", "manual_spreadsheet"], "Buying and markdown decisions drift toward sales volume instead of contribution.", "Install a category margin review cadence.", ["category_margin_review"], "Avoid accounting or inventory valuation language.", "pricing_margin_review", true),
  seed("markdown_reason_missing", "Markdown Reason Missing", ["financial_visibility", "operational_efficiency"], "Trigger when markdowns are taken without reason codes.", null, "boolean", "Markdowns without reasons do not show whether the issue is buying, pricing, seasonality, or merchandising.", ["pos_manual_export", "manual_spreadsheet", "category_margin_report"], "The same inventory mistakes repeat next buying cycle.", "Add markdown reason codes to category review.", ["category_margin_review"], "Do not imply merchandising outcomes are promised.", "pricing_margin_review"),
  seed("returns_reason_missing", "Return Reason Missing", ["revenue_conversion", "operational_efficiency"], "Trigger when returns are logged without a useful reason.", null, "boolean", "Returns without reasons hide product, fit, expectation, or training issues.", ["return_log", "pos_manual_export", "manual_spreadsheet"], "Realized revenue and customer trust weaken without a visible pattern.", "Install a return reason log and weekly category review.", ["return_reason_log", "category_margin_review"], "Operational experience review only.", "customer_experience_review"),
  seed("vendor_lead_time_unknown", "Vendor Lead Time Unknown", ["operational_efficiency"], "Trigger when vendor lead time is unknown for key products.", null, "boolean", "Unknown lead time makes reorder decisions reactive.", ["inventory_count_sheet", "manual_spreadsheet", "owner_interview"], "The business either overbuys or runs out when demand changes.", "Add lead time fields to inventory count and stockout logs.", ["inventory_count_sheet", "stockout_backorder_log"], "Operational vendor visibility only, not contract review.", "vendor_review"),
  seed("cash_close_not_standard", "Cash Close Not Standard", ["financial_visibility", "operational_efficiency"], "Trigger when cash close steps vary by staff member.", null, "boolean", "A standard close routine protects daily visibility.", ["daily_sales_log", "weekly_review_log", "pos_manual_export"], "Daily numbers become harder to trust when closeout steps vary.", "Install opening / closing checklist and daily cash count.", ["opening_closing_checklist", "daily_cash_count"], "Not a formal accounting or loss-prevention determination.", "tighten_cash_visibility", true),
  seed("traffic_conversion_unknown", "Traffic Conversion Unknown", ["demand_generation", "revenue_conversion"], "Trigger when store traffic or inquiries are not compared with sales movement.", null, "boolean", "Retail demand needs conversion context, not just foot traffic or clicks.", ["manual_spreadsheet", "pos_manual_export", "google_analytics_manual_export"], "The owner cannot tell whether demand or conversion is the slipping gear.", "Track traffic/inquiries beside sales by period.", ["weekly_scoreboard", "lead_tracking_sheet"], "If analytics and POS disagree, use conflict review before interpretation.", "source_of_truth_review", true),
  seed("repeat_customer_signal_missing", "Repeat Customer Signal Missing", ["demand_generation", "revenue_conversion"], "Trigger when repeat-customer movement is not reviewed at least quarterly.", null, "boolean", "Repeat customer signals show whether the store is building a base.", ["pos_manual_export", "manual_spreadsheet", "weekly_review_log"], "Demand costs rise when the business cannot see returning customer behavior.", "Add repeat customer review to the quarterly channel review.", ["repeat_purchase_tracker", "channel_concentration_review"], "Operational visibility only; no privacy or loyalty-program advice.", "channel_concentration_review", true),
  seed("assortment_review_missing", "Assortment Review Missing", ["operational_efficiency", "financial_visibility"], "Trigger when assortment decisions are not reviewed by sales velocity and margin.", null, "boolean", "Assortment without velocity and margin review ties cash to weak categories.", ["category_margin_report", "inventory_count_sheet", "pos_manual_export"], "Slow categories occupy space that could support stronger sellers.", "Run category margin and dead-stock review monthly.", ["category_margin_review", "dead_stock_liquidation_plan"], "Do not present as valuation or accounting review.", "inventory_control"),
  seed("employee_product_questions_repeat", "Repeat Product Questions", ["operational_efficiency", "owner_independence"], "Trigger when staff repeatedly ask the same product/process questions.", null, "boolean", "Repeat questions show where the operating standard is not clear.", ["owner_interview", "sop_document", "weekly_review_log"], "Owner or manager knowledge stays trapped in one person.", "Create a short checklist or training handoff for repeat questions.", ["opening_closing_checklist", "role_clarity_sheet"], "Avoid HR/training compliance claims.", "training_handoff"),
  seed("buying_decision_owner_only", "Buying Decision Owner-Only", ["owner_independence", "financial_visibility"], "Trigger when all buying decisions require owner approval.", null, "boolean", "Owner-only buying keeps the owner inside daily inventory decisions.", ["owner_interview", "inventory_count_sheet", "manual_spreadsheet"], "Ordering slows and the team cannot act within clear guardrails.", "Define reorder rights for low-risk recurring items.", ["role_clarity_sheet", "inventory_count_sheet"], "Decision rights are operating guardrails, not employment advice.", "training_handoff"),
  seed("promotion_channel_not_tagged", "Promotion Channel Not Tagged", ["demand_generation"], "Trigger when promotional sales cannot be tied to a channel or offer.", null, "boolean", "Promotion review needs channel context so the owner can see what moved demand.", ["pos_manual_export", "manual_spreadsheet", "meta_ads_manual_export"], "The business repeats promotions without learning which ones helped.", "Add channel and offer tags to weekly promotion review.", ["channel_concentration_review", "weekly_scoreboard"], "Do not claim attribution certainty from manual exports.", "channel_concentration_review", true),
  seed("supplier_cost_change_unreviewed", "Supplier Cost Change Unreviewed", ["financial_visibility"], "Trigger when supplier cost changes are not reviewed against retail price or margin.", null, "boolean", "Supplier cost changes can shrink margin before shelf prices change.", ["manual_spreadsheet", "category_margin_report", "pos_manual_export"], "The owner sees revenue but not the cost pressure underneath.", "Review cost changes against category margin before reorder.", ["category_margin_review"], "Manual cost records may conflict; use source review where needed.", "source_of_truth_review", true),
  seed("online_store_handoff_gap", "Online Store Handoff Gap", ["operational_efficiency", "revenue_conversion"], "Trigger when online orders or pickups have unclear handoff ownership.", null, "boolean", "Retail handoffs need clear ownership so orders do not stall between systems and staff.", ["fulfillment_log", "pos_manual_export", "owner_interview"], "Customer experience weakens because the next step is assumed.", "Document pickup/online handoff and assign the owner role.", ["client_onboarding_checklist", "role_clarity_sheet"], "Use for retail operations only, not carrier or platform guarantees.", "training_handoff"),
  seed("shrink_signal_unreviewed", "Shrink Signal Unreviewed", ["financial_visibility", "operational_efficiency"], "Trigger when inventory variance exists without regular review.", null, "boolean", "Inventory variance needs review so cash, buying, and operations stay connected.", ["inventory_count_sheet", "pos_manual_export", "manual_spreadsheet"], "Variance grows quietly and makes inventory decisions harder.", "Use inventory count sheet and review variance above tolerance.", ["inventory_count_sheet"], "Do not imply fraud, legal, or insurance conclusions.", "inventory_control", true),
  seed("store_priority_overload", "Store Priority Overload", ["owner_independence", "operational_efficiency"], "Trigger when more than five store priorities are active at once.", 5, "count", "Too many active priorities makes store execution noisy.", ["weekly_review_log", "owner_interview", "manual_spreadsheet"], "Staff cannot tell what matters most this week.", "Reduce to the few priorities tied to sales, margin, or service stability.", ["weekly_scoreboard"], "Use as owner review, not staff performance judgment.", "capacity_review"),
];

const PROFESSIONAL_EXPANSION: ExpansionSeed[] = [
  seed("proposal_follow_up_missing", "Proposal Follow-Up Missing", ["revenue_conversion"], "Trigger when open proposals have no next follow-up date.", null, "boolean", "Professional-service proposals stall quickly without next-step ownership.", ["pipedrive_manual_export", "manual_spreadsheet", "owner_interview"], "Good-fit work may die quietly after the proposal is sent.", "Install proposal pipeline tracker and follow-up log.", ["proposal_pipeline_tracker", "follow_up_log"], "Pipeline visibility only; no revenue forecast guarantee.", "tighten_follow_up", true),
  seed("scope_boundary_unclear", "Scope Boundary Unclear", ["revenue_conversion", "financial_visibility"], "Trigger when active engagements have unclear deliverables or change process.", null, "boolean", "Unclear scope turns normal client requests into margin pressure.", ["engagement_letter", "scope_change_log", "owner_interview"], "The team absorbs extra work that is not reviewed or priced.", "Install scope change log and onboarding checklist.", ["scope_change_log", "client_onboarding_checklist"], "Not legal contract review. Use qualified counsel where required.", "pricing_margin_review"),
  seed("utilization_source_conflict", "Utilization Source Conflict", ["financial_visibility", "operational_efficiency"], "Trigger when time records and owner estimates disagree by more than 10%.", 10, "percent", "When utilization sources disagree, capacity decisions become guesswork.", ["utilization_log", "manual_spreadsheet", "owner_interview"], "The owner may hire, sell, or delegate from an unreliable capacity picture.", "Review source-of-truth before using utilization for planning.", ["utilization_tracker"], "Route to Source-of-Truth Conflict Flags™ for admin review. Do not auto-publish.", "source_of_truth_review", true),
  seed("client_onboarding_incomplete", "Client Onboarding Incomplete", ["revenue_conversion", "operational_efficiency"], "Trigger when new client onboarding steps are undocumented or skipped.", null, "boolean", "Onboarding gaps create friction before delivery work even begins.", ["sop_document", "engagement_letter", "owner_interview"], "Early confusion increases rework and weakens client confidence.", "Install a client onboarding checklist for new engagements.", ["client_onboarding_checklist"], "Operational onboarding only, not contract or legal advice.", "standardize_operating_rhythm"),
  seed("ar_follow_up_gap", "A/R Follow-Up Gap", ["financial_visibility"], "Trigger when invoices over 30 days have no next follow-up noted.", 30, "days", "Receivables need a visible follow-up rhythm so earned revenue becomes usable cash.", ["ar_aging_report", "quickbooks_manual_export", "manual_spreadsheet"], "Cash availability weakens while completed work sits unpaid.", "Install weekly A/R review and follow-up cadence.", ["ar_aging_review", "weekly_scoreboard"], "Not collections, legal, or accounting advice.", "tighten_cash_visibility", true),
  seed("owner_delivery_dependency", "Owner Delivery Dependency", ["owner_independence", "operational_efficiency"], "Trigger when the owner is required to deliver or approve most client work.", null, "boolean", "Owner-dependent delivery caps capacity and slows decisions.", ["owner_interview", "utilization_log", "sop_document"], "Growth pressure lands on the owner instead of a repeatable delivery system.", "Run owner time audit and define decision rights for delivery.", ["owner_time_audit_worksheet", "role_clarity_sheet"], "Separate owner judgment from work that can be trained.", "capacity_review"),
  seed("client_issue_response_unknown", "Client Issue Response Unknown", ["operational_efficiency", "revenue_conversion"], "Trigger when client issues have no response-time or owner tracking.", null, "boolean", "Client issues need a visible owner and response rhythm.", ["manual_spreadsheet", "owner_interview", "weekly_review_log"], "Small issues become retention risk when no one owns follow-through.", "Install customer support response tracker for client issues.", ["customer_support_response_tracker"], "Do not imply SLA, warranty, or legal claims.", "customer_experience_review"),
  seed("capacity_pipeline_mismatch", "Capacity / Pipeline Mismatch", ["revenue_conversion", "operational_efficiency"], "Trigger when near-term pipeline exceeds available delivery capacity by more than 20%.", 20, "percent", "Pipeline without capacity visibility creates delivery pressure.", ["pipedrive_manual_export", "utilization_log", "manual_spreadsheet"], "The business sells work the operating system cannot absorb cleanly.", "Review proposal pipeline beside utilization before committing dates.", ["proposal_pipeline_tracker", "utilization_tracker"], "Decision-support only, not staffing or HR advice.", "capacity_review", true),
  seed("handoff_between_sales_delivery_missing", "Sales-to-Delivery Handoff Missing", ["revenue_conversion", "operational_efficiency"], "Trigger when won work has no documented handoff from sales to delivery.", null, "boolean", "Won work needs a clean handoff so client promises become delivery standards.", ["sop_document", "scope_change_log", "owner_interview"], "Delivery starts with missing context and rework follows.", "Install onboarding and handoff checklist for won work.", ["client_onboarding_checklist"], "Operational handoff only. Not contract review.", "training_handoff"),
  seed("service_line_margin_unknown", "Service Line Margin Unknown", ["financial_visibility"], "Trigger when margin is not reviewed by service line or engagement type.", null, "boolean", "Different service lines can look equally busy while producing different margin.", ["quickbooks_manual_export", "freshbooks_manual_export", "manual_spreadsheet"], "The owner may sell more of the work that weakens capacity.", "Add service-line margin review to the weekly or monthly scoreboard.", ["weekly_scoreboard", "utilization_tracker"], "Manual accounting exports are evidence inputs, not accounting treatment.", "pricing_margin_review", true),
  seed("knowledge_base_missing", "Knowledge Base Missing", ["owner_independence", "operational_efficiency"], "Trigger when repeat delivery questions have no written answer or training step.", null, "boolean", "Repeat questions show where delivery knowledge is trapped in people.", ["sop_document", "owner_interview", "weekly_review_log"], "The same explanations repeat and owner time stays consumed.", "Document the top repeat questions as training steps.", ["role_clarity_sheet"], "Operational training aid only.", "training_handoff"),
  seed("client_concentration_high", "Client Concentration High", ["financial_visibility", "demand_generation"], "Trigger when one client contributes more than 35% of revenue.", 35, "percent", "Client concentration makes revenue stability depend heavily on one relationship.", ["quickbooks_manual_export", "manual_spreadsheet", "pipedrive_manual_export"], "A single change can pressure cash, staffing, and owner attention.", "Run channel/client concentration review and plan one diversification step.", ["channel_concentration_review"], "Operational concentration visibility only, not investor or valuation advice.", "channel_concentration_review", true),
  seed("proposal_win_loss_not_reviewed", "Win/Loss Not Reviewed", ["demand_generation", "revenue_conversion"], "Trigger when proposal outcomes are not reviewed monthly.", null, "boolean", "Win/loss review shows whether demand, offer fit, or follow-up is slipping.", ["manual_spreadsheet", "pipedrive_manual_export", "owner_interview"], "The same sales friction repeats without becoming visible.", "Review proposal stages and outcomes monthly.", ["proposal_pipeline_tracker"], "No close-rate guarantee or sales forecast claim.", "tighten_follow_up"),
  seed("delivery_standard_varies", "Delivery Standard Varies", ["operational_efficiency"], "Trigger when similar engagements are delivered in materially different ways.", null, "boolean", "Variable delivery makes quality, timing, and margin harder to manage.", ["sop_document", "weekly_review_log", "owner_interview"], "The team recreates delivery instead of improving a standard.", "Write the first version of the recurring delivery workflow.", ["client_onboarding_checklist", "role_clarity_sheet"], "Operational standard only, not professional-service legal advice.", "standardize_operating_rhythm"),
  seed("billing_trigger_unclear", "Billing Trigger Unclear", ["financial_visibility", "operational_efficiency"], "Trigger when the team cannot name what event triggers billing or invoicing.", null, "boolean", "Unclear billing triggers delay cash after work is complete.", ["engagement_letter", "ar_aging_report", "owner_interview"], "Finished work sits before invoicing or follow-up begins.", "Document billing triggers and add them to onboarding or delivery checklist.", ["ar_aging_review", "client_onboarding_checklist"], "Not accounting or legal advice.", "tighten_cash_visibility"),
  seed("admin_work_owner_hidden", "Admin Work Hidden on Owner Calendar", ["owner_independence"], "Trigger when recurring admin work is not visible in the owner time review.", null, "boolean", "Hidden admin work quietly consumes owner capacity.", ["manual_spreadsheet", "owner_interview", "weekly_review_log"], "The owner stays overloaded without a clear delegation target.", "Run owner time audit and tag delegable admin work.", ["owner_time_audit_worksheet", "role_clarity_sheet"], "Avoid HR/job-classification advice.", "capacity_review"),
  seed("source_records_for_revenue_disagree", "Revenue Records Disagree", ["financial_visibility"], "Trigger when CRM/pipeline revenue and accounting revenue disagree materially for the same period.", 5, "percent", "Revenue records need a clear source-of-truth before the owner acts on them.", ["quickbooks_manual_export", "pipedrive_manual_export", "manual_spreadsheet"], "The owner may read pipeline as revenue or miss cash timing pressure.", "Flag for source-of-truth conflict review before interpretation.", ["weekly_scoreboard"], "Route to Source-of-Truth Conflict Flags™ for admin review. Do not auto-publish.", "source_of_truth_review", true),
];

const ECOMMERCE_EXPANSION: ExpansionSeed[] = [
  seed("fulfillment_backlog_visible_late", "Fulfillment Backlog Visible Late", ["operational_efficiency", "revenue_conversion"], "Trigger when open orders older than 2 days are not reviewed daily.", 2, "days", "Late backlog visibility creates avoidable customer friction.", ["fulfillment_log", "shopify_manual_export", "manual_spreadsheet"], "Support pressure and refund risk rise before the owner sees the backlog.", "Install fulfillment SLA tracker and daily backlog review.", ["fulfillment_sla_tracker"], "Manual platform exports only; no live sync claim.", "standardize_operating_rhythm", true),
  seed("return_reason_unstructured", "Return Reason Unstructured", ["operational_efficiency", "revenue_conversion"], "Trigger when returns are accepted without structured reason codes.", null, "boolean", "Return reasons show whether the issue is product, listing, sizing, or fulfillment.", ["return_log", "shopify_manual_export", "amazon_seller_manual_export"], "The business keeps refunding symptoms without seeing the slipping step.", "Install return reason log and review top SKUs weekly.", ["return_reason_log"], "Customer experience visibility only.", "customer_experience_review"),
  seed("paid_channel_concentration_high", "Paid Channel Concentration High", ["demand_generation", "financial_visibility"], "Trigger when one paid channel contributes more than 60% of orders or tracked revenue.", 60, "percent", "Paid-channel concentration makes demand more fragile if ad costs or platform rules change.", ["meta_ads_manual_export", "google_analytics_manual_export", "shopify_manual_export"], "Demand cost can rise faster than the owner can respond.", "Run channel concentration review and identify one diversification step.", ["channel_concentration_review"], "No attribution certainty or ad performance guarantee.", "channel_concentration_review", true),
  seed("listing_conversion_unknown", "Listing Conversion Unknown", ["demand_generation", "revenue_conversion"], "Trigger when top product listing views and orders are not reviewed together.", null, "boolean", "Listing traffic without conversion context hides whether demand or offer clarity is slipping.", ["shopify_manual_export", "google_analytics_manual_export", "manual_spreadsheet"], "The owner changes ads when the product page may be the issue.", "Review top listings with traffic, conversion, and return reason notes.", ["weekly_scoreboard", "return_reason_log"], "Manual exports may conflict; use source review where needed.", "source_of_truth_review", true),
  seed("inventory_sync_manual_mismatch", "Manual Inventory Mismatch", ["operational_efficiency", "financial_visibility"], "Trigger when manual inventory counts and platform quantities disagree by more than 5%.", 5, "percent", "Inventory mismatch makes stockout and reorder decisions unreliable.", ["inventory_count_sheet", "shopify_manual_export", "woocommerce_manual_export"], "The site may sell unavailable items or hide sellable stock.", "Use inventory count sheet and stockout/backorder log until source is clear.", ["inventory_count_sheet", "stockout_backorder_log"], "No live inventory sync claim. Manual source review only.", "source_of_truth_review", true),
  seed("customer_support_backlog_unknown", "Support Backlog Unknown", ["operational_efficiency", "revenue_conversion"], "Trigger when open support requests are not counted weekly.", null, "boolean", "Support backlog hides order friction and customer experience pressure.", ["weekly_review_log", "manual_spreadsheet", "owner_interview"], "Slow response turns operational misses into refunds, reviews, or lost repeat purchase.", "Install customer support response tracker.", ["customer_support_response_tracker"], "Not warranty, legal, or consumer-protection advice.", "customer_experience_review"),
  seed("repeat_purchase_not_segmented", "Repeat Purchase Not Segmented", ["demand_generation", "revenue_conversion"], "Trigger when repeat purchase is not reviewed by product or customer segment.", null, "boolean", "Segmented repeat purchase shows where the customer base is actually forming.", ["manual_spreadsheet", "shopify_manual_export", "weekly_review_log"], "The business may keep buying first orders without building stability.", "Install repeat purchase tracker by segment.", ["repeat_purchase_tracker"], "No marketing outcome guarantee.", "channel_concentration_review", true),
  seed("shipping_cost_not_margin_checked", "Shipping Cost Not Margin Checked", ["financial_visibility"], "Trigger when shipping cost changes are not compared with product margin.", null, "boolean", "Shipping cost can quietly erase product contribution.", ["shipping_carrier_export", "shopify_manual_export", "manual_spreadsheet"], "Revenue looks stable while net contribution slips.", "Add shipping cost review to weekly margin review.", ["weekly_scoreboard"], "Operational cost visibility only; no accounting treatment.", "pricing_margin_review", true),
  seed("stockout_backorder_no_owner", "Stockout / Backorder No Owner", ["operational_efficiency", "owner_independence"], "Trigger when stockouts or backorders have no assigned owner.", null, "boolean", "Stockouts need ownership so resolution does not sit between purchasing, support, and fulfillment.", ["manual_spreadsheet", "inventory_count_sheet", "owner_interview"], "Customers wait while the team assumes someone else owns it.", "Install stockout/backorder log with owner and resolution fields.", ["stockout_backorder_log"], "Operational ownership only.", "inventory_control"),
  seed("sku_profitability_unknown", "SKU Profitability Unknown", ["financial_visibility"], "Trigger when top SKUs are not reviewed for contribution after returns and shipping.", null, "boolean", "SKU profitability can differ from sales rank once returns and shipping are visible.", ["shopify_manual_export", "return_log", "shipping_carrier_export"], "The owner may scale SKUs that weaken net contribution.", "Review top SKUs with return and shipping context.", ["return_reason_log", "weekly_scoreboard"], "Use operating-contribution language only.", "pricing_margin_review", true),
  seed("marketplace_dependency_high", "Marketplace Dependency High", ["demand_generation", "financial_visibility"], "Trigger when one marketplace or storefront contributes more than 70% of orders.", 70, "percent", "Marketplace dependency puts demand pressure on one platform.", ["amazon_seller_manual_export", "shopify_manual_export", "manual_spreadsheet"], "Platform changes can affect revenue before the owner has a fallback.", "Run channel concentration review and identify one backup channel.", ["channel_concentration_review"], "Operational concentration review only.", "channel_concentration_review", true),
  seed("refund_approval_owner_only", "Refund Approval Owner-Only", ["owner_independence", "operational_efficiency"], "Trigger when common refunds require owner approval every time.", null, "boolean", "Owner-only refund approval slows response and keeps routine decisions on the owner.", ["manual_spreadsheet", "owner_interview", "return_log"], "The owner remains in the middle of repeat support decisions.", "Define refund decision rights for common cases.", ["role_clarity_sheet", "customer_support_response_tracker"], "Not legal, warranty, or policy advice.", "training_handoff"),
  seed("fulfillment_training_varies", "Fulfillment Training Varies", ["operational_efficiency"], "Trigger when packing or fulfillment steps vary by person.", null, "boolean", "Variable fulfillment steps create avoidable errors and support pressure.", ["fulfillment_log", "sop_document", "owner_interview"], "Errors repeat because the standard is not written.", "Document the fulfillment checklist for the common order flow.", ["opening_closing_checklist"], "Operational process only.", "training_handoff"),
  seed("product_launch_review_missing", "Product Launch Review Missing", ["demand_generation", "financial_visibility"], "Trigger when new product launches are not reviewed after 30 days.", 30, "days", "New products need a review rhythm so early demand, margin, and returns are visible.", ["shopify_manual_export", "return_log", "manual_spreadsheet"], "Weak launch signals stay hidden until inventory or ad spend piles up.", "Add launch review to weekly scoreboard and channel review.", ["weekly_scoreboard", "channel_concentration_review"], "No sales or product-market guarantee.", "standardize_operating_rhythm"),
  seed("cart_issue_signal_missing", "Cart Issue Signal Missing", ["revenue_conversion", "operational_efficiency"], "Trigger when checkout or cart issues are mentioned but not logged.", null, "boolean", "Checkout friction needs a record before the owner can see the pattern.", ["manual_spreadsheet", "google_analytics_manual_export", "owner_interview"], "Buyers leak out and support hears about it before the owner does.", "Track cart/support issues and review weekly.", ["customer_support_response_tracker", "weekly_scoreboard"], "Manual analytics only; no automatic site monitoring claim.", "customer_experience_review", true),
  seed("supplier_delay_not_logged", "Supplier Delay Not Logged", ["operational_efficiency", "financial_visibility"], "Trigger when supplier delays affect fulfillment but are not logged.", null, "boolean", "Supplier delay patterns show whether purchasing or vendor review is needed.", ["manual_spreadsheet", "inventory_count_sheet", "owner_interview"], "Backorders repeat and support pressure rises.", "Log supplier delays beside stockout/backorder records.", ["stockout_backorder_log"], "Operational vendor visibility only.", "vendor_review"),
  seed("dashboard_numbers_disagree", "Dashboard Numbers Disagree", ["financial_visibility"], "Trigger when storefront, payment, and spreadsheet totals disagree for the same period.", 5, "percent", "E-commerce dashboards can tell different stories unless the review source is clear.", ["shopify_manual_export", "stripe_manual_export", "manual_spreadsheet"], "The owner may act on whichever number appears first.", "Flag for source-of-truth conflict review before dashboard interpretation.", ["weekly_scoreboard"], "Route to Source-of-Truth Conflict Flags™ for admin review. Do not auto-publish.", "source_of_truth_review", true),
];

const EXPANSION_SEEDS: Record<DepthIndustryKey, ExpansionSeed[]> = {
  general_small_business: GENERAL_EXPANSION,
  restaurant_food_service: RESTAURANT_EXPANSION,
  retail: RETAIL_EXPANSION,
  professional_services: PROFESSIONAL_EXPANSION,
  ecommerce_online_retail: ECOMMERCE_EXPANSION,
};

const PREFIX_BY_INDUSTRY: Record<DepthIndustryKey, string> = {
  general_small_business: "general",
  restaurant_food_service: "restaurant",
  retail: "retail",
  professional_services: "professional",
  ecommerce_online_retail: "ecommerce",
};

function seed(
  slug: string,
  label: string,
  gears: ReadonlyArray<DepthGearKey>,
  trigger_rule: string,
  threshold_value: number | null,
  threshold_unit: DepthMetricDefinition["threshold_unit"],
  client_safe_explanation: string,
  evidence_examples: ReadonlyArray<DepthEvidenceSourceType>,
  forward_risk: string,
  repair_map_recommendation: string,
  recommended_quick_start_templates: ReadonlyArray<QuickStartTemplateKey>,
  admin_only_note: string,
  repair_trigger: RepairMapTriggerKey,
  source_of_truth_conflict_capable = false,
): ExpansionSeed {
  return {
    slug,
    label,
    gears,
    trigger_rule,
    threshold_value,
    threshold_unit,
    client_safe_explanation,
    evidence_examples,
    forward_risk,
    repair_map_recommendation,
    recommended_quick_start_templates,
    admin_only_note,
    repair_trigger,
    source_of_truth_conflict_capable,
  };
}

function metricKey(industry: DepthIndustryKey, slug: string): string {
  return `${PREFIX_BY_INDUSTRY[industry]}.p89.${slug}`;
}

export const INDUSTRY_DEPTH_EXPANSION_METRICS: DepthMetricDefinition[] =
  Object.entries(EXPANSION_SEEDS).flatMap(([industry, seeds]) =>
    seeds.map((s) => ({
      metric_key: metricKey(industry as DepthIndustryKey, s.slug),
      industry_key: industry as DepthIndustryKey,
      label: s.label,
      gears: s.gears,
      trigger_rule: s.trigger_rule,
      threshold_value: s.threshold_value,
      threshold_unit: s.threshold_unit,
      client_safe_explanation: s.client_safe_explanation,
      evidence_examples: s.evidence_examples,
      forward_risk: s.forward_risk,
      repair_map_recommendation: s.repair_map_recommendation,
      recommended_quick_start_templates: s.recommended_quick_start_templates,
    })),
  );

export const INDUSTRY_DEPTH_ADMIN_ANNOTATIONS: DepthMetricAdminAnnotation[] =
  Object.entries(EXPANSION_SEEDS).flatMap(([industry, seeds]) =>
    seeds.map((s) => ({
      metric_key: metricKey(industry as DepthIndustryKey, s.slug),
      admin_only_note: s.admin_only_note,
      repair_trigger: s.repair_trigger,
      source_of_truth_conflict_capable: Boolean(s.source_of_truth_conflict_capable),
      repair_map_trigger_behavior: "additive_admin_annotation_only",
    })),
  );

export const APPROVED_RGS_POSITIONING_SENTENCE =
  "RGS builds the operating structure owners use to see what is slipping, decide what to fix, and run the business with more control.";
