import type { RgsToolInterlockContract } from "./types";

const COMMON_SAFETY = [
  "No frontend secrets or service-role keys.",
  "No cross-client data access.",
  "No admin-only notes in client-visible fields.",
  "No legal, tax, accounting, compliance, fiduciary, valuation, revenue, profit, growth, lead, ROI, or outcome promises.",
  "Deterministic scoring remains the source of truth where scoring is involved.",
];

export const RGS_TOOL_INTERLOCK_REGISTRY: RgsToolInterlockContract[] = [
  {
    toolKey: "scorecard",
    displayName: "Public Business Stability Scorecard",
    stage: "public_funnel",
    customerScopeRequired: false,
    requiredInputs: [],
    optionalInputs: ["buyer_persona_signal"],
    producesSignals: ["scorecard_run", "deterministic_score", "gear_scores"],
    consumesSignals: [],
    downstreamTools: ["paid_diagnostic", "campaign_control_system"],
    upstreamTools: [],
    reportOutputs: ["first_pass_scorecard_result"],
    clientVisibleFields: ["total_score", "gear_scores", "first_pass_disclaimer"],
    adminOnlyFields: ["classifier_meta", "follow_up_email_status_detail"],
    approvalRequired: false,
    evidenceRequired: false,
    reengagementTriggers: ["high_volatility_score", "low_confidence_submission"],
    controlSystemMonitoringHooks: [],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["First-pass self-reported stability check, not a full Diagnostic."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "paid_diagnostic",
    displayName: "Paid Diagnostic",
    stage: "diagnostic",
    customerScopeRequired: true,
    requiredInputs: ["scorecard_run"],
    optionalInputs: ["evidence_record", "swot_signal", "buyer_persona_signal"],
    producesSignals: ["diagnostic_finding", "report_artifact", "repair_map_item"],
    consumesSignals: ["scorecard_run", "gear_scores", "evidence_record"],
    downstreamTools: ["repair_map", "implementation_roadmap", "reports_exports"],
    upstreamTools: ["scorecard", "evidence_vault"],
    reportOutputs: ["diagnostic_report", "stability_snapshot"],
    clientVisibleFields: ["client_safe_findings", "stability_snapshot", "priority_direction"],
    adminOnlyFields: ["admin_notes", "evidence_conflict_notes", "ai_draft_rationale"],
    approvalRequired: true,
    evidenceRequired: true,
    reengagementTriggers: ["diagnostic_stale", "new_major_risk"],
    controlSystemMonitoringHooks: ["gear_score_baseline", "evidence_gaps"],
    standaloneEligible: false,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Diagnostic produces direction; Implementation and Control System are separate unless purchased."],
    missingInputBehavior: "admin_review_required",
  },
  {
    toolKey: "owner_diagnostic_interview",
    displayName: "Diagnostic Interview",
    stage: "diagnostic",
    customerScopeRequired: true,
    requiredInputs: ["scorecard_run"],
    optionalInputs: ["evidence_record"],
    producesSignals: ["owner_interview_answer", "diagnostic_finding", "evidence_record"],
    consumesSignals: ["scorecard_run"],
    downstreamTools: ["paid_diagnostic", "swot_strategic_matrix", "repair_map"],
    upstreamTools: ["scorecard"],
    reportOutputs: ["diagnostic_interview_summary"],
    clientVisibleFields: ["answered_questions", "client_safe_summary"],
    adminOnlyFields: ["contradiction_notes", "confidence_notes", "admin_interpretation"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["unsupported_confident_claim", "missing_evidence"],
    controlSystemMonitoringHooks: ["owner_claim_confidence"],
    standaloneEligible: false,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Interview answers are evidence inputs; they do not replace verified documentation."],
    missingInputBehavior: "admin_review_required",
  },
  {
    toolKey: "swot_strategic_matrix",
    displayName: "SWOT Strategic Matrix",
    stage: "strategic_analysis",
    customerScopeRequired: true,
    requiredInputs: ["scorecard_run"],
    optionalInputs: ["diagnostic_finding", "evidence_record", "buyer_persona_signal"],
    producesSignals: ["swot_signal", "buyer_persona_signal", "priority_action"],
    consumesSignals: ["scorecard_run", "diagnostic_finding", "evidence_record"],
    downstreamTools: ["repair_map", "implementation_roadmap", "campaign_control_system", "buyer_persona_icp"],
    upstreamTools: ["scorecard", "paid_diagnostic", "evidence_vault"],
    reportOutputs: ["strategic_matrix_report"],
    clientVisibleFields: ["client_safe_summary", "approved_signals", "client_visible_items"],
    adminOnlyFields: ["admin_only_notes", "draft_items", "unapproved_signals"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["threat_escalation", "owner_independence_risk"],
    controlSystemMonitoringHooks: ["control_system_watch_item", "reengagement_trigger"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["SWOT signals inform review; they do not create automatic scope or change official score."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "buyer_persona_icp",
    displayName: "Buyer Persona / ICP",
    stage: "strategic_analysis",
    customerScopeRequired: true,
    requiredInputs: ["campaign_profile"],
    optionalInputs: ["swot_signal", "scorecard_run", "diagnostic_finding", "campaign_performance"],
    producesSignals: ["buyer_persona_signal", "campaign_profile"],
    consumesSignals: ["swot_signal", "campaign_performance"],
    downstreamTools: ["campaign_control_system", "reports_exports"],
    upstreamTools: ["swot_strategic_matrix", "campaign_control_system"],
    reportOutputs: ["persona_icp_report"],
    clientVisibleFields: ["persona_summary", "buyer_triggers", "objections", "channel_fit"],
    adminOnlyFields: ["admin_notes", "confidence_rationale"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["new_offer", "segment_mismatch"],
    controlSystemMonitoringHooks: ["audience_signal_quality"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Persona guidance is an operating hypothesis until validated by evidence or performance."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "evidence_vault",
    displayName: "Evidence Vault",
    stage: "diagnostic",
    customerScopeRequired: true,
    requiredInputs: [],
    optionalInputs: ["scorecard_run", "diagnostic_finding"],
    producesSignals: ["evidence_record"],
    consumesSignals: ["scorecard_run", "diagnostic_finding"],
    downstreamTools: ["paid_diagnostic", "repair_map", "reports_exports", "rgs_control_system"],
    upstreamTools: ["scorecard", "paid_diagnostic"],
    reportOutputs: ["evidence_review_summary"],
    clientVisibleFields: ["client_visible_files", "client_visible_evidence_notes"],
    adminOnlyFields: ["admin_evidence_notes", "review_decision_notes"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["stale_evidence", "missing_required_evidence"],
    controlSystemMonitoringHooks: ["evidence_decay", "evidence_refresh"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Evidence supports findings; it does not certify legal, tax, accounting, compliance, or valuation outcomes."],
    missingInputBehavior: "show_empty_state",
  },
  {
    toolKey: "repair_map",
    displayName: "Repair Map",
    stage: "repair_planning",
    customerScopeRequired: true,
    requiredInputs: ["diagnostic_finding"],
    optionalInputs: ["swot_signal", "evidence_record", "priority_action"],
    producesSignals: ["repair_map_item", "priority_action"],
    consumesSignals: ["diagnostic_finding", "swot_signal", "evidence_record"],
    downstreamTools: ["implementation_roadmap", "priority_action_tracker", "rgs_control_system"],
    upstreamTools: ["paid_diagnostic", "swot_strategic_matrix", "evidence_vault"],
    reportOutputs: ["repair_priority_report"],
    clientVisibleFields: ["client_safe_priority_explanation", "repair_map_items"],
    adminOnlyFields: ["admin_priority_note", "dependency_note", "owner_capacity_note"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["repair_scope_expansion", "blocked_foundation"],
    controlSystemMonitoringHooks: ["repair_completion", "open_priority_actions"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Repair Map recommends sequence; it does not install the work unless Implementation is in scope."],
    missingInputBehavior: "admin_review_required",
  },
  {
    toolKey: "implementation_roadmap",
    displayName: "Implementation Roadmap",
    stage: "implementation",
    customerScopeRequired: true,
    requiredInputs: ["repair_map_item"],
    optionalInputs: ["swot_signal", "evidence_record", "sop_record", "decision_rights_map"],
    producesSignals: ["implementation_step", "priority_action"],
    consumesSignals: ["repair_map_item", "swot_signal", "evidence_record"],
    downstreamTools: ["sop_training_bible", "workflow_process_mapping", "tool_assignment_training_tracker", "rgs_control_system"],
    upstreamTools: ["repair_map", "paid_diagnostic", "swot_strategic_matrix"],
    reportOutputs: ["implementation_plan"],
    clientVisibleFields: ["client_summary", "deliverable", "success_indicator"],
    adminOnlyFields: ["internal_notes", "dependency_notes", "admin_sequence_rationale"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["implementation_blocked", "scope_change_request"],
    controlSystemMonitoringHooks: ["implementation_progress", "blocked_items"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Implementation installs approved operating structure; ongoing operation remains the owner's responsibility."],
    missingInputBehavior: "admin_review_required",
  },
  {
    toolKey: "sop_training_bible",
    displayName: "SOP / Training Bible",
    stage: "implementation",
    customerScopeRequired: true,
    requiredInputs: ["workflow_map"],
    optionalInputs: ["decision_rights_map", "evidence_record", "implementation_step"],
    producesSignals: ["sop_record", "training_assignment"],
    consumesSignals: ["workflow_map", "decision_rights_map"],
    downstreamTools: ["tool_assignment_training_tracker", "rgs_control_system", "reports_exports"],
    upstreamTools: ["workflow_process_mapping", "decision_rights_accountability", "implementation_roadmap"],
    reportOutputs: ["sop_report", "training_checklist"],
    clientVisibleFields: ["approved_sop", "training_steps"],
    adminOnlyFields: ["admin_training_notes", "draft_sop_rationale"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["stale_sop", "training_gap"],
    controlSystemMonitoringHooks: ["sop_freshness", "training_completion"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["SOP guidance supports owner/team execution; RGS does not become the operator."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "workflow_process_mapping",
    displayName: "Workflow / Process Mapping",
    stage: "implementation",
    customerScopeRequired: true,
    requiredInputs: ["implementation_step"],
    optionalInputs: ["evidence_record", "sop_record"],
    producesSignals: ["workflow_map", "priority_action"],
    consumesSignals: ["implementation_step", "evidence_record"],
    downstreamTools: ["sop_training_bible", "decision_rights_accountability", "rgs_control_system"],
    upstreamTools: ["implementation_roadmap", "evidence_vault"],
    reportOutputs: ["workflow_map_report"],
    clientVisibleFields: ["process_steps", "handoff_summary"],
    adminOnlyFields: ["process_risk_notes", "admin_observations"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["process_drift", "handoff_failure"],
    controlSystemMonitoringHooks: ["process_drift", "handoff_quality"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Process maps describe operating structure; they do not certify compliance or replace professional review."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "decision_rights_accountability",
    displayName: "Decision Rights / Accountability",
    stage: "implementation",
    customerScopeRequired: true,
    requiredInputs: ["implementation_step"],
    optionalInputs: ["workflow_map", "owner_decision_signal"],
    producesSignals: ["decision_rights_map", "owner_decision_signal"],
    consumesSignals: ["implementation_step", "workflow_map"],
    downstreamTools: ["sop_training_bible", "owner_decision_dashboard", "rgs_control_system"],
    upstreamTools: ["implementation_roadmap", "workflow_process_mapping"],
    reportOutputs: ["accountability_map"],
    clientVisibleFields: ["roles", "decision_owner", "review_cadence"],
    adminOnlyFields: ["admin_owner_dependency_notes", "sensitive_team_notes"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["owner_bottleneck_returned", "unclear_accountability"],
    controlSystemMonitoringHooks: ["owner_dependency", "decision_latency"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Accountability mapping clarifies ownership; RGS does not take over decisions."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "tool_assignment_training_tracker",
    displayName: "Tool Assignment / Training Tracker",
    stage: "implementation",
    customerScopeRequired: true,
    requiredInputs: ["training_assignment"],
    optionalInputs: ["sop_record", "implementation_step"],
    producesSignals: ["training_assignment", "control_system_signal"],
    consumesSignals: ["sop_record", "implementation_step"],
    downstreamTools: ["rgs_control_system", "reports_exports"],
    upstreamTools: ["sop_training_bible", "implementation_roadmap"],
    reportOutputs: ["training_status_report"],
    clientVisibleFields: ["assigned_tools", "training_status"],
    adminOnlyFields: ["admin_training_risk_notes"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["training_stalled", "tool_unused"],
    controlSystemMonitoringHooks: ["tool_usage", "training_staleness"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Training tracker measures adoption; it is not unlimited support."],
    missingInputBehavior: "show_empty_state",
  },
  {
    toolKey: "rgs_control_system",
    displayName: "RGS Control System",
    stage: "control_system",
    customerScopeRequired: true,
    requiredInputs: ["repair_map_item"],
    optionalInputs: ["evidence_record", "campaign_performance", "risk_monitor_signal", "owner_decision_signal"],
    producesSignals: ["control_system_signal", "risk_monitor_signal", "priority_action"],
    consumesSignals: ["repair_map_item", "implementation_step", "evidence_record", "campaign_performance"],
    downstreamTools: ["campaign_control_system", "revenue_risk_monitor", "reports_exports"],
    upstreamTools: ["implementation_roadmap", "evidence_vault", "campaign_control_system"],
    reportOutputs: ["control_system_snapshot"],
    clientVisibleFields: ["monitoring_snapshot", "next_action", "approved_watchlist"],
    adminOnlyFields: ["admin_watch_notes", "reengagement_rationale"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["new_scope_needed", "stability_decline"],
    controlSystemMonitoringHooks: ["score_trend", "repair_progress", "evidence_decay", "campaign_learning"],
    standaloneEligible: false,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Control System monitors what is slipping; it is not a new Implementation project by default."],
    missingInputBehavior: "show_empty_state",
  },
  {
    toolKey: "campaign_control_system",
    displayName: "RGS Campaign Control System",
    stage: "campaign_control",
    customerScopeRequired: true,
    requiredInputs: ["campaign_profile"],
    optionalInputs: ["swot_signal", "buyer_persona_signal", "gear_scores", "repair_map_item", "control_system_signal", "campaign_performance"],
    producesSignals: ["campaign_brief", "campaign_asset", "campaign_performance", "report_artifact"],
    consumesSignals: ["campaign_profile", "swot_signal", "buyer_persona_signal", "gear_scores", "repair_map_item", "control_system_signal"],
    downstreamTools: ["reports_exports", "rgs_control_system", "buyer_persona_icp"],
    upstreamTools: ["swot_strategic_matrix", "buyer_persona_icp", "scorecard", "rgs_control_system"],
    reportOutputs: ["campaign_strategy_report", "campaign_asset_export", "learning_summary"],
    clientVisibleFields: ["approved_briefs", "approved_assets", "client_safe_performance", "manual_posting_instructions"],
    adminOnlyFields: ["admin_only_rationale", "admin_notes", "unapproved_drafts", "connection_proof_notes"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["campaign_needs_implementation", "conversion_or_capacity_blocker"],
    controlSystemMonitoringHooks: ["campaign_performance", "manual_posting_status", "learning_summary"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: [
      ...COMMON_SAFETY,
      "No fake GA4, social posting, ad platform, or CRM connection claims.",
      "No auto-posting. Manual posting is the safe fallback unless verified connectors exist.",
    ],
    scopeBoundaries: ["Campaign Control is inside the Control System lane and can also support bounded standalone campaign deliverables."],
    missingInputBehavior: "manual_fallback",
  },
  {
    toolKey: "reports_exports",
    displayName: "Reports / Exports",
    stage: "reporting",
    customerScopeRequired: true,
    requiredInputs: ["report_artifact"],
    optionalInputs: ["scorecard_run", "diagnostic_finding", "swot_signal", "campaign_brief", "campaign_asset"],
    producesSignals: ["report_artifact"],
    consumesSignals: ["report_artifact", "diagnostic_finding", "swot_signal", "campaign_brief"],
    downstreamTools: ["rgs_control_system"],
    upstreamTools: ["paid_diagnostic", "repair_map", "campaign_control_system"],
    reportOutputs: ["pdf_export", "client_visible_report"],
    clientVisibleFields: ["approved_report_sections", "client_safe_export"],
    adminOnlyFields: ["admin_notes", "draft_sections", "internal_review_status"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["report_update_requested"],
    controlSystemMonitoringHooks: ["report_status"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: [...COMMON_SAFETY, "Export buttons must work or be disabled with a plain-English reason."],
    scopeBoundaries: ["Report outputs only include approved client-safe content."],
    missingInputBehavior: "block",
  },
  {
    toolKey: "rgs_guide_bot",
    displayName: "AI Guide / Chatbot",
    stage: "admin_support",
    customerScopeRequired: false,
    requiredInputs: [],
    optionalInputs: ["scorecard_run", "control_system_signal", "evidence_record", "repair_map_item"],
    producesSignals: ["guide_bot_draft"],
    consumesSignals: ["scorecard_run", "control_system_signal", "evidence_record"],
    downstreamTools: ["scorecard", "evidence_vault", "repair_map"],
    upstreamTools: [],
    reportOutputs: [],
    clientVisibleFields: ["client_safe_guidance", "confirmed_user_inputs"],
    adminOnlyFields: ["admin_context", "system_rationale", "raw_provider_error"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["client_confusion", "missing_next_action"],
    controlSystemMonitoringHooks: ["workflow_help_needed"],
    standaloneEligible: false,
    gigBundleEligible: false,
    safetyBoundaries: [...COMMON_SAFETY, "AI drafts are assistive and never final until confirmed or approved."],
    scopeBoundaries: ["Guide bots route work and draft inputs; they do not publish findings or override scoring."],
    missingInputBehavior: "manual_fallback",
  },
  {
    toolKey: "revenue_risk_monitor",
    displayName: "Revenue & Risk Monitor",
    stage: "control_system",
    customerScopeRequired: true,
    requiredInputs: ["control_system_signal"],
    optionalInputs: ["campaign_performance", "evidence_record", "priority_action"],
    producesSignals: ["risk_monitor_signal", "priority_action"],
    consumesSignals: ["control_system_signal", "campaign_performance", "evidence_record"],
    downstreamTools: ["rgs_control_system", "priority_action_tracker", "reports_exports"],
    upstreamTools: ["rgs_control_system", "campaign_control_system"],
    reportOutputs: ["risk_monitor_snapshot"],
    clientVisibleFields: ["approved_risk_summary", "next_action"],
    adminOnlyFields: ["admin_risk_rationale", "internal_threshold_notes"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["risk_escalation", "renewal_risk"],
    controlSystemMonitoringHooks: ["risk_signal_trend"],
    standaloneEligible: false,
    gigBundleEligible: false,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Risk Monitor flags operating risk; it does not promise prevention or outcomes."],
    missingInputBehavior: "show_empty_state",
  },
  {
    toolKey: "owner_decision_dashboard",
    displayName: "Owner Decision Dashboard",
    stage: "control_system",
    customerScopeRequired: true,
    requiredInputs: ["control_system_signal"],
    optionalInputs: ["decision_rights_map", "priority_action", "risk_monitor_signal"],
    producesSignals: ["owner_decision_signal", "priority_action"],
    consumesSignals: ["decision_rights_map", "control_system_signal", "priority_action"],
    downstreamTools: ["rgs_control_system", "decision_rights_accountability", "reports_exports"],
    upstreamTools: ["decision_rights_accountability", "rgs_control_system"],
    reportOutputs: ["owner_decision_snapshot"],
    clientVisibleFields: ["approved_decisions", "review_cadence", "next_decision"],
    adminOnlyFields: ["admin_owner_bottleneck_notes", "sensitive_decision_context"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["owner_bottleneck_escalation"],
    controlSystemMonitoringHooks: ["decision_latency", "owner_dependency"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Dashboard clarifies decisions; the owner remains accountable for choices."],
    missingInputBehavior: "lower_confidence",
  },
  {
    toolKey: "priority_action_tracker",
    displayName: "Priority Action Tracker",
    stage: "repair_planning",
    customerScopeRequired: true,
    requiredInputs: ["priority_action"],
    optionalInputs: ["repair_map_item", "implementation_step", "control_system_signal"],
    producesSignals: ["priority_action", "control_system_signal"],
    consumesSignals: ["priority_action", "repair_map_item", "implementation_step"],
    downstreamTools: ["implementation_roadmap", "rgs_control_system", "reports_exports"],
    upstreamTools: ["repair_map", "implementation_roadmap", "rgs_control_system"],
    reportOutputs: ["priority_action_status"],
    clientVisibleFields: ["client_safe_action", "status", "due_date"],
    adminOnlyFields: ["admin_blocker_notes", "internal_priority_rationale"],
    approvalRequired: true,
    evidenceRequired: false,
    reengagementTriggers: ["overdue_priority_action", "blocked_action"],
    controlSystemMonitoringHooks: ["priority_action_status"],
    standaloneEligible: true,
    gigBundleEligible: true,
    safetyBoundaries: COMMON_SAFETY,
    scopeBoundaries: ["Tracker follows agreed actions; it does not create unlimited support."],
    missingInputBehavior: "show_empty_state",
  },
];
