import type { GigBundleDefinition } from "./types";

const COMMON_BOUNDARIES = [
  "Standalone/gig work is bounded to the named deliverable.",
  "Do not imply full Diagnostic, Implementation, or RGS Control System access unless explicitly included.",
  "Client-visible output requires review and approval.",
  "No legal, tax, accounting, compliance, fiduciary, valuation, revenue, profit, growth, lead, ROI, or outcome promises.",
  "Cannabis/MMJ work is operational and documentation visibility only, not compliance certification.",
];

export const GIG_BUNDLE_REGISTRY: GigBundleDefinition[] = [
  {
    bundleKey: "buyer_persona_icp_gig",
    displayName: "Buyer Persona / ICP Gig",
    includedTools: ["business_intake", "buyer_persona_icp"],
    optionalTools: ["swot_strategic_matrix", "campaign_control_system"],
    excludedTools: ["paid_diagnostic", "implementation_roadmap", "rgs_control_system"],
    requiredInputs: ["campaign_profile"],
    optionalInputs: ["swot_signal", "buyer_persona_signal", "campaign_performance"],
    deliverables: [
      "Buyer segment summary",
      "Buying triggers and objections",
      "Channel fit notes",
      "Campaign-use audience assumptions",
    ],
    reportOutputs: ["persona_icp_report"],
    approvalRequirements: ["Admin review before client delivery", "Confidence labels included"],
    clientVisibleOutputs: ["persona_summary", "buyer_triggers", "objections", "channel_fit"],
    adminOnlyFields: ["admin_notes", "confidence_rationale", "unvalidated_assumptions"],
    scopeBoundary: "Persona/ICP gig produces a bounded audience strategy deliverable. It is not a full Diagnostic or campaign management engagement.",
    missingInputBehavior: "Collect business intake, offer/service-line, industry, and audience context before drafting.",
    reengagementTriggers: ["client asks for campaign execution", "audience assumptions require deeper Diagnostic evidence"],
    safetyBoundaries: COMMON_BOUNDARIES,
  },
  {
    bundleKey: "campaign_strategy_gig",
    displayName: "Campaign Strategy Gig",
    includedTools: ["business_intake", "buyer_persona_icp", "swot_strategic_matrix", "campaign_control_system"],
    optionalTools: ["scorecard", "evidence_vault", "reports_exports"],
    excludedTools: ["paid_diagnostic", "implementation_roadmap", "rgs_control_system"],
    requiredInputs: ["campaign_profile", "buyer_persona_signal"],
    optionalInputs: ["swot_signal", "gear_scores", "campaign_performance", "evidence_record"],
    deliverables: [
      "Campaign objective and audience",
      "Offer/CTA recommendation",
      "Channel readiness notes",
      "Draft campaign assets",
      "Manual posting instructions",
      "Campaign safety review",
    ],
    reportOutputs: ["campaign_strategy_report", "campaign_asset_export"],
    approvalRequirements: ["Safety checker passed or reviewed", "Admin approval before assets are client-ready"],
    clientVisibleOutputs: ["approved_briefs", "approved_assets", "manual_posting_instructions"],
    adminOnlyFields: ["admin_only_rationale", "connection_proof_notes", "unsafe_claim_flags"],
    scopeBoundary: "Campaign strategy gig supports campaign planning and manual posting instructions only. It does not include live platform management, full Implementation, or Control System monitoring.",
    missingInputBehavior: "Draft can start with lower confidence, but publishing readiness is blocked until offer, audience, CTA, channel, and safety review are complete.",
    reengagementTriggers: ["client requests ongoing posting", "conversion/capacity blockers require implementation work", "analytics learning requires Control System monitoring"],
    safetyBoundaries: [
      ...COMMON_BOUNDARIES,
      "No fake GA4 or live social posting claims.",
      "Reddit is draft/manual only; no auto-posting or stealth lead generation.",
    ],
  },
  {
    bundleKey: "repair_map_gig",
    displayName: "Repair Map Gig",
    includedTools: ["scorecard", "swot_strategic_matrix", "repair_map"],
    optionalTools: ["paid_diagnostic", "evidence_vault", "implementation_roadmap"],
    excludedTools: ["rgs_control_system", "campaign_control_system"],
    requiredInputs: ["scorecard_run"],
    optionalInputs: ["diagnostic_finding", "swot_signal", "evidence_record"],
    deliverables: [
      "Priority repair list",
      "Impact/effort classification",
      "Evidence confidence notes",
      "First recommended actions",
    ],
    reportOutputs: ["repair_priority_report"],
    approvalRequirements: ["Admin review before delivery", "Client-safe language check"],
    clientVisibleOutputs: ["repair_map_items", "client_safe_priority_explanation"],
    adminOnlyFields: ["admin_priority_note", "dependency_note", "evidence_conflict_notes"],
    scopeBoundary: "Repair Map gig identifies what to fix first. It does not install the repair unless Implementation is purchased.",
    missingInputBehavior: "If no Diagnostic exists, use Scorecard/SWOT with low confidence and clear evidence limitations.",
    reengagementTriggers: ["client wants implementation", "repair requires deeper evidence review"],
    safetyBoundaries: COMMON_BOUNDARIES,
  },
  {
    bundleKey: "sop_training_bible_gig",
    displayName: "SOP / Training Bible Gig",
    includedTools: [
      "workflow_process_mapping",
      "decision_rights_accountability",
      "sop_training_bible",
      "tool_assignment_training_tracker",
    ],
    optionalTools: ["evidence_vault", "implementation_roadmap"],
    excludedTools: ["paid_diagnostic", "rgs_control_system", "campaign_control_system"],
    requiredInputs: ["workflow_map"],
    optionalInputs: ["decision_rights_map", "evidence_record", "implementation_step"],
    deliverables: [
      "Process map",
      "Role/accountability summary",
      "SOP draft",
      "Training checklist",
      "Client-ready SOP report",
    ],
    reportOutputs: ["sop_report", "training_checklist"],
    approvalRequirements: ["Client-visible SOP content reviewed", "Admin-only notes removed before export"],
    clientVisibleOutputs: ["approved_sop", "training_steps", "handoff_summary"],
    adminOnlyFields: ["admin_training_notes", "process_risk_notes", "sensitive_team_notes"],
    scopeBoundary: "SOP gig produces documentation and training structure. It does not make RGS responsible for operating or supervising the business.",
    missingInputBehavior: "Collect process intake and owner/team responsibility context before drafting.",
    reengagementTriggers: ["client asks RGS to manage the process", "new system installation is needed"],
    safetyBoundaries: COMMON_BOUNDARIES,
  },
  {
    bundleKey: "control_system_setup_gig",
    displayName: "Control System Setup Gig",
    includedTools: ["scorecard", "repair_map", "priority_action_tracker", "owner_decision_dashboard"],
    optionalTools: ["evidence_vault", "rgs_control_system", "reports_exports"],
    excludedTools: ["paid_diagnostic", "implementation_roadmap", "campaign_control_system"],
    requiredInputs: ["scorecard_run", "repair_map_item"],
    optionalInputs: ["evidence_record", "control_system_signal", "priority_action"],
    deliverables: [
      "Baseline operating snapshot",
      "Priority tracker setup",
      "Owner decision metrics",
      "Monthly review template",
      "Client dashboard handoff",
    ],
    reportOutputs: ["control_system_setup_report"],
    approvalRequirements: ["Scope boundary approved", "Dashboard fields reviewed before client access"],
    clientVisibleOutputs: ["approved_watchlist", "priority_action_status", "monthly_review_template"],
    adminOnlyFields: ["admin_watch_notes", "reengagement_rationale"],
    scopeBoundary: "Control System setup gig creates a handoff-ready monitoring structure. It is not the recurring RGS Control System subscription unless separately activated.",
    missingInputBehavior: "Require Scorecard baseline and at least one approved Repair Map item before setup.",
    reengagementTriggers: ["client wants recurring monitoring", "new implementation scope is requested"],
    safetyBoundaries: COMMON_BOUNDARIES,
  },
];

