-- IB-H2 — Industry Anchor Schema + Content Foundation

-- Additive only. Admin-only RLS. client_visible defaults false. No deterministic scoring change.


-- IB-H2: Companion anchor tables (additive; admin-only; client_visible default false)

CREATE TABLE IF NOT EXISTS public.industry_benchmark_anchors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  industry_key public.industry_brain_industry_key NOT NULL,
  gear public.industry_brain_gear NOT NULL,
  metric_key text NOT NULL,
  metric_label text NOT NULL,
  benchmark_value numeric,
  warning_value numeric,
  critical_value numeric,
  unit text NOT NULL,
  source_status text NOT NULL CHECK (source_status IN (
    'internal operating benchmark',
    'needs external verification',
    'client-provided target'
  )),
  admin_notes text,
  client_safe_wording text,
  client_visible boolean NOT NULL DEFAULT false,
  interpretive_only boolean NOT NULL DEFAULT true,
  related_failure_titles jsonb NOT NULL DEFAULT '[]'::jsonb,
  related_tool_keys jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_iba_industry ON public.industry_benchmark_anchors(industry_key);
CREATE INDEX IF NOT EXISTS idx_iba_gear ON public.industry_benchmark_anchors(gear);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_iba_industry_metric ON public.industry_benchmark_anchors(industry_key, metric_key);

ALTER TABLE public.industry_benchmark_anchors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin manage industry benchmark anchors" ON public.industry_benchmark_anchors;
CREATE POLICY "Admin manage industry benchmark anchors"
  ON public.industry_benchmark_anchors FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

DROP TRIGGER IF EXISTS trg_iba_touch ON public.industry_benchmark_anchors;
CREATE TRIGGER trg_iba_touch BEFORE UPDATE ON public.industry_benchmark_anchors
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


CREATE TABLE IF NOT EXISTS public.industry_glossary_terms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  industry_key public.industry_brain_industry_key NOT NULL,
  term text NOT NULL,
  meaning text NOT NULL,
  cross_industry_note text,
  related_gear public.industry_brain_gear NOT NULL DEFAULT 'general',
  related_tool_questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  report_wording_guidance text,
  client_safe_wording text,
  admin_notes text,
  client_visible boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_igt_industry ON public.industry_glossary_terms(industry_key);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_igt_industry_term ON public.industry_glossary_terms(industry_key, term);

ALTER TABLE public.industry_glossary_terms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin manage industry glossary terms" ON public.industry_glossary_terms;
CREATE POLICY "Admin manage industry glossary terms"
  ON public.industry_glossary_terms FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

DROP TRIGGER IF EXISTS trg_igt_touch ON public.industry_glossary_terms;
CREATE TRIGGER trg_igt_touch BEFORE UPDATE ON public.industry_glossary_terms
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


CREATE TABLE IF NOT EXISTS public.industry_case_studies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  industry_key public.industry_brain_industry_key NOT NULL,
  business_type text NOT NULL,
  case_name text NOT NULL,
  approximate_score integer NOT NULL CHECK (approximate_score BETWEEN 0 AND 1000),
  score_band text NOT NULL CHECK (score_band IN ('300_450','451_650','651_800','801_plus')),
  gear_scores jsonb NOT NULL DEFAULT '{}'::jsonb,
  symptoms text NOT NULL,
  evidence text NOT NULL,
  failure_patterns_detected text NOT NULL,
  benchmark_anchors_involved text,
  admin_interpretation text NOT NULL,
  client_safe_summary text NOT NULL,
  likely_repair_map_priorities text NOT NULL,
  suggested_next_diagnostic_questions text NOT NULL,
  what_not_to_overpromise text,
  is_synthetic boolean NOT NULL DEFAULT true,
  not_real_client boolean NOT NULL DEFAULT true,
  client_visible boolean NOT NULL DEFAULT false,
  display_label text NOT NULL DEFAULT 'Training example — not a real customer.',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ics_must_be_synthetic CHECK (is_synthetic = true AND not_real_client = true)
);
CREATE INDEX IF NOT EXISTS idx_ics_industry ON public.industry_case_studies(industry_key);
CREATE INDEX IF NOT EXISTS idx_ics_band ON public.industry_case_studies(score_band);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_ics_industry_case ON public.industry_case_studies(industry_key, case_name);

ALTER TABLE public.industry_case_studies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin manage industry case studies" ON public.industry_case_studies;
CREATE POLICY "Admin manage industry case studies"
  ON public.industry_case_studies FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

DROP TRIGGER IF EXISTS trg_ics_touch ON public.industry_case_studies;
CREATE TRIGGER trg_ics_touch BEFORE UPDATE ON public.industry_case_studies
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- IB-H2: failure-library entries (admin-only; client_visible=false)
INSERT INTO public.industry_brain_entries (
  industry_key, industry_label, title, summary, content, caution_note,
  template_type, gear, service_lane, customer_journey_phase, industry_behavior,
  status, client_visible, contains_internal_notes, display_order, tags
) VALUES
('general_small_business', 'General Small Business', 'IB-H2 Failure: No defined buyer profile', 'Owner cannot describe ideal customer in one sentence; marketing spreads thin across mismatched leads.', 'Symptoms: leads do not close, ad spend feels random, referrals strongest. Hidden cause: no documented ICP. Evidence: lead quality unknown, no source attribution. Likely score impact: −15 to −30. Diagnostic Qs: Who is your best 3-month customer? Why did they buy? Repair-map: define ICP + qualifier.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'demand_generation', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1010, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: Weak lead qualification', 'Every lead is treated equally; sales time consumed by tire-kickers.', 'Symptoms: long quoting cycle, low close rate, owner doing all qualifying. Hidden cause: no qualifier checklist. Evidence: no disqualified-lead log. Repair-map: add 3-question qualifier.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1020, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: Owner-only sales', 'All deals close through the owner; team cannot quote or negotiate.', 'Symptoms: deals stall when owner travels. Hidden cause: pricing/decision logic in owner''s head. Evidence: no written pricing rules. Repair-map: write decision rights.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'owner_independence', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1030, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: Poor follow-up', 'Quotes/leads sit without contact for days; pipeline rot.', 'Symptoms: lost deals ''reappear'' months later. Evidence: no follow-up cadence in CRM. Repair-map: 3-touch follow-up SOP.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1040, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: Unclear pricing', 'Pricing varies by mood, customer, or memory.', 'Evidence: same service quoted at different prices same week. Repair-map: pricing matrix + minimum margin floor.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1050, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: No SOPs', 'Work performed from memory; quality drifts when staff changes.', 'Evidence: no documented procedures, training is shadowing only. Repair-map: top-5 SOP starter set.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1060, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: Delivery inconsistency', 'Customer experience depends on which staff member handled them.', 'Evidence: review variance, repeat issues by employee. Repair-map: standardized delivery checklist.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1070, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: Cash flow blindness', 'Owner uses bank balance as profitability signal.', 'Evidence: no 13-week cash forecast, surprise shortfalls. Repair-map: weekly cash dashboard.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1080, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: No performance dashboard', 'No single weekly view of revenue, leads, jobs, cash.', 'Evidence: numbers reviewed quarterly or never. Repair-map: 1-page weekly scoreboard.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1090, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('general_small_business', 'General Small Business', 'IB-H2 Failure: No delegation structure', 'Owner is decision bottleneck for routine work.', 'Evidence: questions queue waiting for owner. Repair-map: decision-rights matrix.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'owner_independence', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1100, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Owner is the bottleneck', 'Estimating, scheduling, and invoicing all funnel through the owner.', 'Evidence: jobs slip when owner is on a job, no written estimating rules. Repair-map: estimator role + decision rights.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'owner_independence', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1010, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Quoting delay causes lost jobs', 'Multi-day delay between request and quote; competitor wins on speed.', 'Evidence: average quote-out time > 48h, lost-quote reason ''no response''. Repair-map: 24h quote SLA.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1020, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: No job costing', 'Per-job labor and materials never reconciled to estimate.', 'Evidence: no actual-vs-estimate by job, gross margin estimated from gut. Repair-map: per-job costing template.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1030, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Schedule chaos', 'Scheduling lives in head/text; double-bookings and missed jobs.', 'Evidence: no shared dispatch board, customer status updates ad-hoc. Repair-map: dispatch board + confirmation cadence.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1040, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Callback / rework creep', 'Rework not tracked; same failures repeat.', 'Evidence: no callback log, warranty work absorbs margin. Repair-map: callback log + root-cause review.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1050, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Lead source overdependence', 'One channel (referrals or one ad source) drives most leads.', 'Evidence: no source attribution, sudden quiet weeks unexplained. Repair-map: source tagging + 2nd channel pilot.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'demand_generation', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1060, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: No follow-up process', 'Quotes sent and never re-touched.', 'Evidence: no follow-up in CRM, lost-bid analysis missing. Repair-map: 3-touch follow-up SOP.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1070, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Underpriced labor', 'Hourly labor rate doesn''t recover overhead, vehicles, or warranty.', 'Evidence: gross margin < target, owner can''t explain rate buildup. Repair-map: rebuild rate.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1080, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Unpaid invoices / AR drag', 'Aged AR > 60 days erodes cash.', 'Evidence: AR aging report not run, deposits not standard. Repair-map: deposit policy + AR cadence.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1090, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Technician dependency', 'One technician holds the relationships and the methods.', 'Evidence: customers ask for that tech by name, no documented procedures. Repair-map: cross-train + SOPs.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'owner_independence', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1100, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('trades_services', 'Trades / Services', 'IB-H2 Failure: Service area profitability blind spots', 'Some service lines lose money but get prioritized.', 'Evidence: no margin per service line. Repair-map: service-line P&L cut.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1110, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Labor cost creep', 'Labor % drifts above target without anyone noticing weekly.', 'Evidence: labor % computed monthly or never, schedules built from memory. Repair-map: weekly labor target + sales-driven schedule.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1010, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Food cost creep', 'Vendor price increases pass through silently.', 'Evidence: no menu costing review > 90 days, recipe cards inconsistent. Repair-map: monthly cost recheck on top-20 SKUs.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1020, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Poor menu engineering', 'Menu mix not analyzed; star/dog items unidentified.', 'Evidence: no contribution-margin sort by item. Repair-map: menu engineering matrix.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1030, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Spoilage / yield loss', 'Prep over-built, waste not logged.', 'Evidence: no waste sheet, end-of-day prep dumped. Repair-map: prep par + waste log.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1040, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Weak table turns / throughput', 'Peak hours leave revenue on the table.', 'Evidence: no average ticket-time tracking, server stations unbalanced. Repair-map: ticket-time SLA + station balance.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1050, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Owner-dependent operations', 'Owner expedites, schedules, and reconciles personally.', 'Evidence: shifts collapse when owner absent. Repair-map: shift lead role + checklist.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'owner_independence', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1060, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Inconsistent prep / process standards', 'Recipes executed by memory; quality varies by cook.', 'Evidence: no recipe cards posted, plating varies. Repair-map: recipe cards + line training.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1070, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Inventory leakage', 'Inventory variance not reconciled; theft/over-portioning hidden.', 'Evidence: no weekly count vs theoretical usage. Repair-map: weekly count cycle.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1080, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: No daily break-even visibility', 'Owner can''t say what today needs to cover.', 'Evidence: no daily break-even card. Repair-map: posted daily break-even.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1090, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Review / reputation dependency', 'One bad review week tanks bookings; no proactive review flow.', 'Evidence: no review-request automation. Repair-map: post-visit review request.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'demand_generation', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1100, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('restaurant_food_service', 'Restaurant / Food Service', 'IB-H2 Failure: Delivery-platform margin erosion', 'Third-party delivery margins not separated from in-house margin.', 'Evidence: blended margin only. Repair-map: channel P&L.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1110, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Slow inventory turns', 'Cash tied up in slow SKUs; turn rate not measured by category.', 'Evidence: no turn metric, dead stock visible on shelf. Repair-map: category turn target + clearance cadence.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1010, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Margin erosion', 'Vendor cost increases not reflected in shelf price.', 'Evidence: blended margin only, last cost review > 90 days. Repair-map: monthly margin review.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1020, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Poor sell-through', 'Buys ordered without sell-through targets.', 'Evidence: no sell-through % by buy. Repair-map: sell-through SLA + buy review.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1030, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Shrinkage', 'Shrink not measured; loss invisible.', 'Evidence: no cycle counts, no shrink % reported. Repair-map: cycle count program.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1040, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Seasonal cash crunch', 'Off-season buys not modeled against cash.', 'Evidence: no cash forecast, owner uses LOC reactively. Repair-map: 13-week cash forecast.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1050, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Overdependence on one channel', 'One channel drives most revenue.', 'Evidence: no channel mix report. Repair-map: 2nd channel pilot.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'demand_generation', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1060, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Weak customer retention', 'Repeat customer rate unknown.', 'Evidence: no repeat signal in POS. Repair-map: simple loyalty trigger.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1070, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Weak merchandising discipline', 'Floor sets and end-caps changed inconsistently.', 'Evidence: no merchandising calendar. Repair-map: weekly floor-set plan.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1080, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Stockout / overstock cycle', 'Reorder triggers manual; oscillation between stockout and overstock.', 'Evidence: no min/max in POS. Repair-map: min/max + reorder cadence.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1090, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: No SKU-level visibility', 'Owner manages categories, not SKUs.', 'Evidence: top/bottom SKU report unused. Repair-map: monthly SKU review.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1100, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('retail', 'Retail', 'IB-H2 Failure: Promo / discount leakage', 'Discount stacking erodes margin invisibly.', 'Evidence: no discount % vs gross sales tracking. Repair-map: discount governance.', 'Industry-aware example only. Does not replace owner judgment or qualified advisors.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1110, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Possible documentation gap in compliance evidence', 'Required operational documentation appears incomplete based on operator self-report.', 'Evidence: documentation readiness issue; some operational records not consistently captured. Repair-map: documentation checklist + cadence. Note: compliance-sensitive operational risk; state-specific rules may apply; requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1010, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Inventory control weaknesses (operational visibility)', 'Inventory variance and seed-to-sale traceability handled informally.', 'Evidence: no documented receiving/variance cadence. Repair-map: receiving SOP + weekly variance review. Compliance-sensitive operational risk; state-specific rules may apply; not legal advice; not a compliance guarantee.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1020, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Cash handling risk (operational visibility)', 'Cash-heavy environment with informal counting/transport documentation.', 'Evidence: no documented cash count/transport SOP. Repair-map: dual-control count SOP. Operational documentation readiness, not legal advice.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1030, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Discounting / margin erosion', 'Discount stacking and ''budtender specials'' erode margin invisibly.', 'Evidence: no discount governance. Repair-map: discount cap + manager approval.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1040, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Vendor concentration', 'Reliance on single brand/distributor creates margin and supply risk.', 'Evidence: top vendor > 40% of COGS. Repair-map: 2nd vendor qualification.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1050, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Budtender inconsistency', 'Customer experience and upsell quality vary by budtender.', 'Evidence: ticket size variance by employee. Repair-map: budtender playbook + training cadence.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1060, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Process rigidity gaps (compliance-sensitive)', 'Process exceptions handled ad-hoc rather than via documented variance procedure.', 'Evidence: no exception log. Repair-map: variance-handling SOP. Compliance-sensitive operational risk; state-specific rules may apply; requires qualified legal/compliance review.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1070, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: License / renewal / document tracking risk', 'Renewals and document expirations tracked informally.', 'Evidence: no renewal calendar or owner-side reminder. Repair-map: renewal calendar with 90/60/30 reminders. Operational readiness only; not legal advice.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1080, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Seed-to-sale process gaps', 'Seed-to-sale steps documented unevenly across shifts.', 'Evidence: handoff steps vary by manager. Repair-map: seed-to-sale handoff SOP. State-specific rules may apply; not a compliance guarantee.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1090, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Evidence vault / document readiness gaps', 'Operational evidence not centrally stored for fast retrieval.', 'Evidence: documents scattered across drives. Repair-map: evidence vault + index. Documentation readiness only.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'financial_visibility', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1100, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: Menu / pricing inconsistency', 'Menu price displayed differs from POS or online.', 'Evidence: spot-check variance. Repair-map: weekly menu reconciliation.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'revenue_conversion', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1110, '{"anchor": "failure_library", "ib_h2": true}'::jsonb),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'IB-H2 Failure: ID / check-in process visibility gaps', 'Check-in steps performed by memory; visibility into completion is thin.', 'Evidence: no check-in completion log. Repair-map: documented check-in SOP. Compliance-sensitive operational risk; state-specific rules may apply; not legal advice.', 'Compliance-sensitive operational risk. State-specific rules may apply. Requires qualified legal/compliance review. Operational visibility, not legal advice. RGS does not certify compliance.', 'risk_signal', 'operational_efficiency', 'shared_support', 'admin_review', 'industry_aware_outputs', 'active', false, true, 1120, '{"anchor": "failure_library", "ib_h2": true}'::jsonb);

-- IB-H2: benchmark anchors seed
INSERT INTO public.industry_benchmark_anchors (
  industry_key, gear, metric_key, metric_label, benchmark_value, warning_value, critical_value,
  unit, source_status, admin_notes, client_safe_wording, client_visible, interpretive_only
) VALUES
('general_small_business', 'demand_generation', 'lead_response_time', 'Lead response time', 60, 1440, 4320, 'minutes', 'needs external verification', 'Faster response correlates with close rate.', 'We aim to respond to new leads inside 1 hour.', false, true),
('general_small_business', 'revenue_conversion', 'close_rate', 'Close rate (qualified)', 0.3, 0.15, 0.05, 'ratio', 'internal operating benchmark', 'Anchor only; varies wildly by vertical.', 'Healthy close rate on qualified leads.', false, true),
('general_small_business', 'financial_visibility', 'gross_margin', 'Gross margin', 0.45, 0.3, 0.2, 'ratio', 'needs external verification', 'Anchor only; vertical-specific.', 'Healthy gross margin range for this business type.', false, true),
('general_small_business', 'financial_visibility', 'cash_runway_weeks', 'Cash runway', 13, 8, 4, 'weeks', 'internal operating benchmark', '13 weeks reflects standard rolling forecast practice.', 'Weeks of runway based on current burn.', false, true),
('general_small_business', 'owner_independence', 'owner_decision_dependency', 'Owner decision dependency', 0.3, 0.6, 0.85, 'ratio', 'internal operating benchmark', 'Estimated share of routine decisions requiring owner.', 'Share of routine decisions that require the owner.', false, true),
('trades_services', 'revenue_conversion', 'quote_to_close', 'Quote-to-close', 0.4, 0.25, 0.15, 'ratio', 'needs external verification', 'Anchor only.', 'Healthy quote-to-close range.', false, true),
('trades_services', 'operational_efficiency', 'callback_rate', 'Callback / rework rate', 0.03, 0.07, 0.12, 'ratio', 'needs external verification', 'Anchor only.', 'Callback rate as share of completed jobs.', false, true),
('trades_services', 'operational_efficiency', 'labor_utilization', 'Labor utilization', 0.7, 0.55, 0.4, 'ratio', 'needs external verification', 'Billable hours / available hours.', 'Billable share of available technician time.', false, true),
('trades_services', 'financial_visibility', 'job_gross_margin', 'Job gross margin', 0.4, 0.28, 0.18, 'ratio', 'needs external verification', 'Anchor only.', 'Healthy job-level gross margin.', false, true),
('trades_services', 'financial_visibility', 'ar_aging_60d', 'AR aging > 60 days', 0.05, 0.15, 0.25, 'ratio', 'internal operating benchmark', 'Share of AR aged past 60 days.', 'Aged receivables as a share of total AR.', false, true),
('trades_services', 'operational_efficiency', 'schedule_capacity_utilization', 'Schedule capacity utilization', 0.8, 0.65, 0.5, 'ratio', 'needs external verification', 'Booked / available crew hours.', 'How full the schedule runs.', false, true),
('trades_services', 'revenue_conversion', 'first_response_time', 'First response time', 60, 240, 1440, 'minutes', 'needs external verification', 'Time from inbound request to first human reply.', 'Speed to first reply on inbound requests.', false, true),
('restaurant_food_service', 'financial_visibility', 'prime_cost', 'Prime cost (food + labor)', 0.6, 0.65, 0.7, 'ratio', 'needs external verification', 'Anchor only; concept-dependent.', 'Prime cost as a share of sales.', false, true),
('restaurant_food_service', 'financial_visibility', 'food_cost_pct', 'Food cost %', 0.3, 0.34, 0.38, 'ratio', 'needs external verification', 'Anchor only; varies by menu.', 'Food cost as a share of food sales.', false, true),
('restaurant_food_service', 'financial_visibility', 'labor_cost_pct', 'Labor cost %', 0.28, 0.32, 0.36, 'ratio', 'needs external verification', 'Anchor only.', 'Labor cost as a share of sales.', false, true),
('restaurant_food_service', 'operational_efficiency', 'waste_tracking', 'Weekly waste tracking', 1, 0, 0, 'boolean', 'internal operating benchmark', 'Either tracked or not.', 'Whether waste is logged weekly.', false, true),
('restaurant_food_service', 'operational_efficiency', 'table_turns', 'Peak table turns / hour', 2.0, 1.5, 1.0, 'ratio', 'needs external verification', 'Concept-dependent.', 'Peak-hour throughput per table.', false, true),
('restaurant_food_service', 'financial_visibility', 'daily_breakeven_visibility', 'Daily break-even visibility', 1, 0, 0, 'boolean', 'internal operating benchmark', 'Either posted or not.', 'Whether the daily break-even number is visible to managers.', false, true),
('restaurant_food_service', 'financial_visibility', 'cash_runway_weeks', 'Cash runway', 13, 8, 4, 'weeks', 'internal operating benchmark', 'Standard rolling forecast.', 'Weeks of runway.', false, true),
('retail', 'operational_efficiency', 'inventory_turnover', 'Inventory turnover (annual)', 6, 4, 2, 'turns/yr', 'needs external verification', 'Anchor only; category-dependent.', 'Annual inventory turns.', false, true),
('retail', 'financial_visibility', 'gross_margin', 'Gross margin', 0.45, 0.35, 0.25, 'ratio', 'needs external verification', 'Anchor only.', 'Healthy gross margin range.', false, true),
('retail', 'revenue_conversion', 'sell_through', 'Sell-through (8 wk)', 0.65, 0.45, 0.3, 'ratio', 'needs external verification', 'Per buying cycle.', 'Share of buy sold inside the target window.', false, true),
('retail', 'operational_efficiency', 'stockout_frequency', 'Top-20 SKU stockout frequency', 0.05, 0.1, 0.2, 'ratio', 'needs external verification', 'Share of weeks any top-20 SKU is out.', 'How often top sellers go out of stock.', false, true),
('retail', 'financial_visibility', 'shrinkage', 'Shrinkage', 0.01, 0.02, 0.04, 'ratio', 'needs external verification', 'Anchor only; varies by category.', 'Inventory shrink as a share of sales.', false, true),
('retail', 'demand_generation', 'channel_concentration', 'Single-channel revenue concentration', 0.5, 0.7, 0.85, 'ratio', 'internal operating benchmark', 'Top channel share.', 'How dependent the business is on one channel.', false, true),
('retail', 'financial_visibility', 'cash_runway_weeks', 'Cash runway', 13, 8, 4, 'weeks', 'internal operating benchmark', 'Standard rolling forecast.', 'Weeks of runway.', false, true),
('cannabis_mmj_mmc', 'operational_efficiency', 'inventory_variance', 'Inventory variance (weekly)', 0.005, 0.015, 0.03, 'ratio', 'needs external verification', 'Operational visibility anchor; state-specific rules may apply; not a compliance guarantee.', 'Weekly inventory variance as a share of units.', false, true),
('cannabis_mmj_mmc', 'financial_visibility', 'cash_handling_documentation', 'Cash handling documentation completeness', 1, 0, 0, 'boolean', 'internal operating benchmark', 'Operational readiness only; not legal advice.', 'Whether dual-control cash counts are documented.', false, true),
('cannabis_mmj_mmc', 'operational_efficiency', 'compliance_checklist_completion', 'Operational compliance checklist completion', 0.95, 0.85, 0.7, 'ratio', 'needs external verification', 'Operational documentation readiness only; state-specific rules may apply; not a compliance guarantee.', 'Share of operational checklist items completed on schedule.', false, true),
('cannabis_mmj_mmc', 'operational_efficiency', 'evidence_doc_freshness', 'Evidence document freshness', 30, 90, 180, 'days', 'internal operating benchmark', 'Days since last review of key operational documents.', 'How recently key operational documents were reviewed.', false, true),
('cannabis_mmj_mmc', 'financial_visibility', 'discount_dependency', 'Discount % of gross sales', 0.1, 0.18, 0.25, 'ratio', 'needs external verification', 'Anchor only; market-dependent.', 'Discounts as a share of gross sales.', false, true),
('cannabis_mmj_mmc', 'financial_visibility', 'gross_margin', 'Gross margin', 0.45, 0.35, 0.25, 'ratio', 'needs external verification', 'Anchor only.', 'Healthy gross margin range.', false, true),
('cannabis_mmj_mmc', 'revenue_conversion', 'repeat_customer_rate', 'Repeat customer rate (90d)', 0.45, 0.3, 0.18, 'ratio', 'needs external verification', 'Loyalty/POS-based.', 'Repeat customer share over the last 90 days.', false, true),
('cannabis_mmj_mmc', 'operational_efficiency', 'license_renewal_lead_time', 'License/permit renewal lead time', 90, 60, 30, 'days', 'internal operating benchmark', 'Days before expiration that renewal work begins. Operational readiness only; not legal advice.', 'How far in advance renewal work begins.', false, true) ON CONFLICT (industry_key, metric_key) DO NOTHING;

-- IB-H2: glossary seed
INSERT INTO public.industry_glossary_terms (
  industry_key, term, meaning, cross_industry_note, related_gear, client_safe_wording, client_visible
) VALUES
('general_small_business', 'Qualified lead', 'A prospect that matches ICP and has expressed need + ability to buy.', 'All industries share this term; the qualifier criteria differ by vertical.', 'revenue_conversion', 'A prospect that matches ICP and has expressed need + ability to buy.', false),
('general_small_business', 'Owner bottleneck', 'Routine decisions queued waiting for the owner.', 'Same meaning across verticals; manifests differently.', 'owner_independence', 'Routine decisions queued waiting for the owner.', false),
('general_small_business', 'Recurring revenue', 'Predictable repeat revenue (subscription, retainer, contract).', 'Different mechanism per vertical; same concept.', 'financial_visibility', 'Predictable repeat revenue (subscription, retainer, contract).', false),
('general_small_business', 'Gross margin', 'Revenue minus direct cost of delivery, before overhead.', 'Direct-cost definition varies by vertical.', 'financial_visibility', 'Revenue minus direct cost of delivery, before overhead.', false),
('general_small_business', 'Break-even point', 'Revenue level where contribution covers fixed cost.', 'Calculated daily in restaurants, monthly elsewhere.', 'financial_visibility', 'Revenue level where contribution covers fixed cost.', false),
('general_small_business', 'Delegation', 'Documented authority to act without owner approval.', 'Same across verticals.', 'owner_independence', 'Documented authority to act without owner approval.', false),
('general_small_business', 'SOP coverage', 'Share of repeated work covered by a written procedure.', 'Same across verticals; varies in granularity.', 'operational_efficiency', 'Share of repeated work covered by a written procedure.', false),
('general_small_business', 'Follow-up process', 'A defined cadence and owner for re-touching open leads.', 'Different channels per vertical, same concept.', 'revenue_conversion', 'A defined cadence and owner for re-touching open leads.', false),
('general_small_business', 'Service line profitability', 'Margin attributed to a specific service or product line.', 'Vertical-specific cuts (job, menu item, SKU, category).', 'financial_visibility', 'Margin attributed to a specific service or product line.', false),
('general_small_business', 'Cash runway', 'Weeks the business can operate at current burn.', 'Same across verticals.', 'financial_visibility', 'Weeks the business can operate at current burn.', false),
('trades_services', 'Quote-to-close', 'Won jobs / quotes sent.', 'Trades-specific; restaurants don''t quote individual orders.', 'revenue_conversion', 'Won jobs / quotes sent.', false),
('trades_services', 'Callback', 'Return visit to fix a prior job at no charge.', 'Trades-specific.', 'operational_efficiency', 'Return visit to fix a prior job at no charge.', false),
('trades_services', 'Job costing', 'Reconciling actual labor + materials per job to estimate.', 'Trades/construction-specific cut.', 'financial_visibility', 'Reconciling actual labor + materials per job to estimate.', false),
('trades_services', 'Service area', 'Geographic radius the crew operates in.', 'Trades-specific.', 'operational_efficiency', 'Geographic radius the crew operates in.', false),
('trades_services', 'Dispatch capacity', 'Available crew-hours that can be booked.', 'Trades/field-services specific.', 'operational_efficiency', 'Available crew-hours that can be booked.', false),
('trades_services', 'Technician utilization', 'Billable hours divided by available hours.', 'Trades-specific.', 'operational_efficiency', 'Billable hours divided by available hours.', false),
('trades_services', 'Parts availability', 'Whether crews carry/stock required parts.', 'Trades-specific.', 'operational_efficiency', 'Whether crews carry/stock required parts.', false),
('trades_services', 'Rework', 'Work redone due to quality issue.', 'Cross-vertical concept; tracked formally in trades.', 'operational_efficiency', 'Work redone due to quality issue.', false),
('trades_services', 'AR aging', 'Receivables sorted by days outstanding.', 'Cross-vertical; high-leverage in trades.', 'financial_visibility', 'Receivables sorted by days outstanding.', false),
('trades_services', 'Emergency work', 'After-hours/urgent jobs at premium rate.', 'Trades-specific.', 'revenue_conversion', 'After-hours/urgent jobs at premium rate.', false),
('restaurant_food_service', 'Prime cost', 'Food cost + labor cost as a share of sales.', 'Restaurant-specific composite.', 'financial_visibility', 'Food cost + labor cost as a share of sales.', false),
('restaurant_food_service', 'Food cost', 'COGS for food sales as a share of food sales.', 'Restaurant-specific cut.', 'financial_visibility', 'COGS for food sales as a share of food sales.', false),
('restaurant_food_service', 'Labor percentage', 'Labor cost as a share of sales.', 'Restaurant-specific cadence; computed weekly.', 'financial_visibility', 'Labor cost as a share of sales.', false),
('restaurant_food_service', 'Table turns', 'Average parties served per table per shift.', 'Restaurant-specific.', 'operational_efficiency', 'Average parties served per table per shift.', false),
('restaurant_food_service', 'Ticket time', 'Time from order entry to delivery.', 'Restaurant-specific.', 'operational_efficiency', 'Time from order entry to delivery.', false),
('restaurant_food_service', 'Menu engineering', 'Sorting items by popularity and contribution margin.', 'Restaurant-specific framework.', 'revenue_conversion', 'Sorting items by popularity and contribution margin.', false),
('restaurant_food_service', 'Spoilage', 'Inventory lost to over-prep or expiration.', 'Restaurant-specific.', 'operational_efficiency', 'Inventory lost to over-prep or expiration.', false),
('restaurant_food_service', 'Prep consistency', 'Repeatable execution of recipes and portions.', 'Restaurant-specific.', 'operational_efficiency', 'Repeatable execution of recipes and portions.', false),
('restaurant_food_service', 'Contribution margin', 'Item sales minus item-level direct cost.', 'Used for menu engineering specifically.', 'financial_visibility', 'Item sales minus item-level direct cost.', false),
('restaurant_food_service', 'Vendor ordering', 'Recurring order cadence with primary vendors.', 'Restaurant-specific cadence.', 'operational_efficiency', 'Recurring order cadence with primary vendors.', false),
('retail', 'Sell-through', 'Units sold / units bought, by buying cycle.', 'Retail-specific.', 'revenue_conversion', 'Units sold / units bought, by buying cycle.', false),
('retail', 'Inventory turnover', 'Annualized COGS divided by average inventory.', 'Retail-specific cut.', 'operational_efficiency', 'Annualized COGS divided by average inventory.', false),
('retail', 'Dead stock', 'SKUs with no sales over a defined window.', 'Retail-specific.', 'operational_efficiency', 'SKUs with no sales over a defined window.', false),
('retail', 'Shrink', 'Inventory loss from theft, damage, or error.', 'Retail-specific.', 'financial_visibility', 'Inventory loss from theft, damage, or error.', false),
('retail', 'Basket size', 'Average units (or dollars) per transaction.', 'Retail-specific.', 'revenue_conversion', 'Average units (or dollars) per transaction.', false),
('retail', 'Category margin', 'Gross margin computed per category.', 'Retail-specific cut.', 'financial_visibility', 'Gross margin computed per category.', false),
('retail', 'Merchandising', 'Floor presentation and product placement.', 'Retail-specific discipline.', 'operational_efficiency', 'Floor presentation and product placement.', false),
('retail', 'Stockout', 'A SKU is unavailable when a customer wants it.', 'Retail-specific severity.', 'operational_efficiency', 'A SKU is unavailable when a customer wants it.', false),
('retail', 'Return rate', 'Returned units as a share of sold units.', 'Retail-specific.', 'revenue_conversion', 'Returned units as a share of sold units.', false),
('retail', 'Promo leakage', 'Margin lost to stacked or unmonitored discounts.', 'Retail-specific.', 'financial_visibility', 'Margin lost to stacked or unmonitored discounts.', false),
('cannabis_mmj_mmc', 'Seed-to-sale', 'Operational lifecycle of cannabis product from intake to sale.', 'Cannabis dispensary/retail operations only — not healthcare.', 'operational_efficiency', 'Operational lifecycle of cannabis product from intake to sale.', false),
('cannabis_mmj_mmc', 'Inventory variance', 'Difference between system inventory and physical count.', 'Cannabis dispensary operations; state-specific rules may apply.', 'operational_efficiency', 'Difference between system inventory and physical count.', false),
('cannabis_mmj_mmc', 'METRC / BioTrack (where applicable)', 'State-mandated tracking systems used in many cannabis markets.', 'Operational tooling reference only; not legal advice; state-specific rules may apply.', 'operational_efficiency', 'State-mandated tracking systems used in many cannabis markets.', false),
('cannabis_mmj_mmc', 'ID / check-in process', 'Front-of-house customer verification workflow.', 'Dispensary retail operational workflow; not patient care.', 'operational_efficiency', 'Front-of-house customer verification workflow.', false),
('cannabis_mmj_mmc', 'Purchase limit process visibility', 'Operational visibility into per-customer purchase ceilings.', 'Operational visibility only; state-specific rules may apply; not legal advice.', 'operational_efficiency', 'Operational visibility into per-customer purchase ceilings.', false),
('cannabis_mmj_mmc', 'Evidence readiness', 'Ability to retrieve operational documentation quickly.', 'Documentation readiness, not legal certification.', 'operational_efficiency', 'Ability to retrieve operational documentation quickly.', false),
('cannabis_mmj_mmc', 'License / permit tracking', 'Operational tracking of license and permit expirations.', 'Operational readiness only; not legal advice; state-specific rules may apply.', 'operational_efficiency', 'Operational tracking of license and permit expirations.', false),
('cannabis_mmj_mmc', 'Vendor documentation', 'Operational records of vendor compliance documents on file.', 'Operational readiness only; not legal advice.', 'operational_efficiency', 'Operational records of vendor compliance documents on file.', false),
('cannabis_mmj_mmc', 'Menu / pricing accuracy', 'Match between displayed menu, POS, and online channels.', 'Cannabis dispensary retail operations.', 'revenue_conversion', 'Match between displayed menu, POS, and online channels.', false),
('cannabis_mmj_mmc', 'Compliance-sensitive operational risk', 'An operational gap that may carry compliance exposure but is not itself a legal conclusion.', 'Cannabis-specific framing; requires qualified legal/compliance review; not legal advice; not a compliance guarantee.', 'operational_efficiency', 'An operational gap that may carry compliance exposure but is not itself a legal conclusion.', false) ON CONFLICT (industry_key, term) DO NOTHING;

-- IB-H2: synthetic case study seed (training only — not real proof)
INSERT INTO public.industry_case_studies (
  industry_key, business_type, case_name, approximate_score, score_band, gear_scores,
  symptoms, evidence, failure_patterns_detected, benchmark_anchors_involved,
  admin_interpretation, client_safe_summary, likely_repair_map_priorities,
  suggested_next_diagnostic_questions, what_not_to_overpromise, is_synthetic, not_real_client, client_visible, display_label
) VALUES
('general_small_business', 'General Small Business', 'Owner-trapped consultancy', 380, '300_450', '{"demand": 40, "conversion": 50, "operational": 80, "financial": 90, "owner": 40}'::jsonb, 'Owner closes every deal; no SOPs; cash decisions made from bank balance.', 'No CRM, no SOPs, no weekly review.', 'No defined buyer profile; Owner-only sales; Cash flow blindness.', 'Owner decision dependency, Gross margin unknown.', 'Severe owner dependence; rebuild around documented decision rights and ICP first.', 'Most decisions still funnel through the owner; we''d start by writing what ''a good customer'' looks like and where decisions can move off the owner.', 'ICP doc; decision-rights matrix; weekly scoreboard.', 'Who is your best customer in the last 90 days? What decisions queue when you''re out for a week?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('general_small_business', 'General Small Business', 'Slipping retainer firm', 560, '451_650', '{"demand": 110, "conversion": 110, "operational": 120, "financial": 110, "owner": 110}'::jsonb, 'Decent revenue but margin shrinking; team waits on owner for pricing.', 'Pricing varies week to week; no margin per service line.', 'Unclear pricing; No delegation structure.', 'Gross margin slipping toward warning band.', 'Tighten pricing rules and delegate routine pricing decisions before scaling marketing.', 'Pricing isn''t consistent yet; we''d lock that down before adding more leads.', 'Pricing matrix; delegation of routine pricing.', 'When was the last price-list review? Who can quote without you?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('general_small_business', 'General Small Business', 'Stable SMB', 720, '651_800', '{"demand": 140, "conversion": 150, "operational": 150, "financial": 140, "owner": 140}'::jsonb, 'Good fundamentals; gaps in dashboard discipline and follow-up.', 'No weekly scoreboard; follow-up cadence informal.', 'No performance dashboard; Poor follow-up.', 'Cash runway healthy; close rate near anchor.', 'Mostly stable; the next leverage is consistent weekly visibility.', 'Numbers look healthy; the next step is making them visible weekly.', 'Weekly scoreboard; follow-up SOP.', 'What numbers do you check every Monday?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('general_small_business', 'General Small Business', 'Operating-rhythm SMB', 830, '801_plus', '{"demand": 160, "conversion": 170, "operational": 170, "financial": 170, "owner": 160}'::jsonb, 'Disciplined operator; minor refinements only.', 'Documented SOPs; weekly review running.', 'Minor: review-cadence depth.', 'All gears at or near anchor.', 'Refinement, not repair; deepen review cadence.', 'You''re operating with discipline; we''d refine review depth.', 'Quarterly review depth; metric anchors.', 'Where do you still rely on memory rather than a dashboard?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('general_small_business', 'General Small Business', 'Founder-led startup at 410', 410, '300_450', '{"demand": 60, "conversion": 70, "operational": 90, "financial": 100, "owner": 90}'::jsonb, 'Early traction; no operating system yet.', 'No SOPs; no source attribution; lead quality unknown.', 'No SOPs; No defined buyer profile.', 'Owner decision dependency at critical band.', 'Build the smallest operating spine before scaling spend.', 'We''d build the smallest operating spine before pushing more spend.', 'ICP; 5 SOPs; weekly scoreboard.', 'What''s your best 3-month customer? What 5 things would break if you went on vacation?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('trades_services', 'Trades / Services', 'Owner-driven HVAC', 390, '300_450', '{"demand": 80, "conversion": 50, "operational": 90, "financial": 90, "owner": 80}'::jsonb, 'Owner quotes every job; multi-day quote turnaround; rework not tracked.', 'Average quote-out > 72h; no callback log; AR > 90 days frequent.', 'Owner is the bottleneck; Quoting delay; No job costing; Unpaid invoices.', 'Quote-to-close near critical; AR aging > 60d in critical band.', 'Sequence: quote SLA + estimator role first, then job costing.', 'Quotes are taking too long and we''re losing jobs to faster competitors; we''d fix quote speed first.', '24h quote SLA; estimator role; per-job costing; deposit policy.', 'How long from request to quote? Who else can quote when you''re on a job?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('trades_services', 'Trades / Services', 'Slipping plumbing crew', 560, '451_650', '{"demand": 110, "conversion": 120, "operational": 110, "financial": 110, "owner": 110}'::jsonb, 'Schedule chaos; one tech holds key relationships.', 'No dispatch board; no follow-up after quotes.', 'Schedule chaos; Technician dependency; No follow-up process.', 'Schedule capacity utilization in warning band.', 'Stabilize dispatch and cross-train before scaling demand.', 'Scheduling is creating slip; we''d stabilize dispatch first.', 'Dispatch board; cross-training; 3-touch follow-up SOP.', 'What does your dispatch board look like? Which tech do customers ask for by name?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('trades_services', 'Trades / Services', 'Healthy electrical contractor', 730, '651_800', '{"demand": 140, "conversion": 150, "operational": 150, "financial": 150, "owner": 140}'::jsonb, 'Solid fundamentals; minor margin leak by service line.', 'Service line margin not tracked; AR aging healthy.', 'Service area profitability blind spots.', 'Job gross margin near anchor; AR aging healthy.', 'Add per-service-line P&L cut to harden margin discipline.', 'Strong overall; the next visible win is per-service-line margin.', 'Service-line P&L; quarterly mix review.', 'Which service line do you assume makes you the most? Have you proven it?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('trades_services', 'Trades / Services', 'Operationally tight roofing co.', 820, '801_plus', '{"demand": 160, "conversion": 170, "operational": 170, "financial": 170, "owner": 150}'::jsonb, 'Disciplined operator; small owner-dependence remaining.', 'All metrics tracked; one decision still bottlenecked at owner.', 'Minor owner dependence on bid signoff.', 'All gears near anchor.', 'Refinement only; move bid signoff threshold.', 'Strong shop overall; we''d just move the bid-signoff threshold.', 'Bid signoff delegation; quarterly review.', 'What''s the smallest decision still funneling to you?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('trades_services', 'Trades / Services', 'Field-services startup at 430', 430, '300_450', '{"demand": 70, "conversion": 70, "operational": 110, "financial": 80, "owner": 100}'::jsonb, 'Two-truck startup; lead source single channel; no rate buildup.', 'All leads from one channel; rate set by gut.', 'Lead source overdependence; Underpriced labor.', 'Channel concentration in critical band.', 'Diversify channel and rebuild rate before scaling crews.', 'Most leads come from one source and the rate may not cover overhead.', 'Source attribution + 2nd channel pilot; rebuild hourly rate.', 'Where do leads come from? How is your hourly rate built?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('restaurant_food_service', 'Restaurant / Food Service', 'Owner-expediting bistro', 380, '300_450', '{"demand": 80, "conversion": 80, "operational": 60, "financial": 80, "owner": 80}'::jsonb, 'Owner expedites; no weekly prime cost; recipes by memory.', 'No prime cost number; no recipe cards; no waste log.', 'Labor cost creep; Food cost creep; Inconsistent prep; Owner-dependent operations.', 'Prime cost in warning band.', 'Stand up weekly prime-cost cadence and recipe cards before menu changes.', 'Costs aren''t visible weekly; we''d stand up the basics first.', 'Weekly prime cost; recipe cards; waste log; shift lead role.', 'When did you last cost the menu? What''s today''s break-even?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('restaurant_food_service', 'Restaurant / Food Service', 'Slipping QSR', 560, '451_650', '{"demand": 110, "conversion": 110, "operational": 120, "financial": 110, "owner": 110}'::jsonb, 'Throughput slipping at peak; menu mix not analyzed.', 'No ticket-time tracking; no menu engineering matrix.', 'Weak table turns; Poor menu engineering.', 'Table turns in warning band.', 'Stabilize peak throughput before promo investment.', 'Peak throughput is leaving revenue on the table.', 'Ticket-time SLA; menu engineering matrix.', 'What''s your peak ticket time? Which 3 items earn the most?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('restaurant_food_service', 'Restaurant / Food Service', 'Healthy neighborhood restaurant', 720, '651_800', '{"demand": 140, "conversion": 150, "operational": 150, "financial": 140, "owner": 140}'::jsonb, 'Stable operator; channel margin unclear.', 'Delivery channel margin not separated.', 'Delivery-platform margin erosion.', 'Prime cost near anchor.', 'Add channel P&L to protect margin.', 'Solid overall; we''d separate delivery margin from in-house.', 'Channel P&L; menu mix review.', 'What is your delivery margin compared to dine-in?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('restaurant_food_service', 'Restaurant / Food Service', 'Operating-rhythm restaurant group', 820, '801_plus', '{"demand": 160, "conversion": 170, "operational": 170, "financial": 170, "owner": 150}'::jsonb, 'Multi-unit discipline; minor owner dependency on hiring.', 'All cost metrics weekly.', 'Minor: hiring decisions still owner-led.', 'All gears near anchor.', 'Refinement only; delegate hiring panel.', 'Strong group; the next refinement is hiring delegation.', 'Hiring SOP; manager panel.', 'Who else can run a hiring panel today?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('restaurant_food_service', 'Restaurant / Food Service', 'New-concept restaurant at 420', 420, '300_450', '{"demand": 70, "conversion": 80, "operational": 90, "financial": 90, "owner": 90}'::jsonb, 'First 12 months; no daily break-even visibility.', 'No daily break-even; no waste log.', 'No daily break-even visibility; Spoilage / yield loss.', 'Daily break-even visibility absent.', 'Make break-even visible daily before promo spend.', 'Daily break-even isn''t visible yet; we''d start there.', 'Posted daily break-even; waste log; prep par.', 'What''s today''s break-even? Who logs end-of-shift waste?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('retail', 'Retail', 'Single-store boutique at 380', 380, '300_450', '{"demand": 70, "conversion": 80, "operational": 70, "financial": 80, "owner": 80}'::jsonb, 'Owner buys on instinct; no sell-through targets; no shrink program.', 'No sell-through %, no cycle counts, blended margin only.', 'Poor sell-through; Shrinkage; No SKU-level visibility.', 'Inventory turnover in critical band.', 'Stand up sell-through targets and cycle counts before next buy.', 'Buys aren''t measured against sell-through; we''d start there.', 'Sell-through SLA; cycle counts; SKU-level review.', 'What''s your last buy sell-through? When did you last cycle-count?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('retail', 'Retail', 'Slipping multi-store retailer', 560, '451_650', '{"demand": 110, "conversion": 120, "operational": 110, "financial": 110, "owner": 110}'::jsonb, 'Promo stacking; one channel drives revenue.', 'Discount % not tracked; channel mix unmeasured.', 'Promo / discount leakage; Overdependence on one channel.', 'Channel concentration in warning band.', 'Govern discounts and pilot a second channel.', 'Discounts are eroding margin; we''d govern that first.', 'Discount governance; 2nd channel pilot.', 'What % of sales runs through discount? What''s your second channel?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('retail', 'Retail', 'Healthy specialty retailer', 720, '651_800', '{"demand": 140, "conversion": 150, "operational": 150, "financial": 140, "owner": 140}'::jsonb, 'Stable buy discipline; margin healthy; cash forecast informal.', 'Margin healthy; no 13-week cash forecast.', 'Seasonal cash crunch risk.', 'Gross margin near anchor.', 'Add 13-week cash forecast.', 'Strong overall; we''d add a 13-week cash forecast.', '13-week cash forecast.', 'When does your cash get tightest each year?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('retail', 'Retail', 'Operating-rhythm chain', 820, '801_plus', '{"demand": 160, "conversion": 170, "operational": 170, "financial": 170, "owner": 150}'::jsonb, 'Disciplined buy + merch; minor owner dependence on category sign-off.', 'All metrics tracked.', 'Minor: owner dependence on category sign-off.', 'All gears near anchor.', 'Refinement only.', 'Strong chain; the next refinement is delegating category sign-off.', 'Delegation thresholds.', 'What''s the smallest sign-off still funneling to you?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('retail', 'Retail', 'Pop-up retailer at 430', 430, '300_450', '{"demand": 60, "conversion": 80, "operational": 100, "financial": 90, "owner": 100}'::jsonb, 'Newer operator; no min/max in POS; manual reorder.', 'No min/max; no source attribution.', 'Stockout / overstock cycle; Lead source overdependence.', 'Stockout frequency in critical band.', 'Set min/max and source attribution before next buy.', 'Reorder is reactive; we''d set min/max first.', 'Min/max in POS; source attribution.', 'How do you know when to reorder?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'Compliance-sensitive single dispensary', 380, '300_450', '{"demand": 80, "conversion": 80, "operational": 60, "financial": 80, "owner": 80}'::jsonb, 'Operational documentation appears incomplete; cash counts informal; budtender inconsistency.', 'No documented receiving cadence; informal cash counts.', 'Possible documentation gap in compliance evidence; Cash handling risk; Budtender inconsistency.', 'Inventory variance trending into warning band.', 'Compliance-sensitive operational risk; requires qualified legal/compliance review. Sequence: documentation cadence + cash count SOP first. Operational visibility, not legal advice.', 'Some operational documentation looks thin; we''d tighten that first. This is operational visibility only — not legal advice.', 'Documentation checklist + cadence; dual-control cash count SOP; budtender playbook.', 'How are receiving variances captured today? Who runs the cash count?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'Slipping multi-location dispensary', 560, '451_650', '{"demand": 110, "conversion": 110, "operational": 120, "financial": 110, "owner": 110}'::jsonb, 'Discount stacking; vendor concentration; renewals tracked informally.', 'No discount governance; top vendor > 40% COGS; no renewal calendar.', 'Discounting / margin erosion; Vendor concentration; License / renewal tracking risk.', 'Discount dependency in warning band.', 'Stabilize margin governance and renewal calendar. Operational readiness only; not legal advice.', 'Discounts and vendor concentration are creating risk; we''d stabilize those.', 'Discount cap + manager approval; 2nd vendor; renewal calendar with reminders.', 'What % of gross sales runs through discount? When does your next license renewal land?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'Healthy compliance-aware dispensary', 720, '651_800', '{"demand": 140, "conversion": 150, "operational": 150, "financial": 140, "owner": 140}'::jsonb, 'Mostly stable; menu/pricing mismatch on some channels.', 'Spot-check variance between in-store and online menu.', 'Menu / pricing inconsistency.', 'Repeat customer rate near anchor.', 'Refinement: weekly menu reconciliation across channels.', 'Solid overall; we''d reconcile menu across channels weekly.', 'Weekly menu reconciliation.', 'Who confirms in-store and online menu match each week?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'Operating-rhythm dispensary group', 820, '801_plus', '{"demand": 160, "conversion": 170, "operational": 170, "financial": 170, "owner": 150}'::jsonb, 'Multi-location discipline; minor owner dependence on vendor selection.', 'All operational metrics tracked.', 'Minor: owner dependence on vendor selection.', 'All gears near anchor.', 'Refinement only. Operational readiness, not legal certification.', 'Strong group; the next refinement is vendor-selection delegation.', 'Vendor-selection delegation.', 'What''s the smallest vendor decision still funneling to you?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.'),
('cannabis_mmj_mmc', 'Cannabis / MMJ / MMC', 'New-license dispensary at 420', 420, '300_450', '{"demand": 70, "conversion": 80, "operational": 90, "financial": 90, "owner": 90}'::jsonb, 'Newly licensed; documentation cadence not established; check-in process informal.', 'No documented check-in SOP; evidence vault scattered.', 'ID / check-in process visibility gaps; Evidence vault / document readiness gaps.', 'Operational compliance checklist completion in warning band.', 'Stand up documentation cadence and check-in SOP. Compliance-sensitive operational risk; requires qualified legal/compliance review.', 'Documentation cadence isn''t set yet; we''d start there. This is operational readiness, not legal certification.', 'Documented check-in SOP; evidence vault + index; checklist cadence.', 'How is the daily check-in process documented? Where does operational evidence live?', 'Operational visibility only. Not legal/accounting/HR/compliance certification. RGS does not guarantee revenue outcomes.', true, true, false, 'Training example — not a real customer.') ON CONFLICT (industry_key, case_name) DO NOTHING;
